

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AssessmentSizingCriterion', 'AssessmentStage', 'AssessmentType', 'AsyncCommitModeIntent', 'AutomationArtifactStatus', 'AvsAssessmentScenario', 'AzureArcState', 'AzureAvsNodeType', 'AzureCurrency', 'AzureDiskType', 'AzureEnvironmentType', 'AzureHybridUseBenefit', 'AzureLocation', 'AzureOffer', 'AzureOfferCode', 'AzurePricingTier', 'AzureReservedInstance', 'AzureSecurityOfferingType', 'AzureSqlDataBaseType', 'AzureSqlInstanceType', 'AzureSqlPurchaseModel', 'AzureSqlServiceTier', 'AzureSqlServiceTierV3', 'AzureStorageRedundancy', 'AzureTarget', 'AzureVmCategory', 'AzureVmFamily', 'AzureVmSecurityType', 'BusinessCaseCurrency', 'ComputeTier', 'ConfigurationType', 'ConsolidationType', 'Currency', 'DiscoverySource', 'EnvironmentType', 'ExternalStorageType', 'FttAndRaidLevel', 'GroupType', 'HyperVLicenseType', 'LicensingProgram', 'LoadBalancerType', 'MigrationSpecificPropertiesInstanceType', 'MigrationStrategy', 'MoveType', 'MultiSubnetIntent', 'OperatingSystemType', 'OptimizationLogic', 'OsLicense', 'Percentile', 'PricingTier', 'PrivateEndpointServiceConnectionStatus', 'ProjectStatus', 'ProvisioningState', 'ReservedInstance', 'ResourceIdentityType', 'ResourceIdentityTypes', 'SavingsOption', 'SavingsOptions', 'ScopeType', 'SecretStoreType', 'SqlServerLicense', 'SqlServerLicenseType', 'Status', 'TargetAvailabilityZone', 'TargetHydrationStorageProviderType', 'TargetStorageAccessType', 'TargetStorageProjectionType', 'TaskScope', 'TimeRange', 'WorkloadDeploymentTarget', 'WorkloadDeploymentType', 'WorkloadType', 'ZoneRedundant']
@pulumi.type_token("azure-native:migrate:AssessmentSizingCriterion")
class AssessmentSizingCriterion(_builtins.str, Enum):
    
    PERFORMANCE_BASED = ...
    AS_ON_PREMISES = ...


@pulumi.type_token("azure-native:migrate:AssessmentStage")
class AssessmentStage(_builtins.str, Enum):
    
    IN_PROGRESS = ...
    UNDER_REVIEW = ...
    APPROVED = ...


@pulumi.type_token("azure-native:migrate:AssessmentType")
class AssessmentType(_builtins.str, Enum):
    
    UNKNOWN = ...
    MACHINE_ASSESSMENT = ...
    AVS_ASSESSMENT = ...
    SQL_ASSESSMENT = ...
    WEB_APP_ASSESSMENT = ...


@pulumi.type_token("azure-native:migrate:AsyncCommitModeIntent")
class AsyncCommitModeIntent(_builtins.str, Enum):
    
    NONE = ...
    HIGH_AVAILABILITY = ...
    DISASTER_RECOVERY = ...


@pulumi.type_token("azure-native:migrate:AutomationArtifactStatus")
class AutomationArtifactStatus(_builtins.str, Enum):
    
    NOT_GENERATED = ...
    GENERATED = ...


@pulumi.type_token("azure-native:migrate:AvsAssessmentScenario")
class AvsAssessmentScenario(_builtins.str, Enum):
    
    UNKNOWN = ...
    NEW_AVS_SDDC = ...
    AVS_SDDC_EXPANSION = ...


@pulumi.type_token("azure-native:migrate:AzureArcState")
class AzureArcState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...
    UNKNOWN = ...


@pulumi.type_token("azure-native:migrate:AzureAvsNodeType")
class AzureAvsNodeType(_builtins.str, Enum):
    
    UNKNOWN = ...
    AV36 = ...
    AV36_P = ...
    AV52 = ...
    AV64 = ...


@pulumi.type_token("azure-native:migrate:AzureCurrency")
class AzureCurrency(_builtins.str, Enum):
    
    UNKNOWN = ...
    USD = ...
    DKK = ...
    CAD = ...
    IDR = ...
    JPY = ...
    KRW = ...
    NZD = ...
    NOK = ...
    RUB = ...
    SAR = ...
    ZAR = ...
    SEK = ...
    TRY_ = ...
    GBP = ...
    MXN = ...
    MYR = ...
    INR = ...
    HKD = ...
    BRL = ...
    TWD = ...
    EUR = ...
    CHF = ...
    ARS = ...
    AUD = ...
    CNY = ...


@pulumi.type_token("azure-native:migrate:AzureDiskType")
class AzureDiskType(_builtins.str, Enum):
    
    UNKNOWN = ...
    STANDARD = ...
    STANDARD_SSD = ...
    PREMIUM = ...
    STANDARD_OR_PREMIUM = ...
    ULTRA = ...
    PREMIUM_V2 = ...


@pulumi.type_token("azure-native:migrate:AzureEnvironmentType")
class AzureEnvironmentType(_builtins.str, Enum):
    
    UNKNOWN = ...
    DEV_TEST = ...
    PRODUCTION = ...


@pulumi.type_token("azure-native:migrate:AzureHybridUseBenefit")
class AzureHybridUseBenefit(_builtins.str, Enum):
    
    UNKNOWN = ...
    YES = ...
    NO = ...


@pulumi.type_token("azure-native:migrate:AzureLocation")
class AzureLocation(_builtins.str, Enum):
    
    UNKNOWN = ...
    EAST_ASIA = ...
    SOUTHEAST_ASIA = ...
    AUSTRALIA_EAST = ...
    AUSTRALIA_SOUTHEAST = ...
    BRAZIL_SOUTH = ...
    CANADA_CENTRAL = ...
    CANADA_EAST = ...
    WEST_EUROPE = ...
    NORTH_EUROPE = ...
    CENTRAL_INDIA = ...
    SOUTH_INDIA = ...
    WEST_INDIA = ...
    JAPAN_EAST = ...
    JAPAN_WEST = ...
    KOREA_CENTRAL = ...
    KOREA_SOUTH = ...
    UK_WEST = ...
    UK_SOUTH = ...
    NORTH_CENTRAL_US = ...
    EAST_US = ...
    WEST_US2 = ...
    SOUTH_CENTRAL_US = ...
    CENTRAL_US = ...
    EAST_US2 = ...
    WEST_US = ...
    WEST_CENTRAL_US = ...
    GERMANY_CENTRAL = ...
    GERMANY_NORTHEAST = ...
    CHINA_NORTH = ...
    CHINA_EAST = ...
    US_GOV_ARIZONA = ...
    US_GOV_TEXAS = ...
    US_GOV_IOWA = ...
    US_GOV_VIRGINIA = ...
    US_DO_D_CENTRAL = ...
    US_DO_D_EAST = ...
    FRANCE_CENTRAL = ...
    AUSTRALIA_CENTRAL = ...
    SOUTH_AFRICA_NORTH = ...
    FRANCE_SOUTH = ...
    AUSTRALIA_CENTRAL2 = ...
    SOUTH_AFRICA_WEST = ...
    GERMANY_NORTH = ...
    GERMANY_WEST_CENTRAL = ...
    NORWAY_EAST = ...
    NORWAY_WEST = ...
    CHINA_EAST2 = ...
    CHINA_NORTH2 = ...
    SWITZERLAND_NORTH = ...
    SWITZERLAND_WEST = ...
    UAE_NORTH = ...
    UAE_CENTRAL = ...
    US_NAT_EAST = ...
    US_NAT_WEST = ...
    US_SEC_EAST = ...
    US_SEC_CENTRAL = ...
    US_SEC_WEST = ...
    SWEDEN_CENTRAL = ...
    QATAR_CENTRAL = ...
    JIO_INDIA_WEST = ...
    ITALY_NORTH = ...
    POLAND_CENTRAL = ...
    ISRAEL_CENTRAL = ...
    MEXICO_CENTRAL = ...
    NEW_ZEALAND_NORTH = ...
    SPAIN_CENTRAL = ...


@pulumi.type_token("azure-native:migrate:AzureOffer")
class AzureOffer(_builtins.str, Enum):
    
    UNKNOWN = ...
    MSAZR0003_P = ...
    MSAZR0023_P = ...
    MSMCAZR0044_P = ...
    MSMCAZR0059_P = ...
    MSMCAZR0060_P = ...
    MSMCAZR0063_P = ...
    MSAZRUSGOV0003_P = ...
    EA = ...
    SAVINGS_PLAN1_YEAR = ...
    SAVINGS_PLAN3_YEAR = ...


@pulumi.type_token("azure-native:migrate:AzureOfferCode")
class AzureOfferCode(_builtins.str, Enum):
    
    UNKNOWN = ...
    MSAZR0003_P = ...
    MSAZR0044_P = ...
    MSAZR0059_P = ...
    MSAZR0060_P = ...
    MSAZR0062_P = ...
    MSAZR0063_P = ...
    MSAZR0064_P = ...
    MSAZR0029_P = ...
    MSAZR0022_P = ...
    MSAZR0023_P = ...
    MSAZR0148_P = ...
    MSAZR0025_P = ...
    MSAZR0036_P = ...
    MSAZR0120_P = ...
    MSAZR0121_P = ...
    MSAZR0122_P = ...
    MSAZR0123_P = ...
    MSAZR0124_P = ...
    MSAZR0125_P = ...
    MSAZR0126_P = ...
    MSAZR0127_P = ...
    MSAZR0128_P = ...
    MSAZR0129_P = ...
    MSAZR0130_P = ...
    MSAZR0111_P = ...
    MSAZR0144_P = ...
    MSAZR0149_P = ...
    MSMCAZR0044_P = ...
    MSMCAZR0059_P = ...
    MSMCAZR0060_P = ...
    MSMCAZR0063_P = ...
    MSMCAZR0120_P = ...
    MSMCAZR0121_P = ...
    MSMCAZR0125_P = ...
    MSMCAZR0128_P = ...
    MSAZRDE0003_P = ...
    MSAZRDE0044_P = ...
    MSAZRUSGOV0003_P = ...
    EA = ...
    MSAZR0243_P = ...
    SAVINGS_PLAN1_YEAR = ...
    SAVINGS_PLAN3_YEAR = ...


@pulumi.type_token("azure-native:migrate:AzurePricingTier")
class AzurePricingTier(_builtins.str, Enum):
    
    STANDARD = ...
    BASIC = ...


@pulumi.type_token("azure-native:migrate:AzureReservedInstance")
class AzureReservedInstance(_builtins.str, Enum):
    
    NONE = ...
    RI1_YEAR = ...
    RI3_YEAR = ...


@pulumi.type_token("azure-native:migrate:AzureSecurityOfferingType")
class AzureSecurityOfferingType(_builtins.str, Enum):
    
    NO = ...
    MDC = ...


@pulumi.type_token("azure-native:migrate:AzureSqlDataBaseType")
class AzureSqlDataBaseType(_builtins.str, Enum):
    
    UNKNOWN = ...
    AUTOMATIC = ...
    SINGLE_DATABASE = ...
    ELASTIC_POOL = ...


@pulumi.type_token("azure-native:migrate:AzureSqlInstanceType")
class AzureSqlInstanceType(_builtins.str, Enum):
    
    UNKNOWN = ...
    AUTOMATIC = ...
    SINGLE_INSTANCE = ...
    INSTANCE_POOLS = ...


@pulumi.type_token("azure-native:migrate:AzureSqlPurchaseModel")
class AzureSqlPurchaseModel(_builtins.str, Enum):
    
    UNKNOWN = ...
    V_CORE = ...
    DTU = ...


@pulumi.type_token("azure-native:migrate:AzureSqlServiceTier")
class AzureSqlServiceTier(_builtins.str, Enum):
    
    UNKNOWN = ...
    AUTOMATIC = ...
    GENERAL_PURPOSE = ...
    BUSINESS_CRITICAL = ...
    HYPER_SCALE = ...


@pulumi.type_token("azure-native:migrate:AzureSqlServiceTierV3")
class AzureSqlServiceTierV3(_builtins.str, Enum):
    
    SQL_SERVICE_UNKNOWN = ...
    SQL_SERVICE_AUTOMATIC = ...
    SQL_SERVICE_GENERAL_PURPOSE = ...
    SQL_SERVICE_BUSINESS_CRITICAL = ...
    SQL_SERVICE_HYPER_SCALE = ...


@pulumi.type_token("azure-native:migrate:AzureStorageRedundancy")
class AzureStorageRedundancy(_builtins.str, Enum):
    
    UNKNOWN = ...
    LOCALLY_REDUNDANT = ...
    ZONE_REDUNDANT = ...
    GEO_REDUNDANT = ...
    READ_ACCESS_GEO_REDUNDANT = ...


@pulumi.type_token("azure-native:migrate:AzureTarget")
class AzureTarget(_builtins.str, Enum):
    
    UNKNOWN = ...
    SQL_DATABASE = ...
    SQL_MI = ...
    FLEX_SERVER_PG = ...
    ORACLE_IAAS_VM = ...
    AZURE_SPRING_APPS = ...
    SAP_AZURE_INSTANCE = ...
    AKS = ...
    MY_SQL_AZURE_FLEX_SERVER = ...
    AZURE_SQLVM = ...
    AZURE_VM = ...
    AZURE_APP_SERVICE = ...
    AZURE_APP_SERVICE_CONTAINER = ...
    AVS = ...


@pulumi.type_token("azure-native:migrate:AzureVmCategory")
class AzureVmCategory(_builtins.str, Enum):
    
    ALL = ...
    COMPUTE_OPTIMIZED = ...
    GENERAL_PURPOSE = ...
    GPU_OPTIMIZED = ...
    HIGH_PERFORMANCE_COMPUTE = ...
    MEMORY_OPTIMIZED = ...
    STORAGE_OPTIMIZED = ...
    ISOLATED = ...


@pulumi.type_token("azure-native:migrate:AzureVmFamily")
class AzureVmFamily(_builtins.str, Enum):
    
    UNKNOWN = ...
    BASIC_A0_A4 = ...
    STANDARD_A0_A7 = ...
    STANDARD_A8_A11 = ...
    AV2_SERIES = ...
    D_SERIES = ...
    DV2_SERIES = ...
    DS_SERIES = ...
    D_SV2_SERIES = ...
    F_SERIES = ...
    FS_SERIES = ...
    G_SERIES = ...
    GS_SERIES = ...
    H_SERIES = ...
    LS_SERIES = ...
    DSV3_SERIES = ...
    DV3_SERIES = ...
    FSV2_SERIES = ...
    EV3_SERIES = ...
    ESV3_SERIES = ...
    M_SERIES = ...
    DC_SERIES = ...
    LSV2_SERIES = ...
    EV4_SERIES = ...
    ESV4_SERIES = ...
    EDV4_SERIES = ...
    EDSV4_SERIES = ...
    DV4_SERIES = ...
    DSV4_SERIES = ...
    DDV4_SERIES = ...
    DDSV4_SERIES = ...
    EASV4_SERIES = ...
    DASV4_SERIES = ...
    MV2_SERIES = ...
    EAV4_SERIES = ...
    DAV4_SERIES = ...
    MSV2_SERIES = ...
    MDSV2_SERIES = ...
    DV5_SERIES = ...
    DSV5_SERIES = ...
    DDV5_SERIES = ...
    DDSV5_SERIES = ...
    DASV5_SERIES = ...
    DADSV5_SERIES = ...
    EV5_SERIES = ...
    ESV5_SERIES = ...
    EDV5_SERIES = ...
    EDSV5_SERIES = ...
    EASV5_SERIES = ...
    EADSV5_SERIES = ...
    EBSV5_SERIES = ...
    EBDSV5_SERIES = ...


@pulumi.type_token("azure-native:migrate:AzureVmSecurityType")
class AzureVmSecurityType(_builtins.str, Enum):
    
    UNKNOWN = ...
    STANDARD = ...
    TVM = ...
    CVM = ...


@pulumi.type_token("azure-native:migrate:BusinessCaseCurrency")
class BusinessCaseCurrency(_builtins.str, Enum):
    
    UNKNOWN = ...
    USD = ...
    DKK = ...
    CAD = ...
    IDR = ...
    JPY = ...
    KRW = ...
    NZD = ...
    NOK = ...
    RUB = ...
    SAR = ...
    ZAR = ...
    SEK = ...
    TRY_ = ...
    GBP = ...
    MXN = ...
    MYR = ...
    INR = ...
    HKD = ...
    BRL = ...
    TWD = ...
    EUR = ...
    CHF = ...
    ARS = ...
    AUD = ...
    CNY = ...


@pulumi.type_token("azure-native:migrate:ComputeTier")
class ComputeTier(_builtins.str, Enum):
    
    UNKNOWN = ...
    AUTOMATIC = ...
    PROVISIONED = ...
    SERVERLESS = ...


@pulumi.type_token("azure-native:migrate:ConfigurationType")
class ConfigurationType(_builtins.str, Enum):
    
    IIS_CONNECTION_STRING = ...
    IIS_AUTHENTICATION = ...
    APACHE_TOMCAT_CONTEXT_RESOURCE = ...


@pulumi.type_token("azure-native:migrate:ConsolidationType")
class ConsolidationType(_builtins.str, Enum):
    
    FULL = ...
    AS_ON_SOURCE = ...


@pulumi.type_token("azure-native:migrate:Currency")
class Currency(_builtins.str, Enum):
    
    UNKNOWN = ...
    USD = ...
    DKK = ...
    CAD = ...
    IDR = ...
    JPY = ...
    KRW = ...
    NZD = ...
    NOK = ...
    RUB = ...
    SAR = ...
    ZAR = ...
    SEK = ...
    TRY_ = ...
    GBP = ...
    MXN = ...
    MYR = ...
    INR = ...
    HKD = ...
    BRL = ...
    TWD = ...
    EUR = ...
    CHF = ...
    ARS = ...
    AUD = ...
    CNY = ...


@pulumi.type_token("azure-native:migrate:DiscoverySource")
class DiscoverySource(_builtins.str, Enum):
    
    UNKNOWN = ...
    APPLIANCE = ...
    IMPORT_ = ...


@pulumi.type_token("azure-native:migrate:EnvironmentType")
class EnvironmentType(_builtins.str, Enum):
    
    PRODUCTION = ...
    UNKNOWN = ...
    DEV_TEST = ...


@pulumi.type_token("azure-native:migrate:ExternalStorageType")
class ExternalStorageType(_builtins.str, Enum):
    
    UNKNOWN = ...
    NONE = ...
    ANF_STANDARD = ...
    ANF_PREMIUM = ...
    ANF_ULTRA = ...


@pulumi.type_token("azure-native:migrate:FttAndRaidLevel")
class FttAndRaidLevel(_builtins.str, Enum):
    
    UNKNOWN = ...
    FTT1_RAID1 = ...
    FTT1_RAID5 = ...
    FTT2_RAID1 = ...
    FTT2_RAID6 = ...
    FTT3_RAID1 = ...


@pulumi.type_token("azure-native:migrate:GroupType")
class GroupType(_builtins.str, Enum):
    
    DEFAULT = ...
    IMPORT_ = ...


@pulumi.type_token("azure-native:migrate:HyperVLicenseType")
class HyperVLicenseType(_builtins.str, Enum):
    
    UNKNOWN = ...
    DATACENTRE = ...
    STANDARD = ...


@pulumi.type_token("azure-native:migrate:LicensingProgram")
class LicensingProgram(_builtins.str, Enum):
    
    RETAIL = ...
    UNKNOWN = ...
    EA = ...
    MCA = ...


@pulumi.type_token("azure-native:migrate:LoadBalancerType")
class LoadBalancerType(_builtins.str, Enum):
    
    PRIVATE = ...
    PUBLIC = ...


@pulumi.type_token(...)
class MigrationSpecificPropertiesInstanceType(_builtins.str, Enum):
    
    SERVER_MIGRATION = ...


@pulumi.type_token("azure-native:migrate:MigrationStrategy")
class MigrationStrategy(_builtins.str, Enum):
    
    UNKNOWN = ...
    OPTIMIZE_FOR_COST = ...
    IAA_S_ONLY = ...
    OPTIMIZE_FOR_PAAS = ...
    AVS_ONLY = ...


@pulumi.type_token("azure-native:migrate:MoveType")
class MoveType(_builtins.str, Enum):
    
    REGION_TO_REGION = ...
    REGION_TO_ZONE = ...


@pulumi.type_token("azure-native:migrate:MultiSubnetIntent")
class MultiSubnetIntent(_builtins.str, Enum):
    
    NONE = ...
    HIGH_AVAILABILITY = ...
    DISASTER_RECOVERY = ...


@pulumi.type_token("azure-native:migrate:OperatingSystemType")
class OperatingSystemType(_builtins.str, Enum):
    WINDOWS = ...
    LINUX = ...


@pulumi.type_token("azure-native:migrate:OptimizationLogic")
class OptimizationLogic(_builtins.str, Enum):
    
    MINIMIZE_COST = ...
    MODERNIZE_TO_PAA_S = ...
    MODERNIZE_TO_AZURE_SQL_MI = ...
    MODERNIZE_TO_AZURE_SQL_DB = ...


@pulumi.type_token("azure-native:migrate:OsLicense")
class OsLicense(_builtins.str, Enum):
    
    UNKNOWN = ...
    YES = ...
    NO = ...


@pulumi.type_token("azure-native:migrate:Percentile")
class Percentile(_builtins.str, Enum):
    
    PERCENTILE50 = ...
    PERCENTILE90 = ...
    PERCENTILE95 = ...
    PERCENTILE99 = ...
    PERCENTILE_UNKNOWN = ...


@pulumi.type_token("azure-native:migrate:PricingTier")
class PricingTier(_builtins.str, Enum):
    
    STANDARD = ...
    FREE = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:migrate:ProjectStatus")
class ProjectStatus(_builtins.str, Enum):
    
    ACTIVE = ...
    INACTIVE = ...


@pulumi.type_token("azure-native:migrate:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    PROVISIONING = ...
    UPDATING = ...
    DELETING = ...
    ACCEPTED = ...


@pulumi.type_token("azure-native:migrate:ReservedInstance")
class ReservedInstance(_builtins.str, Enum):
    
    NONE = ...
    RI1_YEAR = ...
    RI3_YEAR = ...


@pulumi.type_token("azure-native:migrate:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


@pulumi.type_token("azure-native:migrate:ResourceIdentityTypes")
class ResourceIdentityTypes(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


@pulumi.type_token("azure-native:migrate:SavingsOption")
class SavingsOption(_builtins.str, Enum):
    
    UNKNOWN = ...
    RI3_YEAR = ...
    SAVINGS_PLAN3_YEAR = ...


@pulumi.type_token("azure-native:migrate:SavingsOptions")
class SavingsOptions(_builtins.str, Enum):
    
    NONE = ...
    RI1_YEAR = ...
    RI3_YEAR = ...
    SAVINGS_PLAN1_YEAR = ...
    SAVINGS_PLAN3_YEAR = ...
    CUSTOM_AZURE_OFFER_CODE = ...


@pulumi.type_token("azure-native:migrate:ScopeType")
class ScopeType(_builtins.str, Enum):
    
    SERVER_GROUP_ID = ...
    AZURE_RESOURCE_GRAPH_QUERY = ...


@pulumi.type_token("azure-native:migrate:SecretStoreType")
class SecretStoreType(_builtins.str, Enum):
    NONE = ...
    KUBE_SECRET = ...
    KEY_VAULT_SECRET = ...
    APP_SERVICE_APP_SETTINGS = ...


@pulumi.type_token("azure-native:migrate:SqlServerLicense")
class SqlServerLicense(_builtins.str, Enum):
    
    UNKNOWN = ...
    YES = ...
    NO = ...


@pulumi.type_token("azure-native:migrate:SqlServerLicenseType")
class SqlServerLicenseType(_builtins.str, Enum):
    
    UNKNOWN = ...
    ENTERPRISE = ...
    STANDARD = ...


@pulumi.type_token("azure-native:migrate:Status")
class Status(_builtins.str, Enum):
    
    APPROVED = ...
    PENDING = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:migrate:TargetAvailabilityZone")
class TargetAvailabilityZone(_builtins.str, Enum):
    
    ONE = ...
    TWO = ...
    THREE = ...
    NA = ...


@pulumi.type_token(...)
class TargetHydrationStorageProviderType(_builtins.str, Enum):
    
    AZURE_FILE_SHARE = ...


@pulumi.type_token("azure-native:migrate:TargetStorageAccessType")
class TargetStorageAccessType(_builtins.str, Enum):
    
    SHARED = ...
    EXCLUSIVE = ...


@pulumi.type_token("azure-native:migrate:TargetStorageProjectionType")
class TargetStorageProjectionType(_builtins.str, Enum):
    
    CONTAINER_FILE_SYSTEM = ...
    PERSISTENT_VOLUME = ...


@pulumi.type_token("azure-native:migrate:TaskScope")
class TaskScope(_builtins.str, Enum):
    
    WAVE = ...
    MIGRATION_ENTITY = ...
    MIGRATION_ENTITY_GROUP = ...


@pulumi.type_token("azure-native:migrate:TimeRange")
class TimeRange(_builtins.str, Enum):
    
    DAY = ...
    WEEK = ...
    MONTH = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:migrate:WorkloadDeploymentTarget")
class WorkloadDeploymentTarget(_builtins.str, Enum):
    
    AZURE_KUBERNETES_SERVICE = ...
    AZURE_APP_SERVICE_CONTAINER = ...
    AZURE_APP_SERVICE_NATIVE = ...


@pulumi.type_token("azure-native:migrate:WorkloadDeploymentType")
class WorkloadDeploymentType(_builtins.str, Enum):
    
    IISAKS_WORKLOAD_DEPLOYMENT = ...
    APACHE_TOMCAT_AKS_WORKLOAD_DEPLOYMENT = ...


@pulumi.type_token("azure-native:migrate:WorkloadType")
class WorkloadType(_builtins.str, Enum):
    
    IIS_WORKLOAD = ...
    APACHE_TOMCAT_WORKLOAD = ...


@pulumi.type_token("azure-native:migrate:ZoneRedundant")
class ZoneRedundant(_builtins.str, Enum):
    
    ENABLE = ...
    DISABLE = ...


