

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['LanguageRuntime', 'LedgerRoleName', 'LedgerSku', 'LedgerType', 'RunningState']
@pulumi.type_token("azure-native:confidentialledger:LanguageRuntime")
class LanguageRuntime(_builtins.str, Enum):
    
    CPP = ...
    JS = ...


@pulumi.type_token("azure-native:confidentialledger:LedgerRoleName")
class LedgerRoleName(_builtins.str, Enum):
    
    READER = ...
    CONTRIBUTOR = ...
    ADMINISTRATOR = ...


@pulumi.type_token("azure-native:confidentialledger:LedgerSku")
class LedgerSku(_builtins.str, Enum):
    
    STANDARD = ...
    BASIC = ...
    UNKNOWN = ...


@pulumi.type_token("azure-native:confidentialledger:LedgerType")
class LedgerType(_builtins.str, Enum):
    
    UNKNOWN = ...
    PUBLIC = ...
    PRIVATE = ...


@pulumi.type_token("azure-native:confidentialledger:RunningState")
class RunningState(_builtins.str, Enum):
    
    ACTIVE = ...
    PAUSED = ...
    UNKNOWN = ...
    PAUSING = ...
    RESUMING = ...


