import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["RecordType"]

@pulumi.type_token("aws:route53/RecordType:RecordType")
class RecordType(_builtins.str, Enum):
    A = ...
    AAAA = ...
    CNAME = ...
    CAA = ...
    MX = ...
    NAPTR = ...
    NS = ...
    PTR = ...
    SOA = ...
    SPF = ...
    SRV = ...
    TXT = ...
