import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ActiveDirectoryAuth",
    "AdministratorType",
    "AzureManagedDiskPerformanceTier",
    "Cancel",
    "CreateMode",
    "DataEncryptionType",
    "GeoRedundantBackup",
    "GeographicallyRedundantBackup",
    "IdentityType",
    "InfrastructureEncryption",
    "LogicalReplicationOnSourceServer",
    "MicrosoftEntraAuth",
    "MigrateRolesAndPermissions",
    "MigrationMode",
    "MigrationOption",
    "MinimalTlsVersionEnum",
    "OverwriteDatabasesOnTargetServer",
    "PasswordAuth",
    "PasswordBasedAuth",
    "PostgreSqlFlexibleServerHighAvailabilityMode",
    "PostgresMajorVersion",
    "PrincipalType",
    "PrivateEndpointServiceConnectionStatus",
    "PublicNetworkAccessEnum",
    "ReadReplicaPromoteMode",
    "ReadReplicaPromoteOption",
    "ReplicationRole",
    "RoleType",
    "ServerPublicNetworkAccessState",
    "ServerSecurityAlertPolicyState",
    "SingleServerCreateMode",
    "SingleServerIdentityProperties",
    "SingleServerSkuTier",
    "SingleServerVersion",
    "SkuTier",
    "SourceType",
    "SslEnforcementEnum",
    "SslMode",
    "StartDataMigration",
    "StorageAutoGrow",
    "StorageAutogrow",
    "StorageType",
    "TriggerCutover",
    "VirtualEndpointType",
]

@pulumi.type_token("azure-native:dbforpostgresql:ActiveDirectoryAuth")
class ActiveDirectoryAuth(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:AdministratorType")
class AdministratorType(_builtins.str, Enum):
    ACTIVE_DIRECTORY = ...

@pulumi.type_token(...)
class AzureManagedDiskPerformanceTier(_builtins.str, Enum):
    P1 = ...
    P2 = ...
    P3 = ...
    P4 = ...
    P6 = ...
    P10 = ...
    P15 = ...
    P20 = ...
    P30 = ...
    P40 = ...
    P50 = ...
    P60 = ...
    P70 = ...
    P80 = ...

@pulumi.type_token("azure-native:dbforpostgresql:Cancel")
class Cancel(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:CreateMode")
class CreateMode(_builtins.str, Enum):
    DEFAULT = ...
    CREATE = ...
    UPDATE = ...
    POINT_IN_TIME_RESTORE = ...
    GEO_RESTORE = ...
    REPLICA = ...
    REVIVE_DROPPED = ...

@pulumi.type_token("azure-native:dbforpostgresql:DataEncryptionType")
class DataEncryptionType(_builtins.str, Enum):
    AZURE_KEY_VAULT = ...
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:dbforpostgresql:GeoRedundantBackup")
class GeoRedundantBackup(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class GeographicallyRedundantBackup(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:IdentityType")
class IdentityType(_builtins.str, Enum):
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED = ...

@pulumi.type_token(...)
class InfrastructureEncryption(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class LogicalReplicationOnSourceServer(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:MicrosoftEntraAuth")
class MicrosoftEntraAuth(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class MigrateRolesAndPermissions(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:MigrationMode")
class MigrationMode(_builtins.str, Enum):
    OFFLINE = ...
    ONLINE = ...

@pulumi.type_token("azure-native:dbforpostgresql:MigrationOption")
class MigrationOption(_builtins.str, Enum):
    VALIDATE = ...
    MIGRATE = ...
    VALIDATE_AND_MIGRATE = ...

@pulumi.type_token("azure-native:dbforpostgresql:MinimalTlsVersionEnum")
class MinimalTlsVersionEnum(_builtins.str, Enum):
    TLS1_0 = ...
    TLS1_1 = ...
    TLS1_2 = ...
    TLS_ENFORCEMENT_DISABLED = ...

@pulumi.type_token(...)
class OverwriteDatabasesOnTargetServer(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:PasswordAuth")
class PasswordAuth(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:PasswordBasedAuth")
class PasswordBasedAuth(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class PostgreSqlFlexibleServerHighAvailabilityMode(_builtins.str, Enum):
    DISABLED = ...
    ZONE_REDUNDANT = ...
    SAME_ZONE = ...

@pulumi.type_token("azure-native:dbforpostgresql:PostgresMajorVersion")
class PostgresMajorVersion(_builtins.str, Enum):
    POSTGRES_MAJOR_VERSION_18 = ...
    POSTGRES_MAJOR_VERSION_17 = ...
    POSTGRES_MAJOR_VERSION_16 = ...
    POSTGRES_MAJOR_VERSION_15 = ...
    POSTGRES_MAJOR_VERSION_14 = ...
    POSTGRES_MAJOR_VERSION_13 = ...
    POSTGRES_MAJOR_VERSION_12 = ...
    POSTGRES_MAJOR_VERSION_11 = ...

@pulumi.type_token("azure-native:dbforpostgresql:PrincipalType")
class PrincipalType(_builtins.str, Enum):
    USER = ...
    SERVICE_PRINCIPAL = ...
    GROUP = ...

@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...

@pulumi.type_token(...)
class PublicNetworkAccessEnum(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class ReadReplicaPromoteMode(_builtins.str, Enum):
    STANDALONE = ...
    SWITCHOVER = ...

@pulumi.type_token(...)
class ReadReplicaPromoteOption(_builtins.str, Enum):
    PLANNED = ...
    FORCED = ...

@pulumi.type_token("azure-native:dbforpostgresql:ReplicationRole")
class ReplicationRole(_builtins.str, Enum):
    NONE = ...
    PRIMARY = ...
    ASYNC_REPLICA = ...
    GEO_ASYNC_REPLICA = ...

@pulumi.type_token("azure-native:dbforpostgresql:RoleType")
class RoleType(_builtins.str, Enum):
    USER = ...
    ADMIN = ...

@pulumi.type_token(...)
class ServerPublicNetworkAccessState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class ServerSecurityAlertPolicyState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class SingleServerCreateMode(_builtins.str, Enum):
    DEFAULT = ...
    POINT_IN_TIME_RESTORE = ...
    GEO_RESTORE = ...
    REPLICA = ...

@pulumi.type_token(...)
class SingleServerIdentityProperties(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:dbforpostgresql:SingleServerSkuTier")
class SingleServerSkuTier(_builtins.str, Enum):
    BASIC = ...
    GENERAL_PURPOSE = ...
    MEMORY_OPTIMIZED = ...

@pulumi.type_token("azure-native:dbforpostgresql:SingleServerVersion")
class SingleServerVersion(_builtins.str, Enum):
    SINGLE_SERVER_VERSION_9_5 = ...
    SINGLE_SERVER_VERSION_9_6 = ...
    SINGLE_SERVER_VERSION_10 = ...
    SINGLE_SERVER_VERSION_10_0 = ...
    SINGLE_SERVER_VERSION_10_2 = ...
    SINGLE_SERVER_VERSION_11 = ...

@pulumi.type_token("azure-native:dbforpostgresql:SkuTier")
class SkuTier(_builtins.str, Enum):
    BURSTABLE = ...
    GENERAL_PURPOSE = ...
    MEMORY_OPTIMIZED = ...

@pulumi.type_token("azure-native:dbforpostgresql:SourceType")
class SourceType(_builtins.str, Enum):
    ON_PREMISES = ...
    AWS = ...
    GCP = ...
    AZURE_VM = ...
    POSTGRE_SQL_SINGLE_SERVER = ...
    AW_S_RDS = ...
    AW_S_AURORA = ...
    AW_S_EC2 = ...
    GC_P_CLOUD_SQL = ...
    GC_P_ALLOY_DB = ...
    GC_P_COMPUTE = ...
    EDB = ...
    ED_B_ORACLE_SERVER = ...
    ED_B_POSTGRE_SQL = ...
    POSTGRE_SQL_FLEXIBLE_SERVER = ...
    POSTGRE_SQL_COSMOS_DB = ...
    HUAWEI_RDS = ...
    HUAWEI_COMPUTE = ...
    HEROKU_POSTGRE_SQL = ...
    CRUNCHY_POSTGRE_SQL = ...
    APSARA_D_B_RDS = ...
    DIGITAL_OCEAN_DROPLETS = ...
    DIGITAL_OCEAN_POSTGRE_SQL = ...
    SUPABASE_POSTGRE_SQL = ...

@pulumi.type_token("azure-native:dbforpostgresql:SslEnforcementEnum")
class SslEnforcementEnum(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:SslMode")
class SslMode(_builtins.str, Enum):
    PREFER = ...
    REQUIRE = ...
    VERIFY_CA = ...
    VERIFY_FULL = ...

@pulumi.type_token("azure-native:dbforpostgresql:StartDataMigration")
class StartDataMigration(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:StorageAutoGrow")
class StorageAutoGrow(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:StorageAutogrow")
class StorageAutogrow(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dbforpostgresql:StorageType")
class StorageType(_builtins.str, Enum):
    PREMIUM_LRS = ...
    PREMIUM_V2_LRS = ...
    ULTRA_SS_D_LRS = ...

@pulumi.type_token("azure-native:dbforpostgresql:TriggerCutover")
class TriggerCutover(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:dbforpostgresql:VirtualEndpointType")
class VirtualEndpointType(_builtins.str, Enum):
    READ_WRITE = ...
