

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AuthType', 'ConnectorClass', 'ConnectorServiceType', 'ConnectorStatus', 'ConnectorType', 'DataFormatType', 'Package', 'PartnerConnectorType', 'SaaSOfferStatus']
@pulumi.type_token("azure-native:confluent:AuthType")
class AuthType(_builtins.str, Enum):
    
    SERVIC_E_ACCOUNT = ...
    KAFK_A_AP_I_KEY = ...


@pulumi.type_token("azure-native:confluent:ConnectorClass")
class ConnectorClass(_builtins.str, Enum):
    
    AZUREBLOBSOURCE = ...
    AZUREBLOBSINK = ...


@pulumi.type_token("azure-native:confluent:ConnectorServiceType")
class ConnectorServiceType(_builtins.str, Enum):
    
    AZURE_BLOB_STORAGE_SINK_CONNECTOR = ...
    AZURE_BLOB_STORAGE_SOURCE_CONNECTOR = ...
    AZURE_COSMOS_DB_SINK_CONNECTOR = ...
    AZURE_COSMOS_DB_SOURCE_CONNECTOR = ...
    AZURE_SYNAPSE_ANALYTICS_SINK_CONNECTOR = ...


@pulumi.type_token("azure-native:confluent:ConnectorStatus")
class ConnectorStatus(_builtins.str, Enum):
    
    PROVISIONING = ...
    RUNNING = ...
    PAUSED = ...
    FAILED = ...


@pulumi.type_token("azure-native:confluent:ConnectorType")
class ConnectorType(_builtins.str, Enum):
    
    SINK = ...
    SOURCE = ...


@pulumi.type_token("azure-native:confluent:DataFormatType")
class DataFormatType(_builtins.str, Enum):
    
    AVRO = ...
    JSON = ...
    STRING = ...
    BYTES = ...
    PROTOBUF = ...


@pulumi.type_token("azure-native:confluent:Package")
class Package(_builtins.str, Enum):
    
    ESSENTIALS = ...
    ADVANCED = ...


@pulumi.type_token("azure-native:confluent:PartnerConnectorType")
class PartnerConnectorType(_builtins.str, Enum):
    
    KAFKA_AZURE_BLOB_STORAGE_SOURCE = ...
    KAFKA_AZURE_BLOB_STORAGE_SINK = ...
    KAFKA_AZURE_COSMOS_DB_SOURCE = ...
    KAFKA_AZURE_COSMOS_DB_SINK = ...
    KAFKA_AZURE_SYNAPSE_ANALYTICS_SINK = ...


@pulumi.type_token("azure-native:confluent:SaaSOfferStatus")
class SaaSOfferStatus(_builtins.str, Enum):
    
    STARTED = ...
    PENDING_FULFILLMENT_START = ...
    IN_PROGRESS = ...
    SUBSCRIBED = ...
    SUSPENDED = ...
    REINSTATED = ...
    SUCCEEDED = ...
    FAILED = ...
    UNSUBSCRIBED = ...
    UPDATING = ...


