import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "CustomImageOsType",
    "EnableStatus",
    "EnvironmentPermission",
    "HostCachingOptions",
    "LinuxOsState",
    "ManagedIdentityType",
    "NotificationChannelEventType",
    "PolicyEvaluatorType",
    "PolicyFactName",
    "PolicyStatus",
    "PremiumDataDisk",
    "SourceControlType",
    "StorageType",
    "TransportProtocol",
    "UsagePermissionType",
    "WindowsOsState",
]

@pulumi.type_token("azure-native:devtestlab:CustomImageOsType")
class CustomImageOsType(_builtins.str, Enum):
    WINDOWS = ...
    LINUX = ...
    NONE = ...

@pulumi.type_token("azure-native:devtestlab:EnableStatus")
class EnableStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:devtestlab:EnvironmentPermission")
class EnvironmentPermission(_builtins.str, Enum):
    READER = ...
    CONTRIBUTOR = ...

@pulumi.type_token("azure-native:devtestlab:HostCachingOptions")
class HostCachingOptions(_builtins.str, Enum):
    NONE = ...
    READ_ONLY = ...
    READ_WRITE = ...

@pulumi.type_token("azure-native:devtestlab:LinuxOsState")
class LinuxOsState(_builtins.str, Enum):
    NON_DEPROVISIONED = ...
    DEPROVISION_REQUESTED = ...
    DEPROVISION_APPLIED = ...

@pulumi.type_token("azure-native:devtestlab:ManagedIdentityType")
class ManagedIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token(...)
class NotificationChannelEventType(_builtins.str, Enum):
    AUTO_SHUTDOWN = ...
    COST = ...

@pulumi.type_token("azure-native:devtestlab:PolicyEvaluatorType")
class PolicyEvaluatorType(_builtins.str, Enum):
    ALLOWED_VALUES_POLICY = ...
    MAX_VALUE_POLICY = ...

@pulumi.type_token("azure-native:devtestlab:PolicyFactName")
class PolicyFactName(_builtins.str, Enum):
    USER_OWNED_LAB_VM_COUNT = ...
    USER_OWNED_LAB_PREMIUM_VM_COUNT = ...
    LAB_VM_COUNT = ...
    LAB_PREMIUM_VM_COUNT = ...
    LAB_VM_SIZE = ...
    GALLERY_IMAGE = ...
    USER_OWNED_LAB_VM_COUNT_IN_SUBNET = ...
    LAB_TARGET_COST = ...
    ENVIRONMENT_TEMPLATE = ...
    SCHEDULE_EDIT_PERMISSION = ...

@pulumi.type_token("azure-native:devtestlab:PolicyStatus")
class PolicyStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:devtestlab:PremiumDataDisk")
class PremiumDataDisk(_builtins.str, Enum):
    DISABLED = ...
    ENABLED = ...

@pulumi.type_token("azure-native:devtestlab:SourceControlType")
class SourceControlType(_builtins.str, Enum):
    VSO_GIT = ...
    GIT_HUB = ...
    STORAGE_ACCOUNT = ...

@pulumi.type_token("azure-native:devtestlab:StorageType")
class StorageType(_builtins.str, Enum):
    STANDARD = ...
    PREMIUM = ...
    STANDARD_SSD = ...

@pulumi.type_token("azure-native:devtestlab:TransportProtocol")
class TransportProtocol(_builtins.str, Enum):
    TCP = ...
    UDP = ...

@pulumi.type_token("azure-native:devtestlab:UsagePermissionType")
class UsagePermissionType(_builtins.str, Enum):
    DEFAULT = ...
    DENY = ...
    ALLOW = ...

@pulumi.type_token("azure-native:devtestlab:WindowsOsState")
class WindowsOsState(_builtins.str, Enum):
    NON_SYSPREPPED = ...
    SYSPREP_REQUESTED = ...
    SYSPREP_APPLIED = ...
