

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['Action', 'Architecture', 'ContentType', 'CredentialType', 'DraftPackageSourceType', 'Engagements', 'FileUploadResourceType', 'ImageArchitecture', 'ImageOSState', 'ImageSecurityType', 'ImageSource', 'InteropExecutionMode', 'IntuneExtractStatus', 'PackageStudioTabs', 'RequestTypes', 'SystemAssignedServiceIdentityType', 'TestType', 'Tier']
@pulumi.type_token("azure-native:testbase:Action")
class Action(_builtins.str, Enum):
    
    INSTALL = ...
    LAUNCH = ...
    CLOSE = ...
    UNINSTALL = ...
    CUSTOM = ...
    FLOW_DRIVEN_CUSTOM = ...


@pulumi.type_token("azure-native:testbase:Architecture")
class Architecture(_builtins.str, Enum):
    
    X86 = ...
    X64 = ...
    ARM64 = ...


@pulumi.type_token("azure-native:testbase:ContentType")
class ContentType(_builtins.str, Enum):
    
    INLINE = ...
    FILE = ...
    PATH = ...


@pulumi.type_token("azure-native:testbase:CredentialType")
class CredentialType(_builtins.str, Enum):
    
    INTUNE_ACCOUNT = ...


@pulumi.type_token("azure-native:testbase:DraftPackageSourceType")
class DraftPackageSourceType(_builtins.str, Enum):
    
    NATIVE = ...
    INTUNE_WIN = ...
    TEST_BASE_PACKAGE = ...
    GALLERY_APP = ...
    INTUNE_ENROLLMENT = ...


@pulumi.type_token("azure-native:testbase:Engagements")
class Engagements(_builtins.str, Enum):
    MVI = ...
    MVP = ...
    SUVP = ...
    MAPP = ...
    OTHER = ...


@pulumi.type_token("azure-native:testbase:FileUploadResourceType")
class FileUploadResourceType(_builtins.str, Enum):
    
    PACKAGE = ...
    VHD = ...


@pulumi.type_token("azure-native:testbase:ImageArchitecture")
class ImageArchitecture(_builtins.str, Enum):
    
    X64 = ...


@pulumi.type_token("azure-native:testbase:ImageOSState")
class ImageOSState(_builtins.str, Enum):
    
    GENERALIZED = ...
    SPECIALIZED = ...


@pulumi.type_token("azure-native:testbase:ImageSecurityType")
class ImageSecurityType(_builtins.str, Enum):
    
    STANDARD = ...
    TRUSTED_LAUNCH = ...


@pulumi.type_token("azure-native:testbase:ImageSource")
class ImageSource(_builtins.str, Enum):
    
    UNKNOWN = ...
    VHD = ...


@pulumi.type_token("azure-native:testbase:InteropExecutionMode")
class InteropExecutionMode(_builtins.str, Enum):
    
    FIRST_PARTY_APP_WITH_TESTS = ...
    FIRST_PARTY_APP = ...


@pulumi.type_token("azure-native:testbase:IntuneExtractStatus")
class IntuneExtractStatus(_builtins.str, Enum):
    
    READY = ...
    UPLOADING = ...
    UPLOAD_FAILED = ...
    EXTRACT_FAILED = ...
    NO_DEPENDENCY_APP = ...


@pulumi.type_token("azure-native:testbase:PackageStudioTabs")
class PackageStudioTabs(_builtins.str, Enum):
    
    UNSPECIFIED = ...
    BASICS_TAB = ...
    CONFIGURE_TEST_TAB = ...
    EDIT_PACKAGE_TAB = ...
    TEST_MATRIX_TAB = ...
    TAGS_TAB = ...
    REVIEW_AND_CREATE_TAB = ...


@pulumi.type_token("azure-native:testbase:RequestTypes")
class RequestTypes(_builtins.str, Enum):
    PRE_RELEASE_ACCESS = ...


@pulumi.type_token(...)
class SystemAssignedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...


@pulumi.type_token("azure-native:testbase:TestType")
class TestType(_builtins.str, Enum):
    
    OUT_OF_BOX_TEST = ...
    FUNCTIONAL_TEST = ...
    FLOW_DRIVEN_TEST = ...


@pulumi.type_token("azure-native:testbase:Tier")
class Tier(_builtins.str, Enum):
    
    STANDARD = ...


