import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetPackageResult",
    "AwaitableGetPackageResult",
    "get_package",
    "get_package_output",
]

@pulumi.output_type
class GetPackageResult:
    def __init__(
        __self__,
        application_name=...,
        azure_api_version=...,
        blob_path=...,
        draft_package_id=...,
        first_party_apps=...,
        flighting_ring=...,
        gallery_apps=...,
        id=...,
        inplace_upgrade_os_pair=...,
        intune_enrollment_metadata=...,
        is_enabled=...,
        last_modified_time=...,
        location=...,
        name=...,
        package_status=...,
        provisioning_state=...,
        system_data=...,
        tags=...,
        target_os_list=...,
        test_types=...,
        tests=...,
        type=...,
        validation_results=...,
        version=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="blobPath")
    def blob_path(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="draftPackageId")
    def draft_package_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="firstPartyApps")
    def first_party_apps(
        self,
    ) -> Optional[Sequence[outputs.FirstPartyAppDefinitionResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="flightingRing")
    def flighting_ring(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="galleryApps")
    def gallery_apps(self) -> Sequence[outputs.GalleryAppDefinitionResponse]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="inplaceUpgradeOSPair")
    def inplace_upgrade_os_pair(
        self,
    ) -> Optional[outputs.InplaceUpgradeOSInfoResponse]: ...
    @_builtins.property
    @pulumi.getter(name="intuneEnrollmentMetadata")
    def intune_enrollment_metadata(
        self,
    ) -> Optional[outputs.IntuneEnrollmentMetadataResponse]: ...
    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="lastModifiedTime")
    def last_modified_time(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="packageStatus")
    def package_status(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="targetOSList")
    def target_os_list(self) -> Optional[Sequence[outputs.TargetOSInfoResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="testTypes")
    def test_types(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def tests(self) -> Optional[Sequence[outputs.TestResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="validationResults")
    def validation_results(
        self,
    ) -> Sequence[outputs.PackageValidationResultResponse]: ...
    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str: ...

class AwaitableGetPackageResult(GetPackageResult):
    def __await__(self): ...

def get_package(
    package_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    test_base_account_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetPackageResult: ...
def get_package_output(
    package_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    test_base_account_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetPackageResult]: ...
