import builtins as _builtins
import sys
import pulumi
from typing import Any, Optional, Union, overload
from ._enums import *
from ._inputs import *

if sys.version_info >= (3, 11): ...
else: ...
__all__ = ["LinkedServiceArgs", "LinkedService"]

@pulumi.input_type
class LinkedServiceArgs:
    def __init__(
        __self__,
        *,
        factory_name: pulumi.Input[_builtins.str],
        properties: pulumi.Input[
            Union[
                AmazonMWSLinkedServiceArgs,
                AmazonRdsForOracleLinkedServiceArgs,
                AmazonRdsForSqlServerLinkedServiceArgs,
                AmazonRedshiftLinkedServiceArgs,
                AmazonS3CompatibleLinkedServiceArgs,
                AmazonS3LinkedServiceArgs,
                AppFiguresLinkedServiceArgs,
                AsanaLinkedServiceArgs,
                AzureBatchLinkedServiceArgs,
                AzureBlobFSLinkedServiceArgs,
                AzureBlobStorageLinkedServiceArgs,
                AzureDataExplorerLinkedServiceArgs,
                AzureDataLakeAnalyticsLinkedServiceArgs,
                AzureDataLakeStoreLinkedServiceArgs,
                AzureDatabricksDeltaLakeLinkedServiceArgs,
                AzureDatabricksLinkedServiceArgs,
                AzureFileStorageLinkedServiceArgs,
                AzureFunctionLinkedServiceArgs,
                AzureKeyVaultLinkedServiceArgs,
                AzureMLLinkedServiceArgs,
                AzureMLServiceLinkedServiceArgs,
                AzureMariaDBLinkedServiceArgs,
                AzureMySqlLinkedServiceArgs,
                AzurePostgreSqlLinkedServiceArgs,
                AzureSearchLinkedServiceArgs,
                AzureSqlDWLinkedServiceArgs,
                AzureSqlDatabaseLinkedServiceArgs,
                AzureSqlMILinkedServiceArgs,
                AzureStorageLinkedServiceArgs,
                AzureSynapseArtifactsLinkedServiceArgs,
                AzureTableStorageLinkedServiceArgs,
                CassandraLinkedServiceArgs,
                CommonDataServiceForAppsLinkedServiceArgs,
                ConcurLinkedServiceArgs,
                CosmosDbLinkedServiceArgs,
                CosmosDbMongoDbApiLinkedServiceArgs,
                CouchbaseLinkedServiceArgs,
                CustomDataSourceLinkedServiceArgs,
                DataworldLinkedServiceArgs,
                Db2LinkedServiceArgs,
                DrillLinkedServiceArgs,
                DynamicsAXLinkedServiceArgs,
                DynamicsCrmLinkedServiceArgs,
                DynamicsLinkedServiceArgs,
                EloquaLinkedServiceArgs,
                FileServerLinkedServiceArgs,
                FtpServerLinkedServiceArgs,
                GoogleAdWordsLinkedServiceArgs,
                GoogleBigQueryLinkedServiceArgs,
                GoogleBigQueryV2LinkedServiceArgs,
                GoogleCloudStorageLinkedServiceArgs,
                GoogleSheetsLinkedServiceArgs,
                GreenplumLinkedServiceArgs,
                HBaseLinkedServiceArgs,
                HDInsightLinkedServiceArgs,
                HDInsightOnDemandLinkedServiceArgs,
                HdfsLinkedServiceArgs,
                HiveLinkedServiceArgs,
                HttpLinkedServiceArgs,
                HubspotLinkedServiceArgs,
                ImpalaLinkedServiceArgs,
                InformixLinkedServiceArgs,
                JiraLinkedServiceArgs,
                LakeHouseLinkedServiceArgs,
                MagentoLinkedServiceArgs,
                MariaDBLinkedServiceArgs,
                MarketoLinkedServiceArgs,
                MicrosoftAccessLinkedServiceArgs,
                MongoDbAtlasLinkedServiceArgs,
                MongoDbLinkedServiceArgs,
                MongoDbV2LinkedServiceArgs,
                MySqlLinkedServiceArgs,
                NetezzaLinkedServiceArgs,
                ODataLinkedServiceArgs,
                OdbcLinkedServiceArgs,
                Office365LinkedServiceArgs,
                OracleCloudStorageLinkedServiceArgs,
                OracleLinkedServiceArgs,
                OracleServiceCloudLinkedServiceArgs,
                PaypalLinkedServiceArgs,
                PhoenixLinkedServiceArgs,
                PostgreSqlLinkedServiceArgs,
                PostgreSqlV2LinkedServiceArgs,
                PrestoLinkedServiceArgs,
                QuickBooksLinkedServiceArgs,
                QuickbaseLinkedServiceArgs,
                ResponsysLinkedServiceArgs,
                RestServiceLinkedServiceArgs,
                SalesforceLinkedServiceArgs,
                SalesforceMarketingCloudLinkedServiceArgs,
                SalesforceServiceCloudLinkedServiceArgs,
                SalesforceServiceCloudV2LinkedServiceArgs,
                SalesforceV2LinkedServiceArgs,
                SapBWLinkedServiceArgs,
                SapCloudForCustomerLinkedServiceArgs,
                SapEccLinkedServiceArgs,
                SapHanaLinkedServiceArgs,
                SapOdpLinkedServiceArgs,
                SapOpenHubLinkedServiceArgs,
                SapTableLinkedServiceArgs,
                ServiceNowLinkedServiceArgs,
                ServiceNowV2LinkedServiceArgs,
                SftpServerLinkedServiceArgs,
                SharePointOnlineListLinkedServiceArgs,
                ShopifyLinkedServiceArgs,
                SmartsheetLinkedServiceArgs,
                SnowflakeLinkedServiceArgs,
                SnowflakeV2LinkedServiceArgs,
                SparkLinkedServiceArgs,
                SqlServerLinkedServiceArgs,
                SquareLinkedServiceArgs,
                SybaseLinkedServiceArgs,
                TeamDeskLinkedServiceArgs,
                TeradataLinkedServiceArgs,
                TwilioLinkedServiceArgs,
                VerticaLinkedServiceArgs,
                WarehouseLinkedServiceArgs,
                WebLinkedServiceArgs,
                XeroLinkedServiceArgs,
                ZendeskLinkedServiceArgs,
                ZohoLinkedServiceArgs,
            ]
        ],
        resource_group_name: pulumi.Input[_builtins.str],
        linked_service_name: Optional[pulumi.Input[_builtins.str]] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="factoryName")
    def factory_name(self) -> pulumi.Input[_builtins.str]: ...
    @factory_name.setter
    def factory_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter
    def properties(
        self,
    ) -> pulumi.Input[
        Union[
            AmazonMWSLinkedServiceArgs,
            AmazonRdsForOracleLinkedServiceArgs,
            AmazonRdsForSqlServerLinkedServiceArgs,
            AmazonRedshiftLinkedServiceArgs,
            AmazonS3CompatibleLinkedServiceArgs,
            AmazonS3LinkedServiceArgs,
            AppFiguresLinkedServiceArgs,
            AsanaLinkedServiceArgs,
            AzureBatchLinkedServiceArgs,
            AzureBlobFSLinkedServiceArgs,
            AzureBlobStorageLinkedServiceArgs,
            AzureDataExplorerLinkedServiceArgs,
            AzureDataLakeAnalyticsLinkedServiceArgs,
            AzureDataLakeStoreLinkedServiceArgs,
            AzureDatabricksDeltaLakeLinkedServiceArgs,
            AzureDatabricksLinkedServiceArgs,
            AzureFileStorageLinkedServiceArgs,
            AzureFunctionLinkedServiceArgs,
            AzureKeyVaultLinkedServiceArgs,
            AzureMLLinkedServiceArgs,
            AzureMLServiceLinkedServiceArgs,
            AzureMariaDBLinkedServiceArgs,
            AzureMySqlLinkedServiceArgs,
            AzurePostgreSqlLinkedServiceArgs,
            AzureSearchLinkedServiceArgs,
            AzureSqlDWLinkedServiceArgs,
            AzureSqlDatabaseLinkedServiceArgs,
            AzureSqlMILinkedServiceArgs,
            AzureStorageLinkedServiceArgs,
            AzureSynapseArtifactsLinkedServiceArgs,
            AzureTableStorageLinkedServiceArgs,
            CassandraLinkedServiceArgs,
            CommonDataServiceForAppsLinkedServiceArgs,
            ConcurLinkedServiceArgs,
            CosmosDbLinkedServiceArgs,
            CosmosDbMongoDbApiLinkedServiceArgs,
            CouchbaseLinkedServiceArgs,
            CustomDataSourceLinkedServiceArgs,
            DataworldLinkedServiceArgs,
            Db2LinkedServiceArgs,
            DrillLinkedServiceArgs,
            DynamicsAXLinkedServiceArgs,
            DynamicsCrmLinkedServiceArgs,
            DynamicsLinkedServiceArgs,
            EloquaLinkedServiceArgs,
            FileServerLinkedServiceArgs,
            FtpServerLinkedServiceArgs,
            GoogleAdWordsLinkedServiceArgs,
            GoogleBigQueryLinkedServiceArgs,
            GoogleBigQueryV2LinkedServiceArgs,
            GoogleCloudStorageLinkedServiceArgs,
            GoogleSheetsLinkedServiceArgs,
            GreenplumLinkedServiceArgs,
            HBaseLinkedServiceArgs,
            HDInsightLinkedServiceArgs,
            HDInsightOnDemandLinkedServiceArgs,
            HdfsLinkedServiceArgs,
            HiveLinkedServiceArgs,
            HttpLinkedServiceArgs,
            HubspotLinkedServiceArgs,
            ImpalaLinkedServiceArgs,
            InformixLinkedServiceArgs,
            JiraLinkedServiceArgs,
            LakeHouseLinkedServiceArgs,
            MagentoLinkedServiceArgs,
            MariaDBLinkedServiceArgs,
            MarketoLinkedServiceArgs,
            MicrosoftAccessLinkedServiceArgs,
            MongoDbAtlasLinkedServiceArgs,
            MongoDbLinkedServiceArgs,
            MongoDbV2LinkedServiceArgs,
            MySqlLinkedServiceArgs,
            NetezzaLinkedServiceArgs,
            ODataLinkedServiceArgs,
            OdbcLinkedServiceArgs,
            Office365LinkedServiceArgs,
            OracleCloudStorageLinkedServiceArgs,
            OracleLinkedServiceArgs,
            OracleServiceCloudLinkedServiceArgs,
            PaypalLinkedServiceArgs,
            PhoenixLinkedServiceArgs,
            PostgreSqlLinkedServiceArgs,
            PostgreSqlV2LinkedServiceArgs,
            PrestoLinkedServiceArgs,
            QuickBooksLinkedServiceArgs,
            QuickbaseLinkedServiceArgs,
            ResponsysLinkedServiceArgs,
            RestServiceLinkedServiceArgs,
            SalesforceLinkedServiceArgs,
            SalesforceMarketingCloudLinkedServiceArgs,
            SalesforceServiceCloudLinkedServiceArgs,
            SalesforceServiceCloudV2LinkedServiceArgs,
            SalesforceV2LinkedServiceArgs,
            SapBWLinkedServiceArgs,
            SapCloudForCustomerLinkedServiceArgs,
            SapEccLinkedServiceArgs,
            SapHanaLinkedServiceArgs,
            SapOdpLinkedServiceArgs,
            SapOpenHubLinkedServiceArgs,
            SapTableLinkedServiceArgs,
            ServiceNowLinkedServiceArgs,
            ServiceNowV2LinkedServiceArgs,
            SftpServerLinkedServiceArgs,
            SharePointOnlineListLinkedServiceArgs,
            ShopifyLinkedServiceArgs,
            SmartsheetLinkedServiceArgs,
            SnowflakeLinkedServiceArgs,
            SnowflakeV2LinkedServiceArgs,
            SparkLinkedServiceArgs,
            SqlServerLinkedServiceArgs,
            SquareLinkedServiceArgs,
            SybaseLinkedServiceArgs,
            TeamDeskLinkedServiceArgs,
            TeradataLinkedServiceArgs,
            TwilioLinkedServiceArgs,
            VerticaLinkedServiceArgs,
            WarehouseLinkedServiceArgs,
            WebLinkedServiceArgs,
            XeroLinkedServiceArgs,
            ZendeskLinkedServiceArgs,
            ZohoLinkedServiceArgs,
        ]
    ]: ...
    @properties.setter
    def properties(
        self,
        value: pulumi.Input[
            Union[
                AmazonMWSLinkedServiceArgs,
                AmazonRdsForOracleLinkedServiceArgs,
                AmazonRdsForSqlServerLinkedServiceArgs,
                AmazonRedshiftLinkedServiceArgs,
                AmazonS3CompatibleLinkedServiceArgs,
                AmazonS3LinkedServiceArgs,
                AppFiguresLinkedServiceArgs,
                AsanaLinkedServiceArgs,
                AzureBatchLinkedServiceArgs,
                AzureBlobFSLinkedServiceArgs,
                AzureBlobStorageLinkedServiceArgs,
                AzureDataExplorerLinkedServiceArgs,
                AzureDataLakeAnalyticsLinkedServiceArgs,
                AzureDataLakeStoreLinkedServiceArgs,
                AzureDatabricksDeltaLakeLinkedServiceArgs,
                AzureDatabricksLinkedServiceArgs,
                AzureFileStorageLinkedServiceArgs,
                AzureFunctionLinkedServiceArgs,
                AzureKeyVaultLinkedServiceArgs,
                AzureMLLinkedServiceArgs,
                AzureMLServiceLinkedServiceArgs,
                AzureMariaDBLinkedServiceArgs,
                AzureMySqlLinkedServiceArgs,
                AzurePostgreSqlLinkedServiceArgs,
                AzureSearchLinkedServiceArgs,
                AzureSqlDWLinkedServiceArgs,
                AzureSqlDatabaseLinkedServiceArgs,
                AzureSqlMILinkedServiceArgs,
                AzureStorageLinkedServiceArgs,
                AzureSynapseArtifactsLinkedServiceArgs,
                AzureTableStorageLinkedServiceArgs,
                CassandraLinkedServiceArgs,
                CommonDataServiceForAppsLinkedServiceArgs,
                ConcurLinkedServiceArgs,
                CosmosDbLinkedServiceArgs,
                CosmosDbMongoDbApiLinkedServiceArgs,
                CouchbaseLinkedServiceArgs,
                CustomDataSourceLinkedServiceArgs,
                DataworldLinkedServiceArgs,
                Db2LinkedServiceArgs,
                DrillLinkedServiceArgs,
                DynamicsAXLinkedServiceArgs,
                DynamicsCrmLinkedServiceArgs,
                DynamicsLinkedServiceArgs,
                EloquaLinkedServiceArgs,
                FileServerLinkedServiceArgs,
                FtpServerLinkedServiceArgs,
                GoogleAdWordsLinkedServiceArgs,
                GoogleBigQueryLinkedServiceArgs,
                GoogleBigQueryV2LinkedServiceArgs,
                GoogleCloudStorageLinkedServiceArgs,
                GoogleSheetsLinkedServiceArgs,
                GreenplumLinkedServiceArgs,
                HBaseLinkedServiceArgs,
                HDInsightLinkedServiceArgs,
                HDInsightOnDemandLinkedServiceArgs,
                HdfsLinkedServiceArgs,
                HiveLinkedServiceArgs,
                HttpLinkedServiceArgs,
                HubspotLinkedServiceArgs,
                ImpalaLinkedServiceArgs,
                InformixLinkedServiceArgs,
                JiraLinkedServiceArgs,
                LakeHouseLinkedServiceArgs,
                MagentoLinkedServiceArgs,
                MariaDBLinkedServiceArgs,
                MarketoLinkedServiceArgs,
                MicrosoftAccessLinkedServiceArgs,
                MongoDbAtlasLinkedServiceArgs,
                MongoDbLinkedServiceArgs,
                MongoDbV2LinkedServiceArgs,
                MySqlLinkedServiceArgs,
                NetezzaLinkedServiceArgs,
                ODataLinkedServiceArgs,
                OdbcLinkedServiceArgs,
                Office365LinkedServiceArgs,
                OracleCloudStorageLinkedServiceArgs,
                OracleLinkedServiceArgs,
                OracleServiceCloudLinkedServiceArgs,
                PaypalLinkedServiceArgs,
                PhoenixLinkedServiceArgs,
                PostgreSqlLinkedServiceArgs,
                PostgreSqlV2LinkedServiceArgs,
                PrestoLinkedServiceArgs,
                QuickBooksLinkedServiceArgs,
                QuickbaseLinkedServiceArgs,
                ResponsysLinkedServiceArgs,
                RestServiceLinkedServiceArgs,
                SalesforceLinkedServiceArgs,
                SalesforceMarketingCloudLinkedServiceArgs,
                SalesforceServiceCloudLinkedServiceArgs,
                SalesforceServiceCloudV2LinkedServiceArgs,
                SalesforceV2LinkedServiceArgs,
                SapBWLinkedServiceArgs,
                SapCloudForCustomerLinkedServiceArgs,
                SapEccLinkedServiceArgs,
                SapHanaLinkedServiceArgs,
                SapOdpLinkedServiceArgs,
                SapOpenHubLinkedServiceArgs,
                SapTableLinkedServiceArgs,
                ServiceNowLinkedServiceArgs,
                ServiceNowV2LinkedServiceArgs,
                SftpServerLinkedServiceArgs,
                SharePointOnlineListLinkedServiceArgs,
                ShopifyLinkedServiceArgs,
                SmartsheetLinkedServiceArgs,
                SnowflakeLinkedServiceArgs,
                SnowflakeV2LinkedServiceArgs,
                SparkLinkedServiceArgs,
                SqlServerLinkedServiceArgs,
                SquareLinkedServiceArgs,
                SybaseLinkedServiceArgs,
                TeamDeskLinkedServiceArgs,
                TeradataLinkedServiceArgs,
                TwilioLinkedServiceArgs,
                VerticaLinkedServiceArgs,
                WarehouseLinkedServiceArgs,
                WebLinkedServiceArgs,
                XeroLinkedServiceArgs,
                ZendeskLinkedServiceArgs,
                ZohoLinkedServiceArgs,
            ]
        ],
    ): ...
    @_builtins.property
    @pulumi.getter(name="resourceGroupName")
    def resource_group_name(self) -> pulumi.Input[_builtins.str]: ...
    @resource_group_name.setter
    def resource_group_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter(name="linkedServiceName")
    def linked_service_name(self) -> Optional[pulumi.Input[_builtins.str]]: ...
    @linked_service_name.setter
    def linked_service_name(self, value: Optional[pulumi.Input[_builtins.str]]): ...

@pulumi.type_token("azure-native:datafactory:LinkedService")
class LinkedService(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: Optional[pulumi.ResourceOptions] = ...,
        factory_name: Optional[pulumi.Input[_builtins.str]] = ...,
        linked_service_name: Optional[pulumi.Input[_builtins.str]] = ...,
        properties: Optional[
            pulumi.Input[
                Union[
                    Union[AmazonMWSLinkedServiceArgs, AmazonMWSLinkedServiceArgsDict],
                    Union[
                        AmazonRdsForOracleLinkedServiceArgs,
                        AmazonRdsForOracleLinkedServiceArgsDict,
                    ],
                    Union[
                        AmazonRdsForSqlServerLinkedServiceArgs,
                        AmazonRdsForSqlServerLinkedServiceArgsDict,
                    ],
                    Union[
                        AmazonRedshiftLinkedServiceArgs,
                        AmazonRedshiftLinkedServiceArgsDict,
                    ],
                    Union[
                        AmazonS3CompatibleLinkedServiceArgs,
                        AmazonS3CompatibleLinkedServiceArgsDict,
                    ],
                    Union[AmazonS3LinkedServiceArgs, AmazonS3LinkedServiceArgsDict],
                    Union[AppFiguresLinkedServiceArgs, AppFiguresLinkedServiceArgsDict],
                    Union[AsanaLinkedServiceArgs, AsanaLinkedServiceArgsDict],
                    Union[AzureBatchLinkedServiceArgs, AzureBatchLinkedServiceArgsDict],
                    Union[
                        AzureBlobFSLinkedServiceArgs, AzureBlobFSLinkedServiceArgsDict
                    ],
                    Union[
                        AzureBlobStorageLinkedServiceArgs,
                        AzureBlobStorageLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureDataExplorerLinkedServiceArgs,
                        AzureDataExplorerLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureDataLakeAnalyticsLinkedServiceArgs,
                        AzureDataLakeAnalyticsLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureDataLakeStoreLinkedServiceArgs,
                        AzureDataLakeStoreLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureDatabricksDeltaLakeLinkedServiceArgs,
                        AzureDatabricksDeltaLakeLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureDatabricksLinkedServiceArgs,
                        AzureDatabricksLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureFileStorageLinkedServiceArgs,
                        AzureFileStorageLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureFunctionLinkedServiceArgs,
                        AzureFunctionLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureKeyVaultLinkedServiceArgs,
                        AzureKeyVaultLinkedServiceArgsDict,
                    ],
                    Union[AzureMLLinkedServiceArgs, AzureMLLinkedServiceArgsDict],
                    Union[
                        AzureMLServiceLinkedServiceArgs,
                        AzureMLServiceLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureMariaDBLinkedServiceArgs, AzureMariaDBLinkedServiceArgsDict
                    ],
                    Union[AzureMySqlLinkedServiceArgs, AzureMySqlLinkedServiceArgsDict],
                    Union[
                        AzurePostgreSqlLinkedServiceArgs,
                        AzurePostgreSqlLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureSearchLinkedServiceArgs, AzureSearchLinkedServiceArgsDict
                    ],
                    Union[AzureSqlDWLinkedServiceArgs, AzureSqlDWLinkedServiceArgsDict],
                    Union[
                        AzureSqlDatabaseLinkedServiceArgs,
                        AzureSqlDatabaseLinkedServiceArgsDict,
                    ],
                    Union[AzureSqlMILinkedServiceArgs, AzureSqlMILinkedServiceArgsDict],
                    Union[
                        AzureStorageLinkedServiceArgs, AzureStorageLinkedServiceArgsDict
                    ],
                    Union[
                        AzureSynapseArtifactsLinkedServiceArgs,
                        AzureSynapseArtifactsLinkedServiceArgsDict,
                    ],
                    Union[
                        AzureTableStorageLinkedServiceArgs,
                        AzureTableStorageLinkedServiceArgsDict,
                    ],
                    Union[CassandraLinkedServiceArgs, CassandraLinkedServiceArgsDict],
                    Union[
                        CommonDataServiceForAppsLinkedServiceArgs,
                        CommonDataServiceForAppsLinkedServiceArgsDict,
                    ],
                    Union[ConcurLinkedServiceArgs, ConcurLinkedServiceArgsDict],
                    Union[CosmosDbLinkedServiceArgs, CosmosDbLinkedServiceArgsDict],
                    Union[
                        CosmosDbMongoDbApiLinkedServiceArgs,
                        CosmosDbMongoDbApiLinkedServiceArgsDict,
                    ],
                    Union[CouchbaseLinkedServiceArgs, CouchbaseLinkedServiceArgsDict],
                    Union[
                        CustomDataSourceLinkedServiceArgs,
                        CustomDataSourceLinkedServiceArgsDict,
                    ],
                    Union[DataworldLinkedServiceArgs, DataworldLinkedServiceArgsDict],
                    Union[Db2LinkedServiceArgs, Db2LinkedServiceArgsDict],
                    Union[DrillLinkedServiceArgs, DrillLinkedServiceArgsDict],
                    Union[DynamicsAXLinkedServiceArgs, DynamicsAXLinkedServiceArgsDict],
                    Union[
                        DynamicsCrmLinkedServiceArgs, DynamicsCrmLinkedServiceArgsDict
                    ],
                    Union[DynamicsLinkedServiceArgs, DynamicsLinkedServiceArgsDict],
                    Union[EloquaLinkedServiceArgs, EloquaLinkedServiceArgsDict],
                    Union[FileServerLinkedServiceArgs, FileServerLinkedServiceArgsDict],
                    Union[FtpServerLinkedServiceArgs, FtpServerLinkedServiceArgsDict],
                    Union[
                        GoogleAdWordsLinkedServiceArgs,
                        GoogleAdWordsLinkedServiceArgsDict,
                    ],
                    Union[
                        GoogleBigQueryLinkedServiceArgs,
                        GoogleBigQueryLinkedServiceArgsDict,
                    ],
                    Union[
                        GoogleBigQueryV2LinkedServiceArgs,
                        GoogleBigQueryV2LinkedServiceArgsDict,
                    ],
                    Union[
                        GoogleCloudStorageLinkedServiceArgs,
                        GoogleCloudStorageLinkedServiceArgsDict,
                    ],
                    Union[
                        GoogleSheetsLinkedServiceArgs, GoogleSheetsLinkedServiceArgsDict
                    ],
                    Union[GreenplumLinkedServiceArgs, GreenplumLinkedServiceArgsDict],
                    Union[HBaseLinkedServiceArgs, HBaseLinkedServiceArgsDict],
                    Union[HDInsightLinkedServiceArgs, HDInsightLinkedServiceArgsDict],
                    Union[
                        HDInsightOnDemandLinkedServiceArgs,
                        HDInsightOnDemandLinkedServiceArgsDict,
                    ],
                    Union[HdfsLinkedServiceArgs, HdfsLinkedServiceArgsDict],
                    Union[HiveLinkedServiceArgs, HiveLinkedServiceArgsDict],
                    Union[HttpLinkedServiceArgs, HttpLinkedServiceArgsDict],
                    Union[HubspotLinkedServiceArgs, HubspotLinkedServiceArgsDict],
                    Union[ImpalaLinkedServiceArgs, ImpalaLinkedServiceArgsDict],
                    Union[InformixLinkedServiceArgs, InformixLinkedServiceArgsDict],
                    Union[JiraLinkedServiceArgs, JiraLinkedServiceArgsDict],
                    Union[LakeHouseLinkedServiceArgs, LakeHouseLinkedServiceArgsDict],
                    Union[MagentoLinkedServiceArgs, MagentoLinkedServiceArgsDict],
                    Union[MariaDBLinkedServiceArgs, MariaDBLinkedServiceArgsDict],
                    Union[MarketoLinkedServiceArgs, MarketoLinkedServiceArgsDict],
                    Union[
                        MicrosoftAccessLinkedServiceArgs,
                        MicrosoftAccessLinkedServiceArgsDict,
                    ],
                    Union[
                        MongoDbAtlasLinkedServiceArgs, MongoDbAtlasLinkedServiceArgsDict
                    ],
                    Union[MongoDbLinkedServiceArgs, MongoDbLinkedServiceArgsDict],
                    Union[MongoDbV2LinkedServiceArgs, MongoDbV2LinkedServiceArgsDict],
                    Union[MySqlLinkedServiceArgs, MySqlLinkedServiceArgsDict],
                    Union[NetezzaLinkedServiceArgs, NetezzaLinkedServiceArgsDict],
                    Union[ODataLinkedServiceArgs, ODataLinkedServiceArgsDict],
                    Union[OdbcLinkedServiceArgs, OdbcLinkedServiceArgsDict],
                    Union[Office365LinkedServiceArgs, Office365LinkedServiceArgsDict],
                    Union[
                        OracleCloudStorageLinkedServiceArgs,
                        OracleCloudStorageLinkedServiceArgsDict,
                    ],
                    Union[OracleLinkedServiceArgs, OracleLinkedServiceArgsDict],
                    Union[
                        OracleServiceCloudLinkedServiceArgs,
                        OracleServiceCloudLinkedServiceArgsDict,
                    ],
                    Union[PaypalLinkedServiceArgs, PaypalLinkedServiceArgsDict],
                    Union[PhoenixLinkedServiceArgs, PhoenixLinkedServiceArgsDict],
                    Union[PostgreSqlLinkedServiceArgs, PostgreSqlLinkedServiceArgsDict],
                    Union[
                        PostgreSqlV2LinkedServiceArgs, PostgreSqlV2LinkedServiceArgsDict
                    ],
                    Union[PrestoLinkedServiceArgs, PrestoLinkedServiceArgsDict],
                    Union[QuickBooksLinkedServiceArgs, QuickBooksLinkedServiceArgsDict],
                    Union[QuickbaseLinkedServiceArgs, QuickbaseLinkedServiceArgsDict],
                    Union[ResponsysLinkedServiceArgs, ResponsysLinkedServiceArgsDict],
                    Union[
                        RestServiceLinkedServiceArgs, RestServiceLinkedServiceArgsDict
                    ],
                    Union[SalesforceLinkedServiceArgs, SalesforceLinkedServiceArgsDict],
                    Union[
                        SalesforceMarketingCloudLinkedServiceArgs,
                        SalesforceMarketingCloudLinkedServiceArgsDict,
                    ],
                    Union[
                        SalesforceServiceCloudLinkedServiceArgs,
                        SalesforceServiceCloudLinkedServiceArgsDict,
                    ],
                    Union[
                        SalesforceServiceCloudV2LinkedServiceArgs,
                        SalesforceServiceCloudV2LinkedServiceArgsDict,
                    ],
                    Union[
                        SalesforceV2LinkedServiceArgs, SalesforceV2LinkedServiceArgsDict
                    ],
                    Union[SapBWLinkedServiceArgs, SapBWLinkedServiceArgsDict],
                    Union[
                        SapCloudForCustomerLinkedServiceArgs,
                        SapCloudForCustomerLinkedServiceArgsDict,
                    ],
                    Union[SapEccLinkedServiceArgs, SapEccLinkedServiceArgsDict],
                    Union[SapHanaLinkedServiceArgs, SapHanaLinkedServiceArgsDict],
                    Union[SapOdpLinkedServiceArgs, SapOdpLinkedServiceArgsDict],
                    Union[SapOpenHubLinkedServiceArgs, SapOpenHubLinkedServiceArgsDict],
                    Union[SapTableLinkedServiceArgs, SapTableLinkedServiceArgsDict],
                    Union[ServiceNowLinkedServiceArgs, ServiceNowLinkedServiceArgsDict],
                    Union[
                        ServiceNowV2LinkedServiceArgs, ServiceNowV2LinkedServiceArgsDict
                    ],
                    Union[SftpServerLinkedServiceArgs, SftpServerLinkedServiceArgsDict],
                    Union[
                        SharePointOnlineListLinkedServiceArgs,
                        SharePointOnlineListLinkedServiceArgsDict,
                    ],
                    Union[ShopifyLinkedServiceArgs, ShopifyLinkedServiceArgsDict],
                    Union[SmartsheetLinkedServiceArgs, SmartsheetLinkedServiceArgsDict],
                    Union[SnowflakeLinkedServiceArgs, SnowflakeLinkedServiceArgsDict],
                    Union[
                        SnowflakeV2LinkedServiceArgs, SnowflakeV2LinkedServiceArgsDict
                    ],
                    Union[SparkLinkedServiceArgs, SparkLinkedServiceArgsDict],
                    Union[SqlServerLinkedServiceArgs, SqlServerLinkedServiceArgsDict],
                    Union[SquareLinkedServiceArgs, SquareLinkedServiceArgsDict],
                    Union[SybaseLinkedServiceArgs, SybaseLinkedServiceArgsDict],
                    Union[TeamDeskLinkedServiceArgs, TeamDeskLinkedServiceArgsDict],
                    Union[TeradataLinkedServiceArgs, TeradataLinkedServiceArgsDict],
                    Union[TwilioLinkedServiceArgs, TwilioLinkedServiceArgsDict],
                    Union[VerticaLinkedServiceArgs, VerticaLinkedServiceArgsDict],
                    Union[WarehouseLinkedServiceArgs, WarehouseLinkedServiceArgsDict],
                    Union[WebLinkedServiceArgs, WebLinkedServiceArgsDict],
                    Union[XeroLinkedServiceArgs, XeroLinkedServiceArgsDict],
                    Union[ZendeskLinkedServiceArgs, ZendeskLinkedServiceArgsDict],
                    Union[ZohoLinkedServiceArgs, ZohoLinkedServiceArgsDict],
                ]
            ]
        ] = ...,
        resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
        __props__=...,
    ) -> None: ...
    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: LinkedServiceArgs,
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> None: ...
    def __init__(__self__, resource_name: str, *args, **kwargs) -> None: ...
    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> LinkedService: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def etag(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> pulumi.Output[Any]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]: ...
