

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ContentSourceType', 'EncryptionKeySourceType', 'LinuxUpdateClasses', 'OperatingSystemType', 'ResourceIdentityType', 'RunbookTypeEnum', 'ScheduleDay', 'ScheduleFrequency', 'SkuNameEnum', 'SourceType', 'TagOperators', 'TokenType', 'WindowsUpdateClasses']
@pulumi.type_token("azure-native:automation:ContentSourceType")
class ContentSourceType(_builtins.str, Enum):
    
    EMBEDDED_CONTENT = ...
    URI = ...


@pulumi.type_token("azure-native:automation:EncryptionKeySourceType")
class EncryptionKeySourceType(_builtins.str, Enum):
    
    MICROSOFT_AUTOMATION = ...
    MICROSOFT_KEYVAULT = ...


@pulumi.type_token("azure-native:automation:LinuxUpdateClasses")
class LinuxUpdateClasses(_builtins.str, Enum):
    
    UNCLASSIFIED = ...
    CRITICAL = ...
    SECURITY = ...
    OTHER = ...


@pulumi.type_token("azure-native:automation:OperatingSystemType")
class OperatingSystemType(_builtins.str, Enum):
    
    WINDOWS = ...
    LINUX = ...


@pulumi.type_token("azure-native:automation:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:automation:RunbookTypeEnum")
class RunbookTypeEnum(_builtins.str, Enum):
    
    SCRIPT = ...
    GRAPH = ...
    POWER_SHELL_WORKFLOW = ...
    POWER_SHELL = ...
    GRAPH_POWER_SHELL_WORKFLOW = ...
    GRAPH_POWER_SHELL = ...
    PYTHON2 = ...
    PYTHON3 = ...
    PYTHON = ...
    POWER_SHELL72 = ...


@pulumi.type_token("azure-native:automation:ScheduleDay")
class ScheduleDay(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


@pulumi.type_token("azure-native:automation:ScheduleFrequency")
class ScheduleFrequency(_builtins.str, Enum):
    
    ONE_TIME = ...
    DAY = ...
    HOUR = ...
    WEEK = ...
    MONTH = ...
    MINUTE = ...


@pulumi.type_token("azure-native:automation:SkuNameEnum")
class SkuNameEnum(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...


@pulumi.type_token("azure-native:automation:SourceType")
class SourceType(_builtins.str, Enum):
    
    VSO_GIT = ...
    VSO_TFVC = ...
    GIT_HUB = ...


@pulumi.type_token("azure-native:automation:TagOperators")
class TagOperators(_builtins.str, Enum):
    
    ALL = ...
    ANY = ...


@pulumi.type_token("azure-native:automation:TokenType")
class TokenType(_builtins.str, Enum):
    
    PERSONAL_ACCESS_TOKEN = ...
    OAUTH = ...


@pulumi.type_token("azure-native:automation:WindowsUpdateClasses")
class WindowsUpdateClasses(_builtins.str, Enum):
    
    UNCLASSIFIED = ...
    CRITICAL = ...
    SECURITY = ...
    UPDATE_ROLLUP = ...
    FEATURE_PACK = ...
    SERVICE_PACK = ...
    DEFINITION = ...
    TOOLS = ...
    UPDATES = ...


