

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['CannedAcl']
@pulumi.type_token("aws:s3/CannedAcl:CannedAcl")
class CannedAcl(_builtins.str, Enum):
    
    PRIVATE = ...
    PUBLIC_READ = ...
    PUBLIC_READ_WRITE = ...
    AWS_EXEC_READ = ...
    AUTHENTICATED_READ = ...
    BUCKET_OWNER_READ = ...
    BUCKET_OWNER_FULL_CONTROL = ...
    LOG_DELIVERY_WRITE = ...


