import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ActionType",
    "AlertDetail",
    "AlertProperty",
    "AlertRuleKind",
    "AlertSeverity",
    "AttackTactic",
    "AutomationRuleBooleanConditionSupportedOperator",
    ...,
    ...,
    ...,
    ...,
    ...,
    ...,
    "AutomationRulePropertyConditionSupportedOperator",
    "AutomationRulePropertyConditionSupportedProperty",
    "CcpAuthType",
    "ConditionType",
    "ContentType",
    "CustomEntityQueryKind",
    "DataConnectorDefinitionKind",
    "DataConnectorKind",
    "DataTypeState",
    "DeploymentFetchStatus",
    "DeploymentResult",
    "DeploymentState",
    "EntityMappingType",
    "EntityProviders",
    "EntityTimelineKind",
    "EntityType",
    "EventGroupingAggregationKind",
    "FileFormat",
    "FileImportContentType",
    "Flag",
    "HttpMethodVerb",
    "HypothesisStatus",
    "IncidentClassification",
    "IncidentClassificationReason",
    "IncidentSeverity",
    "IncidentStatus",
    "IncidentTaskStatus",
    "IngestionMode",
    "Kind",
    "MatchingMethod",
    "MicrosoftSecurityProductName",
    "Mode",
    "Operator",
    "OwnerType",
    "PackageKind",
    "ProviderPermissionsScope",
    "RepoType",
    "RepositoryAccessKind",
    "RestApiPollerRequestPagingKind",
    "SecurityMLAnalyticsSettingsKind",
    "SettingKind",
    "SettingsStatus",
    "SourceKind",
    "SourceType",
    "Status",
    "SupportTier",
    "ThreatIntelligenceResourceInnerKind",
    "TriggerOperator",
    "TriggersOn",
    "TriggersWhen",
    "UebaDataSources",
    "Version",
]

@pulumi.type_token("azure-native:securityinsights:ActionType")
class ActionType(_builtins.str, Enum):
    MODIFY_PROPERTIES = ...
    RUN_PLAYBOOK = ...
    ADD_INCIDENT_TASK = ...

@pulumi.type_token("azure-native:securityinsights:AlertDetail")
class AlertDetail(_builtins.str, Enum):
    DISPLAY_NAME = ...
    SEVERITY = ...

@pulumi.type_token("azure-native:securityinsights:AlertProperty")
class AlertProperty(_builtins.str, Enum):
    ALERT_LINK = ...
    CONFIDENCE_LEVEL = ...
    CONFIDENCE_SCORE = ...
    EXTENDED_LINKS = ...
    PRODUCT_NAME = ...
    PROVIDER_NAME = ...
    PRODUCT_COMPONENT_NAME = ...
    REMEDIATION_STEPS = ...
    TECHNIQUES = ...

@pulumi.type_token("azure-native:securityinsights:AlertRuleKind")
class AlertRuleKind(_builtins.str, Enum):
    SCHEDULED = ...
    MICROSOFT_SECURITY_INCIDENT_CREATION = ...
    FUSION = ...

@pulumi.type_token("azure-native:securityinsights:AlertSeverity")
class AlertSeverity(_builtins.str, Enum):
    HIGH = ...
    MEDIUM = ...
    LOW = ...
    INFORMATIONAL = ...

@pulumi.type_token("azure-native:securityinsights:AttackTactic")
class AttackTactic(_builtins.str, Enum):
    RECONNAISSANCE = ...
    RESOURCE_DEVELOPMENT = ...
    INITIAL_ACCESS = ...
    EXECUTION = ...
    PERSISTENCE = ...
    PRIVILEGE_ESCALATION = ...
    DEFENSE_EVASION = ...
    CREDENTIAL_ACCESS = ...
    DISCOVERY = ...
    LATERAL_MOVEMENT = ...
    COLLECTION = ...
    EXFILTRATION = ...
    COMMAND_AND_CONTROL = ...
    IMPACT = ...
    PRE_ATTACK = ...
    IMPAIR_PROCESS_CONTROL = ...
    INHIBIT_RESPONSE_FUNCTION = ...

@pulumi.type_token(...)
class AutomationRuleBooleanConditionSupportedOperator(_builtins.str, Enum):
    AND_ = ...
    OR_ = ...

@pulumi.type_token(...)
class AutomationRulePropertyArrayChangedConditionSupportedArrayType(
    _builtins.str, Enum
):
    ALERTS = ...
    LABELS = ...
    TACTICS = ...
    COMMENTS = ...

@pulumi.type_token(...)
class AutomationRulePropertyArrayChangedConditionSupportedChangeType(
    _builtins.str, Enum
):
    ADDED = ...

@pulumi.type_token(...)
class AutomationRulePropertyArrayConditionSupportedArrayConditionType(
    _builtins.str, Enum
):
    ANY_ITEM = ...

@pulumi.type_token(...)
class AutomationRulePropertyArrayConditionSupportedArrayType(_builtins.str, Enum):
    CUSTOM_DETAILS = ...
    CUSTOM_DETAIL_VALUES = ...

@pulumi.type_token(...)
class AutomationRulePropertyChangedConditionSupportedChangedType(_builtins.str, Enum):
    CHANGED_FROM = ...
    CHANGED_TO = ...

@pulumi.type_token(...)
class AutomationRulePropertyChangedConditionSupportedPropertyType(_builtins.str, Enum):
    INCIDENT_SEVERITY = ...
    INCIDENT_STATUS = ...
    INCIDENT_OWNER = ...

@pulumi.type_token(...)
class AutomationRulePropertyConditionSupportedOperator(_builtins.str, Enum):
    EQUALS = ...
    NOT_EQUALS = ...
    CONTAINS = ...
    NOT_CONTAINS = ...
    STARTS_WITH = ...
    NOT_STARTS_WITH = ...
    ENDS_WITH = ...
    NOT_ENDS_WITH = ...

@pulumi.type_token(...)
class AutomationRulePropertyConditionSupportedProperty(_builtins.str, Enum):
    INCIDENT_TITLE = ...
    INCIDENT_DESCRIPTION = ...
    INCIDENT_SEVERITY = ...
    INCIDENT_STATUS = ...
    INCIDENT_RELATED_ANALYTIC_RULE_IDS = ...
    INCIDENT_TACTICS = ...
    INCIDENT_LABEL = ...
    INCIDENT_PROVIDER_NAME = ...
    INCIDENT_UPDATED_BY_SOURCE = ...
    INCIDENT_CUSTOM_DETAILS_KEY = ...
    INCIDENT_CUSTOM_DETAILS_VALUE = ...
    ACCOUNT_AAD_TENANT_ID = ...
    ACCOUNT_AAD_USER_ID = ...
    ACCOUNT_NAME = ...
    ACCOUNT_NT_DOMAIN = ...
    ACCOUNT_PUID = ...
    ACCOUNT_SID = ...
    ACCOUNT_OBJECT_GUID = ...
    ACCOUNT_UPN_SUFFIX = ...
    ALERT_PRODUCT_NAMES = ...
    ALERT_ANALYTIC_RULE_IDS = ...
    AZURE_RESOURCE_RESOURCE_ID = ...
    AZURE_RESOURCE_SUBSCRIPTION_ID = ...
    CLOUD_APPLICATION_APP_ID = ...
    CLOUD_APPLICATION_APP_NAME = ...
    DNS_DOMAIN_NAME = ...
    FILE_DIRECTORY = ...
    FILE_NAME = ...
    FILE_HASH_VALUE = ...
    HOST_AZURE_ID = ...
    HOST_NAME = ...
    HOST_NET_BIOS_NAME = ...
    HOST_NT_DOMAIN = ...
    HOST_OS_VERSION = ...
    IO_T_DEVICE_ID = ...
    IO_T_DEVICE_NAME = ...
    IO_T_DEVICE_TYPE = ...
    IO_T_DEVICE_VENDOR = ...
    IO_T_DEVICE_MODEL = ...
    IO_T_DEVICE_OPERATING_SYSTEM = ...
    IP_ADDRESS = ...
    MAILBOX_DISPLAY_NAME = ...
    MAILBOX_PRIMARY_ADDRESS = ...
    MAILBOX_UPN = ...
    MAIL_MESSAGE_DELIVERY_ACTION = ...
    MAIL_MESSAGE_DELIVERY_LOCATION = ...
    MAIL_MESSAGE_RECIPIENT = ...
    MAIL_MESSAGE_SENDER_IP = ...
    MAIL_MESSAGE_SUBJECT = ...
    MAIL_MESSAGE_P1_SENDER = ...
    MAIL_MESSAGE_P2_SENDER = ...
    MALWARE_CATEGORY = ...
    MALWARE_NAME = ...
    PROCESS_COMMAND_LINE = ...
    PROCESS_ID = ...
    REGISTRY_KEY = ...
    REGISTRY_VALUE_DATA = ...
    URL = ...

@pulumi.type_token("azure-native:securityinsights:CcpAuthType")
class CcpAuthType(_builtins.str, Enum):
    BASIC = ...
    API_KEY = ...
    O_AUTH2 = ...
    AWS = ...
    GCP = ...
    SESSION = ...
    JWT_TOKEN = ...
    GIT_HUB = ...
    SERVICE_BUS = ...
    ORACLE = ...
    NONE = ...

@pulumi.type_token("azure-native:securityinsights:ConditionType")
class ConditionType(_builtins.str, Enum):
    PROPERTY = ...
    PROPERTY_ARRAY = ...
    PROPERTY_CHANGED = ...
    PROPERTY_ARRAY_CHANGED = ...
    BOOLEAN = ...

@pulumi.type_token("azure-native:securityinsights:ContentType")
class ContentType(_builtins.str, Enum):
    ANALYTICS_RULE = ...
    WORKBOOK = ...

@pulumi.type_token(...)
class CustomEntityQueryKind(_builtins.str, Enum):
    ACTIVITY = ...

@pulumi.type_token(...)
class DataConnectorDefinitionKind(_builtins.str, Enum):
    CUSTOMIZABLE = ...

@pulumi.type_token("azure-native:securityinsights:DataConnectorKind")
class DataConnectorKind(_builtins.str, Enum):
    AZURE_ACTIVE_DIRECTORY = ...
    AZURE_SECURITY_CENTER = ...
    MICROSOFT_CLOUD_APP_SECURITY = ...
    THREAT_INTELLIGENCE = ...
    MICROSOFT_THREAT_INTELLIGENCE = ...
    PREMIUM_MICROSOFT_DEFENDER_FOR_THREAT_INTELLIGENCE = ...
    OFFICE365 = ...
    AMAZON_WEB_SERVICES_CLOUD_TRAIL = ...
    AZURE_ADVANCED_THREAT_PROTECTION = ...
    MICROSOFT_DEFENDER_ADVANCED_THREAT_PROTECTION = ...
    REST_API_POLLER = ...

@pulumi.type_token("azure-native:securityinsights:DataTypeState")
class DataTypeState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class DeploymentFetchStatus(_builtins.str, Enum):
    SUCCESS = ...
    UNAUTHORIZED = ...
    NOT_FOUND = ...

@pulumi.type_token("azure-native:securityinsights:DeploymentResult")
class DeploymentResult(_builtins.str, Enum):
    SUCCESS = ...
    CANCELED = ...
    FAILED = ...

@pulumi.type_token("azure-native:securityinsights:DeploymentState")
class DeploymentState(_builtins.str, Enum):
    IN_PROGRESS = ...
    COMPLETED = ...
    QUEUED = ...
    CANCELING = ...

@pulumi.type_token("azure-native:securityinsights:EntityMappingType")
class EntityMappingType(_builtins.str, Enum):
    ACCOUNT = ...
    HOST = ...
    IP = ...
    MALWARE = ...
    FILE = ...
    PROCESS = ...
    CLOUD_APPLICATION = ...
    DNS = ...
    AZURE_RESOURCE = ...
    FILE_HASH = ...
    REGISTRY_KEY = ...
    REGISTRY_VALUE = ...
    SECURITY_GROUP = ...
    URL = ...
    MAILBOX = ...
    MAIL_CLUSTER = ...
    MAIL_MESSAGE = ...
    SUBMISSION_MAIL = ...

@pulumi.type_token("azure-native:securityinsights:EntityProviders")
class EntityProviders(_builtins.str, Enum):
    ACTIVE_DIRECTORY = ...
    AZURE_ACTIVE_DIRECTORY = ...

@pulumi.type_token("azure-native:securityinsights:EntityTimelineKind")
class EntityTimelineKind(_builtins.str, Enum):
    ACTIVITY = ...
    BOOKMARK = ...
    SECURITY_ALERT = ...
    ANOMALY = ...

@pulumi.type_token("azure-native:securityinsights:EntityType")
class EntityType(_builtins.str, Enum):
    ACCOUNT = ...
    HOST = ...
    FILE = ...
    AZURE_RESOURCE = ...
    CLOUD_APPLICATION = ...
    DNS = ...
    FILE_HASH = ...
    IP = ...
    MALWARE = ...
    PROCESS = ...
    REGISTRY_KEY = ...
    REGISTRY_VALUE = ...
    SECURITY_GROUP = ...
    URL = ...
    IO_T_DEVICE = ...
    SECURITY_ALERT = ...
    HUNTING_BOOKMARK = ...
    MAIL_CLUSTER = ...
    MAIL_MESSAGE = ...
    MAILBOX = ...
    SUBMISSION_MAIL = ...
    NIC = ...

@pulumi.type_token(...)
class EventGroupingAggregationKind(_builtins.str, Enum):
    SINGLE_ALERT = ...
    ALERT_PER_RESULT = ...

@pulumi.type_token("azure-native:securityinsights:FileFormat")
class FileFormat(_builtins.str, Enum):
    CSV = ...
    JSON = ...
    UNSPECIFIED = ...

@pulumi.type_token(...)
class FileImportContentType(_builtins.str, Enum):
    BASIC_INDICATOR = ...
    STIX_INDICATOR = ...
    UNSPECIFIED = ...

@pulumi.type_token("azure-native:securityinsights:Flag")
class Flag(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token("azure-native:securityinsights:HttpMethodVerb")
class HttpMethodVerb(_builtins.str, Enum):
    GET = ...
    POST = ...
    PUT = ...
    DELETE = ...

@pulumi.type_token("azure-native:securityinsights:HypothesisStatus")
class HypothesisStatus(_builtins.str, Enum):
    UNKNOWN = ...
    INVALIDATED = ...
    VALIDATED = ...

@pulumi.type_token(...)
class IncidentClassification(_builtins.str, Enum):
    UNDETERMINED = ...
    TRUE_POSITIVE = ...
    BENIGN_POSITIVE = ...
    FALSE_POSITIVE = ...

@pulumi.type_token(...)
class IncidentClassificationReason(_builtins.str, Enum):
    SUSPICIOUS_ACTIVITY = ...
    SUSPICIOUS_BUT_EXPECTED = ...
    INCORRECT_ALERT_LOGIC = ...
    INACCURATE_DATA = ...

@pulumi.type_token("azure-native:securityinsights:IncidentSeverity")
class IncidentSeverity(_builtins.str, Enum):
    HIGH = ...
    MEDIUM = ...
    LOW = ...
    INFORMATIONAL = ...

@pulumi.type_token("azure-native:securityinsights:IncidentStatus")
class IncidentStatus(_builtins.str, Enum):
    NEW = ...
    ACTIVE = ...
    CLOSED = ...

@pulumi.type_token("azure-native:securityinsights:IncidentTaskStatus")
class IncidentTaskStatus(_builtins.str, Enum):
    NEW = ...
    COMPLETED = ...

@pulumi.type_token("azure-native:securityinsights:IngestionMode")
class IngestionMode(_builtins.str, Enum):
    INGEST_ONLY_IF_ALL_ARE_VALID = ...
    INGEST_ANY_VALID_RECORDS = ...
    UNSPECIFIED = ...

@pulumi.type_token("azure-native:securityinsights:Kind")
class Kind(_builtins.str, Enum):
    DATA_CONNECTOR = ...
    DATA_TYPE = ...
    WORKBOOK = ...
    WORKBOOK_TEMPLATE = ...
    PLAYBOOK = ...
    PLAYBOOK_TEMPLATE = ...
    ANALYTICS_RULE_TEMPLATE = ...
    ANALYTICS_RULE = ...
    HUNTING_QUERY = ...
    INVESTIGATION_QUERY = ...
    PARSER = ...
    WATCHLIST = ...
    WATCHLIST_TEMPLATE = ...
    SOLUTION = ...
    AZURE_FUNCTION = ...
    LOGIC_APPS_CUSTOM_CONNECTOR = ...
    AUTOMATION_RULE = ...

@pulumi.type_token("azure-native:securityinsights:MatchingMethod")
class MatchingMethod(_builtins.str, Enum):
    ALL_ENTITIES = ...
    ANY_ALERT = ...
    SELECTED = ...

@pulumi.type_token(...)
class MicrosoftSecurityProductName(_builtins.str, Enum):
    MICROSOFT_CLOUD_APP_SECURITY = ...
    AZURE_SECURITY_CENTER = ...
    AZURE_ADVANCED_THREAT_PROTECTION = ...
    AZURE_ACTIVE_DIRECTORY_IDENTITY_PROTECTION = ...
    AZURE_SECURITY_CENTER_FOR_IO_T = ...

@pulumi.type_token("azure-native:securityinsights:Mode")
class Mode(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:securityinsights:Operator")
class Operator(_builtins.str, Enum):
    AND_ = ...
    OR_ = ...

@pulumi.type_token("azure-native:securityinsights:OwnerType")
class OwnerType(_builtins.str, Enum):
    UNKNOWN = ...
    USER = ...
    GROUP = ...

@pulumi.type_token("azure-native:securityinsights:PackageKind")
class PackageKind(_builtins.str, Enum):
    SOLUTION = ...
    STANDALONE = ...

@pulumi.type_token(...)
class ProviderPermissionsScope(_builtins.str, Enum):
    SUBSCRIPTION = ...
    RESOURCE_GROUP = ...
    WORKSPACE = ...

@pulumi.type_token("azure-native:securityinsights:RepoType")
class RepoType(_builtins.str, Enum):
    GITHUB = ...
    DEV_OPS = ...

@pulumi.type_token("azure-native:securityinsights:RepositoryAccessKind")
class RepositoryAccessKind(_builtins.str, Enum):
    O_AUTH = ...
    PAT = ...
    APP = ...

@pulumi.type_token(...)
class RestApiPollerRequestPagingKind(_builtins.str, Enum):
    LINK_HEADER = ...
    NEXT_PAGE_TOKEN = ...
    NEXT_PAGE_URL = ...
    PERSISTENT_TOKEN = ...
    PERSISTENT_LINK_HEADER = ...
    OFFSET = ...
    COUNT_BASED_PAGING = ...

@pulumi.type_token(...)
class SecurityMLAnalyticsSettingsKind(_builtins.str, Enum):
    ANOMALY = ...

@pulumi.type_token("azure-native:securityinsights:SettingKind")
class SettingKind(_builtins.str, Enum):
    ANOMALIES = ...
    EYES_ON = ...
    ENTITY_ANALYTICS = ...
    UEBA = ...

@pulumi.type_token("azure-native:securityinsights:SettingsStatus")
class SettingsStatus(_builtins.str, Enum):
    PRODUCTION = ...
    FLIGHTING = ...

@pulumi.type_token("azure-native:securityinsights:SourceKind")
class SourceKind(_builtins.str, Enum):
    LOCAL_WORKSPACE = ...
    COMMUNITY = ...
    SOLUTION = ...
    SOURCE_REPOSITORY = ...

@pulumi.type_token("azure-native:securityinsights:SourceType")
class SourceType(_builtins.str, Enum):
    LOCAL = ...
    AZURE_STORAGE = ...

@pulumi.type_token("azure-native:securityinsights:Status")
class Status(_builtins.str, Enum):
    NEW = ...
    ACTIVE = ...
    CLOSED = ...
    BACKLOG = ...
    APPROVED = ...

@pulumi.type_token("azure-native:securityinsights:SupportTier")
class SupportTier(_builtins.str, Enum):
    MICROSOFT = ...
    PARTNER = ...
    COMMUNITY = ...

@pulumi.type_token(...)
class ThreatIntelligenceResourceInnerKind(_builtins.str, Enum):
    INDICATOR = ...

@pulumi.type_token("azure-native:securityinsights:TriggerOperator")
class TriggerOperator(_builtins.str, Enum):
    GREATER_THAN = ...
    LESS_THAN = ...
    EQUAL = ...
    NOT_EQUAL = ...

@pulumi.type_token("azure-native:securityinsights:TriggersOn")
class TriggersOn(_builtins.str, Enum):
    INCIDENTS = ...
    ALERTS = ...

@pulumi.type_token("azure-native:securityinsights:TriggersWhen")
class TriggersWhen(_builtins.str, Enum):
    CREATED = ...
    UPDATED = ...

@pulumi.type_token("azure-native:securityinsights:UebaDataSources")
class UebaDataSources(_builtins.str, Enum):
    AUDIT_LOGS = ...
    AZURE_ACTIVITY = ...
    SECURITY_EVENT = ...
    SIGNIN_LOGS = ...

@pulumi.type_token("azure-native:securityinsights:Version")
class Version(_builtins.str, Enum):
    V1 = ...
    V2 = ...
