

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['Access', 'AccessRuleDirection', 'ActionType', 'AddressPrefixType', 'AddressSpaceAggregationOption', 'AdminRuleKind', 'AdminState', 'ApplicationGatewayClientRevocationOptions', 'ApplicationGatewayCookieBasedAffinity', 'ApplicationGatewayCustomErrorStatusCode', 'ApplicationGatewayFirewallMode', 'ApplicationGatewayFirewallRateLimitDuration', 'ApplicationGatewayFirewallUserSessionVariable', 'ApplicationGatewayLoadDistributionAlgorithm', 'ApplicationGatewayProtocol', 'ApplicationGatewayRedirectType', 'ApplicationGatewayRequestRoutingRuleType', 'ApplicationGatewaySkuFamily', 'ApplicationGatewaySkuName', 'ApplicationGatewaySslCipherSuite', 'ApplicationGatewaySslPolicyName', 'ApplicationGatewaySslPolicyType', 'ApplicationGatewaySslProtocol', 'ApplicationGatewayTier', 'AssociationAccessMode', 'AuthorizationUseStatus', 'AutoLearnPrivateRangesMode', 'AzureFirewallApplicationRuleProtocolType', 'AzureFirewallNatRCActionType', 'AzureFirewallNetworkRuleProtocol', 'AzureFirewallRCActionType', 'AzureFirewallSkuName', 'AzureFirewallSkuTier', 'AzureFirewallThreatIntelMode', 'BastionHostSkuName', 'CommissionedState', 'ConfigurationType', 'ConnectionMonitorEndpointFilterItemType', 'ConnectionMonitorEndpointFilterType', 'ConnectionMonitorTestConfigurationProtocol', 'ConnectivityTopology', 'CoverageLevel', 'CustomIpPrefixType', 'DdosSettingsProtectionMode', 'DeleteExistingPeering', 'DeleteOptions', 'DestinationPortBehavior', 'DhGroup', 'DisableBgpRoutePropagation', 'EndpointType', 'ExceptionEntryMatchVariable', 'ExceptionEntrySelectorMatchOperator', 'ExceptionEntryValueMatchOperator', 'ExpressRouteCircuitPeeringState', 'ExpressRouteCircuitSkuFamily', 'ExpressRouteCircuitSkuTier', 'ExpressRouteLinkAdminState', 'ExpressRouteLinkMacSecCipher', 'ExpressRouteLinkMacSecSciState', 'ExpressRoutePeeringState', 'ExpressRoutePeeringType', 'ExpressRoutePortsBillingType', 'ExpressRoutePortsEncapsulation', 'ExtendedLocationTypes', 'FirewallPolicyFilterRuleActionType', 'FirewallPolicyFilterRuleCollectionActionType', 'FirewallPolicyIDPSQuerySortOrder', 'FirewallPolicyIntrusionDetectionProfileType', 'FirewallPolicyIntrusionDetectionProtocol', 'FirewallPolicyIntrusionDetectionStateType', 'FirewallPolicyNatRuleActionType', 'FirewallPolicyNatRuleCollectionActionType', 'FirewallPolicyRuleApplicationProtocolType', 'FirewallPolicyRuleCollectionType', 'FirewallPolicyRuleConditionApplicationProtocolType', 'FirewallPolicyRuleConditionNetworkProtocol', 'FirewallPolicyRuleConditionType', 'FirewallPolicyRuleNetworkProtocol', 'FirewallPolicyRuleType', 'FirewallPolicySkuTier', 'FlowLogFormatType', 'GatewayLoadBalancerTunnelInterfaceType', 'GatewayLoadBalancerTunnelProtocol', 'Geo', 'GroupConnectivity', 'GroupMemberType', 'HTTPConfigurationMethod', 'HubRoutingPreference', 'IPAllocationMethod', 'IPVersion', 'IkeEncryption', 'IkeIntegrity', 'IpAllocationType', 'IpsecEncryption', 'IpsecIntegrity', 'IsGlobal', 'LoadBalancerBackendAddressAdminState', 'LoadBalancerOutboundRuleProtocol', 'LoadBalancerSkuName', 'LoadBalancerSkuTier', 'LoadDistribution', 'ManagedRuleEnabledState', 'NatGatewaySkuName', 'NetworkIntentPolicyBasedService', 'NetworkInterfaceAuxiliaryMode', 'NetworkInterfaceAuxiliarySku', 'NetworkInterfaceMigrationPhase', 'NetworkInterfaceNicType', 'NetworkProtocol', 'NextStep', 'NicTypeInRequest', 'OutputType', 'OwaspCrsExclusionEntryMatchVariable', 'OwaspCrsExclusionEntrySelectorMatchOperator', 'PacketCaptureTargetType', 'PcProtocol', 'PfsGroup', 'PreferredIPVersion', 'PreferredRoutingGateway', 'PrivateEndpointVNetPolicies', 'ProbeNoHealthyBackendsBehavior', 'ProbeProtocol', 'ProtocolType', 'PublicIPAddressMigrationPhase', 'PublicIPAddressSkuName', 'PublicIPAddressSkuTier', 'PublicIPPrefixSkuName', 'PublicIPPrefixSkuTier', 'PublicIpAddressDnsSettingsDomainNameLabelScope', 'ResiliencyModel', 'ResourceIdentityType', 'RouteFilterRuleType', 'RouteMapActionType', 'RouteMapMatchCondition', 'RouteNextHopType', 'RoutingRuleDestinationType', 'RoutingRuleNextHopType', 'ScrubbingRuleEntryMatchOperator', 'ScrubbingRuleEntryMatchVariable', 'ScrubbingRuleEntryState', 'SecurityConfigurationRuleAccess', 'SecurityConfigurationRuleDirection', 'SecurityConfigurationRuleProtocol', 'SecurityProviderName', 'SecurityRuleAccess', 'SecurityRuleDirection', 'SecurityRuleProtocol', 'SensitivityType', 'ServiceGatewaySkuName', 'ServiceGatewaySkuTier', 'ServiceProviderProvisioningState', 'SharingScope', 'SyncMode', 'TransportProtocol', 'UseHubGateway', 'UserRuleKind', 'VirtualNetworkEncryptionEnforcement', 'VirtualNetworkGatewayConnectionMode', 'VirtualNetworkGatewayConnectionProtocol', 'VirtualNetworkGatewayConnectionType', 'VirtualNetworkGatewaySkuName', 'VirtualNetworkGatewaySkuTier', 'VirtualNetworkGatewayType', 'VirtualNetworkPeeringLevel', 'VirtualNetworkPeeringState', 'VirtualNetworkPrivateEndpointNetworkPolicies', 'VirtualNetworkPrivateLinkServiceNetworkPolicies', 'VnetLocalRouteOverrideCriteria', 'VpnAuthenticationType', 'VpnClientProtocol', 'VpnGatewayGeneration', 'VpnGatewayTunnelingProtocol', 'VpnLinkConnectionMode', 'VpnNatRuleMode', 'VpnNatRuleType', 'VpnPolicyMemberAttributeType', 'VpnType', 'WebApplicationFirewallAction', 'WebApplicationFirewallEnabledState', 'WebApplicationFirewallMatchVariable', 'WebApplicationFirewallMode', 'WebApplicationFirewallOperator', 'WebApplicationFirewallRuleType', 'WebApplicationFirewallScrubbingState', 'WebApplicationFirewallState', 'WebApplicationFirewallTransform']
@pulumi.type_token("azure-native:network:Access")
class Access(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:network:AccessRuleDirection")
class AccessRuleDirection(_builtins.str, Enum):
    
    INBOUND = ...
    OUTBOUND = ...


@pulumi.type_token("azure-native:network:ActionType")
class ActionType(_builtins.str, Enum):
    
    ANOMALY_SCORING = ...
    ALLOW = ...
    BLOCK = ...
    LOG = ...
    JS_CHALLENGE = ...


@pulumi.type_token("azure-native:network:AddressPrefixType")
class AddressPrefixType(_builtins.str, Enum):
    
    IP_PREFIX = ...
    SERVICE_TAG = ...


@pulumi.type_token("azure-native:network:AddressSpaceAggregationOption")
class AddressSpaceAggregationOption(_builtins.str, Enum):
    
    NONE = ...
    MANUAL = ...


@pulumi.type_token("azure-native:network:AdminRuleKind")
class AdminRuleKind(_builtins.str, Enum):
    
    CUSTOM = ...
    DEFAULT = ...


@pulumi.type_token("azure-native:network:AdminState")
class AdminState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class ApplicationGatewayClientRevocationOptions(_builtins.str, Enum):
    
    NONE = ...
    OCSP = ...


@pulumi.type_token(...)
class ApplicationGatewayCookieBasedAffinity(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class ApplicationGatewayCustomErrorStatusCode(_builtins.str, Enum):
    
    HTTP_STATUS400 = ...
    HTTP_STATUS403 = ...
    HTTP_STATUS404 = ...
    HTTP_STATUS405 = ...
    HTTP_STATUS408 = ...
    HTTP_STATUS500 = ...
    HTTP_STATUS502 = ...
    HTTP_STATUS503 = ...
    HTTP_STATUS504 = ...


@pulumi.type_token(...)
class ApplicationGatewayFirewallMode(_builtins.str, Enum):
    
    DETECTION = ...
    PREVENTION = ...


@pulumi.type_token(...)
class ApplicationGatewayFirewallRateLimitDuration(_builtins.str, Enum):
    
    ONE_MIN = ...
    FIVE_MINS = ...


@pulumi.type_token(...)
class ApplicationGatewayFirewallUserSessionVariable(_builtins.str, Enum):
    
    CLIENT_ADDR = ...
    GEO_LOCATION = ...
    NONE = ...


@pulumi.type_token(...)
class ApplicationGatewayLoadDistributionAlgorithm(_builtins.str, Enum):
    
    ROUND_ROBIN = ...
    LEAST_CONNECTIONS = ...
    IP_HASH = ...


@pulumi.type_token("azure-native:network:ApplicationGatewayProtocol")
class ApplicationGatewayProtocol(_builtins.str, Enum):
    
    HTTP = ...
    HTTPS = ...
    TCP = ...
    TLS = ...


@pulumi.type_token(...)
class ApplicationGatewayRedirectType(_builtins.str, Enum):
    
    PERMANENT = ...
    FOUND = ...
    SEE_OTHER = ...
    TEMPORARY = ...


@pulumi.type_token(...)
class ApplicationGatewayRequestRoutingRuleType(_builtins.str, Enum):
    
    BASIC = ...
    PATH_BASED_ROUTING = ...


@pulumi.type_token("azure-native:network:ApplicationGatewaySkuFamily")
class ApplicationGatewaySkuFamily(_builtins.str, Enum):
    
    GENERATION_1 = ...
    GENERATION_2 = ...


@pulumi.type_token("azure-native:network:ApplicationGatewaySkuName")
class ApplicationGatewaySkuName(_builtins.str, Enum):
    
    STANDARD_SMALL = ...
    STANDARD_MEDIUM = ...
    STANDARD_LARGE = ...
    WA_F_MEDIUM = ...
    WA_F_LARGE = ...
    STANDARD_V2 = ...
    WA_F_V2 = ...
    BASIC = ...


@pulumi.type_token(...)
class ApplicationGatewaySslCipherSuite(_builtins.str, Enum):
    
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA384 = ...
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA256 = ...
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA = ...
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA = ...
    TL_S_DH_E_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = ...
    TL_S_DH_E_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = ...
    TL_S_DH_E_RS_A_WIT_H_AE_S_256_CB_C_SHA = ...
    TL_S_DH_E_RS_A_WIT_H_AE_S_128_CB_C_SHA = ...
    TL_S_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = ...
    TL_S_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = ...
    TL_S_RS_A_WIT_H_AE_S_256_CB_C_SHA256 = ...
    TL_S_RS_A_WIT_H_AE_S_128_CB_C_SHA256 = ...
    TL_S_RS_A_WIT_H_AE_S_256_CB_C_SHA = ...
    TL_S_RS_A_WIT_H_AE_S_128_CB_C_SHA = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_GC_M_SHA384 = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_GC_M_SHA256 = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_CB_C_SHA384 = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_CB_C_SHA256 = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_256_CB_C_SHA = ...
    TL_S_ECDH_E_ECDS_A_WIT_H_AE_S_128_CB_C_SHA = ...
    TL_S_DH_E_DS_S_WIT_H_AE_S_256_CB_C_SHA256 = ...
    TL_S_DH_E_DS_S_WIT_H_AE_S_128_CB_C_SHA256 = ...
    TL_S_DH_E_DS_S_WIT_H_AE_S_256_CB_C_SHA = ...
    TL_S_DH_E_DS_S_WIT_H_AE_S_128_CB_C_SHA = ...
    TL_S_RS_A_WIT_H_3_DE_S_ED_E_CB_C_SHA = ...
    TL_S_DH_E_DS_S_WIT_H_3_DE_S_ED_E_CB_C_SHA = ...
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_128_GC_M_SHA256 = ...
    TL_S_ECDH_E_RS_A_WIT_H_AE_S_256_GC_M_SHA384 = ...


@pulumi.type_token(...)
class ApplicationGatewaySslPolicyName(_builtins.str, Enum):
    
    APP_GW_SSL_POLICY20150501 = ...
    APP_GW_SSL_POLICY20170401 = ...
    APP_GW_SSL_POLICY20170401_S = ...
    APP_GW_SSL_POLICY20220101 = ...
    APP_GW_SSL_POLICY20220101_S = ...


@pulumi.type_token(...)
class ApplicationGatewaySslPolicyType(_builtins.str, Enum):
    
    PREDEFINED = ...
    CUSTOM = ...
    CUSTOM_V2 = ...


@pulumi.type_token("azure-native:network:ApplicationGatewaySslProtocol")
class ApplicationGatewaySslProtocol(_builtins.str, Enum):
    
    TL_SV1_0 = ...
    TL_SV1_1 = ...
    TL_SV1_2 = ...
    TL_SV1_3 = ...


@pulumi.type_token("azure-native:network:ApplicationGatewayTier")
class ApplicationGatewayTier(_builtins.str, Enum):
    
    STANDARD = ...
    WAF = ...
    STANDARD_V2 = ...
    WA_F_V2 = ...
    BASIC = ...


@pulumi.type_token("azure-native:network:AssociationAccessMode")
class AssociationAccessMode(_builtins.str, Enum):
    
    LEARNING = ...
    ENFORCED = ...
    AUDIT = ...


@pulumi.type_token("azure-native:network:AuthorizationUseStatus")
class AuthorizationUseStatus(_builtins.str, Enum):
    
    AVAILABLE = ...
    IN_USE = ...


@pulumi.type_token("azure-native:network:AutoLearnPrivateRangesMode")
class AutoLearnPrivateRangesMode(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class AzureFirewallApplicationRuleProtocolType(_builtins.str, Enum):
    
    HTTP = ...
    HTTPS = ...
    MSSQL = ...


@pulumi.type_token("azure-native:network:AzureFirewallNatRCActionType")
class AzureFirewallNatRCActionType(_builtins.str, Enum):
    
    SNAT = ...
    DNAT = ...


@pulumi.type_token(...)
class AzureFirewallNetworkRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ANY = ...
    ICMP = ...


@pulumi.type_token("azure-native:network:AzureFirewallRCActionType")
class AzureFirewallRCActionType(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:network:AzureFirewallSkuName")
class AzureFirewallSkuName(_builtins.str, Enum):
    
    AZF_W_V_NET = ...
    AZF_W_HUB = ...


@pulumi.type_token("azure-native:network:AzureFirewallSkuTier")
class AzureFirewallSkuTier(_builtins.str, Enum):
    
    STANDARD = ...
    PREMIUM = ...
    BASIC = ...


@pulumi.type_token("azure-native:network:AzureFirewallThreatIntelMode")
class AzureFirewallThreatIntelMode(_builtins.str, Enum):
    
    ALERT = ...
    DENY = ...
    OFF = ...


@pulumi.type_token("azure-native:network:BastionHostSkuName")
class BastionHostSkuName(_builtins.str, Enum):
    
    BASIC = ...
    STANDARD = ...
    DEVELOPER = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:network:CommissionedState")
class CommissionedState(_builtins.str, Enum):
    
    PROVISIONING = ...
    PROVISIONED = ...
    COMMISSIONING = ...
    COMMISSIONED_NO_INTERNET_ADVERTISE = ...
    COMMISSIONED = ...
    DECOMMISSIONING = ...
    DEPROVISIONING = ...
    DEPROVISIONED = ...


@pulumi.type_token("azure-native:network:ConfigurationType")
class ConfigurationType(_builtins.str, Enum):
    
    SECURITY_ADMIN = ...
    CONNECTIVITY = ...
    SECURITY_USER = ...
    ROUTING = ...


@pulumi.type_token(...)
class ConnectionMonitorEndpointFilterItemType(_builtins.str, Enum):
    
    AGENT_ADDRESS = ...


@pulumi.type_token(...)
class ConnectionMonitorEndpointFilterType(_builtins.str, Enum):
    
    INCLUDE = ...


@pulumi.type_token(...)
class ConnectionMonitorTestConfigurationProtocol(_builtins.str, Enum):
    
    TCP = ...
    HTTP = ...
    ICMP = ...


@pulumi.type_token("azure-native:network:ConnectivityTopology")
class ConnectivityTopology(_builtins.str, Enum):
    
    HUB_AND_SPOKE = ...
    MESH = ...


@pulumi.type_token("azure-native:network:CoverageLevel")
class CoverageLevel(_builtins.str, Enum):
    
    DEFAULT = ...
    LOW = ...
    BELOW_AVERAGE = ...
    AVERAGE = ...
    ABOVE_AVERAGE = ...
    FULL = ...


@pulumi.type_token("azure-native:network:CustomIpPrefixType")
class CustomIpPrefixType(_builtins.str, Enum):
    
    SINGULAR = ...
    PARENT = ...
    CHILD = ...


@pulumi.type_token("azure-native:network:DdosSettingsProtectionMode")
class DdosSettingsProtectionMode(_builtins.str, Enum):
    
    VIRTUAL_NETWORK_INHERITED = ...
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:network:DeleteExistingPeering")
class DeleteExistingPeering(_builtins.str, Enum):
    
    FALSE = ...
    TRUE = ...


@pulumi.type_token("azure-native:network:DeleteOptions")
class DeleteOptions(_builtins.str, Enum):
    
    DELETE = ...
    DETACH = ...


@pulumi.type_token("azure-native:network:DestinationPortBehavior")
class DestinationPortBehavior(_builtins.str, Enum):
    
    NONE = ...
    LISTEN_IF_AVAILABLE = ...


@pulumi.type_token("azure-native:network:DhGroup")
class DhGroup(_builtins.str, Enum):
    
    NONE = ...
    DH_GROUP1 = ...
    DH_GROUP2 = ...
    DH_GROUP14 = ...
    DH_GROUP2048 = ...
    ECP256 = ...
    ECP384 = ...
    DH_GROUP24 = ...


@pulumi.type_token("azure-native:network:DisableBgpRoutePropagation")
class DisableBgpRoutePropagation(_builtins.str, Enum):
    
    FALSE = ...
    TRUE = ...


@pulumi.type_token("azure-native:network:EndpointType")
class EndpointType(_builtins.str, Enum):
    
    AZURE_VM = ...
    AZURE_V_NET = ...
    AZURE_SUBNET = ...
    EXTERNAL_ADDRESS = ...
    MMA_WORKSPACE_MACHINE = ...
    MMA_WORKSPACE_NETWORK = ...
    AZURE_ARC_VM = ...
    AZURE_VMSS = ...
    AZURE_ARC_NETWORK = ...


@pulumi.type_token("azure-native:network:ExceptionEntryMatchVariable")
class ExceptionEntryMatchVariable(_builtins.str, Enum):
    
    REQUEST_URI = ...
    REMOTE_ADDR = ...
    REQUEST_HEADER = ...


@pulumi.type_token(...)
class ExceptionEntrySelectorMatchOperator(_builtins.str, Enum):
    
    EQUALS = ...
    CONTAINS = ...
    STARTS_WITH = ...
    ENDS_WITH = ...


@pulumi.type_token(...)
class ExceptionEntryValueMatchOperator(_builtins.str, Enum):
    
    EQUALS = ...
    CONTAINS = ...
    STARTS_WITH = ...
    ENDS_WITH = ...
    IP_MATCH = ...


@pulumi.type_token(...)
class ExpressRouteCircuitPeeringState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:network:ExpressRouteCircuitSkuFamily")
class ExpressRouteCircuitSkuFamily(_builtins.str, Enum):
    
    UNLIMITED_DATA = ...
    METERED_DATA = ...


@pulumi.type_token("azure-native:network:ExpressRouteCircuitSkuTier")
class ExpressRouteCircuitSkuTier(_builtins.str, Enum):
    
    STANDARD = ...
    PREMIUM = ...
    BASIC = ...
    LOCAL = ...


@pulumi.type_token("azure-native:network:ExpressRouteLinkAdminState")
class ExpressRouteLinkAdminState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:network:ExpressRouteLinkMacSecCipher")
class ExpressRouteLinkMacSecCipher(_builtins.str, Enum):
    
    GCM_AES256 = ...
    GCM_AES128 = ...
    GCM_AES_XPN128 = ...
    GCM_AES_XPN256 = ...


@pulumi.type_token(...)
class ExpressRouteLinkMacSecSciState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:network:ExpressRoutePeeringState")
class ExpressRoutePeeringState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:network:ExpressRoutePeeringType")
class ExpressRoutePeeringType(_builtins.str, Enum):
    
    AZURE_PUBLIC_PEERING = ...
    AZURE_PRIVATE_PEERING = ...
    MICROSOFT_PEERING = ...


@pulumi.type_token("azure-native:network:ExpressRoutePortsBillingType")
class ExpressRoutePortsBillingType(_builtins.str, Enum):
    
    METERED_DATA = ...
    UNLIMITED_DATA = ...


@pulumi.type_token(...)
class ExpressRoutePortsEncapsulation(_builtins.str, Enum):
    
    DOT1_Q = ...
    QIN_Q = ...


@pulumi.type_token("azure-native:network:ExtendedLocationTypes")
class ExtendedLocationTypes(_builtins.str, Enum):
    
    EDGE_ZONE = ...


@pulumi.type_token(...)
class FirewallPolicyFilterRuleActionType(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token(...)
class FirewallPolicyFilterRuleCollectionActionType(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token(...)
class FirewallPolicyIDPSQuerySortOrder(_builtins.str, Enum):
    
    ASCENDING = ...
    DESCENDING = ...


@pulumi.type_token(...)
class FirewallPolicyIntrusionDetectionProfileType(_builtins.str, Enum):
    
    BASIC = ...
    STANDARD = ...
    ADVANCED = ...
    EXTENDED = ...


@pulumi.type_token(...)
class FirewallPolicyIntrusionDetectionProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ICMP = ...
    ANY = ...


@pulumi.type_token(...)
class FirewallPolicyIntrusionDetectionStateType(_builtins.str, Enum):
    
    OFF = ...
    ALERT = ...
    DENY = ...


@pulumi.type_token(...)
class FirewallPolicyNatRuleActionType(_builtins.str, Enum):
    
    DNAT = ...


@pulumi.type_token(...)
class FirewallPolicyNatRuleCollectionActionType(_builtins.str, Enum):
    
    DNAT = ...


@pulumi.type_token(...)
class FirewallPolicyRuleApplicationProtocolType(_builtins.str, Enum):
    
    HTTP = ...
    HTTPS = ...


@pulumi.type_token(...)
class FirewallPolicyRuleCollectionType(_builtins.str, Enum):
    
    FIREWALL_POLICY_NAT_RULE_COLLECTION = ...
    FIREWALL_POLICY_FILTER_RULE_COLLECTION = ...


@pulumi.type_token(...)
class FirewallPolicyRuleConditionApplicationProtocolType(_builtins.str, Enum):
    
    HTTP = ...
    HTTPS = ...


@pulumi.type_token(...)
class FirewallPolicyRuleConditionNetworkProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ANY = ...
    ICMP = ...


@pulumi.type_token(...)
class FirewallPolicyRuleConditionType(_builtins.str, Enum):
    
    APPLICATION_RULE_CONDITION = ...
    NETWORK_RULE_CONDITION = ...
    NAT_RULE_CONDITION = ...


@pulumi.type_token(...)
class FirewallPolicyRuleNetworkProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ANY = ...
    ICMP = ...


@pulumi.type_token("azure-native:network:FirewallPolicyRuleType")
class FirewallPolicyRuleType(_builtins.str, Enum):
    
    FIREWALL_POLICY_NAT_RULE = ...
    FIREWALL_POLICY_FILTER_RULE = ...


@pulumi.type_token("azure-native:network:FirewallPolicySkuTier")
class FirewallPolicySkuTier(_builtins.str, Enum):
    
    STANDARD = ...
    PREMIUM = ...
    BASIC = ...


@pulumi.type_token("azure-native:network:FlowLogFormatType")
class FlowLogFormatType(_builtins.str, Enum):
    
    JSON = ...


@pulumi.type_token(...)
class GatewayLoadBalancerTunnelInterfaceType(_builtins.str, Enum):
    
    NONE = ...
    INTERNAL = ...
    EXTERNAL = ...


@pulumi.type_token(...)
class GatewayLoadBalancerTunnelProtocol(_builtins.str, Enum):
    
    NONE = ...
    NATIVE = ...
    VXLAN = ...


@pulumi.type_token("azure-native:network:Geo")
class Geo(_builtins.str, Enum):
    
    GLOBAL_ = ...
    AFRI = ...
    APAC = ...
    EURO = ...
    LATAM = ...
    NAM = ...
    ME = ...
    OCEANIA = ...
    AQ = ...


@pulumi.type_token("azure-native:network:GroupConnectivity")
class GroupConnectivity(_builtins.str, Enum):
    
    NONE = ...
    DIRECTLY_CONNECTED = ...


@pulumi.type_token("azure-native:network:GroupMemberType")
class GroupMemberType(_builtins.str, Enum):
    
    VIRTUAL_NETWORK = ...
    SUBNET = ...


@pulumi.type_token("azure-native:network:HTTPConfigurationMethod")
class HTTPConfigurationMethod(_builtins.str, Enum):
    
    GET = ...
    POST = ...


@pulumi.type_token("azure-native:network:HubRoutingPreference")
class HubRoutingPreference(_builtins.str, Enum):
    
    EXPRESS_ROUTE = ...
    VPN_GATEWAY = ...
    AS_PATH = ...


@pulumi.type_token("azure-native:network:IPAllocationMethod")
class IPAllocationMethod(_builtins.str, Enum):
    
    STATIC = ...
    DYNAMIC = ...


@pulumi.type_token("azure-native:network:IPVersion")
class IPVersion(_builtins.str, Enum):
    
    I_PV4 = ...
    I_PV6 = ...


@pulumi.type_token("azure-native:network:IkeEncryption")
class IkeEncryption(_builtins.str, Enum):
    
    DES = ...
    DES3 = ...
    AES128 = ...
    AES192 = ...
    AES256 = ...
    GCMAES256 = ...
    GCMAES128 = ...


@pulumi.type_token("azure-native:network:IkeIntegrity")
class IkeIntegrity(_builtins.str, Enum):
    
    MD5 = ...
    SHA1 = ...
    SHA256 = ...
    SHA384 = ...
    GCMAES256 = ...
    GCMAES128 = ...


@pulumi.type_token("azure-native:network:IpAllocationType")
class IpAllocationType(_builtins.str, Enum):
    
    UNDEFINED = ...
    HYPERNET = ...


@pulumi.type_token("azure-native:network:IpsecEncryption")
class IpsecEncryption(_builtins.str, Enum):
    
    NONE = ...
    DES = ...
    DES3 = ...
    AES128 = ...
    AES192 = ...
    AES256 = ...
    GCMAES128 = ...
    GCMAES192 = ...
    GCMAES256 = ...


@pulumi.type_token("azure-native:network:IpsecIntegrity")
class IpsecIntegrity(_builtins.str, Enum):
    
    MD5 = ...
    SHA1 = ...
    SHA256 = ...
    GCMAES128 = ...
    GCMAES192 = ...
    GCMAES256 = ...


@pulumi.type_token("azure-native:network:IsGlobal")
class IsGlobal(_builtins.str, Enum):
    
    FALSE = ...
    TRUE = ...


@pulumi.type_token(...)
class LoadBalancerBackendAddressAdminState(_builtins.str, Enum):
    
    NONE = ...
    UP = ...
    DOWN = ...


@pulumi.type_token(...)
class LoadBalancerOutboundRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ALL = ...


@pulumi.type_token("azure-native:network:LoadBalancerSkuName")
class LoadBalancerSkuName(_builtins.str, Enum):
    
    BASIC = ...
    STANDARD = ...
    GATEWAY = ...


@pulumi.type_token("azure-native:network:LoadBalancerSkuTier")
class LoadBalancerSkuTier(_builtins.str, Enum):
    
    REGIONAL = ...
    GLOBAL_ = ...


@pulumi.type_token("azure-native:network:LoadDistribution")
class LoadDistribution(_builtins.str, Enum):
    
    DEFAULT = ...
    SOURCE_IP = ...
    SOURCE_IP_PROTOCOL = ...


@pulumi.type_token("azure-native:network:ManagedRuleEnabledState")
class ManagedRuleEnabledState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:network:NatGatewaySkuName")
class NatGatewaySkuName(_builtins.str, Enum):
    
    STANDARD = ...


@pulumi.type_token(...)
class NetworkIntentPolicyBasedService(_builtins.str, Enum):
    
    NONE = ...
    ALL = ...
    ALLOW_RULES_ONLY = ...


@pulumi.type_token("azure-native:network:NetworkInterfaceAuxiliaryMode")
class NetworkInterfaceAuxiliaryMode(_builtins.str, Enum):
    
    NONE = ...
    MAX_CONNECTIONS = ...
    FLOATING = ...
    ACCELERATED_CONNECTIONS = ...


@pulumi.type_token("azure-native:network:NetworkInterfaceAuxiliarySku")
class NetworkInterfaceAuxiliarySku(_builtins.str, Enum):
    
    NONE = ...
    A1 = ...
    A2 = ...
    A4 = ...
    A8 = ...


@pulumi.type_token(...)
class NetworkInterfaceMigrationPhase(_builtins.str, Enum):
    
    NONE = ...
    PREPARE = ...
    COMMIT = ...
    ABORT = ...
    COMMITTED = ...


@pulumi.type_token("azure-native:network:NetworkInterfaceNicType")
class NetworkInterfaceNicType(_builtins.str, Enum):
    
    STANDARD = ...
    ELASTIC = ...


@pulumi.type_token("azure-native:network:NetworkProtocol")
class NetworkProtocol(_builtins.str, Enum):
    
    ANY = ...
    TCP = ...
    UDP = ...
    ICMP = ...


@pulumi.type_token("azure-native:network:NextStep")
class NextStep(_builtins.str, Enum):
    
    UNKNOWN = ...
    CONTINUE_ = ...
    TERMINATE = ...


@pulumi.type_token("azure-native:network:NicTypeInRequest")
class NicTypeInRequest(_builtins.str, Enum):
    
    PUBLIC_NIC = ...
    PRIVATE_NIC = ...


@pulumi.type_token("azure-native:network:OutputType")
class OutputType(_builtins.str, Enum):
    
    WORKSPACE = ...


@pulumi.type_token(...)
class OwaspCrsExclusionEntryMatchVariable(_builtins.str, Enum):
    
    REQUEST_HEADER_NAMES = ...
    REQUEST_COOKIE_NAMES = ...
    REQUEST_ARG_NAMES = ...
    REQUEST_HEADER_KEYS = ...
    REQUEST_HEADER_VALUES = ...
    REQUEST_COOKIE_KEYS = ...
    REQUEST_COOKIE_VALUES = ...
    REQUEST_ARG_KEYS = ...
    REQUEST_ARG_VALUES = ...


@pulumi.type_token(...)
class OwaspCrsExclusionEntrySelectorMatchOperator(_builtins.str, Enum):
    
    EQUALS = ...
    CONTAINS = ...
    STARTS_WITH = ...
    ENDS_WITH = ...
    EQUALS_ANY = ...


@pulumi.type_token("azure-native:network:PacketCaptureTargetType")
class PacketCaptureTargetType(_builtins.str, Enum):
    
    AZURE_VM = ...
    AZURE_VMSS = ...


@pulumi.type_token("azure-native:network:PcProtocol")
class PcProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ANY = ...


@pulumi.type_token("azure-native:network:PfsGroup")
class PfsGroup(_builtins.str, Enum):
    
    NONE = ...
    PFS1 = ...
    PFS2 = ...
    PFS2048 = ...
    ECP256 = ...
    ECP384 = ...
    PFS24 = ...
    PFS14 = ...
    PFSMM = ...


@pulumi.type_token("azure-native:network:PreferredIPVersion")
class PreferredIPVersion(_builtins.str, Enum):
    
    I_PV4 = ...
    I_PV6 = ...


@pulumi.type_token("azure-native:network:PreferredRoutingGateway")
class PreferredRoutingGateway(_builtins.str, Enum):
    
    EXPRESS_ROUTE = ...
    VPN_GATEWAY = ...
    NONE = ...


@pulumi.type_token("azure-native:network:PrivateEndpointVNetPolicies")
class PrivateEndpointVNetPolicies(_builtins.str, Enum):
    
    DISABLED = ...
    BASIC = ...


@pulumi.type_token(...)
class ProbeNoHealthyBackendsBehavior(_builtins.str, Enum):
    
    ALL_PROBED_DOWN = ...
    ALL_PROBED_UP = ...


@pulumi.type_token("azure-native:network:ProbeProtocol")
class ProbeProtocol(_builtins.str, Enum):
    
    HTTP = ...
    TCP = ...
    HTTPS = ...


@pulumi.type_token("azure-native:network:ProtocolType")
class ProtocolType(_builtins.str, Enum):
    
    DO_NOT_USE = ...
    ICMP = ...
    TCP = ...
    UDP = ...
    GRE = ...
    ESP = ...
    AH = ...
    VXLAN = ...
    ALL = ...


@pulumi.type_token("azure-native:network:PublicIPAddressMigrationPhase")
class PublicIPAddressMigrationPhase(_builtins.str, Enum):
    
    NONE = ...
    PREPARE = ...
    COMMIT = ...
    ABORT = ...
    COMMITTED = ...


@pulumi.type_token("azure-native:network:PublicIPAddressSkuName")
class PublicIPAddressSkuName(_builtins.str, Enum):
    
    BASIC = ...
    STANDARD = ...


@pulumi.type_token("azure-native:network:PublicIPAddressSkuTier")
class PublicIPAddressSkuTier(_builtins.str, Enum):
    
    REGIONAL = ...
    GLOBAL_ = ...


@pulumi.type_token("azure-native:network:PublicIPPrefixSkuName")
class PublicIPPrefixSkuName(_builtins.str, Enum):
    
    STANDARD = ...


@pulumi.type_token("azure-native:network:PublicIPPrefixSkuTier")
class PublicIPPrefixSkuTier(_builtins.str, Enum):
    
    REGIONAL = ...
    GLOBAL_ = ...


@pulumi.type_token(...)
class PublicIpAddressDnsSettingsDomainNameLabelScope(_builtins.str, Enum):
    
    TENANT_REUSE = ...
    SUBSCRIPTION_REUSE = ...
    RESOURCE_GROUP_REUSE = ...
    NO_REUSE = ...


@pulumi.type_token("azure-native:network:ResiliencyModel")
class ResiliencyModel(_builtins.str, Enum):
    
    SINGLE_HOMED = ...
    MULTI_HOMED = ...


@pulumi.type_token("azure-native:network:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:network:RouteFilterRuleType")
class RouteFilterRuleType(_builtins.str, Enum):
    
    COMMUNITY = ...


@pulumi.type_token("azure-native:network:RouteMapActionType")
class RouteMapActionType(_builtins.str, Enum):
    
    UNKNOWN = ...
    REMOVE = ...
    ADD = ...
    REPLACE = ...
    DROP = ...


@pulumi.type_token("azure-native:network:RouteMapMatchCondition")
class RouteMapMatchCondition(_builtins.str, Enum):
    
    UNKNOWN = ...
    CONTAINS = ...
    EQUALS = ...
    NOT_CONTAINS = ...
    NOT_EQUALS = ...


@pulumi.type_token("azure-native:network:RouteNextHopType")
class RouteNextHopType(_builtins.str, Enum):
    
    VIRTUAL_NETWORK_GATEWAY = ...
    VNET_LOCAL = ...
    INTERNET = ...
    VIRTUAL_APPLIANCE = ...
    NONE = ...


@pulumi.type_token("azure-native:network:RoutingRuleDestinationType")
class RoutingRuleDestinationType(_builtins.str, Enum):
    
    ADDRESS_PREFIX = ...
    SERVICE_TAG = ...


@pulumi.type_token("azure-native:network:RoutingRuleNextHopType")
class RoutingRuleNextHopType(_builtins.str, Enum):
    
    INTERNET = ...
    NO_NEXT_HOP = ...
    VIRTUAL_APPLIANCE = ...
    VIRTUAL_NETWORK_GATEWAY = ...
    VNET_LOCAL = ...


@pulumi.type_token(...)
class ScrubbingRuleEntryMatchOperator(_builtins.str, Enum):
    
    EQUALS = ...
    EQUALS_ANY = ...


@pulumi.type_token(...)
class ScrubbingRuleEntryMatchVariable(_builtins.str, Enum):
    
    REQUEST_HEADER_NAMES = ...
    REQUEST_COOKIE_NAMES = ...
    REQUEST_ARG_NAMES = ...
    REQUEST_POST_ARG_NAMES = ...
    REQUEST_JSON_ARG_NAMES = ...
    REQUEST_IP_ADDRESS = ...


@pulumi.type_token("azure-native:network:ScrubbingRuleEntryState")
class ScrubbingRuleEntryState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class SecurityConfigurationRuleAccess(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...
    ALWAYS_ALLOW = ...


@pulumi.type_token(...)
class SecurityConfigurationRuleDirection(_builtins.str, Enum):
    
    INBOUND = ...
    OUTBOUND = ...


@pulumi.type_token(...)
class SecurityConfigurationRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ICMP = ...
    ESP = ...
    ANY = ...
    AH = ...


@pulumi.type_token("azure-native:network:SecurityProviderName")
class SecurityProviderName(_builtins.str, Enum):
    
    Z_SCALER = ...
    I_BOSS = ...
    CHECKPOINT = ...


@pulumi.type_token("azure-native:network:SecurityRuleAccess")
class SecurityRuleAccess(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:network:SecurityRuleDirection")
class SecurityRuleDirection(_builtins.str, Enum):
    
    INBOUND = ...
    OUTBOUND = ...


@pulumi.type_token("azure-native:network:SecurityRuleProtocol")
class SecurityRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ICMP = ...
    ESP = ...
    ASTERISK = ...
    AH = ...


@pulumi.type_token("azure-native:network:SensitivityType")
class SensitivityType(_builtins.str, Enum):
    
    NONE = ...
    LOW = ...
    MEDIUM = ...
    HIGH = ...


@pulumi.type_token("azure-native:network:ServiceGatewaySkuName")
class ServiceGatewaySkuName(_builtins.str, Enum):
    
    STANDARD = ...


@pulumi.type_token("azure-native:network:ServiceGatewaySkuTier")
class ServiceGatewaySkuTier(_builtins.str, Enum):
    
    REGIONAL = ...


@pulumi.type_token(...)
class ServiceProviderProvisioningState(_builtins.str, Enum):
    
    NOT_PROVISIONED = ...
    PROVISIONING = ...
    PROVISIONED = ...
    DEPROVISIONING = ...


@pulumi.type_token("azure-native:network:SharingScope")
class SharingScope(_builtins.str, Enum):
    
    TENANT = ...
    DELEGATED_SERVICES = ...


@pulumi.type_token("azure-native:network:SyncMode")
class SyncMode(_builtins.str, Enum):
    
    AUTOMATIC = ...
    MANUAL = ...


@pulumi.type_token("azure-native:network:TransportProtocol")
class TransportProtocol(_builtins.str, Enum):
    
    UDP = ...
    TCP = ...
    ALL = ...


@pulumi.type_token("azure-native:network:UseHubGateway")
class UseHubGateway(_builtins.str, Enum):
    
    FALSE = ...
    TRUE = ...


@pulumi.type_token("azure-native:network:UserRuleKind")
class UserRuleKind(_builtins.str, Enum):
    
    CUSTOM = ...
    DEFAULT = ...


@pulumi.type_token(...)
class VirtualNetworkEncryptionEnforcement(_builtins.str, Enum):
    
    DROP_UNENCRYPTED = ...
    ALLOW_UNENCRYPTED = ...


@pulumi.type_token(...)
class VirtualNetworkGatewayConnectionMode(_builtins.str, Enum):
    
    DEFAULT = ...
    RESPONDER_ONLY = ...
    INITIATOR_ONLY = ...


@pulumi.type_token(...)
class VirtualNetworkGatewayConnectionProtocol(_builtins.str, Enum):
    
    IK_EV2 = ...
    IK_EV1 = ...


@pulumi.type_token(...)
class VirtualNetworkGatewayConnectionType(_builtins.str, Enum):
    
    IPSEC = ...
    VNET2_VNET = ...
    EXPRESS_ROUTE = ...
    VPN_CLIENT = ...


@pulumi.type_token("azure-native:network:VirtualNetworkGatewaySkuName")
class VirtualNetworkGatewaySkuName(_builtins.str, Enum):
    
    BASIC = ...
    HIGH_PERFORMANCE = ...
    STANDARD = ...
    ULTRA_PERFORMANCE = ...
    VPN_GW1 = ...
    VPN_GW2 = ...
    VPN_GW3 = ...
    VPN_GW4 = ...
    VPN_GW5 = ...
    VPN_GW1_AZ = ...
    VPN_GW2_AZ = ...
    VPN_GW3_AZ = ...
    VPN_GW4_AZ = ...
    VPN_GW5_AZ = ...
    ER_GW1_AZ = ...
    ER_GW2_AZ = ...
    ER_GW3_AZ = ...
    ER_GW_SCALE = ...


@pulumi.type_token("azure-native:network:VirtualNetworkGatewaySkuTier")
class VirtualNetworkGatewaySkuTier(_builtins.str, Enum):
    
    BASIC = ...
    HIGH_PERFORMANCE = ...
    STANDARD = ...
    ULTRA_PERFORMANCE = ...
    VPN_GW1 = ...
    VPN_GW2 = ...
    VPN_GW3 = ...
    VPN_GW4 = ...
    VPN_GW5 = ...
    VPN_GW1_AZ = ...
    VPN_GW2_AZ = ...
    VPN_GW3_AZ = ...
    VPN_GW4_AZ = ...
    VPN_GW5_AZ = ...
    ER_GW1_AZ = ...
    ER_GW2_AZ = ...
    ER_GW3_AZ = ...
    ER_GW_SCALE = ...


@pulumi.type_token("azure-native:network:VirtualNetworkGatewayType")
class VirtualNetworkGatewayType(_builtins.str, Enum):
    
    VPN = ...
    EXPRESS_ROUTE = ...
    LOCAL_GATEWAY = ...


@pulumi.type_token("azure-native:network:VirtualNetworkPeeringLevel")
class VirtualNetworkPeeringLevel(_builtins.str, Enum):
    
    FULLY_IN_SYNC = ...
    REMOTE_NOT_IN_SYNC = ...
    LOCAL_NOT_IN_SYNC = ...
    LOCAL_AND_REMOTE_NOT_IN_SYNC = ...


@pulumi.type_token("azure-native:network:VirtualNetworkPeeringState")
class VirtualNetworkPeeringState(_builtins.str, Enum):
    
    INITIATED = ...
    CONNECTED = ...
    DISCONNECTED = ...


@pulumi.type_token(...)
class VirtualNetworkPrivateEndpointNetworkPolicies(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    NETWORK_SECURITY_GROUP_ENABLED = ...
    ROUTE_TABLE_ENABLED = ...


@pulumi.type_token(...)
class VirtualNetworkPrivateLinkServiceNetworkPolicies(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class VnetLocalRouteOverrideCriteria(_builtins.str, Enum):
    
    CONTAINS = ...
    EQUAL = ...


@pulumi.type_token("azure-native:network:VpnAuthenticationType")
class VpnAuthenticationType(_builtins.str, Enum):
    
    CERTIFICATE = ...
    RADIUS = ...
    AAD = ...


@pulumi.type_token("azure-native:network:VpnClientProtocol")
class VpnClientProtocol(_builtins.str, Enum):
    
    IKE_V2 = ...
    SSTP = ...
    OPEN_VPN = ...


@pulumi.type_token("azure-native:network:VpnGatewayGeneration")
class VpnGatewayGeneration(_builtins.str, Enum):
    
    NONE = ...
    GENERATION1 = ...
    GENERATION2 = ...


@pulumi.type_token("azure-native:network:VpnGatewayTunnelingProtocol")
class VpnGatewayTunnelingProtocol(_builtins.str, Enum):
    
    IKE_V2 = ...
    OPEN_VPN = ...


@pulumi.type_token("azure-native:network:VpnLinkConnectionMode")
class VpnLinkConnectionMode(_builtins.str, Enum):
    
    DEFAULT = ...
    RESPONDER_ONLY = ...
    INITIATOR_ONLY = ...


@pulumi.type_token("azure-native:network:VpnNatRuleMode")
class VpnNatRuleMode(_builtins.str, Enum):
    
    EGRESS_SNAT = ...
    INGRESS_SNAT = ...


@pulumi.type_token("azure-native:network:VpnNatRuleType")
class VpnNatRuleType(_builtins.str, Enum):
    
    STATIC = ...
    DYNAMIC = ...


@pulumi.type_token("azure-native:network:VpnPolicyMemberAttributeType")
class VpnPolicyMemberAttributeType(_builtins.str, Enum):
    
    CERTIFICATE_GROUP_ID = ...
    AAD_GROUP_ID = ...
    RADIUS_AZURE_GROUP_ID = ...


@pulumi.type_token("azure-native:network:VpnType")
class VpnType(_builtins.str, Enum):
    
    POLICY_BASED = ...
    ROUTE_BASED = ...


@pulumi.type_token("azure-native:network:WebApplicationFirewallAction")
class WebApplicationFirewallAction(_builtins.str, Enum):
    
    ALLOW = ...
    BLOCK = ...
    LOG = ...
    JS_CHALLENGE = ...


@pulumi.type_token(...)
class WebApplicationFirewallEnabledState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token(...)
class WebApplicationFirewallMatchVariable(_builtins.str, Enum):
    
    REMOTE_ADDR = ...
    REQUEST_METHOD = ...
    QUERY_STRING = ...
    POST_ARGS = ...
    REQUEST_URI = ...
    REQUEST_HEADERS = ...
    REQUEST_BODY = ...
    REQUEST_COOKIES = ...


@pulumi.type_token("azure-native:network:WebApplicationFirewallMode")
class WebApplicationFirewallMode(_builtins.str, Enum):
    
    PREVENTION = ...
    DETECTION = ...


@pulumi.type_token(...)
class WebApplicationFirewallOperator(_builtins.str, Enum):
    
    IP_MATCH = ...
    EQUAL = ...
    CONTAINS = ...
    LESS_THAN = ...
    GREATER_THAN = ...
    LESS_THAN_OR_EQUAL = ...
    GREATER_THAN_OR_EQUAL = ...
    BEGINS_WITH = ...
    ENDS_WITH = ...
    REGEX = ...
    GEO_MATCH = ...
    ANY = ...


@pulumi.type_token(...)
class WebApplicationFirewallRuleType(_builtins.str, Enum):
    
    MATCH_RULE = ...
    RATE_LIMIT_RULE = ...
    INVALID = ...


@pulumi.type_token(...)
class WebApplicationFirewallScrubbingState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:network:WebApplicationFirewallState")
class WebApplicationFirewallState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token(...)
class WebApplicationFirewallTransform(_builtins.str, Enum):
    
    UPPERCASE = ...
    LOWERCASE = ...
    TRIM = ...
    URL_DECODE = ...
    URL_ENCODE = ...
    REMOVE_NULLS = ...
    HTML_ENTITY_DECODE = ...


