import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListVpnServerConfigurationRadiusSecretsResult",
    ...,
    "list_vpn_server_configuration_radius_secrets",
    ...,
]

@pulumi.output_type
class ListVpnServerConfigurationRadiusSecretsResult:
    def __init__(__self__, next_link=..., value=...) -> None: ...
    @_builtins.property
    @pulumi.getter(name="nextLink")
    def next_link(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[Sequence[outputs.RadiusAuthServerResponse]]: ...

class AwaitableListVpnServerConfigurationRadiusSecretsResult(
    ListVpnServerConfigurationRadiusSecretsResult
):
    def __await__(self): ...

def list_vpn_server_configuration_radius_secrets(
    resource_group_name: Optional[_builtins.str] = ...,
    vpn_server_configuration_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListVpnServerConfigurationRadiusSecretsResult: ...
def list_vpn_server_configuration_radius_secrets_output(
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    vpn_server_configuration_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListVpnServerConfigurationRadiusSecretsResult]: ...
