

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ManagedServiceIdentityType', 'Region', 'SingleSignOnStates', 'SingleSignOnType']
@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:weightsandbiases:Region")
class Region(_builtins.str, Enum):
    
    EASTUS = ...
    CENTRALUS = ...
    WESTUS = ...
    WESTEUROPE = ...
    JAPANEAST = ...
    KOREACENTRAL = ...


@pulumi.type_token("azure-native:weightsandbiases:SingleSignOnStates")
class SingleSignOnStates(_builtins.str, Enum):
    
    INITIAL = ...
    ENABLE = ...
    DISABLE = ...


@pulumi.type_token("azure-native:weightsandbiases:SingleSignOnType")
class SingleSignOnType(_builtins.str, Enum):
    
    SAML = ...
    OPEN_ID = ...


