

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AllowedContentLevel', 'ApplicationSharingPolicy', 'AuthMode', 'AutoRebuildSetting', 'BatchDeploymentConfigurationType', 'BatchLoggingLevel', 'BatchOutputAction', 'BlockedTransformers', 'CapabilityHostKind', 'CategoricalDataDriftMetric', 'CategoricalDataQualityMetric', 'CategoricalPredictionDriftMetric', 'ClassificationModels', 'ClassificationMultilabelPrimaryMetrics', 'ClassificationPrimaryMetrics', 'ClusterPurpose', 'ComputeInstanceAuthorizationType', 'ComputePowerAction', 'ComputeRecurrenceFrequency', 'ComputeTriggerType', 'ComputeType', 'ComputeWeekDay', 'ConnectionAuthType', 'ConnectionCategory', 'ContainerType', 'ContentSafetyStatus', 'CredentialsType', 'DataCollectionMode', 'DataType', 'DatasetType', 'DatastoreType', 'DatastoreTypeArm', 'DeploymentModelVersionUpgradeOption', 'DistributionType', 'DockerSpecificationType', 'EarlyTerminationPolicyType', 'EgressPublicNetworkAccessType', 'EmailNotificationEnableType', 'EncryptionStatus', 'EndpointAuthMode', 'EndpointComputeType', 'EndpointServiceConnectionStatus', 'EnvironmentVariableType', 'FeatureAttributionMetric', 'FeatureDataType', 'FeatureImportanceMode', 'FeatureLags', 'FeaturizationMode', 'FirewallSku', 'ForecastHorizonMode', 'ForecastingModels', 'ForecastingPrimaryMetrics', 'Goal', 'Header', 'IdentityConfigurationType', 'ImageAnnotationType', 'ImageType', 'IncrementalDataRefresh', 'InputDeliveryMode', 'InstanceSegmentationPrimaryMetrics', 'IsolationMode', 'JobInputType', 'JobLimitsType', 'JobOutputType', 'JobTier', 'JobType', 'LearningRateScheduler', 'LinkedServiceLinkType', 'LoadBalancerType', 'LogVerbosity', 'MLAssistConfigurationType', 'ManagedNetworkKind', 'ManagedNetworkStatus', 'ManagedPERequirement', 'ManagedPEStatus', 'ManagedServiceIdentityType', 'MaterializationStoreType', 'MediaType', 'ModelSize', 'ModelTaskType', 'MonitorComputeIdentityType', 'MonitorComputeType', 'MonitoringFeatureDataType', 'MonitoringFeatureFilterType', 'MonitoringInputDataType', 'MonitoringNotificationType', 'MonitoringSignalType', 'MultiSelect', 'NCrossValidationsMode', 'NodesValueType', 'NumericalDataDriftMetric', 'NumericalDataQualityMetric', 'NumericalPredictionDriftMetric', 'ObjectDetectionPrimaryMetrics', 'OneLakeArtifactType', 'OperatingSystemType', 'OsType', 'OutputDeliveryMode', 'Protocol', 'PublicNetworkAccessType', 'RaiPolicyContentSource', 'RaiPolicyMode', 'RaiPolicyType', 'RandomSamplingAlgorithmRule', 'RecurrenceFrequency', 'ReferenceType', 'RegressionModels', 'RegressionPrimaryMetrics', 'RemoteLoginPortPublicAccess', 'ResourceIdentityType', 'RollingRateType', 'RuleAction', 'RuleCategory', 'RuleStatus', 'RuleType', 'SamplingAlgorithmType', 'ScaleType', 'ScheduleActionType', 'ScheduleProvisioningState', 'ScheduleStatus', 'SeasonalityMode', 'SecretsType', 'ServerlessInferenceEndpointAuthMode', 'ServiceDataAccessAuthIdentity', 'ShortSeriesHandlingConfiguration', 'SkuTier', 'SourceType', 'SparkJobEntryType', 'SshPublicAccess', 'SslConfigStatus', 'StackMetaLearnerType', 'StochasticOptimizer', 'SystemDatastoresAuthMode', 'TargetAggregationFunction', 'TargetLagsMode', 'TargetRollingWindowSizeMode', 'TaskType', 'TextAnnotationType', 'TriggerType', 'UseStl', 'ValidationMetricType', 'VmPriority', 'VolumeDefinitionType', 'WebhookType', 'WeekDay']
@pulumi.type_token(...)
class AllowedContentLevel(_builtins.str, Enum):
    
    LOW = ...
    MEDIUM = ...
    HIGH = ...


@pulumi.type_token(...)
class ApplicationSharingPolicy(_builtins.str, Enum):
    
    PERSONAL = ...
    SHARED = ...


@pulumi.type_token("azure-native:machinelearningservices:AuthMode")
class AuthMode(_builtins.str, Enum):
    
    AAD = ...


@pulumi.type_token(...)
class AutoRebuildSetting(_builtins.str, Enum):
    
    DISABLED = ...
    ON_BASE_IMAGE_UPDATE = ...


@pulumi.type_token(...)
class BatchDeploymentConfigurationType(_builtins.str, Enum):
    
    MODEL = ...
    PIPELINE_COMPONENT = ...


@pulumi.type_token(...)
class BatchLoggingLevel(_builtins.str, Enum):
    
    INFO = ...
    WARNING = ...
    DEBUG = ...


@pulumi.type_token(...)
class BatchOutputAction(_builtins.str, Enum):
    
    SUMMARY_ONLY = ...
    APPEND_ROW = ...


@pulumi.type_token(...)
class BlockedTransformers(_builtins.str, Enum):
    
    TEXT_TARGET_ENCODER = ...
    ONE_HOT_ENCODER = ...
    CAT_TARGET_ENCODER = ...
    TF_IDF = ...
    WO_E_TARGET_ENCODER = ...
    LABEL_ENCODER = ...
    WORD_EMBEDDING = ...
    NAIVE_BAYES = ...
    COUNT_VECTORIZER = ...
    HASH_ONE_HOT_ENCODER = ...


@pulumi.type_token(...)
class CapabilityHostKind(_builtins.str, Enum):
    
    AGENTS = ...


@pulumi.type_token(...)
class CategoricalDataDriftMetric(_builtins.str, Enum):
    
    JENSEN_SHANNON_DISTANCE = ...
    POPULATION_STABILITY_INDEX = ...
    PEARSONS_CHI_SQUARED_TEST = ...


@pulumi.type_token(...)
class CategoricalDataQualityMetric(_builtins.str, Enum):
    
    NULL_VALUE_RATE = ...
    DATA_TYPE_ERROR_RATE = ...
    OUT_OF_BOUNDS_RATE = ...


@pulumi.type_token(...)
class CategoricalPredictionDriftMetric(_builtins.str, Enum):
    
    JENSEN_SHANNON_DISTANCE = ...
    POPULATION_STABILITY_INDEX = ...
    PEARSONS_CHI_SQUARED_TEST = ...


@pulumi.type_token(...)
class ClassificationModels(_builtins.str, Enum):
    
    LOGISTIC_REGRESSION = ...
    SGD = ...
    MULTINOMIAL_NAIVE_BAYES = ...
    BERNOULLI_NAIVE_BAYES = ...
    SVM = ...
    LINEAR_SVM = ...
    KNN = ...
    DECISION_TREE = ...
    RANDOM_FOREST = ...
    EXTREME_RANDOM_TREES = ...
    LIGHT_GBM = ...
    GRADIENT_BOOSTING = ...
    XG_BOOST_CLASSIFIER = ...


@pulumi.type_token(...)
class ClassificationMultilabelPrimaryMetrics(_builtins.str, Enum):
    
    AUC_WEIGHTED = ...
    ACCURACY = ...
    NORM_MACRO_RECALL = ...
    AVERAGE_PRECISION_SCORE_WEIGHTED = ...
    PRECISION_SCORE_WEIGHTED = ...
    IOU = ...


@pulumi.type_token(...)
class ClassificationPrimaryMetrics(_builtins.str, Enum):
    
    AUC_WEIGHTED = ...
    ACCURACY = ...
    NORM_MACRO_RECALL = ...
    AVERAGE_PRECISION_SCORE_WEIGHTED = ...
    PRECISION_SCORE_WEIGHTED = ...


@pulumi.type_token(...)
class ClusterPurpose(_builtins.str, Enum):
    
    FAST_PROD = ...
    DENSE_PROD = ...
    DEV_TEST = ...


@pulumi.type_token(...)
class ComputeInstanceAuthorizationType(_builtins.str, Enum):
    
    PERSONAL = ...


@pulumi.type_token(...)
class ComputePowerAction(_builtins.str, Enum):
    
    START = ...
    STOP = ...


@pulumi.type_token(...)
class ComputeRecurrenceFrequency(_builtins.str, Enum):
    
    MINUTE = ...
    HOUR = ...
    DAY = ...
    WEEK = ...
    MONTH = ...


@pulumi.type_token(...)
class ComputeTriggerType(_builtins.str, Enum):
    
    RECURRENCE = ...
    CRON = ...


@pulumi.type_token("azure-native:machinelearningservices:ComputeType")
class ComputeType(_builtins.str, Enum):
    
    AKS = ...
    KUBERNETES = ...
    AML_COMPUTE = ...
    COMPUTE_INSTANCE = ...
    DATA_FACTORY = ...
    VIRTUAL_MACHINE = ...
    HD_INSIGHT = ...
    DATABRICKS = ...
    DATA_LAKE_ANALYTICS = ...
    SYNAPSE_SPARK = ...


@pulumi.type_token(...)
class ComputeWeekDay(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


@pulumi.type_token(...)
class ConnectionAuthType(_builtins.str, Enum):
    
    PAT = ...
    MANAGED_IDENTITY = ...
    USERNAME_PASSWORD = ...
    NONE = ...
    SAS = ...
    ACCOUNT_KEY = ...
    SERVICE_PRINCIPAL = ...
    ACCESS_KEY = ...
    API_KEY = ...
    CUSTOM_KEYS = ...
    O_AUTH2 = ...
    AAD = ...
    DELEGATED_SAS = ...
    PROJECT_MANAGED_IDENTITY = ...
    ACCOUNT_MANAGED_IDENTITY = ...
    USER_ENTRA_TOKEN = ...
    AGENT_USER_IMPERSONATION = ...
    AGENTIC_IDENTITY_TOKEN = ...
    AGENTIC_USER = ...


@pulumi.type_token(...)
class ConnectionCategory(_builtins.str, Enum):
    
    PYTHON_FEED = ...
    CONTAINER_REGISTRY = ...
    GIT = ...
    S3 = ...
    SNOWFLAKE = ...
    AZURE_KEY_VAULT = ...
    AZURE_SQL_DB = ...
    AZURE_SYNAPSE_ANALYTICS = ...
    AZURE_MY_SQL_DB = ...
    AZURE_POSTGRES_DB = ...
    ADLS_GEN2 = ...
    AZURE_CONTAINER_APP_ENVIRONMENT = ...
    REDIS = ...
    API_KEY = ...
    AZURE_OPEN_AI = ...
    AI_SERVICES = ...
    COGNITIVE_SEARCH = ...
    COGNITIVE_SERVICE = ...
    CUSTOM_KEYS = ...
    AZURE_BLOB = ...
    AZURE_STORAGE_ACCOUNT = ...
    AZURE_ONE_LAKE = ...
    COSMOS_DB = ...
    COSMOS_DB_MONGO_DB_API = ...
    AZURE_DATA_EXPLORER = ...
    AZURE_MARIA_DB = ...
    AZURE_DATABRICKS_DELTA_LAKE = ...
    AZURE_SQL_MI = ...
    AZURE_TABLE_STORAGE = ...
    AMAZON_RDS_FOR_ORACLE = ...
    AMAZON_RDS_FOR_SQL_SERVER = ...
    AMAZON_REDSHIFT = ...
    DB2 = ...
    DRILL = ...
    GOOGLE_BIG_QUERY = ...
    GREENPLUM = ...
    HBASE = ...
    HIVE = ...
    IMPALA = ...
    INFORMIX = ...
    MARIA_DB = ...
    MICROSOFT_ACCESS = ...
    MY_SQL = ...
    NETEZZA = ...
    ORACLE = ...
    PHOENIX = ...
    POSTGRE_SQL = ...
    PRESTO = ...
    SAP_OPEN_HUB = ...
    SAP_BW = ...
    SAP_HANA = ...
    SAP_TABLE = ...
    SPARK = ...
    SQL_SERVER = ...
    SYBASE = ...
    TERADATA = ...
    VERTICA = ...
    PINECONE = ...
    DATABRICKS = ...
    CASSANDRA = ...
    COUCHBASE = ...
    MONGO_DB_V2 = ...
    MONGO_DB_ATLAS = ...
    AMAZON_S3_COMPATIBLE = ...
    FILE_SERVER = ...
    FTP_SERVER = ...
    GOOGLE_CLOUD_STORAGE = ...
    HDFS = ...
    ORACLE_CLOUD_STORAGE = ...
    SFTP = ...
    GENERIC_HTTP = ...
    O_DATA_REST = ...
    ODBC = ...
    GENERIC_REST = ...
    REMOTE_TOOL = ...
    AMAZON_MWS = ...
    CONCUR = ...
    DYNAMICS = ...
    DYNAMICS_AX = ...
    DYNAMICS_CRM = ...
    GOOGLE_AD_WORDS = ...
    HUBSPOT = ...
    JIRA = ...
    MAGENTO = ...
    MARKETO = ...
    OFFICE365 = ...
    ELOQUA = ...
    RESPONSYS = ...
    ORACLE_SERVICE_CLOUD = ...
    PAY_PAL = ...
    QUICK_BOOKS = ...
    SALESFORCE = ...
    SALESFORCE_SERVICE_CLOUD = ...
    SALESFORCE_MARKETING_CLOUD = ...
    SAP_CLOUD_FOR_CUSTOMER = ...
    SAP_ECC = ...
    SERVICE_NOW = ...
    SHARE_POINT_ONLINE_LIST = ...
    SHOPIFY = ...
    SQUARE = ...
    WEB_TABLE = ...
    XERO = ...
    ZOHO = ...
    GENERIC_CONTAINER_REGISTRY = ...
    ELASTICSEARCH = ...
    APP_INSIGHTS = ...
    APP_CONFIG = ...
    OPEN_AI = ...
    SERP = ...
    BING_LLM_SEARCH = ...
    SERVERLESS = ...
    MANAGED_ONLINE_ENDPOINT = ...
    API_MANAGEMENT = ...
    MODEL_GATEWAY = ...
    GROUNDING_WITH_BING_SEARCH = ...
    GROUNDING_WITH_CUSTOM_SEARCH = ...
    SHAREPOINT = ...
    MICROSOFT_FABRIC = ...
    POWER_PLATFORM_ENVIRONMENT = ...
    REMOTE_A2_A = ...


@pulumi.type_token("azure-native:machinelearningservices:ContainerType")
class ContainerType(_builtins.str, Enum):
    
    STORAGE_INITIALIZER = ...
    INFERENCE_SERVER = ...


@pulumi.type_token(...)
class ContentSafetyStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class CredentialsType(_builtins.str, Enum):
    
    ACCOUNT_KEY = ...
    CERTIFICATE = ...
    NONE = ...
    SAS = ...
    SERVICE_PRINCIPAL = ...


@pulumi.type_token(...)
class DataCollectionMode(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:machinelearningservices:DataType")
class DataType(_builtins.str, Enum):
    
    URI_FILE = ...
    URI_FOLDER = ...
    MLTABLE = ...


@pulumi.type_token("azure-native:machinelearningservices:DatasetType")
class DatasetType(_builtins.str, Enum):
    
    TABULAR = ...
    FILE = ...


@pulumi.type_token("azure-native:machinelearningservices:DatastoreType")
class DatastoreType(_builtins.str, Enum):
    
    AZURE_BLOB = ...
    AZURE_DATA_LAKE_GEN1 = ...
    AZURE_DATA_LAKE_GEN2 = ...
    AZURE_FILE = ...
    ONE_LAKE = ...


@pulumi.type_token(...)
class DatastoreTypeArm(_builtins.str, Enum):
    
    BLOB = ...
    ADLS = ...
    ADLS_GEN2 = ...
    DBFS = ...
    FILE = ...
    MYSQLDB = ...
    SQLDB = ...
    PSQLDB = ...


@pulumi.type_token(...)
class DeploymentModelVersionUpgradeOption(_builtins.str, Enum):
    
    ONCE_NEW_DEFAULT_VERSION_AVAILABLE = ...
    ONCE_CURRENT_VERSION_EXPIRED = ...
    NO_AUTO_UPGRADE = ...


@pulumi.type_token(...)
class DistributionType(_builtins.str, Enum):
    
    PY_TORCH = ...
    TENSOR_FLOW = ...
    MPI = ...


@pulumi.type_token(...)
class DockerSpecificationType(_builtins.str, Enum):
    
    BUILD = ...
    IMAGE = ...


@pulumi.type_token(...)
class EarlyTerminationPolicyType(_builtins.str, Enum):
    
    BANDIT = ...
    MEDIAN_STOPPING = ...
    TRUNCATION_SELECTION = ...


@pulumi.type_token(...)
class EgressPublicNetworkAccessType(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class EmailNotificationEnableType(_builtins.str, Enum):
    
    JOB_COMPLETED = ...
    JOB_FAILED = ...
    JOB_CANCELLED = ...


@pulumi.type_token(...)
class EncryptionStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class EndpointAuthMode(_builtins.str, Enum):
    
    AML_TOKEN = ...
    KEY = ...
    AAD_TOKEN = ...


@pulumi.type_token(...)
class EndpointComputeType(_builtins.str, Enum):
    
    MANAGED = ...
    KUBERNETES = ...
    AZURE_ML_COMPUTE = ...


@pulumi.type_token(...)
class EndpointServiceConnectionStatus(_builtins.str, Enum):
    
    APPROVED = ...
    PENDING = ...
    REJECTED = ...
    DISCONNECTED = ...
    TIMEOUT = ...


@pulumi.type_token(...)
class EnvironmentVariableType(_builtins.str, Enum):
    
    LOCAL = ...


@pulumi.type_token(...)
class FeatureAttributionMetric(_builtins.str, Enum):
    
    NORMALIZED_DISCOUNTED_CUMULATIVE_GAIN = ...


@pulumi.type_token(...)
class FeatureDataType(_builtins.str, Enum):
    
    STRING = ...
    INTEGER = ...
    LONG = ...
    FLOAT = ...
    DOUBLE = ...
    BINARY = ...
    DATETIME = ...
    BOOLEAN = ...


@pulumi.type_token(...)
class FeatureImportanceMode(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:machinelearningservices:FeatureLags")
class FeatureLags(_builtins.str, Enum):
    
    NONE = ...
    AUTO = ...


@pulumi.type_token(...)
class FeaturizationMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...
    OFF = ...


@pulumi.type_token("azure-native:machinelearningservices:FirewallSku")
class FirewallSku(_builtins.str, Enum):
    
    STANDARD = ...
    BASIC = ...


@pulumi.type_token(...)
class ForecastHorizonMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...


@pulumi.type_token(...)
class ForecastingModels(_builtins.str, Enum):
    
    AUTO_ARIMA = ...
    PROPHET = ...
    NAIVE = ...
    SEASONAL_NAIVE = ...
    AVERAGE = ...
    SEASONAL_AVERAGE = ...
    EXPONENTIAL_SMOOTHING = ...
    ARIMAX = ...
    TCN_FORECASTER = ...
    ELASTIC_NET = ...
    GRADIENT_BOOSTING = ...
    DECISION_TREE = ...
    KNN = ...
    LASSO_LARS = ...
    SGD = ...
    RANDOM_FOREST = ...
    EXTREME_RANDOM_TREES = ...
    LIGHT_GBM = ...
    XG_BOOST_REGRESSOR = ...


@pulumi.type_token(...)
class ForecastingPrimaryMetrics(_builtins.str, Enum):
    
    SPEARMAN_CORRELATION = ...
    NORMALIZED_ROOT_MEAN_SQUARED_ERROR = ...
    R2_SCORE = ...
    NORMALIZED_MEAN_ABSOLUTE_ERROR = ...


@pulumi.type_token("azure-native:machinelearningservices:Goal")
class Goal(_builtins.str, Enum):
    
    MINIMIZE = ...
    MAXIMIZE = ...


@pulumi.type_token("azure-native:machinelearningservices:Header")
class Header(_builtins.str, Enum):
    
    ALL_FILES_HAVE_SAME_HEADERS = ...
    ONLY_FIRST_FILE_HAS_HEADERS = ...
    NO_HEADERS = ...
    COMBINE_ALL_FILES_HEADERS = ...


@pulumi.type_token(...)
class IdentityConfigurationType(_builtins.str, Enum):
    
    MANAGED = ...
    AML_TOKEN = ...
    USER_IDENTITY = ...


@pulumi.type_token(...)
class ImageAnnotationType(_builtins.str, Enum):
    
    CLASSIFICATION = ...
    BOUNDING_BOX = ...
    INSTANCE_SEGMENTATION = ...


@pulumi.type_token("azure-native:machinelearningservices:ImageType")
class ImageType(_builtins.str, Enum):
    
    DOCKER = ...
    AZUREML = ...


@pulumi.type_token(...)
class IncrementalDataRefresh(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class InputDeliveryMode(_builtins.str, Enum):
    
    READ_ONLY_MOUNT = ...
    READ_WRITE_MOUNT = ...
    DOWNLOAD = ...
    DIRECT = ...
    EVAL_MOUNT = ...
    EVAL_DOWNLOAD = ...


@pulumi.type_token(...)
class InstanceSegmentationPrimaryMetrics(_builtins.str, Enum):
    
    MEAN_AVERAGE_PRECISION = ...


@pulumi.type_token("azure-native:machinelearningservices:IsolationMode")
class IsolationMode(_builtins.str, Enum):
    
    DISABLED = ...
    ALLOW_INTERNET_OUTBOUND = ...
    ALLOW_ONLY_APPROVED_OUTBOUND = ...


@pulumi.type_token("azure-native:machinelearningservices:JobInputType")
class JobInputType(_builtins.str, Enum):
    
    LITERAL = ...
    URI_FILE = ...
    URI_FOLDER = ...
    MLTABLE = ...
    CUSTOM_MODEL = ...
    MLFLOW_MODEL = ...
    TRITON_MODEL = ...


@pulumi.type_token("azure-native:machinelearningservices:JobLimitsType")
class JobLimitsType(_builtins.str, Enum):
    
    COMMAND = ...
    SWEEP = ...


@pulumi.type_token("azure-native:machinelearningservices:JobOutputType")
class JobOutputType(_builtins.str, Enum):
    
    URI_FILE = ...
    URI_FOLDER = ...
    MLTABLE = ...
    CUSTOM_MODEL = ...
    MLFLOW_MODEL = ...
    TRITON_MODEL = ...


@pulumi.type_token("azure-native:machinelearningservices:JobTier")
class JobTier(_builtins.str, Enum):
    
    NULL = ...
    SPOT = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:machinelearningservices:JobType")
class JobType(_builtins.str, Enum):
    
    AUTO_ML = ...
    COMMAND = ...
    SWEEP = ...
    PIPELINE = ...
    SPARK = ...


@pulumi.type_token(...)
class LearningRateScheduler(_builtins.str, Enum):
    
    NONE = ...
    WARMUP_COSINE = ...
    STEP = ...


@pulumi.type_token(...)
class LinkedServiceLinkType(_builtins.str, Enum):
    
    SYNAPSE = ...


@pulumi.type_token(...)
class LoadBalancerType(_builtins.str, Enum):
    
    PUBLIC_IP = ...
    INTERNAL_LOAD_BALANCER = ...


@pulumi.type_token("azure-native:machinelearningservices:LogVerbosity")
class LogVerbosity(_builtins.str, Enum):
    
    NOT_SET = ...
    DEBUG = ...
    INFO = ...
    WARNING = ...
    ERROR = ...
    CRITICAL = ...


@pulumi.type_token(...)
class MLAssistConfigurationType(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class ManagedNetworkKind(_builtins.str, Enum):
    
    V1 = ...
    V2 = ...


@pulumi.type_token(...)
class ManagedNetworkStatus(_builtins.str, Enum):
    
    INACTIVE = ...
    ACTIVE = ...


@pulumi.type_token(...)
class ManagedPERequirement(_builtins.str, Enum):
    REQUIRED = ...
    NOT_REQUIRED = ...
    NOT_APPLICABLE = ...


@pulumi.type_token(...)
class ManagedPEStatus(_builtins.str, Enum):
    INACTIVE = ...
    ACTIVE = ...
    NOT_APPLICABLE = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token(...)
class MaterializationStoreType(_builtins.str, Enum):
    
    NONE = ...
    ONLINE = ...
    OFFLINE = ...
    ONLINE_AND_OFFLINE = ...


@pulumi.type_token("azure-native:machinelearningservices:MediaType")
class MediaType(_builtins.str, Enum):
    
    IMAGE = ...
    TEXT = ...


@pulumi.type_token("azure-native:machinelearningservices:ModelSize")
class ModelSize(_builtins.str, Enum):
    
    NONE = ...
    SMALL = ...
    MEDIUM = ...
    LARGE = ...
    EXTRA_LARGE = ...


@pulumi.type_token("azure-native:machinelearningservices:ModelTaskType")
class ModelTaskType(_builtins.str, Enum):
    
    CLASSIFICATION = ...
    REGRESSION = ...


@pulumi.type_token(...)
class MonitorComputeIdentityType(_builtins.str, Enum):
    
    AML_TOKEN = ...
    MANAGED_IDENTITY = ...


@pulumi.type_token(...)
class MonitorComputeType(_builtins.str, Enum):
    
    SERVERLESS_SPARK = ...


@pulumi.type_token(...)
class MonitoringFeatureDataType(_builtins.str, Enum):
    
    NUMERICAL = ...
    CATEGORICAL = ...


@pulumi.type_token(...)
class MonitoringFeatureFilterType(_builtins.str, Enum):
    
    ALL_FEATURES = ...
    TOP_N_BY_ATTRIBUTION = ...
    FEATURE_SUBSET = ...


@pulumi.type_token(...)
class MonitoringInputDataType(_builtins.str, Enum):
    
    STATIC = ...
    ROLLING = ...
    FIXED = ...


@pulumi.type_token(...)
class MonitoringNotificationType(_builtins.str, Enum):
    AML_NOTIFICATION = ...


@pulumi.type_token(...)
class MonitoringSignalType(_builtins.str, Enum):
    
    DATA_DRIFT = ...
    PREDICTION_DRIFT = ...
    DATA_QUALITY = ...
    FEATURE_ATTRIBUTION_DRIFT = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:machinelearningservices:MultiSelect")
class MultiSelect(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class NCrossValidationsMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...


@pulumi.type_token(...)
class NodesValueType(_builtins.str, Enum):
    
    ALL = ...


@pulumi.type_token(...)
class NumericalDataDriftMetric(_builtins.str, Enum):
    
    JENSEN_SHANNON_DISTANCE = ...
    POPULATION_STABILITY_INDEX = ...
    NORMALIZED_WASSERSTEIN_DISTANCE = ...
    TWO_SAMPLE_KOLMOGOROV_SMIRNOV_TEST = ...


@pulumi.type_token(...)
class NumericalDataQualityMetric(_builtins.str, Enum):
    
    NULL_VALUE_RATE = ...
    DATA_TYPE_ERROR_RATE = ...
    OUT_OF_BOUNDS_RATE = ...


@pulumi.type_token(...)
class NumericalPredictionDriftMetric(_builtins.str, Enum):
    
    JENSEN_SHANNON_DISTANCE = ...
    POPULATION_STABILITY_INDEX = ...
    NORMALIZED_WASSERSTEIN_DISTANCE = ...
    TWO_SAMPLE_KOLMOGOROV_SMIRNOV_TEST = ...


@pulumi.type_token(...)
class ObjectDetectionPrimaryMetrics(_builtins.str, Enum):
    
    MEAN_AVERAGE_PRECISION = ...


@pulumi.type_token(...)
class OneLakeArtifactType(_builtins.str, Enum):
    
    LAKE_HOUSE = ...


@pulumi.type_token(...)
class OperatingSystemType(_builtins.str, Enum):
    
    LINUX = ...
    WINDOWS = ...


@pulumi.type_token("azure-native:machinelearningservices:OsType")
class OsType(_builtins.str, Enum):
    
    LINUX = ...
    WINDOWS = ...


@pulumi.type_token(...)
class OutputDeliveryMode(_builtins.str, Enum):
    
    READ_WRITE_MOUNT = ...
    UPLOAD = ...
    DIRECT = ...


@pulumi.type_token("azure-native:machinelearningservices:Protocol")
class Protocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    HTTP = ...


@pulumi.type_token(...)
class PublicNetworkAccessType(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class RaiPolicyContentSource(_builtins.str, Enum):
    
    PROMPT = ...
    COMPLETION = ...


@pulumi.type_token("azure-native:machinelearningservices:RaiPolicyMode")
class RaiPolicyMode(_builtins.str, Enum):
    
    DEFAULT = ...
    DEFERRED = ...
    BLOCKING = ...


@pulumi.type_token("azure-native:machinelearningservices:RaiPolicyType")
class RaiPolicyType(_builtins.str, Enum):
    
    USER_MANAGED = ...
    SYSTEM_MANAGED = ...


@pulumi.type_token(...)
class RandomSamplingAlgorithmRule(_builtins.str, Enum):
    
    RANDOM = ...
    SOBOL = ...


@pulumi.type_token(...)
class RecurrenceFrequency(_builtins.str, Enum):
    
    MINUTE = ...
    HOUR = ...
    DAY = ...
    WEEK = ...
    MONTH = ...


@pulumi.type_token("azure-native:machinelearningservices:ReferenceType")
class ReferenceType(_builtins.str, Enum):
    
    ID = ...
    DATA_PATH = ...
    OUTPUT_PATH = ...


@pulumi.type_token(...)
class RegressionModels(_builtins.str, Enum):
    
    ELASTIC_NET = ...
    GRADIENT_BOOSTING = ...
    DECISION_TREE = ...
    KNN = ...
    LASSO_LARS = ...
    SGD = ...
    RANDOM_FOREST = ...
    EXTREME_RANDOM_TREES = ...
    LIGHT_GBM = ...
    XG_BOOST_REGRESSOR = ...


@pulumi.type_token(...)
class RegressionPrimaryMetrics(_builtins.str, Enum):
    
    SPEARMAN_CORRELATION = ...
    NORMALIZED_ROOT_MEAN_SQUARED_ERROR = ...
    R2_SCORE = ...
    NORMALIZED_MEAN_ABSOLUTE_ERROR = ...


@pulumi.type_token(...)
class RemoteLoginPortPublicAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    NOT_SPECIFIED = ...


@pulumi.type_token(...)
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token(...)
class RollingRateType(_builtins.str, Enum):
    
    YEAR = ...
    MONTH = ...
    DAY = ...
    HOUR = ...
    MINUTE = ...


@pulumi.type_token("azure-native:machinelearningservices:RuleAction")
class RuleAction(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:machinelearningservices:RuleCategory")
class RuleCategory(_builtins.str, Enum):
    
    REQUIRED = ...
    RECOMMENDED = ...
    USER_DEFINED = ...
    DEPENDENCY = ...


@pulumi.type_token("azure-native:machinelearningservices:RuleStatus")
class RuleStatus(_builtins.str, Enum):
    
    INACTIVE = ...
    ACTIVE = ...
    PROVISIONING = ...
    DELETING = ...
    FAILED = ...


@pulumi.type_token("azure-native:machinelearningservices:RuleType")
class RuleType(_builtins.str, Enum):
    
    FQDN = ...
    PRIVATE_ENDPOINT = ...
    SERVICE_TAG = ...


@pulumi.type_token(...)
class SamplingAlgorithmType(_builtins.str, Enum):
    
    GRID = ...
    RANDOM = ...
    BAYESIAN = ...


@pulumi.type_token("azure-native:machinelearningservices:ScaleType")
class ScaleType(_builtins.str, Enum):
    
    DEFAULT = ...
    TARGET_UTILIZATION = ...


@pulumi.type_token(...)
class ScheduleActionType(_builtins.str, Enum):
    
    CREATE_JOB = ...
    INVOKE_BATCH_ENDPOINT = ...
    CREATE_MONITOR = ...


@pulumi.type_token(...)
class ScheduleProvisioningState(_builtins.str, Enum):
    
    COMPLETED = ...
    PROVISIONING = ...
    FAILED = ...


@pulumi.type_token(...)
class ScheduleStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class SeasonalityMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:machinelearningservices:SecretsType")
class SecretsType(_builtins.str, Enum):
    
    ACCOUNT_KEY = ...
    CERTIFICATE = ...
    SAS = ...
    SERVICE_PRINCIPAL = ...


@pulumi.type_token(...)
class ServerlessInferenceEndpointAuthMode(_builtins.str, Enum):
    
    KEY = ...
    AAD = ...
    KEY_AND_AAD = ...


@pulumi.type_token(...)
class ServiceDataAccessAuthIdentity(_builtins.str, Enum):
    
    NONE = ...
    WORKSPACE_SYSTEM_ASSIGNED_IDENTITY = ...
    WORKSPACE_USER_ASSIGNED_IDENTITY = ...


@pulumi.type_token(...)
class ShortSeriesHandlingConfiguration(_builtins.str, Enum):
    
    NONE = ...
    AUTO = ...
    PAD = ...
    DROP = ...


@pulumi.type_token("azure-native:machinelearningservices:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:machinelearningservices:SourceType")
class SourceType(_builtins.str, Enum):
    
    DELIMITED_FILES = ...
    JSON_LINES_FILES = ...
    PARQUET_FILES = ...


@pulumi.type_token(...)
class SparkJobEntryType(_builtins.str, Enum):
    
    SPARK_JOB_PYTHON_ENTRY = ...
    SPARK_JOB_SCALA_ENTRY = ...


@pulumi.type_token(...)
class SshPublicAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class SslConfigStatus(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...
    AUTO = ...


@pulumi.type_token(...)
class StackMetaLearnerType(_builtins.str, Enum):
    
    NONE = ...
    LOGISTIC_REGRESSION = ...
    LOGISTIC_REGRESSION_CV = ...
    LIGHT_GBM_CLASSIFIER = ...
    ELASTIC_NET = ...
    ELASTIC_NET_CV = ...
    LIGHT_GBM_REGRESSOR = ...
    LINEAR_REGRESSION = ...


@pulumi.type_token(...)
class StochasticOptimizer(_builtins.str, Enum):
    
    NONE = ...
    SGD = ...
    ADAM = ...
    ADAMW = ...


@pulumi.type_token(...)
class SystemDatastoresAuthMode(_builtins.str, Enum):
    
    ACCESS_KEY = ...
    IDENTITY = ...
    USER_DELEGATION_SAS = ...


@pulumi.type_token(...)
class TargetAggregationFunction(_builtins.str, Enum):
    
    NONE = ...
    SUM = ...
    MAX = ...
    MIN = ...
    MEAN = ...


@pulumi.type_token(...)
class TargetLagsMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...


@pulumi.type_token(...)
class TargetRollingWindowSizeMode(_builtins.str, Enum):
    
    AUTO = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:machinelearningservices:TaskType")
class TaskType(_builtins.str, Enum):
    
    CLASSIFICATION = ...
    REGRESSION = ...
    FORECASTING = ...
    IMAGE_CLASSIFICATION = ...
    IMAGE_CLASSIFICATION_MULTILABEL = ...
    IMAGE_OBJECT_DETECTION = ...
    IMAGE_INSTANCE_SEGMENTATION = ...
    TEXT_CLASSIFICATION = ...
    TEXT_CLASSIFICATION_MULTILABEL = ...
    TEXT_NER = ...


@pulumi.type_token(...)
class TextAnnotationType(_builtins.str, Enum):
    
    CLASSIFICATION = ...
    NAMED_ENTITY_RECOGNITION = ...


@pulumi.type_token("azure-native:machinelearningservices:TriggerType")
class TriggerType(_builtins.str, Enum):
    
    RECURRENCE = ...
    CRON = ...


@pulumi.type_token("azure-native:machinelearningservices:UseStl")
class UseStl(_builtins.str, Enum):
    
    NONE = ...
    SEASON = ...
    SEASON_TREND = ...


@pulumi.type_token(...)
class ValidationMetricType(_builtins.str, Enum):
    
    NONE = ...
    COCO = ...
    VOC = ...
    COCO_VOC = ...


@pulumi.type_token("azure-native:machinelearningservices:VmPriority")
class VmPriority(_builtins.str, Enum):
    
    DEDICATED = ...
    LOW_PRIORITY = ...


@pulumi.type_token(...)
class VolumeDefinitionType(_builtins.str, Enum):
    
    BIND = ...
    VOLUME = ...
    TMPFS = ...
    NPIPE = ...


@pulumi.type_token("azure-native:machinelearningservices:WebhookType")
class WebhookType(_builtins.str, Enum):
    
    AZURE_DEV_OPS = ...


@pulumi.type_token("azure-native:machinelearningservices:WeekDay")
class WeekDay(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


