import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AuthType",
    "AuthenticationType",
    "BackupMode",
    "ManagedServiceIdentityType",
    "MongoDbReplication",
    "MongoDbShardKeyOrder",
    "MySqlTargetPlatformType",
    "ProjectSourcePlatform",
    "ProjectTargetPlatform",
    "ResourceType",
    "ServerLevelPermissionsGroup",
    "SqlSourcePlatform",
    "SsisMigrationOverwriteOption",
    "SsisStoreType",
    "TaskType",
]

@pulumi.type_token("azure-native:datamigration:AuthType")
class AuthType(_builtins.str, Enum):
    ACCOUNT_KEY = ...
    MANAGED_IDENTITY = ...

@pulumi.type_token("azure-native:datamigration:AuthenticationType")
class AuthenticationType(_builtins.str, Enum):
    NONE = ...
    WINDOWS_AUTHENTICATION = ...
    SQL_AUTHENTICATION = ...
    ACTIVE_DIRECTORY_INTEGRATED = ...
    ACTIVE_DIRECTORY_PASSWORD = ...

@pulumi.type_token("azure-native:datamigration:BackupMode")
class BackupMode(_builtins.str, Enum):
    CREATE_BACKUP = ...
    EXISTING_BACKUP = ...

@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:datamigration:MongoDbReplication")
class MongoDbReplication(_builtins.str, Enum):
    DISABLED = ...
    ONE_TIME = ...
    CONTINUOUS = ...

@pulumi.type_token("azure-native:datamigration:MongoDbShardKeyOrder")
class MongoDbShardKeyOrder(_builtins.str, Enum):
    FORWARD = ...
    REVERSE = ...
    HASHED = ...

@pulumi.type_token("azure-native:datamigration:MySqlTargetPlatformType")
class MySqlTargetPlatformType(_builtins.str, Enum):
    SQL_SERVER = ...
    AZURE_DB_FOR_MY_SQL = ...

@pulumi.type_token("azure-native:datamigration:ProjectSourcePlatform")
class ProjectSourcePlatform(_builtins.str, Enum):
    SQL = ...
    MY_SQL = ...
    POSTGRE_SQL = ...
    MONGO_DB = ...
    UNKNOWN = ...

@pulumi.type_token("azure-native:datamigration:ProjectTargetPlatform")
class ProjectTargetPlatform(_builtins.str, Enum):
    SQLDB = ...
    SQLMI = ...
    AZURE_DB_FOR_MY_SQL = ...
    AZURE_DB_FOR_POSTGRE_SQL = ...
    MONGO_DB = ...
    UNKNOWN = ...

@pulumi.type_token("azure-native:datamigration:ResourceType")
class ResourceType(_builtins.str, Enum):
    SQL_MI = ...
    SQL_VM = ...
    SQL_DB = ...
    MONGO_TO_COSMOS_DB_MONGO = ...

@pulumi.type_token(...)
class ServerLevelPermissionsGroup(_builtins.str, Enum):
    DEFAULT = ...
    MIGRATION_FROM_SQL_SERVER_TO_AZURE_DB = ...
    MIGRATION_FROM_SQL_SERVER_TO_AZURE_MI = ...
    MIGRATION_FROM_MY_SQL_TO_AZURE_DB_FOR_MY_SQL = ...
    MIGRATION_FROM_SQL_SERVER_TO_AZURE_VM = ...

@pulumi.type_token("azure-native:datamigration:SqlSourcePlatform")
class SqlSourcePlatform(_builtins.str, Enum):
    SQL_ON_PREM = ...

@pulumi.type_token(...)
class SsisMigrationOverwriteOption(_builtins.str, Enum):
    IGNORE = ...
    OVERWRITE = ...

@pulumi.type_token("azure-native:datamigration:SsisStoreType")
class SsisStoreType(_builtins.str, Enum):
    SSIS_CATALOG = ...

@pulumi.type_token("azure-native:datamigration:TaskType")
class TaskType(_builtins.str, Enum):
    CONNECT_MONGO_DB = ...
    CONNECT_TO_SOURCE_SQL_SERVER = ...
    CONNECT_TO_SOURCE_SQL_SERVER_SYNC = ...
    CONNECT_TO_SOURCE_POSTGRE_SQL_SYNC = ...
    CONNECT_TO_SOURCE_MY_SQL = ...
    CONNECT_TO_SOURCE_ORACLE_SYNC = ...
    CONNECT_TO_TARGET_SQL_DB = ...
    CONNECT_TO_TARGET_SQL_DB_SYNC = ...
    CONNECT_TO_TARGET_AZURE_DB_FOR_POSTGRE_SQL_SYNC = ...
    CONNECT_TO_TARGET_ORACLE_AZURE_DB_FOR_POSTGRE_SQL_SYNC = ...
    CONNECT_TO_TARGET_AZURE_SQL_DB_MI = ...
    CONNECT_TO_TARGET_AZURE_SQL_DB_M_I_SYNC_LRS = ...
    CONNECT_TO_TARGET_AZURE_DB_FOR_MY_SQL = ...
    GET_USER_TABLES_SQL = ...
    GET_USER_TABLES_AZURE_SQL_DB_SYNC = ...
    GET_USER_TABLES_ORACLE = ...
    GET_USER_TABLES_POSTGRE_SQL = ...
    GET_USER_TABLES_MY_SQL = ...
    MIGRATE_MONGO_DB = ...
    MIGRATE_SQL_SERVER_AZURE_SQL_DB_MI = ...
    MIGRATE_SQL_SERVER_AZURE_SQL_DB_M_I_SYNC_LRS = ...
    MIGRATE_SQL_SERVER_SQL_DB = ...
    MIGRATE_SQL_SERVER_AZURE_SQL_DB_SYNC = ...
    MIGRATE_MY_SQL_AZURE_DB_FOR_MY_SQL_SYNC = ...
    MIGRATE_MY_SQL_AZURE_DB_FOR_MY_SQL = ...
    MIGRATE_POSTGRE_SQL_AZURE_DB_FOR_POSTGRE_SQL_SYNC_V2 = ...
    MIGRATE_ORACLE_AZURE_DB_FOR_POSTGRE_SQL_SYNC = ...
    VALIDATE_MIGRATION_INPUT_SQL_SERVER_SQL_DB_SYNC = ...
    VALIDATE_MIGRATION_INPUT_SQL_SERVER_AZURE_SQL_DB_MI = ...
    VALIDATE_MIGRATION_INPUT_SQL_SERVER_AZURE_SQL_DB_M_I_SYNC_LRS = ...
    VALIDATE_MONGO_DB = ...
    VALIDATE_ORACLE_AZURE_DB_POSTGRE_SQL_SYNC = ...
    GET_TDE_CERTIFICATES_SQL = ...
    MIGRATE_SSIS = ...
    SERVICE_CHECK_OCI = ...
    SERVICE_UPLOAD_OCI = ...
    SERVICE_INSTALL_OCI = ...
    MIGRATE_SCHEMA_SQL_SERVER_SQL_DB = ...
