import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["SubscriptionFeatureRegistrationState"]

@pulumi.type_token(...)
class SubscriptionFeatureRegistrationState(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NOT_REGISTERED = ...
    PENDING = ...
    REGISTERING = ...
    REGISTERED = ...
    UNREGISTERING = ...
    UNREGISTERED = ...
