import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "FirewallCreationOptions",
    "ManagedIdentityResourceType",
    "ManagedServiceIdentityType",
    "ResourceCreationOptions",
    "ResourceType",
]

@pulumi.type_token("azure-native:sovereign:FirewallCreationOptions")
class FirewallCreationOptions(_builtins.str, Enum):
    NONE = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:sovereign:ManagedIdentityResourceType")
class ManagedIdentityResourceType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:sovereign:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:sovereign:ResourceCreationOptions")
class ResourceCreationOptions(_builtins.str, Enum):
    YES = ...
    NO = ...
    USE_EXISTING = ...

@pulumi.type_token("azure-native:sovereign:ResourceType")
class ResourceType(_builtins.str, Enum):
    AZURE_FIREWALLS = ...
    WORKSPACES = ...
    AUTOMATION_ACCOUNTS = ...
    DASHBOARDS = ...
    USER_ASSIGNED_IDENTITIES = ...
    BASTION_HOSTS = ...
    DDOS_PROTECTION_PLANS = ...
    NETWORK_SECURITY_GROUPS = ...
    VIRTUAL_NETWORKS = ...
    ROUTE_TABLES = ...
