import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetOuContainerResult",
    "AwaitableGetOuContainerResult",
    "get_ou_container",
    "get_ou_container_output",
]

@pulumi.output_type
class GetOuContainerResult:
    def __init__(
        __self__,
        accounts=...,
        azure_api_version=...,
        container_id=...,
        deployment_id=...,
        distinguished_name=...,
        domain_name=...,
        etag=...,
        id=...,
        location=...,
        name=...,
        provisioning_state=...,
        service_status=...,
        system_data=...,
        tags=...,
        tenant_id=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def accounts(self) -> Optional[Sequence[outputs.ContainerAccountResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="containerId")
    def container_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="deploymentId")
    def deployment_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="distinguishedName")
    def distinguished_name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="domainName")
    def domain_name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def etag(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="serviceStatus")
    def service_status(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetOuContainerResult(GetOuContainerResult):
    def __await__(self): ...

def get_ou_container(
    domain_service_name: Optional[_builtins.str] = ...,
    ou_container_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetOuContainerResult: ...
def get_ou_container_output(
    domain_service_name: Optional[pulumi.Input[_builtins.str]] = ...,
    ou_container_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetOuContainerResult]: ...
