

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccountType', 'AddonType', 'AzureContainerDataFormat', 'ClientPermissionType', 'DataPolicy', 'DataResidencyType', 'DayOfWeek', 'EncryptionAlgorithm', 'MonitoringStatus', 'MsiIdentityType', 'PlatformType', 'RoleStatus', 'RoleTypes', 'SSLStatus', 'ShareAccessProtocol', 'ShareAccessType', 'ShareStatus', 'ShipmentType', 'SkuName', 'SkuTier', 'StorageAccountStatus', 'TriggerEventType', 'UserType']
@pulumi.type_token("azure-native:databoxedge:AccountType")
class AccountType(_builtins.str, Enum):
    
    GENERAL_PURPOSE_STORAGE = ...
    BLOB_STORAGE = ...


@pulumi.type_token("azure-native:databoxedge:AddonType")
class AddonType(_builtins.str, Enum):
    
    IOT_EDGE = ...
    ARC_FOR_KUBERNETES = ...


@pulumi.type_token("azure-native:databoxedge:AzureContainerDataFormat")
class AzureContainerDataFormat(_builtins.str, Enum):
    
    BLOCK_BLOB = ...
    PAGE_BLOB = ...
    AZURE_FILE = ...


@pulumi.type_token("azure-native:databoxedge:ClientPermissionType")
class ClientPermissionType(_builtins.str, Enum):
    
    NO_ACCESS = ...
    READ_ONLY = ...
    READ_WRITE = ...


@pulumi.type_token("azure-native:databoxedge:DataPolicy")
class DataPolicy(_builtins.str, Enum):
    
    CLOUD = ...
    LOCAL = ...


@pulumi.type_token("azure-native:databoxedge:DataResidencyType")
class DataResidencyType(_builtins.str, Enum):
    
    GEO_ZONE_REPLICATION = ...
    ZONE_REPLICATION = ...


@pulumi.type_token("azure-native:databoxedge:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...


@pulumi.type_token("azure-native:databoxedge:EncryptionAlgorithm")
class EncryptionAlgorithm(_builtins.str, Enum):
    
    NONE = ...
    AES256 = ...
    RSAE_S_PKCS1_V_1_5 = ...


@pulumi.type_token("azure-native:databoxedge:MonitoringStatus")
class MonitoringStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:databoxedge:MsiIdentityType")
class MsiIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


@pulumi.type_token("azure-native:databoxedge:PlatformType")
class PlatformType(_builtins.str, Enum):
    
    WINDOWS = ...
    LINUX = ...


@pulumi.type_token("azure-native:databoxedge:RoleStatus")
class RoleStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:databoxedge:RoleTypes")
class RoleTypes(_builtins.str, Enum):
    
    IOT = ...
    ASA = ...
    FUNCTIONS = ...
    COGNITIVE = ...
    MEC = ...
    CLOUD_EDGE_MANAGEMENT = ...
    KUBERNETES = ...


@pulumi.type_token("azure-native:databoxedge:SSLStatus")
class SSLStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:databoxedge:ShareAccessProtocol")
class ShareAccessProtocol(_builtins.str, Enum):
    
    SMB = ...
    NFS = ...


@pulumi.type_token("azure-native:databoxedge:ShareAccessType")
class ShareAccessType(_builtins.str, Enum):
    
    CHANGE = ...
    READ = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:databoxedge:ShareStatus")
class ShareStatus(_builtins.str, Enum):
    
    OFFLINE = ...
    UNKNOWN = ...
    OK = ...
    UPDATING = ...
    NEEDS_ATTENTION = ...


@pulumi.type_token("azure-native:databoxedge:ShipmentType")
class ShipmentType(_builtins.str, Enum):
    
    NOT_APPLICABLE = ...
    SHIPPED_TO_CUSTOMER = ...
    SELF_PICKUP = ...


@pulumi.type_token("azure-native:databoxedge:SkuName")
class SkuName(_builtins.str, Enum):
    
    GATEWAY = ...
    EDGE = ...
    TE_A_1_NODE = ...
    TE_A_1_NODE_UPS = ...
    TE_A_1_NODE_HEATER = ...
    TE_A_1_NODE_UP_S_HEATER = ...
    TE_A_4_NODE_HEATER = ...
    TE_A_4_NODE_UP_S_HEATER = ...
    TMA = ...
    TDC = ...
    TC_A_SMALL = ...
    GPU = ...
    TC_A_LARGE = ...
    EDGE_P_BASE = ...
    EDGE_P_HIGH = ...
    EDGE_P_R_BASE = ...
    EDGE_P_R_BASE_UPS = ...
    EP2_64_1_VP_U_W = ...
    EP2_128_1_T4_MX1_W = ...
    EP2_256_2_T4_W = ...
    EDGE_M_R_MINI = ...
    RC_A_SMALL = ...
    RC_A_LARGE = ...
    RDC = ...
    MANAGEMENT = ...
    EP2_64_MX1_W = ...
    EP2_128_GPU1_MX1_W = ...
    EP2_256_GPU2_MX1 = ...
    EDGE_M_R_TCP = ...


@pulumi.type_token("azure-native:databoxedge:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    STANDARD = ...


@pulumi.type_token("azure-native:databoxedge:StorageAccountStatus")
class StorageAccountStatus(_builtins.str, Enum):
    
    OK = ...
    OFFLINE = ...
    UNKNOWN = ...
    UPDATING = ...
    NEEDS_ATTENTION = ...


@pulumi.type_token("azure-native:databoxedge:TriggerEventType")
class TriggerEventType(_builtins.str, Enum):
    
    FILE_EVENT = ...
    PERIODIC_TIMER_EVENT = ...


@pulumi.type_token("azure-native:databoxedge:UserType")
class UserType(_builtins.str, Enum):
    
    SHARE = ...
    LOCAL_MANAGEMENT = ...
    ARM = ...


