[project]
name = "pulumi-stubs"
version = "0.1.0"
description = "Type stubs for pulumi Python SDK"
license = "MIT"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
readme = "README.md"
requires-python = ">=3.9,<4"
dependencies = [
    "pulumi-aws-stubs",
    "pulumi-gcp-stubs",
    "pulumi-azure-native-stubs",
]

[tool.uv.sources]
pulumi-aws-stubs = { path = "packages/pulumi-aws-stubs" }
pulumi-gcp-stubs = { path = "packages/pulumi-gcp-stubs" }
pulumi-azure-native-stubs = { path = "packages/pulumi-azure-native-stubs" }

[dependency-groups]
dev = [
    "pyright>=1.1.408",
    "ruff>=0.15.7",
    "pulumi-aws==7.23.0",
    "pulumi-gcp==9.16.0",
    "pulumi-azure-native==3.16.0",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[tool.ruff]
force-exclude = true
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = [
  "PYI021",
]
