import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AlertAutoMitigate",
    "AlertRuleStatus",
    "AppServicePlanTier",
    "BackupType",
    "ConditionalOperator",
    "DayOfWeek",
    "DiskSkuName",
    "FileShareConfigurationType",
    "IAASVMPolicyType",
    "ManagedResourcesNetworkAccessType",
    "ManagedServiceIdentityType",
    "MonthOfYear",
    "NamingPatternType",
    "OSType",
    "PolicyType",
    "RetentionDurationType",
    "RetentionScheduleFormat",
    "RoutingPreference",
    "SAPConfigurationType",
    "SAPDatabaseScaleMethod",
    "SAPDatabaseType",
    "SAPDeploymentType",
    "SAPEnvironmentType",
    "SAPHighAvailabilityType",
    "SAPProductType",
    "SAPSoftwareInstallationType",
    "SAPVirtualInstanceIdentityType",
    "ScheduleRunType",
    "SslCryptoProvider",
    "SslPreference",
    "TieringMode",
    "VaultType",
    "WeekOfMonth",
    "WorkloadType",
]

@pulumi.type_token("azure-native:workloads:AlertAutoMitigate")
class AlertAutoMitigate(_builtins.str, Enum):
    ENABLE = ...
    DISABLE = ...

@pulumi.type_token("azure-native:workloads:AlertRuleStatus")
class AlertRuleStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:workloads:AppServicePlanTier")
class AppServicePlanTier(_builtins.str, Enum):
    ELASTIC_PREMIUM = ...
    PREMIUM_V3 = ...

@pulumi.type_token("azure-native:workloads:BackupType")
class BackupType(_builtins.str, Enum):
    VM = ...
    SQL = ...
    HANA = ...

@pulumi.type_token("azure-native:workloads:ConditionalOperator")
class ConditionalOperator(_builtins.str, Enum):
    LESS_THAN = ...
    GREATER_THAN = ...
    EQUAL = ...
    GREATER_THAN_OR_EQUAL = ...
    LESS_THAN_OR_EQUAL = ...

@pulumi.type_token("azure-native:workloads:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:workloads:DiskSkuName")
class DiskSkuName(_builtins.str, Enum):
    STANDARD_LRS = ...
    PREMIUM_LRS = ...
    STANDARD_SS_D_LRS = ...
    ULTRA_SS_D_LRS = ...
    PREMIUM_ZRS = ...
    STANDARD_SS_D_ZRS = ...
    PREMIUM_V2_LRS = ...

@pulumi.type_token("azure-native:workloads:FileShareConfigurationType")
class FileShareConfigurationType(_builtins.str, Enum):
    SKIP = ...
    CREATE_AND_MOUNT = ...
    MOUNT = ...

@pulumi.type_token("azure-native:workloads:IAASVMPolicyType")
class IAASVMPolicyType(_builtins.str, Enum):
    INVALID = ...
    V1 = ...
    V2 = ...

@pulumi.type_token(...)
class ManagedResourcesNetworkAccessType(_builtins.str, Enum):
    PUBLIC = ...
    PRIVATE = ...

@pulumi.type_token("azure-native:workloads:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:workloads:MonthOfYear")
class MonthOfYear(_builtins.str, Enum):
    INVALID = ...
    JANUARY = ...
    FEBRUARY = ...
    MARCH = ...
    APRIL = ...
    MAY = ...
    JUNE = ...
    JULY = ...
    AUGUST = ...
    SEPTEMBER = ...
    OCTOBER = ...
    NOVEMBER = ...
    DECEMBER = ...

@pulumi.type_token("azure-native:workloads:NamingPatternType")
class NamingPatternType(_builtins.str, Enum):
    FULL_RESOURCE_NAME = ...

@pulumi.type_token("azure-native:workloads:OSType")
class OSType(_builtins.str, Enum):
    LINUX = ...
    WINDOWS = ...

@pulumi.type_token("azure-native:workloads:PolicyType")
class PolicyType(_builtins.str, Enum):
    INVALID = ...
    FULL = ...
    DIFFERENTIAL = ...
    LOG = ...
    COPY_ONLY_FULL = ...
    INCREMENTAL = ...
    SNAPSHOT_FULL = ...
    SNAPSHOT_COPY_ONLY_FULL = ...

@pulumi.type_token("azure-native:workloads:RetentionDurationType")
class RetentionDurationType(_builtins.str, Enum):
    INVALID = ...
    DAYS = ...
    WEEKS = ...
    MONTHS = ...
    YEARS = ...

@pulumi.type_token("azure-native:workloads:RetentionScheduleFormat")
class RetentionScheduleFormat(_builtins.str, Enum):
    INVALID = ...
    DAILY = ...
    WEEKLY = ...

@pulumi.type_token("azure-native:workloads:RoutingPreference")
class RoutingPreference(_builtins.str, Enum):
    DEFAULT = ...
    ROUTE_ALL = ...

@pulumi.type_token("azure-native:workloads:SAPConfigurationType")
class SAPConfigurationType(_builtins.str, Enum):
    DEPLOYMENT = ...
    DISCOVERY = ...
    DEPLOYMENT_WITH_OS_CONFIG = ...

@pulumi.type_token("azure-native:workloads:SAPDatabaseScaleMethod")
class SAPDatabaseScaleMethod(_builtins.str, Enum):
    SCALE_UP = ...

@pulumi.type_token("azure-native:workloads:SAPDatabaseType")
class SAPDatabaseType(_builtins.str, Enum):
    HANA = ...
    DB2 = ...

@pulumi.type_token("azure-native:workloads:SAPDeploymentType")
class SAPDeploymentType(_builtins.str, Enum):
    SINGLE_SERVER = ...
    THREE_TIER = ...

@pulumi.type_token("azure-native:workloads:SAPEnvironmentType")
class SAPEnvironmentType(_builtins.str, Enum):
    NON_PROD = ...
    PROD = ...

@pulumi.type_token("azure-native:workloads:SAPHighAvailabilityType")
class SAPHighAvailabilityType(_builtins.str, Enum):
    AVAILABILITY_SET = ...
    AVAILABILITY_ZONE = ...

@pulumi.type_token("azure-native:workloads:SAPProductType")
class SAPProductType(_builtins.str, Enum):
    ECC = ...
    S4_HANA = ...
    OTHER = ...

@pulumi.type_token("azure-native:workloads:SAPSoftwareInstallationType")
class SAPSoftwareInstallationType(_builtins.str, Enum):
    SERVICE_INITIATED = ...
    SAP_INSTALL_WITHOUT_OS_CONFIG = ...
    EXTERNAL = ...

@pulumi.type_token(...)
class SAPVirtualInstanceIdentityType(_builtins.str, Enum):
    NONE = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:workloads:ScheduleRunType")
class ScheduleRunType(_builtins.str, Enum):
    INVALID = ...
    DAILY = ...
    WEEKLY = ...
    HOURLY = ...

@pulumi.type_token("azure-native:workloads:SslCryptoProvider")
class SslCryptoProvider(_builtins.str, Enum):
    COMMONCRYPTO = ...
    OPENSSL = ...

@pulumi.type_token("azure-native:workloads:SslPreference")
class SslPreference(_builtins.str, Enum):
    DISABLED = ...
    ROOT_CERTIFICATE = ...
    SERVER_CERTIFICATE = ...

@pulumi.type_token("azure-native:workloads:TieringMode")
class TieringMode(_builtins.str, Enum):
    INVALID = ...
    TIER_RECOMMENDED = ...
    TIER_AFTER = ...
    DO_NOT_TIER = ...

@pulumi.type_token("azure-native:workloads:VaultType")
class VaultType(_builtins.str, Enum):
    EXISTING = ...
    NEW = ...

@pulumi.type_token("azure-native:workloads:WeekOfMonth")
class WeekOfMonth(_builtins.str, Enum):
    FIRST = ...
    SECOND = ...
    THIRD = ...
    FOURTH = ...
    LAST = ...
    INVALID = ...

@pulumi.type_token("azure-native:workloads:WorkloadType")
class WorkloadType(_builtins.str, Enum):
    INVALID = ...
    VM = ...
    FILE_FOLDER = ...
    AZURE_SQL_DB = ...
    SQLDB = ...
    EXCHANGE = ...
    SHAREPOINT = ...
    V_MWARE_VM = ...
    SYSTEM_STATE = ...
    CLIENT = ...
    GENERIC_DATA_SOURCE = ...
    SQL_DATA_BASE = ...
    AZURE_FILE_SHARE = ...
    SAP_HANA_DATABASE = ...
    SAPASE_DATABASE = ...
    SAP_HANA_DB_INSTANCE = ...
