

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AuthCredentialsKind', 'ManagedServiceIdentityType', 'SkuTier']
@pulumi.type_token(...)
class AuthCredentialsKind(_builtins.str, Enum):
    
    O_AUTH_CLIENT_CREDENTIALS = ...
    API_KEY_AUTH_CREDENTIALS = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:agricultureplatform:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


