

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessKeyPermissions', 'ActionType', 'AllowType', 'AuthMode', 'AuthType', 'AzureResourceType', 'ClientType', 'DaprMetadataRequired', 'DeleteOrUpdateBehavior', 'DryrunActionName', 'SecretType', 'TargetServiceType', 'VNetSolutionType']
@pulumi.type_token("azure-native:servicelinker:AccessKeyPermissions")
class AccessKeyPermissions(_builtins.str, Enum):
    READ = ...
    WRITE = ...
    LISTEN = ...
    SEND = ...
    MANAGE = ...


@pulumi.type_token("azure-native:servicelinker:ActionType")
class ActionType(_builtins.str, Enum):
    
    ENABLE = ...
    OPT_OUT = ...


@pulumi.type_token("azure-native:servicelinker:AllowType")
class AllowType(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:servicelinker:AuthMode")
class AuthMode(_builtins.str, Enum):
    
    OPT_IN_ALL_AUTH = ...
    OPT_OUT_ALL_AUTH = ...


@pulumi.type_token("azure-native:servicelinker:AuthType")
class AuthType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED_IDENTITY = ...
    USER_ASSIGNED_IDENTITY = ...
    SERVICE_PRINCIPAL_SECRET = ...
    SERVICE_PRINCIPAL_CERTIFICATE = ...
    SECRET = ...
    ACCESS_KEY = ...
    USER_ACCOUNT = ...
    EASY_AUTH_MICROSOFT_ENTRA_ID = ...


@pulumi.type_token("azure-native:servicelinker:AzureResourceType")
class AzureResourceType(_builtins.str, Enum):
    
    KEY_VAULT = ...


@pulumi.type_token("azure-native:servicelinker:ClientType")
class ClientType(_builtins.str, Enum):
    
    NONE = ...
    DOTNET = ...
    JAVA = ...
    PYTHON = ...
    GO = ...
    PHP = ...
    RUBY = ...
    DJANGO = ...
    NODEJS = ...
    SPRING_BOOT = ...
    KAFKA_SPRING_BOOT = ...
    JMS_SPRING_BOOT = ...
    DAPR = ...


@pulumi.type_token("azure-native:servicelinker:DaprMetadataRequired")
class DaprMetadataRequired(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:servicelinker:DeleteOrUpdateBehavior")
class DeleteOrUpdateBehavior(_builtins.str, Enum):
    
    DEFAULT = ...
    FORCED_CLEANUP = ...


@pulumi.type_token("azure-native:servicelinker:DryrunActionName")
class DryrunActionName(_builtins.str, Enum):
    
    CREATE_OR_UPDATE = ...


@pulumi.type_token("azure-native:servicelinker:SecretType")
class SecretType(_builtins.str, Enum):
    
    RAW_VALUE = ...
    KEY_VAULT_SECRET_URI = ...
    KEY_VAULT_SECRET_REFERENCE = ...


@pulumi.type_token("azure-native:servicelinker:TargetServiceType")
class TargetServiceType(_builtins.str, Enum):
    
    AZURE_RESOURCE = ...
    CONFLUENT_BOOTSTRAP_SERVER = ...
    CONFLUENT_SCHEMA_REGISTRY = ...
    SELF_HOSTED_SERVER = ...


@pulumi.type_token("azure-native:servicelinker:VNetSolutionType")
class VNetSolutionType(_builtins.str, Enum):
    
    SERVICE_ENDPOINT = ...
    PRIVATE_LINK = ...


