

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['KeyEncryptionKeyIdentityType', 'ManagedServiceIdentityType', 'OnlineExperimentationWorkspaceSkuName', 'PrivateEndpointServiceConnectionStatus']
@pulumi.type_token(...)
class KeyEncryptionKeyIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED_IDENTITY = ...
    USER_ASSIGNED_IDENTITY = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token(...)
class OnlineExperimentationWorkspaceSkuName(_builtins.str, Enum):
    
    F0 = ...
    S0 = ...
    P0 = ...
    D0 = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


