import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AgreementType",
    "DayOfWeek",
    "DaysOfWeek",
    "EdifactCharacterSet",
    "EdifactDecimalIndicator",
    "EncryptionAlgorithm",
    "HashingAlgorithm",
    "IntegrationAccountSkuName",
    "IntegrationServiceEnvironmentAccessEndpointType",
    "IntegrationServiceEnvironmentSkuName",
    "KeyType",
    "ManagedServiceIdentityType",
    "MapType",
    "MessageFilterType",
    "OpenAuthenticationProviderType",
    "ParameterType",
    "PartnerType",
    "RecurrenceFrequency",
    "RosettaNetActionType",
    "RosettaNetPipActivityType",
    "RosettaNetPipConfidentialityScope",
    "RosettaNetPipRoleType",
    "RosettaNetResponseType",
    "SchemaType",
    "SegmentTerminatorSuffix",
    "SigningAlgorithm",
    "TrailingSeparatorPolicy",
    "UsageIndicator",
    "WorkflowProvisioningState",
    "WorkflowState",
    "X12CharacterSet",
    "X12DateFormat",
    "X12TimeFormat",
]

@pulumi.type_token("azure-native:logic:AgreementType")
class AgreementType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    AS2 = ...
    X12 = ...
    EDIFACT = ...

@pulumi.type_token("azure-native:logic:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:logic:DaysOfWeek")
class DaysOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:logic:EdifactCharacterSet")
class EdifactCharacterSet(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    UNOB = ...
    UNOA = ...
    UNOC = ...
    UNOD = ...
    UNOE = ...
    UNOF = ...
    UNOG = ...
    UNOH = ...
    UNOI = ...
    UNOJ = ...
    UNOK = ...
    UNOX = ...
    UNOY = ...
    KECA = ...

@pulumi.type_token("azure-native:logic:EdifactDecimalIndicator")
class EdifactDecimalIndicator(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    COMMA = ...
    DECIMAL = ...

@pulumi.type_token("azure-native:logic:EncryptionAlgorithm")
class EncryptionAlgorithm(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NONE = ...
    DES3 = ...
    RC2 = ...
    AES128 = ...
    AES192 = ...
    AES256 = ...

@pulumi.type_token("azure-native:logic:HashingAlgorithm")
class HashingAlgorithm(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NONE = ...
    MD5 = ...
    SHA1 = ...
    SHA2256 = ...
    SHA2384 = ...
    SHA2512 = ...

@pulumi.type_token("azure-native:logic:IntegrationAccountSkuName")
class IntegrationAccountSkuName(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    FREE = ...
    BASIC = ...
    STANDARD = ...

@pulumi.type_token(...)
class IntegrationServiceEnvironmentAccessEndpointType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    EXTERNAL = ...
    INTERNAL = ...

@pulumi.type_token(...)
class IntegrationServiceEnvironmentSkuName(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    PREMIUM = ...
    DEVELOPER = ...

@pulumi.type_token("azure-native:logic:KeyType")
class KeyType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    PRIMARY = ...
    SECONDARY = ...

@pulumi.type_token("azure-native:logic:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    NONE = ...

@pulumi.type_token("azure-native:logic:MapType")
class MapType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    XSLT = ...
    XSLT20 = ...
    XSLT30 = ...
    LIQUID = ...

@pulumi.type_token("azure-native:logic:MessageFilterType")
class MessageFilterType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    INCLUDE = ...
    EXCLUDE = ...

@pulumi.type_token("azure-native:logic:OpenAuthenticationProviderType")
class OpenAuthenticationProviderType(_builtins.str, Enum):
    AAD = ...

@pulumi.type_token("azure-native:logic:ParameterType")
class ParameterType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    STRING = ...
    SECURE_STRING = ...
    INT = ...
    FLOAT = ...
    BOOL = ...
    ARRAY = ...
    OBJECT = ...
    SECURE_OBJECT = ...

@pulumi.type_token("azure-native:logic:PartnerType")
class PartnerType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    B2_B = ...

@pulumi.type_token("azure-native:logic:RecurrenceFrequency")
class RecurrenceFrequency(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SECOND = ...
    MINUTE = ...
    HOUR = ...
    DAY = ...
    WEEK = ...
    MONTH = ...
    YEAR = ...

@pulumi.type_token("azure-native:logic:RosettaNetActionType")
class RosettaNetActionType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SINGLE_ACTION = ...
    DOUBLE_ACTION = ...

@pulumi.type_token("azure-native:logic:RosettaNetPipActivityType")
class RosettaNetPipActivityType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    INFORMATION_DISTRIBUTION = ...
    BUSINESS_TRANSACTION = ...
    NOTIFICATION = ...
    QUERY_RESPONSE = ...
    REQUEST_CONFIRM = ...
    REQUEST_RESPONSE = ...

@pulumi.type_token(...)
class RosettaNetPipConfidentialityScope(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NONE = ...
    PAYLOAD = ...
    PAYLOAD_CONTAINER = ...

@pulumi.type_token("azure-native:logic:RosettaNetPipRoleType")
class RosettaNetPipRoleType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    FUNCTIONAL = ...
    ORGANIZATIONAL = ...
    EMPLOYEE = ...

@pulumi.type_token("azure-native:logic:RosettaNetResponseType")
class RosettaNetResponseType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SYNC = ...
    ASYNC_ = ...

@pulumi.type_token("azure-native:logic:SchemaType")
class SchemaType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    XML = ...

@pulumi.type_token("azure-native:logic:SegmentTerminatorSuffix")
class SegmentTerminatorSuffix(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NONE = ...
    CR = ...
    LF = ...
    CRLF = ...

@pulumi.type_token("azure-native:logic:SigningAlgorithm")
class SigningAlgorithm(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    DEFAULT = ...
    SHA1 = ...
    SHA2256 = ...
    SHA2384 = ...
    SHA2512 = ...

@pulumi.type_token("azure-native:logic:TrailingSeparatorPolicy")
class TrailingSeparatorPolicy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NOT_ALLOWED = ...
    OPTIONAL = ...
    MANDATORY = ...

@pulumi.type_token("azure-native:logic:UsageIndicator")
class UsageIndicator(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    TEST = ...
    INFORMATION = ...
    PRODUCTION = ...

@pulumi.type_token("azure-native:logic:WorkflowProvisioningState")
class WorkflowProvisioningState(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ACCEPTED = ...
    RUNNING = ...
    READY = ...
    CREATING = ...
    CREATED = ...
    DELETING = ...
    DELETED = ...
    CANCELED = ...
    FAILED = ...
    SUCCEEDED = ...
    MOVING = ...
    UPDATING = ...
    REGISTERING = ...
    REGISTERED = ...
    UNREGISTERING = ...
    UNREGISTERED = ...
    COMPLETED = ...
    RENEWING = ...
    PENDING = ...
    WAITING = ...
    IN_PROGRESS = ...

@pulumi.type_token("azure-native:logic:WorkflowState")
class WorkflowState(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    COMPLETED = ...
    ENABLED = ...
    DISABLED = ...
    DELETED = ...
    SUSPENDED = ...

@pulumi.type_token("azure-native:logic:X12CharacterSet")
class X12CharacterSet(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    BASIC = ...
    EXTENDED = ...
    UTF8 = ...

@pulumi.type_token("azure-native:logic:X12DateFormat")
class X12DateFormat(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CCYYMMDD = ...
    YYMMDD = ...

@pulumi.type_token("azure-native:logic:X12TimeFormat")
class X12TimeFormat(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    HHMM = ...
    HHMMSS = ...
    HHMMS_SDD = ...
    HHMMS_SD = ...
