import builtins as _builtins
import typing
from .. import _utilities
from ._enums import *
from .auto_scale_v_core import *
from .capacity_details import *
from .get_auto_scale_v_core import *
from .get_capacity_details import *
from ._inputs import *
from . import outputs

"""
This type stub file was generated by pyright.
"""
