import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ACLAction",
    "FeatureFlags",
    "ManagedIdentityType",
    "PrivateLinkServiceConnectionStatus",
    "ServiceKind",
    "SignalRRequestType",
    "SignalRSkuTier",
    "UpstreamAuthType",
]

@pulumi.type_token("azure-native:signalrservice:ACLAction")
class ACLAction(_builtins.str, Enum):
    ALLOW = ...
    DENY = ...

@pulumi.type_token("azure-native:signalrservice:FeatureFlags")
class FeatureFlags(_builtins.str, Enum):
    SERVICE_MODE = ...
    ENABLE_CONNECTIVITY_LOGS = ...
    ENABLE_MESSAGING_LOGS = ...
    ENABLE_LIVE_TRACE = ...

@pulumi.type_token("azure-native:signalrservice:ManagedIdentityType")
class ManagedIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token(...)
class PrivateLinkServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:signalrservice:ServiceKind")
class ServiceKind(_builtins.str, Enum):
    SIGNAL_R = ...
    RAW_WEB_SOCKETS = ...

@pulumi.type_token("azure-native:signalrservice:SignalRRequestType")
class SignalRRequestType(_builtins.str, Enum):
    CLIENT_CONNECTION = ...
    SERVER_CONNECTION = ...
    RESTAPI = ...
    TRACE = ...

@pulumi.type_token("azure-native:signalrservice:SignalRSkuTier")
class SignalRSkuTier(_builtins.str, Enum):
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:signalrservice:UpstreamAuthType")
class UpstreamAuthType(_builtins.str, Enum):
    NONE = ...
    MANAGED_IDENTITY = ...
