

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['Action', 'ActionsRequired', 'Architecture', 'AuditLogStatus', 'AzureADAuthenticationAsArmPolicyStatus', 'BaseImageTriggerType', 'ConnectedRegistryMode', 'ConnectionStatus', 'CredentialName', 'DefaultAction', 'EncryptionStatus', 'ExportPolicyStatus', 'LogLevel', 'NetworkRuleBypassOptions', 'OS', 'PackageSourceType', 'PipelineOptions', 'PipelineRunSourceType', 'PipelineRunTargetType', 'PipelineSourceType', 'PolicyStatus', 'PublicNetworkAccess', 'ResourceIdentityType', 'SecretObjectType', 'SkuName', 'SourceControlType', 'SourceRegistryLoginMode', 'SourceTriggerEvent', 'StepType', 'TaskStatus', 'TokenCertificateName', 'TokenPasswordName', 'TokenStatus', 'TokenType', 'TriggerStatus', 'TrustPolicyType', 'UpdateTriggerPayloadType', 'Variant', 'WebhookAction', 'WebhookStatus', 'ZoneRedundancy']
@pulumi.type_token("azure-native:containerregistry:Action")
class Action(_builtins.str, Enum):
    
    ALLOW = ...


@pulumi.type_token("azure-native:containerregistry:ActionsRequired")
class ActionsRequired(_builtins.str, Enum):
    
    NONE = ...
    RECREATE = ...


@pulumi.type_token("azure-native:containerregistry:Architecture")
class Architecture(_builtins.str, Enum):
    
    AMD64 = ...
    X86 = ...
    ARCHITECTURE_386 = ...
    ARM = ...
    ARM64 = ...


@pulumi.type_token("azure-native:containerregistry:AuditLogStatus")
class AuditLogStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class AzureADAuthenticationAsArmPolicyStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class BaseImageTriggerType(_builtins.str, Enum):
    
    ALL = ...
    RUNTIME = ...


@pulumi.type_token(...)
class ConnectedRegistryMode(_builtins.str, Enum):
    
    READ_WRITE = ...
    READ_ONLY = ...
    REGISTRY = ...
    MIRROR = ...


@pulumi.type_token("azure-native:containerregistry:ConnectionStatus")
class ConnectionStatus(_builtins.str, Enum):
    
    APPROVED = ...
    PENDING = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:containerregistry:CredentialName")
class CredentialName(_builtins.str, Enum):
    
    CREDENTIAL1 = ...


@pulumi.type_token("azure-native:containerregistry:DefaultAction")
class DefaultAction(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:containerregistry:EncryptionStatus")
class EncryptionStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerregistry:ExportPolicyStatus")
class ExportPolicyStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerregistry:LogLevel")
class LogLevel(_builtins.str, Enum):
    
    DEBUG = ...
    INFORMATION = ...
    WARNING = ...
    ERROR = ...
    NONE = ...


@pulumi.type_token(...)
class NetworkRuleBypassOptions(_builtins.str, Enum):
    
    AZURE_SERVICES = ...
    NONE = ...


@pulumi.type_token("azure-native:containerregistry:OS")
class OS(_builtins.str, Enum):
    
    WINDOWS = ...
    LINUX = ...


@pulumi.type_token("azure-native:containerregistry:PackageSourceType")
class PackageSourceType(_builtins.str, Enum):
    
    REMOTE = ...


@pulumi.type_token("azure-native:containerregistry:PipelineOptions")
class PipelineOptions(_builtins.str, Enum):
    OVERWRITE_TAGS = ...
    OVERWRITE_BLOBS = ...
    DELETE_SOURCE_BLOB_ON_SUCCESS = ...
    CONTINUE_ON_ERRORS = ...


@pulumi.type_token(...)
class PipelineRunSourceType(_builtins.str, Enum):
    
    AZURE_STORAGE_BLOB = ...


@pulumi.type_token(...)
class PipelineRunTargetType(_builtins.str, Enum):
    
    AZURE_STORAGE_BLOB = ...


@pulumi.type_token("azure-native:containerregistry:PipelineSourceType")
class PipelineSourceType(_builtins.str, Enum):
    
    AZURE_STORAGE_BLOB_CONTAINER = ...


@pulumi.type_token("azure-native:containerregistry:PolicyStatus")
class PolicyStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerregistry:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:containerregistry:SecretObjectType")
class SecretObjectType(_builtins.str, Enum):
    
    OPAQUE = ...
    VAULTSECRET = ...


@pulumi.type_token("azure-native:containerregistry:SkuName")
class SkuName(_builtins.str, Enum):
    
    CLASSIC = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:containerregistry:SourceControlType")
class SourceControlType(_builtins.str, Enum):
    
    GITHUB = ...
    VISUAL_STUDIO_TEAM_SERVICE = ...


@pulumi.type_token(...)
class SourceRegistryLoginMode(_builtins.str, Enum):
    
    NONE = ...
    DEFAULT = ...


@pulumi.type_token("azure-native:containerregistry:SourceTriggerEvent")
class SourceTriggerEvent(_builtins.str, Enum):
    COMMIT = ...
    PULLREQUEST = ...


@pulumi.type_token("azure-native:containerregistry:StepType")
class StepType(_builtins.str, Enum):
    
    DOCKER = ...
    FILE_TASK = ...
    ENCODED_TASK = ...


@pulumi.type_token("azure-native:containerregistry:TaskStatus")
class TaskStatus(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token(...)
class TokenCertificateName(_builtins.str, Enum):
    CERTIFICATE1 = ...
    CERTIFICATE2 = ...


@pulumi.type_token("azure-native:containerregistry:TokenPasswordName")
class TokenPasswordName(_builtins.str, Enum):
    
    PASSWORD1 = ...
    PASSWORD2 = ...


@pulumi.type_token("azure-native:containerregistry:TokenStatus")
class TokenStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerregistry:TokenType")
class TokenType(_builtins.str, Enum):
    
    PAT = ...
    O_AUTH = ...


@pulumi.type_token("azure-native:containerregistry:TriggerStatus")
class TriggerStatus(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:containerregistry:TrustPolicyType")
class TrustPolicyType(_builtins.str, Enum):
    
    NOTARY = ...


@pulumi.type_token(...)
class UpdateTriggerPayloadType(_builtins.str, Enum):
    
    DEFAULT = ...
    TOKEN = ...


@pulumi.type_token("azure-native:containerregistry:Variant")
class Variant(_builtins.str, Enum):
    
    V6 = ...
    V7 = ...
    V8 = ...


@pulumi.type_token("azure-native:containerregistry:WebhookAction")
class WebhookAction(_builtins.str, Enum):
    PUSH = ...
    DELETE = ...
    QUARANTINE = ...
    CHART_PUSH = ...
    CHART_DELETE = ...


@pulumi.type_token("azure-native:containerregistry:WebhookStatus")
class WebhookStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerregistry:ZoneRedundancy")
class ZoneRedundancy(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


