

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['MasterSitePropertiesPublicNetworkAccess', 'PrivateLinkServiceConnectionStateStatus', 'ProvisioningState', 'SqlSitePropertiesDiscoveryScenario', 'WebAppSitePropertiesDiscoveryScenario']
@pulumi.type_token(...)
class MasterSitePropertiesPublicNetworkAccess(_builtins.str, Enum):
    
    NOT_SPECIFIED = ...
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class PrivateLinkServiceConnectionStateStatus(_builtins.str, Enum):
    
    APPROVED = ...
    PENDING = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:offazure:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    
    CREATED = ...
    UPDATED = ...
    RUNNING = ...
    COMPLETED = ...
    FAILED = ...
    SUCCEEDED = ...
    CANCELED = ...


@pulumi.type_token(...)
class SqlSitePropertiesDiscoveryScenario(_builtins.str, Enum):
    
    MIGRATE = ...
    DR = ...


@pulumi.type_token(...)
class WebAppSitePropertiesDiscoveryScenario(_builtins.str, Enum):
    
    MIGRATE = ...
    DR = ...


