import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AddressType",
    "ClassDiscriminator",
    "DataAccountType",
    "DoubleEncryption",
    "FilterFileType",
    "HardwareEncryption",
    "JobDeliveryType",
    "KekType",
    "LogCollectionLevel",
    "NotificationStageName",
    "SkuName",
    "StorageAccountAccessTier",
    "TransferConfigurationType",
    "TransferType",
    "TransportShipmentTypes",
]

@pulumi.type_token("azure-native:databox:AddressType")
class AddressType(_builtins.str, Enum):
    NONE = ...
    RESIDENTIAL = ...
    COMMERCIAL = ...

@pulumi.type_token("azure-native:databox:ClassDiscriminator")
class ClassDiscriminator(_builtins.str, Enum):
    DATA_BOX = ...
    DATA_BOX_DISK = ...
    DATA_BOX_HEAVY = ...
    DATA_BOX_CUSTOMER_DISK = ...

@pulumi.type_token("azure-native:databox:DataAccountType")
class DataAccountType(_builtins.str, Enum):
    STORAGE_ACCOUNT = ...
    MANAGED_DISK = ...

@pulumi.type_token("azure-native:databox:DoubleEncryption")
class DoubleEncryption(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:databox:FilterFileType")
class FilterFileType(_builtins.str, Enum):
    AZURE_BLOB = ...
    AZURE_FILE = ...

@pulumi.type_token("azure-native:databox:HardwareEncryption")
class HardwareEncryption(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:databox:JobDeliveryType")
class JobDeliveryType(_builtins.str, Enum):
    NON_SCHEDULED = ...
    SCHEDULED = ...

@pulumi.type_token("azure-native:databox:KekType")
class KekType(_builtins.str, Enum):
    MICROSOFT_MANAGED = ...
    CUSTOMER_MANAGED = ...

@pulumi.type_token("azure-native:databox:LogCollectionLevel")
class LogCollectionLevel(_builtins.str, Enum):
    ERROR = ...
    VERBOSE = ...

@pulumi.type_token("azure-native:databox:NotificationStageName")
class NotificationStageName(_builtins.str, Enum):
    DEVICE_PREPARED = ...
    DISPATCHED = ...
    DELIVERED = ...
    PICKED_UP = ...
    AT_AZURE_DC = ...
    DATA_COPY = ...
    CREATED = ...
    SHIPPED_TO_CUSTOMER = ...

@pulumi.type_token("azure-native:databox:SkuName")
class SkuName(_builtins.str, Enum):
    DATA_BOX = ...
    DATA_BOX_DISK = ...
    DATA_BOX_HEAVY = ...
    DATA_BOX_CUSTOMER_DISK = ...

@pulumi.type_token("azure-native:databox:StorageAccountAccessTier")
class StorageAccountAccessTier(_builtins.str, Enum):
    ARCHIVE = ...

@pulumi.type_token("azure-native:databox:TransferConfigurationType")
class TransferConfigurationType(_builtins.str, Enum):
    TRANSFER_ALL = ...
    TRANSFER_USING_FILTER = ...

@pulumi.type_token("azure-native:databox:TransferType")
class TransferType(_builtins.str, Enum):
    IMPORT_TO_AZURE = ...
    EXPORT_FROM_AZURE = ...

@pulumi.type_token("azure-native:databox:TransportShipmentTypes")
class TransportShipmentTypes(_builtins.str, Enum):
    CUSTOMER_MANAGED = ...
    MICROSOFT_MANAGED = ...
