import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "DashboardPartMetadataType",
    "FontSize",
    "FontStyle",
    "OsType",
    "ProvisioningState",
    "ShellType",
]

@pulumi.type_token("azure-native:portal:DashboardPartMetadataType")
class DashboardPartMetadataType(_builtins.str, Enum):
    MARKDOWN = ...

@pulumi.type_token("azure-native:portal:FontSize")
class FontSize(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SMALL = ...
    MEDIUM = ...
    LARGE = ...

@pulumi.type_token("azure-native:portal:FontStyle")
class FontStyle(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    MONOSPACE = ...
    COURIER = ...

@pulumi.type_token("azure-native:portal:OsType")
class OsType(_builtins.str, Enum):
    WINDOWS = ...
    LINUX = ...

@pulumi.type_token("azure-native:portal:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ACCEPTED = ...
    PENDING = ...
    UPDATING = ...
    CREATING = ...
    REPAIRING = ...
    FAILED = ...
    CANCELED = ...
    SUCCEEDED = ...

@pulumi.type_token("azure-native:portal:ShellType")
class ShellType(_builtins.str, Enum):
    BASH = ...
    PWSH = ...
    POWERSHELL = ...
