

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AdditionalVmPatch', 'AssessmentDayOfWeek', 'AutoBackupDaysOfWeek', 'BackupScheduleType', 'ClusterSubnetType', 'Commit', 'ConnectivityType', 'DayOfWeek', 'DiskConfigurationType', 'Failover', 'FullBackupFrequencyType', 'IdentityType', 'LeastPrivilegeMode', 'ReadableSecondary', 'Role', 'SqlImageSku', 'SqlManagementMode', 'SqlServerLicenseType', 'SqlVmGroupImageSku', 'SqlWorkloadType', 'StorageWorkloadType', 'VmIdentityType']
@pulumi.type_token("azure-native:sqlvirtualmachine:AdditionalVmPatch")
class AdditionalVmPatch(_builtins.str, Enum):
    
    NOT_SET = ...
    MICROSOFT_UPDATE = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:AssessmentDayOfWeek")
class AssessmentDayOfWeek(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


@pulumi.type_token(...)
class AutoBackupDaysOfWeek(_builtins.str, Enum):
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:BackupScheduleType")
class BackupScheduleType(_builtins.str, Enum):
    
    MANUAL = ...
    AUTOMATED = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:ClusterSubnetType")
class ClusterSubnetType(_builtins.str, Enum):
    
    SINGLE_SUBNET = ...
    MULTI_SUBNET = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:Commit")
class Commit(_builtins.str, Enum):
    
    SYNCHRONOUS_COMMIT = ...
    ASYNCHRONOUS_COMMIT = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:ConnectivityType")
class ConnectivityType(_builtins.str, Enum):
    
    LOCAL = ...
    PRIVATE = ...
    PUBLIC = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    
    EVERYDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...


@pulumi.type_token(...)
class DiskConfigurationType(_builtins.str, Enum):
    
    NEW = ...
    EXTEND = ...
    ADD = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:Failover")
class Failover(_builtins.str, Enum):
    
    AUTOMATIC = ...
    MANUAL = ...


@pulumi.type_token(...)
class FullBackupFrequencyType(_builtins.str, Enum):
    
    DAILY = ...
    WEEKLY = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:IdentityType")
class IdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:LeastPrivilegeMode")
class LeastPrivilegeMode(_builtins.str, Enum):
    
    ENABLED = ...
    NOT_SET = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:ReadableSecondary")
class ReadableSecondary(_builtins.str, Enum):
    
    NO = ...
    ALL = ...
    READ_ONLY = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:Role")
class Role(_builtins.str, Enum):
    
    PRIMARY = ...
    SECONDARY = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:SqlImageSku")
class SqlImageSku(_builtins.str, Enum):
    
    DEVELOPER = ...
    EXPRESS = ...
    STANDARD = ...
    ENTERPRISE = ...
    WEB = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:SqlManagementMode")
class SqlManagementMode(_builtins.str, Enum):
    
    FULL = ...
    LIGHT_WEIGHT = ...
    NO_AGENT = ...


@pulumi.type_token(...)
class SqlServerLicenseType(_builtins.str, Enum):
    
    PAYG = ...
    AHUB = ...
    DR = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:SqlVmGroupImageSku")
class SqlVmGroupImageSku(_builtins.str, Enum):
    
    DEVELOPER = ...
    ENTERPRISE = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:SqlWorkloadType")
class SqlWorkloadType(_builtins.str, Enum):
    
    GENERAL = ...
    OLTP = ...
    DW = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:StorageWorkloadType")
class StorageWorkloadType(_builtins.str, Enum):
    
    GENERAL = ...
    OLTP = ...
    DW = ...


@pulumi.type_token("azure-native:sqlvirtualmachine:VmIdentityType")
class VmIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


