import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ActionPerformed",
    "ApprovalPolicy",
    "ApprovalStatus",
    "CommunityEndpointProtocol",
    "DestinationType",
    "DiagnosticDestination",
    "EnclaveEndpointProtocol",
    "Enforcement",
    "FirewallSKU",
    "Justification",
    "ManagedServiceIdentityType",
    "Mode",
    "Option",
    "PolicyAction",
    "PolicyOverride",
    "ServiceIdentifier",
    "TransitHubState",
    "TransitOptionType",
    "Type",
]

@pulumi.type_token("azure-native:mission:ActionPerformed")
class ActionPerformed(_builtins.str, Enum):
    APPROVED = ...
    REJECTED = ...

@pulumi.type_token("azure-native:mission:ApprovalPolicy")
class ApprovalPolicy(_builtins.str, Enum):
    REQUIRED = ...
    NOT_REQUIRED = ...

@pulumi.type_token("azure-native:mission:ApprovalStatus")
class ApprovalStatus(_builtins.str, Enum):
    APPROVED = ...
    REJECTED = ...
    PENDING = ...
    DELETED = ...
    EXPIRED = ...

@pulumi.type_token("azure-native:mission:CommunityEndpointProtocol")
class CommunityEndpointProtocol(_builtins.str, Enum):
    ANY = ...
    TCP = ...
    UDP = ...
    ICMP = ...
    ESP = ...
    AH = ...
    HTTPS = ...
    HTTP = ...

@pulumi.type_token("azure-native:mission:DestinationType")
class DestinationType(_builtins.str, Enum):
    FQDN = ...
    FQDN_TAG = ...
    IP_ADDRESS = ...
    PRIVATE_NETWORK = ...

@pulumi.type_token("azure-native:mission:DiagnosticDestination")
class DiagnosticDestination(_builtins.str, Enum):
    COMMUNITY_ONLY = ...
    ENCLAVE_ONLY = ...
    BOTH = ...

@pulumi.type_token("azure-native:mission:EnclaveEndpointProtocol")
class EnclaveEndpointProtocol(_builtins.str, Enum):
    ANY = ...
    TCP = ...
    UDP = ...
    ICMP = ...
    ESP = ...
    AH = ...

@pulumi.type_token("azure-native:mission:Enforcement")
class Enforcement(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:mission:FirewallSKU")
class FirewallSKU(_builtins.str, Enum):
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:mission:Justification")
class Justification(_builtins.str, Enum):
    NETWORKING = ...
    GOVERNANCE = ...
    OFF = ...

@pulumi.type_token("azure-native:mission:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:mission:Mode")
class Mode(_builtins.str, Enum):
    ON = ...
    CAN_NOT_DELETE = ...
    OFF = ...
    GENERAL = ...
    ADVANCED = ...

@pulumi.type_token("azure-native:mission:Option")
class Option(_builtins.str, Enum):
    ALLOW = ...
    DENY = ...
    EXCEPTION_ONLY = ...
    NOT_APPLICABLE = ...

@pulumi.type_token("azure-native:mission:PolicyAction")
class PolicyAction(_builtins.str, Enum):
    AUDIT_ONLY = ...
    ENFORCE = ...
    NONE = ...

@pulumi.type_token("azure-native:mission:PolicyOverride")
class PolicyOverride(_builtins.str, Enum):
    ENCLAVE = ...
    NONE = ...

@pulumi.type_token("azure-native:mission:ServiceIdentifier")
class ServiceIdentifier(_builtins.str, Enum):
    AKS = ...
    APP_SERVICE = ...
    AZURE_FIREWALLS = ...
    CONTAINER_REGISTRY = ...
    COSMOS_DB = ...
    DATA_CONNECTORS = ...
    INSIGHTS = ...
    KEY_VAULT = ...
    LOGIC = ...
    MICROSOFT_SQL = ...
    MONITORING = ...
    POSTGRE_SQL = ...
    PRIVATE_DNS_ZONES = ...
    SERVICE_BUS = ...
    STORAGE = ...

@pulumi.type_token("azure-native:mission:TransitHubState")
class TransitHubState(_builtins.str, Enum):
    PENDING_APPROVAL = ...
    APPROVED = ...
    PENDING_UPDATE = ...
    ACTIVE = ...
    FAILED = ...

@pulumi.type_token("azure-native:mission:TransitOptionType")
class TransitOptionType(_builtins.str, Enum):
    EXPRESS_ROUTE = ...
    GATEWAY = ...
    PEERING = ...

@pulumi.type_token("azure-native:mission:Type")
class Type(_builtins.str, Enum):
    USER = ...
    GROUP = ...
    SERVICE_PRINCIPAL = ...
