import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetCommunityEndpointResult",
    "AwaitableGetCommunityEndpointResult",
    "get_community_endpoint",
    "get_community_endpoint_output",
]

@pulumi.output_type
class GetCommunityEndpointResult:
    def __init__(
        __self__,
        azure_api_version=...,
        id=...,
        location=...,
        name=...,
        provisioning_state=...,
        resource_collection=...,
        rule_collection=...,
        system_data=...,
        tags=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="resourceCollection")
    def resource_collection(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="ruleCollection")
    def rule_collection(
        self,
    ) -> Sequence[outputs.CommunityEndpointDestinationRuleResponse]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetCommunityEndpointResult(GetCommunityEndpointResult):
    def __await__(self): ...

def get_community_endpoint(
    community_endpoint_name: Optional[_builtins.str] = ...,
    community_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetCommunityEndpointResult: ...
def get_community_endpoint_output(
    community_endpoint_name: Optional[pulumi.Input[_builtins.str]] = ...,
    community_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetCommunityEndpointResult]: ...
