

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['Kind', 'MsaAppType', 'PrivateEndpointServiceConnectionStatus', 'PublicNetworkAccess', 'SkuName']
@pulumi.type_token("azure-native:botservice:Kind")
class Kind(_builtins.str, Enum):
    
    SDK = ...
    DESIGNER = ...
    BOT = ...
    FUNCTION = ...
    AZUREBOT = ...


@pulumi.type_token("azure-native:botservice:MsaAppType")
class MsaAppType(_builtins.str, Enum):
    
    USER_ASSIGNED_MSI = ...
    SINGLE_TENANT = ...
    MULTI_TENANT = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:botservice:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...


@pulumi.type_token("azure-native:botservice:SkuName")
class SkuName(_builtins.str, Enum):
    
    F0 = ...
    S1 = ...


