

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['CustomerManagedKeys', 'NetworkEgressType', 'PrivateEndpointServiceConnectionStatus', 'PublicNetworkAccess', 'ScaleSetPriority', 'StorageStoreType', 'SystemSku', 'VmSize']
@pulumi.type_token("azure-native:discovery:CustomerManagedKeys")
class CustomerManagedKeys(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:discovery:NetworkEgressType")
class NetworkEgressType(_builtins.str, Enum):
    
    LOAD_BALANCER = ...
    NONE = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:discovery:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:discovery:ScaleSetPriority")
class ScaleSetPriority(_builtins.str, Enum):
    
    REGULAR = ...
    SPOT = ...


@pulumi.type_token("azure-native:discovery:StorageStoreType")
class StorageStoreType(_builtins.str, Enum):
    
    AZURE_STORAGE_BLOB = ...
    AZURE_NET_APP_FILES = ...


@pulumi.type_token("azure-native:discovery:SystemSku")
class SystemSku(_builtins.str, Enum):
    
    STANDARD_D4S_V6 = ...
    STANDARD_D4S_V5 = ...
    STANDARD_D4S_V4 = ...


@pulumi.type_token("azure-native:discovery:VmSize")
class VmSize(_builtins.str, Enum):
    
    STANDARD_NC24ADS_A100_V4 = ...
    STANDARD_NC48ADS_A100_V4 = ...
    STANDARD_NC96ADS_A100_V4 = ...
    STANDARD_NC4AS_T4_V3 = ...
    STANDARD_NC8AS_T4_V3 = ...
    STANDARD_NC16AS_T4_V3 = ...
    STANDARD_NC64AS_T4_V3 = ...
    STANDARD_NV6ADS_A10_V5 = ...
    STANDARD_NV12ADS_A10_V5 = ...
    STANDARD_NV24ADS_A10_V5 = ...
    STANDARD_NV36ADS_A10_V5 = ...
    STANDARD_NV36ADMS_A10_V5 = ...
    STANDARD_NV72ADS_A10_V5 = ...
    STANDARD_ND40RS_V2 = ...


