

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AgentDeploymentState', 'AgentDeploymentType', 'AgentProtocol', 'BuiltInAuthorizationScheme', 'ByPassSelection', 'CapabilityHostKind', 'ConnectionAuthType', 'ConnectionCategory', 'ContentLevel', 'DeploymentModelVersionUpgradeOption', 'DeploymentScaleType', 'EncryptionScopeState', 'HostingModel', 'IdentityKind', 'IdentityManagementType', 'KeySource', 'ManagedPERequirement', 'ManagedPEStatus', 'NetworkRuleAction', 'PrivateEndpointServiceConnectionStatus', 'PublicNetworkAccess', 'RaiActionType', 'RaiPolicyContentSource', 'RaiPolicyMode', 'ResourceIdentityType', 'RoutingMethods', 'RuleCategory', 'RuleStatus', 'RuleType', 'ScenarioType', 'SkuTier', 'TrafficRoutingProtocol']
@pulumi.type_token(...)
class AgentDeploymentState(_builtins.str, Enum):
    
    STARTING = ...
    RUNNING = ...
    STOPPING = ...
    STOPPED = ...
    FAILED = ...
    DELETING = ...
    DELETED = ...
    UPDATING = ...


@pulumi.type_token("azure-native:cognitiveservices:AgentDeploymentType")
class AgentDeploymentType(_builtins.str, Enum):
    
    MANAGED = ...
    HOSTED = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:cognitiveservices:AgentProtocol")
class AgentProtocol(_builtins.str, Enum):
    
    AGENT = ...
    A2_A = ...
    RESPONSES = ...


@pulumi.type_token(...)
class BuiltInAuthorizationScheme(_builtins.str, Enum):
    
    DEFAULT = ...
    ORGANIZATION_SCOPE = ...
    CHANNELS = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:cognitiveservices:ByPassSelection")
class ByPassSelection(_builtins.str, Enum):
    
    NONE = ...
    AZURE_SERVICES = ...


@pulumi.type_token("azure-native:cognitiveservices:CapabilityHostKind")
class CapabilityHostKind(_builtins.str, Enum):
    
    AGENTS = ...


@pulumi.type_token("azure-native:cognitiveservices:ConnectionAuthType")
class ConnectionAuthType(_builtins.str, Enum):
    
    PAT = ...
    MANAGED_IDENTITY = ...
    USERNAME_PASSWORD = ...
    NONE = ...
    SAS = ...
    ACCOUNT_KEY = ...
    SERVICE_PRINCIPAL = ...
    ACCESS_KEY = ...
    API_KEY = ...
    CUSTOM_KEYS = ...
    O_AUTH2 = ...
    AAD = ...


@pulumi.type_token("azure-native:cognitiveservices:ConnectionCategory")
class ConnectionCategory(_builtins.str, Enum):
    
    PYTHON_FEED = ...
    CONTAINER_REGISTRY = ...
    GIT = ...
    S3 = ...
    SNOWFLAKE = ...
    AZURE_SQL_DB = ...
    AZURE_SYNAPSE_ANALYTICS = ...
    AZURE_MY_SQL_DB = ...
    AZURE_POSTGRES_DB = ...
    ADLS_GEN2 = ...
    REDIS = ...
    API_KEY = ...
    AZURE_OPEN_AI = ...
    AI_SERVICES = ...
    COGNITIVE_SEARCH = ...
    COGNITIVE_SERVICE = ...
    CUSTOM_KEYS = ...
    AZURE_BLOB = ...
    AZURE_ONE_LAKE = ...
    COSMOS_DB = ...
    COSMOS_DB_MONGO_DB_API = ...
    AZURE_DATA_EXPLORER = ...
    AZURE_MARIA_DB = ...
    AZURE_DATABRICKS_DELTA_LAKE = ...
    AZURE_SQL_MI = ...
    AZURE_TABLE_STORAGE = ...
    AMAZON_RDS_FOR_ORACLE = ...
    AMAZON_RDS_FOR_SQL_SERVER = ...
    AMAZON_REDSHIFT = ...
    DB2 = ...
    DRILL = ...
    GOOGLE_BIG_QUERY = ...
    GREENPLUM = ...
    HBASE = ...
    HIVE = ...
    IMPALA = ...
    INFORMIX = ...
    MARIA_DB = ...
    MICROSOFT_ACCESS = ...
    MY_SQL = ...
    NETEZZA = ...
    ORACLE = ...
    PHOENIX = ...
    POSTGRE_SQL = ...
    PRESTO = ...
    SAP_OPEN_HUB = ...
    SAP_BW = ...
    SAP_HANA = ...
    SAP_TABLE = ...
    SPARK = ...
    SQL_SERVER = ...
    SYBASE = ...
    TERADATA = ...
    VERTICA = ...
    PINECONE = ...
    CASSANDRA = ...
    COUCHBASE = ...
    MONGO_DB_V2 = ...
    MONGO_DB_ATLAS = ...
    AMAZON_S3_COMPATIBLE = ...
    FILE_SERVER = ...
    FTP_SERVER = ...
    GOOGLE_CLOUD_STORAGE = ...
    HDFS = ...
    ORACLE_CLOUD_STORAGE = ...
    SFTP = ...
    GENERIC_HTTP = ...
    O_DATA_REST = ...
    ODBC = ...
    GENERIC_REST = ...
    AMAZON_MWS = ...
    CONCUR = ...
    DYNAMICS = ...
    DYNAMICS_AX = ...
    DYNAMICS_CRM = ...
    GOOGLE_AD_WORDS = ...
    HUBSPOT = ...
    JIRA = ...
    MAGENTO = ...
    MARKETO = ...
    OFFICE365 = ...
    ELOQUA = ...
    RESPONSYS = ...
    ORACLE_SERVICE_CLOUD = ...
    PAY_PAL = ...
    QUICK_BOOKS = ...
    SALESFORCE = ...
    SALESFORCE_SERVICE_CLOUD = ...
    SALESFORCE_MARKETING_CLOUD = ...
    SAP_CLOUD_FOR_CUSTOMER = ...
    SAP_ECC = ...
    SERVICE_NOW = ...
    SHARE_POINT_ONLINE_LIST = ...
    SHOPIFY = ...
    SQUARE = ...
    WEB_TABLE = ...
    XERO = ...
    ZOHO = ...
    GENERIC_CONTAINER_REGISTRY = ...
    ELASTICSEARCH = ...
    OPEN_AI = ...
    SERP = ...
    BING_LLM_SEARCH = ...
    SERVERLESS = ...
    MANAGED_ONLINE_ENDPOINT = ...


@pulumi.type_token("azure-native:cognitiveservices:ContentLevel")
class ContentLevel(_builtins.str, Enum):
    
    LOW = ...
    MEDIUM = ...
    HIGH = ...


@pulumi.type_token(...)
class DeploymentModelVersionUpgradeOption(_builtins.str, Enum):
    
    ONCE_NEW_DEFAULT_VERSION_AVAILABLE = ...
    ONCE_CURRENT_VERSION_EXPIRED = ...
    NO_AUTO_UPGRADE = ...


@pulumi.type_token("azure-native:cognitiveservices:DeploymentScaleType")
class DeploymentScaleType(_builtins.str, Enum):
    
    STANDARD = ...
    MANUAL = ...


@pulumi.type_token(...)
class EncryptionScopeState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:cognitiveservices:HostingModel")
class HostingModel(_builtins.str, Enum):
    
    WEB = ...
    CONNECTED_CONTAINER = ...
    DISCONNECTED_CONTAINER = ...
    PROVISIONED_WEB = ...


@pulumi.type_token("azure-native:cognitiveservices:IdentityKind")
class IdentityKind(_builtins.str, Enum):
    
    AGENT_BLUEPRINT = ...
    AGENT_INSTANCE = ...
    AGENTIC_USER = ...
    MANAGED = ...
    NONE = ...


@pulumi.type_token(...)
class IdentityManagementType(_builtins.str, Enum):
    
    SYSTEM = ...
    USER = ...
    NONE = ...


@pulumi.type_token("azure-native:cognitiveservices:KeySource")
class KeySource(_builtins.str, Enum):
    
    MICROSOFT_COGNITIVE_SERVICES = ...
    MICROSOFT_KEY_VAULT = ...


@pulumi.type_token(...)
class ManagedPERequirement(_builtins.str, Enum):
    
    REQUIRED = ...
    NOT_REQUIRED = ...
    NOT_APPLICABLE = ...


@pulumi.type_token("azure-native:cognitiveservices:ManagedPEStatus")
class ManagedPEStatus(_builtins.str, Enum):
    
    INACTIVE = ...
    ACTIVE = ...
    NOT_APPLICABLE = ...


@pulumi.type_token("azure-native:cognitiveservices:NetworkRuleAction")
class NetworkRuleAction(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:cognitiveservices:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:cognitiveservices:RaiActionType")
class RaiActionType(_builtins.str, Enum):
    
    NONE = ...
    BLOCKING = ...
    ANNOTATING = ...
    HITL = ...
    RETRY = ...


@pulumi.type_token(...)
class RaiPolicyContentSource(_builtins.str, Enum):
    
    PROMPT = ...
    COMPLETION = ...
    PRE_TOOL_CALL = ...
    POST_TOOL_CALL = ...
    PRE_RUN = ...
    POST_RUN = ...


@pulumi.type_token("azure-native:cognitiveservices:RaiPolicyMode")
class RaiPolicyMode(_builtins.str, Enum):
    
    DEFAULT = ...
    DEFERRED = ...
    BLOCKING = ...
    ASYNCHRONOUS_FILTER = ...


@pulumi.type_token(...)
class ResourceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:cognitiveservices:RoutingMethods")
class RoutingMethods(_builtins.str, Enum):
    
    PRIORITY = ...
    WEIGHTED = ...
    PERFORMANCE = ...


@pulumi.type_token("azure-native:cognitiveservices:RuleCategory")
class RuleCategory(_builtins.str, Enum):
    
    REQUIRED = ...
    RECOMMENDED = ...
    USER_DEFINED = ...
    DEPENDENCY = ...


@pulumi.type_token("azure-native:cognitiveservices:RuleStatus")
class RuleStatus(_builtins.str, Enum):
    
    INACTIVE = ...
    ACTIVE = ...
    PROVISIONING = ...
    DELETING = ...
    FAILED = ...


@pulumi.type_token("azure-native:cognitiveservices:RuleType")
class RuleType(_builtins.str, Enum):
    
    FQDN = ...
    PRIVATE_ENDPOINT = ...
    SERVICE_TAG = ...


@pulumi.type_token("azure-native:cognitiveservices:ScenarioType")
class ScenarioType(_builtins.str, Enum):
    
    NONE = ...
    AGENT = ...


@pulumi.type_token("azure-native:cognitiveservices:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...
    ENTERPRISE = ...


@pulumi.type_token(...)
class TrafficRoutingProtocol(_builtins.str, Enum):
    
    FIXED_RATIO = ...


