

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ApplyDiscountOn', 'CommitmentGrain', 'ConditionalCreditEntityType', 'ConditionalCreditStatus', 'CreditExpirationPolicy', 'CreditRedemptionPolicy', 'CreditStatus', 'DiscountAppliedScopeType', 'DiscountCombinationRule', 'DiscountEntityType', 'DiscountRuleType', 'DiscountType', 'EnablementMode', 'FreeServicesStatus', 'MaccEntityType', 'MaccMilestoneStatus', 'MaccStatus', 'ManagedServiceIdentityType', 'PricingPolicy', 'SkuTier']
@pulumi.type_token("azure-native:billingbenefits:ApplyDiscountOn")
class ApplyDiscountOn(_builtins.str, Enum):
    
    PURCHASE = ...
    CONSUME = ...
    RENEW = ...


@pulumi.type_token("azure-native:billingbenefits:CommitmentGrain")
class CommitmentGrain(_builtins.str, Enum):
    
    UNKNOWN = ...
    HOURLY = ...
    FULL_TERM = ...


@pulumi.type_token(...)
class ConditionalCreditEntityType(_builtins.str, Enum):
    
    PRIMARY = ...
    CONTRIBUTOR = ...


@pulumi.type_token(...)
class ConditionalCreditStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    SCHEDULED = ...
    ACTIVE = ...
    PENDING = ...
    FAILED = ...
    CANCELED = ...
    COMPLETED = ...
    STOPPED = ...
    PENDING_SETTLEMENT = ...


@pulumi.type_token(...)
class CreditExpirationPolicy(_builtins.str, Enum):
    
    NONE = ...
    SUSPEND_BILLING_PROFILE = ...


@pulumi.type_token(...)
class CreditRedemptionPolicy(_builtins.str, Enum):
    
    NOT_APPLICABLE = ...
    AUTO_REDEEM = ...
    MANUAL_REDEEM = ...


@pulumi.type_token("azure-native:billingbenefits:CreditStatus")
class CreditStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    PENDING = ...
    ACTIVE = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...
    EXPIRED = ...
    EXHAUSTED = ...
    NOT_STARTED = ...


@pulumi.type_token(...)
class DiscountAppliedScopeType(_builtins.str, Enum):
    
    BILLING_ACCOUNT = ...
    BILLING_PROFILE = ...
    CUSTOMER = ...


@pulumi.type_token(...)
class DiscountCombinationRule(_builtins.str, Enum):
    
    BEST_OF = ...
    STACKABLE = ...


@pulumi.type_token("azure-native:billingbenefits:DiscountEntityType")
class DiscountEntityType(_builtins.str, Enum):
    
    PRIMARY = ...
    AFFILIATE = ...


@pulumi.type_token("azure-native:billingbenefits:DiscountRuleType")
class DiscountRuleType(_builtins.str, Enum):
    
    FIXED_PRICE_LOCK = ...
    FIXED_LIST_PRICE = ...
    PRICE_CEILING = ...


@pulumi.type_token("azure-native:billingbenefits:DiscountType")
class DiscountType(_builtins.str, Enum):
    
    PRODUCT_FAMILY = ...
    PRODUCT = ...
    SKU = ...
    CUSTOM_PRICE = ...
    CUSTOM_PRICE_MULTI_CURRENCY = ...


@pulumi.type_token("azure-native:billingbenefits:EnablementMode")
class EnablementMode(_builtins.str, Enum):
    
    UNKNOWN = ...
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:billingbenefits:FreeServicesStatus")
class FreeServicesStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    PENDING = ...
    ACTIVE = ...
    CANCELED = ...
    COMPLETED = ...


@pulumi.type_token("azure-native:billingbenefits:MaccEntityType")
class MaccEntityType(_builtins.str, Enum):
    
    PRIMARY = ...
    CONTRIBUTOR = ...


@pulumi.type_token("azure-native:billingbenefits:MaccMilestoneStatus")
class MaccMilestoneStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    SCHEDULED = ...
    ACTIVE = ...
    PENDING = ...
    FAILED = ...
    COMPLETED = ...
    CANCELED = ...
    REMOVED = ...
    PENDING_SETTLEMENT = ...
    SHORTFALL_CHARGED = ...
    SHORTFALL_WAIVED = ...


@pulumi.type_token("azure-native:billingbenefits:MaccStatus")
class MaccStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    SCHEDULED = ...
    ACTIVE = ...
    PENDING = ...
    FAILED = ...
    CANCELED = ...
    COMPLETED = ...
    STOPPED = ...
    PENDING_SETTLEMENT = ...
    SHORTFALL_CHARGED = ...
    SHORTFALL_WAIVED = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:billingbenefits:PricingPolicy")
class PricingPolicy(_builtins.str, Enum):
    
    PROTECTED = ...
    LOCKED = ...


@pulumi.type_token("azure-native:billingbenefits:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


