

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessRightsDescription', 'AllocationPolicy', 'IotDpsSku', 'IpFilterActionType', 'IpFilterTargetType', 'ManagedServiceIdentityType', 'PrivateLinkServiceConnectionStatus', 'PublicNetworkAccess', 'State']
@pulumi.type_token(...)
class AccessRightsDescription(_builtins.str, Enum):
    
    SERVICE_CONFIG = ...
    ENROLLMENT_READ = ...
    ENROLLMENT_WRITE = ...
    DEVICE_CONNECT = ...
    REGISTRATION_STATUS_READ = ...
    REGISTRATION_STATUS_WRITE = ...


@pulumi.type_token(...)
class AllocationPolicy(_builtins.str, Enum):
    
    HASHED = ...
    GEO_LATENCY = ...
    STATIC = ...


@pulumi.type_token("azure-native:deviceprovisioningservices:IotDpsSku")
class IotDpsSku(_builtins.str, Enum):
    
    S1 = ...


@pulumi.type_token(...)
class IpFilterActionType(_builtins.str, Enum):
    
    ACCEPT = ...
    REJECT = ...


@pulumi.type_token(...)
class IpFilterTargetType(_builtins.str, Enum):
    
    ALL = ...
    SERVICE_API = ...
    DEVICE_API = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token(...)
class PrivateLinkServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token(...)
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:deviceprovisioningservices:State")
class State(_builtins.str, Enum):
    
    ACTIVATING = ...
    ACTIVE = ...
    DELETING = ...
    DELETED = ...
    ACTIVATION_FAILED = ...
    DELETION_FAILED = ...
    TRANSITIONING = ...
    SUSPENDING = ...
    SUSPENDED = ...
    RESUMING = ...
    FAILING_OVER = ...
    FAILOVER_FAILED = ...


