

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['MaintenanceScope', 'RebootOptions', 'TagOperators', 'Visibility']
@pulumi.type_token("azure-native:maintenance:MaintenanceScope")
class MaintenanceScope(_builtins.str, Enum):
    
    HOST = ...
    RESOURCE = ...
    OS_IMAGE = ...
    EXTENSION = ...
    IN_GUEST_PATCH = ...
    SQLDB = ...
    SQL_MANAGED_INSTANCE = ...


@pulumi.type_token("azure-native:maintenance:RebootOptions")
class RebootOptions(_builtins.str, Enum):
    
    IF_REQUIRED = ...
    NEVER = ...
    ALWAYS = ...


@pulumi.type_token("azure-native:maintenance:TagOperators")
class TagOperators(_builtins.str, Enum):
    
    ALL = ...
    ANY = ...


@pulumi.type_token("azure-native:maintenance:Visibility")
class Visibility(_builtins.str, Enum):
    
    CUSTOM = ...
    PUBLIC = ...


