import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetLinkedStorageAccountResult",
    "AwaitableGetLinkedStorageAccountResult",
    "get_linked_storage_account",
    "get_linked_storage_account_output",
]

@pulumi.output_type
class GetLinkedStorageAccountResult:
    def __init__(
        __self__,
        azure_api_version=...,
        data_source_type=...,
        id=...,
        name=...,
        storage_account_ids=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="dataSourceType")
    def data_source_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="storageAccountIds")
    def storage_account_ids(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetLinkedStorageAccountResult(GetLinkedStorageAccountResult):
    def __await__(self): ...

def get_linked_storage_account(
    data_source_type: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    workspace_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetLinkedStorageAccountResult: ...
def get_linked_storage_account_output(
    data_source_type: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    workspace_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetLinkedStorageAccountResult]: ...
