import builtins as _builtins
import sys
import pulumi
from typing import Any, Optional, Union, overload
from . import outputs
from ._enums import *
from ._inputs import *

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = ["SignalDefinitionArgs", "SignalDefinition"]

@pulumi.input_type
class SignalDefinitionArgs:
    def __init__(
        __self__,
        *,
        azure_monitor_workspace_name: pulumi.Input[_builtins.str],
        health_model_name: pulumi.Input[_builtins.str],
        resource_group_name: pulumi.Input[_builtins.str],
        properties: Optional[
            pulumi.Input[
                Union[
                    LogAnalyticsQuerySignalDefinitionPropertiesArgs,
                    PrometheusMetricsSignalDefinitionPropertiesArgs,
                    ResourceMetricSignalDefinitionPropertiesArgs,
                ]
            ]
        ] = ...,
        signal_definition_name: Optional[pulumi.Input[_builtins.str]] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureMonitorWorkspaceName")
    def azure_monitor_workspace_name(self) -> pulumi.Input[_builtins.str]: ...
    @azure_monitor_workspace_name.setter
    def azure_monitor_workspace_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter(name="healthModelName")
    def health_model_name(self) -> pulumi.Input[_builtins.str]: ...
    @health_model_name.setter
    def health_model_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter(name="resourceGroupName")
    def resource_group_name(self) -> pulumi.Input[_builtins.str]: ...
    @resource_group_name.setter
    def resource_group_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter
    def properties(
        self,
    ) -> Optional[
        pulumi.Input[
            Union[
                LogAnalyticsQuerySignalDefinitionPropertiesArgs,
                PrometheusMetricsSignalDefinitionPropertiesArgs,
                ResourceMetricSignalDefinitionPropertiesArgs,
            ]
        ]
    ]: ...
    @properties.setter
    def properties(
        self,
        value: Optional[
            pulumi.Input[
                Union[
                    LogAnalyticsQuerySignalDefinitionPropertiesArgs,
                    PrometheusMetricsSignalDefinitionPropertiesArgs,
                    ResourceMetricSignalDefinitionPropertiesArgs,
                ]
            ]
        ],
    ): ...
    @_builtins.property
    @pulumi.getter(name="signalDefinitionName")
    def signal_definition_name(self) -> Optional[pulumi.Input[_builtins.str]]: ...
    @signal_definition_name.setter
    def signal_definition_name(self, value: Optional[pulumi.Input[_builtins.str]]): ...

@pulumi.type_token("azure-native:monitor:SignalDefinition")
class SignalDefinition(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: Optional[pulumi.ResourceOptions] = ...,
        azure_monitor_workspace_name: Optional[pulumi.Input[_builtins.str]] = ...,
        health_model_name: Optional[pulumi.Input[_builtins.str]] = ...,
        properties: Optional[
            pulumi.Input[
                Union[
                    Union[
                        LogAnalyticsQuerySignalDefinitionPropertiesArgs,
                        LogAnalyticsQuerySignalDefinitionPropertiesArgsDict,
                    ],
                    Union[
                        PrometheusMetricsSignalDefinitionPropertiesArgs,
                        PrometheusMetricsSignalDefinitionPropertiesArgsDict,
                    ],
                    Union[
                        ResourceMetricSignalDefinitionPropertiesArgs,
                        ResourceMetricSignalDefinitionPropertiesArgsDict,
                    ],
                ]
            ]
        ] = ...,
        resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
        signal_definition_name: Optional[pulumi.Input[_builtins.str]] = ...,
        __props__=...,
    ) -> None: ...
    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: SignalDefinitionArgs,
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> None: ...
    def __init__(__self__, resource_name: str, *args, **kwargs) -> None: ...
    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> SignalDefinition: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> pulumi.Output[Any]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> pulumi.Output[outputs.SystemDataResponse]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]: ...
