import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ManagedIdentityTypes",
    "MonitoringStatus",
    "Operation",
    "ProvisioningState",
    "Status",
    "TagAction",
]

@pulumi.type_token("azure-native:elastic:ManagedIdentityTypes")
class ManagedIdentityTypes(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:elastic:MonitoringStatus")
class MonitoringStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:elastic:Operation")
class Operation(_builtins.str, Enum):
    ADD_BEGIN = ...
    ADD_COMPLETE = ...
    DELETE_BEGIN = ...
    DELETE_COMPLETE = ...
    ACTIVE = ...

@pulumi.type_token("azure-native:elastic:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    ACCEPTED = ...
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    DELETED = ...
    NOT_SPECIFIED = ...

@pulumi.type_token("azure-native:elastic:Status")
class Status(_builtins.str, Enum):
    IN_PROGRESS = ...
    ACTIVE = ...
    FAILED = ...
    DELETING = ...

@pulumi.type_token("azure-native:elastic:TagAction")
class TagAction(_builtins.str, Enum):
    INCLUDE = ...
    EXCLUDE = ...
