import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AuthenticationType",
    "ConnectionType",
    "DigitalTwinsIdentityType",
    "EndpointType",
    "IdentityType",
    "PrivateLinkServiceConnectionStatus",
    "PublicNetworkAccess",
    "RecordPropertyAndItemRemovals",
]

@pulumi.type_token("azure-native:digitaltwins:AuthenticationType")
class AuthenticationType(_builtins.str, Enum):
    KEY_BASED = ...
    IDENTITY_BASED = ...

@pulumi.type_token("azure-native:digitaltwins:ConnectionType")
class ConnectionType(_builtins.str, Enum):
    AZURE_DATA_EXPLORER = ...

@pulumi.type_token("azure-native:digitaltwins:DigitalTwinsIdentityType")
class DigitalTwinsIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:digitaltwins:EndpointType")
class EndpointType(_builtins.str, Enum):
    EVENT_HUB = ...
    EVENT_GRID = ...
    SERVICE_BUS = ...

@pulumi.type_token("azure-native:digitaltwins:IdentityType")
class IdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token(...)
class PrivateLinkServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:digitaltwins:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class RecordPropertyAndItemRemovals(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...
