import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "EnterprisePolicyKind",
    "HealthStatus",
    "PrivateEndpointServiceConnectionStatus",
    "ResourceIdentityType",
    "State",
]

@pulumi.type_token("azure-native:powerplatform:EnterprisePolicyKind")
class EnterprisePolicyKind(_builtins.str, Enum):
    LOCKBOX = ...
    PRIVATE_ENDPOINT = ...
    ENCRYPTION = ...
    NETWORK_INJECTION = ...
    IDENTITY = ...

@pulumi.type_token("azure-native:powerplatform:HealthStatus")
class HealthStatus(_builtins.str, Enum):
    UNDETERMINED = ...
    HEALTHY = ...
    WARNING = ...
    UNHEALTHY = ...

@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...

@pulumi.type_token("azure-native:powerplatform:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    NONE = ...

@pulumi.type_token("azure-native:powerplatform:State")
class State(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    NOT_CONFIGURED = ...
