

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ArcKindEnum', 'AssessmentModeTypes', 'GatewayType', 'LicenseAssignmentState', 'LicenseCoreType', 'LicenseEdition', 'LicenseProfileProductType', 'LicenseProfileSubscriptionStatus', 'LicenseState', 'LicenseTarget', 'LicenseType', 'PatchModeTypes', 'ProgramYear', 'PublicNetworkAccessType', 'ResourceIdentityType', 'StatusLevelTypes']
@pulumi.type_token("azure-native:hybridcompute:ArcKindEnum")
class ArcKindEnum(_builtins.str, Enum):
    
    AVS = ...
    HCI = ...
    SCVMM = ...
    V_MWARE = ...
    EPS = ...
    GCP = ...
    AWS = ...


@pulumi.type_token("azure-native:hybridcompute:AssessmentModeTypes")
class AssessmentModeTypes(_builtins.str, Enum):
    
    IMAGE_DEFAULT = ...
    AUTOMATIC_BY_PLATFORM = ...


@pulumi.type_token("azure-native:hybridcompute:GatewayType")
class GatewayType(_builtins.str, Enum):
    
    PUBLIC = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseAssignmentState")
class LicenseAssignmentState(_builtins.str, Enum):
    
    ASSIGNED = ...
    NOT_ASSIGNED = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseCoreType")
class LicenseCoreType(_builtins.str, Enum):
    
    P_CORE = ...
    V_CORE = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseEdition")
class LicenseEdition(_builtins.str, Enum):
    
    STANDARD = ...
    DATACENTER = ...


@pulumi.type_token(...)
class LicenseProfileProductType(_builtins.str, Enum):
    
    WINDOWS_SERVER = ...
    WINDOWS_IO_T_ENTERPRISE = ...


@pulumi.type_token(...)
class LicenseProfileSubscriptionStatus(_builtins.str, Enum):
    
    UNKNOWN = ...
    ENABLING = ...
    ENABLED = ...
    DISABLED = ...
    DISABLING = ...
    FAILED = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseState")
class LicenseState(_builtins.str, Enum):
    
    ACTIVATED = ...
    DEACTIVATED = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseTarget")
class LicenseTarget(_builtins.str, Enum):
    
    WINDOWS_SERVER_2012 = ...
    WINDOWS_SERVER_2012_R2 = ...


@pulumi.type_token("azure-native:hybridcompute:LicenseType")
class LicenseType(_builtins.str, Enum):
    
    ESU = ...


@pulumi.type_token("azure-native:hybridcompute:PatchModeTypes")
class PatchModeTypes(_builtins.str, Enum):
    
    IMAGE_DEFAULT = ...
    AUTOMATIC_BY_PLATFORM = ...
    AUTOMATIC_BY_OS = ...
    MANUAL = ...


@pulumi.type_token("azure-native:hybridcompute:ProgramYear")
class ProgramYear(_builtins.str, Enum):
    
    YEAR_1 = ...
    YEAR_2 = ...
    YEAR_3 = ...


@pulumi.type_token("azure-native:hybridcompute:PublicNetworkAccessType")
class PublicNetworkAccessType(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...


@pulumi.type_token("azure-native:hybridcompute:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...


@pulumi.type_token("azure-native:hybridcompute:StatusLevelTypes")
class StatusLevelTypes(_builtins.str, Enum):
    
    INFO = ...
    WARNING = ...
    ERROR = ...


