import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "DayOfWeek",
    "HttpAuthenticationType",
    "JobActionType",
    "JobCollectionState",
    "JobScheduleDay",
    "JobState",
    "RecurrenceFrequency",
    "RetryType",
    "ServiceBusAuthenticationType",
    "ServiceBusTransportType",
    "SkuDefinition",
]

@pulumi.type_token("azure-native:scheduler:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:scheduler:HttpAuthenticationType")
class HttpAuthenticationType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CLIENT_CERTIFICATE = ...
    ACTIVE_DIRECTORY_O_AUTH = ...
    BASIC = ...

@pulumi.type_token("azure-native:scheduler:JobActionType")
class JobActionType(_builtins.str, Enum):
    HTTP = ...
    HTTPS = ...
    STORAGE_QUEUE = ...
    SERVICE_BUS_QUEUE = ...
    SERVICE_BUS_TOPIC = ...

@pulumi.type_token("azure-native:scheduler:JobCollectionState")
class JobCollectionState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    SUSPENDED = ...
    DELETED = ...

@pulumi.type_token("azure-native:scheduler:JobScheduleDay")
class JobScheduleDay(_builtins.str, Enum):
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...

@pulumi.type_token("azure-native:scheduler:JobState")
class JobState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    FAULTED = ...
    COMPLETED = ...

@pulumi.type_token("azure-native:scheduler:RecurrenceFrequency")
class RecurrenceFrequency(_builtins.str, Enum):
    MINUTE = ...
    HOUR = ...
    DAY = ...
    WEEK = ...
    MONTH = ...

@pulumi.type_token("azure-native:scheduler:RetryType")
class RetryType(_builtins.str, Enum):
    NONE = ...
    FIXED = ...

@pulumi.type_token(...)
class ServiceBusAuthenticationType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SHARED_ACCESS_KEY = ...

@pulumi.type_token("azure-native:scheduler:ServiceBusTransportType")
class ServiceBusTransportType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NET_MESSAGING = ...
    AMQP = ...

@pulumi.type_token("azure-native:scheduler:SkuDefinition")
class SkuDefinition(_builtins.str, Enum):
    STANDARD = ...
    FREE = ...
    P10_PREMIUM = ...
    P20_PREMIUM = ...
