import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union
from . import outputs
from ._enums import *

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetLogAnalyticExportRequestRateByIntervalResult",
    ...,
    "get_log_analytic_export_request_rate_by_interval",
    ...,
]

@pulumi.output_type
class GetLogAnalyticExportRequestRateByIntervalResult:
    def __init__(__self__, properties=...) -> None: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> outputs.LogAnalyticsOutputResponse: ...

class AwaitableGetLogAnalyticExportRequestRateByIntervalResult(
    GetLogAnalyticExportRequestRateByIntervalResult
):
    def __await__(self): ...

def get_log_analytic_export_request_rate_by_interval(
    blob_container_sas_uri: Optional[_builtins.str] = ...,
    from_time: Optional[_builtins.str] = ...,
    group_by_client_application_id: Optional[_builtins.bool] = ...,
    group_by_operation_name: Optional[_builtins.bool] = ...,
    group_by_resource_name: Optional[_builtins.bool] = ...,
    group_by_throttle_policy: Optional[_builtins.bool] = ...,
    group_by_user_agent: Optional[_builtins.bool] = ...,
    interval_length: Optional[IntervalInMins] = ...,
    location: Optional[_builtins.str] = ...,
    to_time: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetLogAnalyticExportRequestRateByIntervalResult: ...
def get_log_analytic_export_request_rate_by_interval_output(
    blob_container_sas_uri: Optional[pulumi.Input[_builtins.str]] = ...,
    from_time: Optional[pulumi.Input[_builtins.str]] = ...,
    group_by_client_application_id: Optional[
        pulumi.Input[Optional[_builtins.bool]]
    ] = ...,
    group_by_operation_name: Optional[pulumi.Input[Optional[_builtins.bool]]] = ...,
    group_by_resource_name: Optional[pulumi.Input[Optional[_builtins.bool]]] = ...,
    group_by_throttle_policy: Optional[pulumi.Input[Optional[_builtins.bool]]] = ...,
    group_by_user_agent: Optional[pulumi.Input[Optional[_builtins.bool]]] = ...,
    interval_length: Optional[pulumi.Input[IntervalInMins]] = ...,
    location: Optional[pulumi.Input[_builtins.str]] = ...,
    to_time: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetLogAnalyticExportRequestRateByIntervalResult]: ...
