import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = ["GetDiskResult", "AwaitableGetDiskResult", "get_disk", "get_disk_output"]

@pulumi.output_type
class GetDiskResult:
    def __init__(
        __self__,
        azure_api_version=...,
        bursting_enabled=...,
        bursting_enabled_time=...,
        completion_percent=...,
        creation_data=...,
        data_access_auth_mode=...,
        disk_access_id=...,
        disk_iops_read_only=...,
        disk_iops_read_write=...,
        disk_m_bps_read_only=...,
        disk_m_bps_read_write=...,
        disk_size_bytes=...,
        disk_size_gb=...,
        disk_state=...,
        encryption=...,
        encryption_settings_collection=...,
        extended_location=...,
        hyper_v_generation=...,
        id=...,
        last_ownership_update_time=...,
        location=...,
        managed_by=...,
        managed_by_extended=...,
        max_shares=...,
        name=...,
        network_access_policy=...,
        optimized_for_frequent_attach=...,
        os_type=...,
        property_updates_in_progress=...,
        provisioning_state=...,
        public_network_access=...,
        purchase_plan=...,
        security_profile=...,
        share_info=...,
        sku=...,
        supported_capabilities=...,
        supports_hibernation=...,
        system_data=...,
        tags=...,
        tier=...,
        time_created=...,
        type=...,
        unique_id=...,
        zones=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="burstingEnabled")
    def bursting_enabled(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="burstingEnabledTime")
    def bursting_enabled_time(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="completionPercent")
    def completion_percent(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="creationData")
    def creation_data(self) -> outputs.CreationDataResponse: ...
    @_builtins.property
    @pulumi.getter(name="dataAccessAuthMode")
    def data_access_auth_mode(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="diskAccessId")
    def disk_access_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="diskIOPSReadOnly")
    def disk_iops_read_only(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="diskIOPSReadWrite")
    def disk_iops_read_write(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="diskMBpsReadOnly")
    def disk_m_bps_read_only(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="diskMBpsReadWrite")
    def disk_m_bps_read_write(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="diskSizeBytes")
    def disk_size_bytes(self) -> _builtins.float: ...
    @_builtins.property
    @pulumi.getter(name="diskSizeGB")
    def disk_size_gb(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter(name="diskState")
    def disk_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def encryption(self) -> Optional[outputs.EncryptionResponse]: ...
    @_builtins.property
    @pulumi.getter(name="encryptionSettingsCollection")
    def encryption_settings_collection(
        self,
    ) -> Optional[outputs.EncryptionSettingsCollectionResponse]: ...
    @_builtins.property
    @pulumi.getter(name="extendedLocation")
    def extended_location(self) -> Optional[outputs.ExtendedLocationResponse]: ...
    @_builtins.property
    @pulumi.getter(name="hyperVGeneration")
    def hyper_v_generation(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="lastOwnershipUpdateTime")
    def last_ownership_update_time(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="managedBy")
    def managed_by(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="managedByExtended")
    def managed_by_extended(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="maxShares")
    def max_shares(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="networkAccessPolicy")
    def network_access_policy(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="optimizedForFrequentAttach")
    def optimized_for_frequent_attach(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="osType")
    def os_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="propertyUpdatesInProgress")
    def property_updates_in_progress(
        self,
    ) -> outputs.PropertyUpdatesInProgressResponse: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="publicNetworkAccess")
    def public_network_access(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="purchasePlan")
    def purchase_plan(self) -> Optional[outputs.DiskPurchasePlanResponse]: ...
    @_builtins.property
    @pulumi.getter(name="securityProfile")
    def security_profile(self) -> Optional[outputs.DiskSecurityProfileResponse]: ...
    @_builtins.property
    @pulumi.getter(name="shareInfo")
    def share_info(self) -> Sequence[outputs.ShareInfoElementResponse]: ...
    @_builtins.property
    @pulumi.getter
    def sku(self) -> Optional[outputs.DiskSkuResponse]: ...
    @_builtins.property
    @pulumi.getter(name="supportedCapabilities")
    def supported_capabilities(
        self,
    ) -> Optional[outputs.SupportedCapabilitiesResponse]: ...
    @_builtins.property
    @pulumi.getter(name="supportsHibernation")
    def supports_hibernation(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def tier(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="timeCreated")
    def time_created(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="uniqueId")
    def unique_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def zones(self) -> Optional[Sequence[_builtins.str]]: ...

class AwaitableGetDiskResult(GetDiskResult):
    def __await__(self): ...

def get_disk(
    disk_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetDiskResult: ...
def get_disk_output(
    disk_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetDiskResult]: ...
