

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessRights', 'NamespaceStatus', 'NamespaceType', 'OperationProvisioningState', 'PrivateEndpointConnectionProvisioningState', 'PrivateLinkConnectionStatus', 'PublicNetworkAccess', 'ReplicationRegion', 'SkuName', 'ZoneRedundancyPreference']
@pulumi.type_token("azure-native:notificationhubs:AccessRights")
class AccessRights(_builtins.str, Enum):
    
    MANAGE = ...
    SEND = ...
    LISTEN = ...


@pulumi.type_token("azure-native:notificationhubs:NamespaceStatus")
class NamespaceStatus(_builtins.str, Enum):
    
    CREATED = ...
    CREATING = ...
    SUSPENDED = ...
    DELETING = ...


@pulumi.type_token("azure-native:notificationhubs:NamespaceType")
class NamespaceType(_builtins.str, Enum):
    
    MESSAGING = ...
    NOTIFICATION_HUB = ...


@pulumi.type_token(...)
class OperationProvisioningState(_builtins.str, Enum):
    
    UNKNOWN = ...
    IN_PROGRESS = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    PENDING = ...
    DISABLED = ...


@pulumi.type_token(...)
class PrivateEndpointConnectionProvisioningState(_builtins.str, Enum):
    
    UNKNOWN = ...
    SUCCEEDED = ...
    CREATING = ...
    UPDATING = ...
    UPDATING_BY_PROXY = ...
    DELETING = ...
    DELETING_BY_PROXY = ...
    DELETED = ...


@pulumi.type_token(...)
class PrivateLinkConnectionStatus(_builtins.str, Enum):
    
    DISCONNECTED = ...
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:notificationhubs:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:notificationhubs:ReplicationRegion")
class ReplicationRegion(_builtins.str, Enum):
    
    DEFAULT = ...
    WEST_US2 = ...
    NORTH_EUROPE = ...
    AUSTRALIA_EAST = ...
    BRAZIL_SOUTH = ...
    SOUTH_EAST_ASIA = ...
    SOUTH_AFRICA_NORTH = ...
    NONE = ...


@pulumi.type_token("azure-native:notificationhubs:SkuName")
class SkuName(_builtins.str, Enum):
    
    FREE = ...
    BASIC = ...
    STANDARD = ...


@pulumi.type_token(...)
class ZoneRedundancyPreference(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


