import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ActionRuleStatus",
    "ActionRuleType",
    "ActionType",
    "AlertRuleState",
    "DaysOfWeek",
    "Field",
    "Operator",
    "RecurrenceType",
    "ScopeType",
    "Severity",
    "Status",
    "SuppressionType",
]

@pulumi.type_token("azure-native:alertsmanagement:ActionRuleStatus")
class ActionRuleStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:alertsmanagement:ActionRuleType")
class ActionRuleType(_builtins.str, Enum):
    SUPPRESSION = ...
    ACTION_GROUP = ...
    DIAGNOSTICS = ...

@pulumi.type_token("azure-native:alertsmanagement:ActionType")
class ActionType(_builtins.str, Enum):
    ADD_ACTION_GROUPS = ...
    REMOVE_ALL_ACTION_GROUPS = ...

@pulumi.type_token("azure-native:alertsmanagement:AlertRuleState")
class AlertRuleState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:alertsmanagement:DaysOfWeek")
class DaysOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:alertsmanagement:Field")
class Field(_builtins.str, Enum):
    SEVERITY = ...
    MONITOR_SERVICE = ...
    MONITOR_CONDITION = ...
    SIGNAL_TYPE = ...
    TARGET_RESOURCE_TYPE = ...
    TARGET_RESOURCE = ...
    TARGET_RESOURCE_GROUP = ...
    ALERT_RULE_ID = ...
    ALERT_RULE_NAME = ...
    DESCRIPTION = ...
    ALERT_CONTEXT = ...

@pulumi.type_token("azure-native:alertsmanagement:Operator")
class Operator(_builtins.str, Enum):
    EQUALS = ...
    NOT_EQUALS = ...
    CONTAINS = ...
    DOES_NOT_CONTAIN = ...

@pulumi.type_token("azure-native:alertsmanagement:RecurrenceType")
class RecurrenceType(_builtins.str, Enum):
    DAILY = ...
    WEEKLY = ...
    MONTHLY = ...

@pulumi.type_token("azure-native:alertsmanagement:ScopeType")
class ScopeType(_builtins.str, Enum):
    RESOURCE_GROUP = ...
    RESOURCE = ...
    SUBSCRIPTION = ...

@pulumi.type_token("azure-native:alertsmanagement:Severity")
class Severity(_builtins.str, Enum):
    SEV0 = ...
    SEV1 = ...
    SEV2 = ...
    SEV3 = ...
    SEV4 = ...

@pulumi.type_token("azure-native:alertsmanagement:Status")
class Status(_builtins.str, Enum):
    NEW = ...
    IN_PROGRESS = ...
    MITIGATED = ...
    CLOSED = ...
    CANCELED = ...

@pulumi.type_token("azure-native:alertsmanagement:SuppressionType")
class SuppressionType(_builtins.str, Enum):
    ALWAYS = ...
    ONCE = ...
    DAILY = ...
    WEEKLY = ...
    MONTHLY = ...
