import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListKustoPoolFollowerDatabasesResult",
    "AwaitableListKustoPoolFollowerDatabasesResult",
    "list_kusto_pool_follower_databases",
    "list_kusto_pool_follower_databases_output",
]

@pulumi.output_type
class ListKustoPoolFollowerDatabasesResult:
    def __init__(__self__, value=...) -> None: ...
    @_builtins.property
    @pulumi.getter
    def value(
        self,
    ) -> Optional[Sequence[outputs.FollowerDatabaseDefinitionResponse]]: ...

class AwaitableListKustoPoolFollowerDatabasesResult(
    ListKustoPoolFollowerDatabasesResult
):
    def __await__(self): ...

def list_kusto_pool_follower_databases(
    kusto_pool_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    workspace_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListKustoPoolFollowerDatabasesResult: ...
def list_kusto_pool_follower_databases_output(
    kusto_pool_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    workspace_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListKustoPoolFollowerDatabasesResult]: ...
