import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AdvancedFilterOperatorType",
    "ChannelProvisioningState",
    "ChannelType",
    "ClientCertificateValidationScheme",
    "ClientState",
    "CustomDomainIdentityType",
    "CustomDomainValidationState",
    "DataResidencyBoundary",
    "DeadLetterEndPointType",
    "DeliveryAttributeMappingType",
    "DeliveryMode",
    "DeliverySchema",
    "EndpointType",
    "EventDefinitionKind",
    "EventDeliverySchema",
    "EventInputSchema",
    "EventSubscriptionIdentityType",
    "FilterOperatorType",
    "IdentityType",
    "InputSchema",
    "InputSchemaMappingType",
    "IpActionType",
    "MonitorAlertSeverity",
    "PartnerConfigurationProvisioningState",
    "PartnerDestinationActivationState",
    "PartnerTopicActivationState",
    "PartnerTopicRoutingMode",
    "PermissionType",
    "PersistedConnectionStatus",
    "PublicNetworkAccess",
    "PublisherType",
    "ReadinessState",
    "ResourceProvisioningState",
    "RoutingIdentityType",
    "SkuName",
    "StaticRoutingEnrichmentType",
    "TlsVersion",
    "TopicSpacesConfigurationState",
]

@pulumi.type_token("azure-native:eventgrid:AdvancedFilterOperatorType")
class AdvancedFilterOperatorType(_builtins.str, Enum):
    NUMBER_IN = ...
    NUMBER_NOT_IN = ...
    NUMBER_LESS_THAN = ...
    NUMBER_GREATER_THAN = ...
    NUMBER_LESS_THAN_OR_EQUALS = ...
    NUMBER_GREATER_THAN_OR_EQUALS = ...
    BOOL_EQUALS = ...
    STRING_IN = ...
    STRING_NOT_IN = ...
    STRING_BEGINS_WITH = ...
    STRING_ENDS_WITH = ...
    STRING_CONTAINS = ...
    NUMBER_IN_RANGE = ...
    NUMBER_NOT_IN_RANGE = ...
    STRING_NOT_BEGINS_WITH = ...
    STRING_NOT_ENDS_WITH = ...
    STRING_NOT_CONTAINS = ...
    IS_NULL_OR_UNDEFINED = ...
    IS_NOT_NULL = ...

@pulumi.type_token("azure-native:eventgrid:ChannelProvisioningState")
class ChannelProvisioningState(_builtins.str, Enum):
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...
    IDLE_DUE_TO_MIRRORED_PARTNER_TOPIC_DELETION = ...

@pulumi.type_token("azure-native:eventgrid:ChannelType")
class ChannelType(_builtins.str, Enum):
    PARTNER_TOPIC = ...

@pulumi.type_token(...)
class ClientCertificateValidationScheme(_builtins.str, Enum):
    SUBJECT_MATCHES_AUTHENTICATION_NAME = ...
    DNS_MATCHES_AUTHENTICATION_NAME = ...
    URI_MATCHES_AUTHENTICATION_NAME = ...
    IP_MATCHES_AUTHENTICATION_NAME = ...
    EMAIL_MATCHES_AUTHENTICATION_NAME = ...
    THUMBPRINT_MATCH = ...

@pulumi.type_token("azure-native:eventgrid:ClientState")
class ClientState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:eventgrid:CustomDomainIdentityType")
class CustomDomainIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:eventgrid:CustomDomainValidationState")
class CustomDomainValidationState(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    ERROR_RETRIEVING_DNS_RECORD = ...

@pulumi.type_token("azure-native:eventgrid:DataResidencyBoundary")
class DataResidencyBoundary(_builtins.str, Enum):
    WITHIN_GEOPAIR = ...
    WITHIN_REGION = ...

@pulumi.type_token("azure-native:eventgrid:DeadLetterEndPointType")
class DeadLetterEndPointType(_builtins.str, Enum):
    STORAGE_BLOB = ...

@pulumi.type_token(...)
class DeliveryAttributeMappingType(_builtins.str, Enum):
    STATIC = ...
    DYNAMIC = ...

@pulumi.type_token("azure-native:eventgrid:DeliveryMode")
class DeliveryMode(_builtins.str, Enum):
    QUEUE = ...
    PUSH = ...

@pulumi.type_token("azure-native:eventgrid:DeliverySchema")
class DeliverySchema(_builtins.str, Enum):
    CLOUD_EVENT_SCHEMA_V1_0 = ...

@pulumi.type_token("azure-native:eventgrid:EndpointType")
class EndpointType(_builtins.str, Enum):
    WEB_HOOK = ...
    EVENT_HUB = ...
    STORAGE_QUEUE = ...
    HYBRID_CONNECTION = ...
    SERVICE_BUS_QUEUE = ...
    SERVICE_BUS_TOPIC = ...
    AZURE_FUNCTION = ...
    MONITOR_ALERT = ...
    NAMESPACE_TOPIC = ...

@pulumi.type_token("azure-native:eventgrid:EventDefinitionKind")
class EventDefinitionKind(_builtins.str, Enum):
    INLINE = ...

@pulumi.type_token("azure-native:eventgrid:EventDeliverySchema")
class EventDeliverySchema(_builtins.str, Enum):
    EVENT_GRID_SCHEMA = ...
    CUSTOM_INPUT_SCHEMA = ...
    CLOUD_EVENT_SCHEMA_V1_0 = ...

@pulumi.type_token("azure-native:eventgrid:EventInputSchema")
class EventInputSchema(_builtins.str, Enum):
    CLOUD_EVENT_SCHEMA_V1_0 = ...

@pulumi.type_token(...)
class EventSubscriptionIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:eventgrid:FilterOperatorType")
class FilterOperatorType(_builtins.str, Enum):
    NUMBER_IN = ...
    NUMBER_NOT_IN = ...
    NUMBER_LESS_THAN = ...
    NUMBER_GREATER_THAN = ...
    NUMBER_LESS_THAN_OR_EQUALS = ...
    NUMBER_GREATER_THAN_OR_EQUALS = ...
    BOOL_EQUALS = ...
    STRING_IN = ...
    STRING_NOT_IN = ...
    STRING_BEGINS_WITH = ...
    STRING_ENDS_WITH = ...
    STRING_CONTAINS = ...
    NUMBER_IN_RANGE = ...
    NUMBER_NOT_IN_RANGE = ...
    STRING_NOT_BEGINS_WITH = ...
    STRING_NOT_ENDS_WITH = ...
    STRING_NOT_CONTAINS = ...
    IS_NULL_OR_UNDEFINED = ...
    IS_NOT_NULL = ...

@pulumi.type_token("azure-native:eventgrid:IdentityType")
class IdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:eventgrid:InputSchema")
class InputSchema(_builtins.str, Enum):
    EVENT_GRID_SCHEMA = ...
    CUSTOM_EVENT_SCHEMA = ...
    CLOUD_EVENT_SCHEMA_V1_0 = ...

@pulumi.type_token("azure-native:eventgrid:InputSchemaMappingType")
class InputSchemaMappingType(_builtins.str, Enum):
    JSON = ...

@pulumi.type_token("azure-native:eventgrid:IpActionType")
class IpActionType(_builtins.str, Enum):
    ALLOW = ...

@pulumi.type_token("azure-native:eventgrid:MonitorAlertSeverity")
class MonitorAlertSeverity(_builtins.str, Enum):
    SEV0 = ...
    SEV1 = ...
    SEV2 = ...
    SEV3 = ...
    SEV4 = ...

@pulumi.type_token(...)
class PartnerConfigurationProvisioningState(_builtins.str, Enum):
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...

@pulumi.type_token(...)
class PartnerDestinationActivationState(_builtins.str, Enum):
    NEVER_ACTIVATED = ...
    ACTIVATED = ...

@pulumi.type_token("azure-native:eventgrid:PartnerTopicActivationState")
class PartnerTopicActivationState(_builtins.str, Enum):
    NEVER_ACTIVATED = ...
    ACTIVATED = ...
    DEACTIVATED = ...

@pulumi.type_token("azure-native:eventgrid:PartnerTopicRoutingMode")
class PartnerTopicRoutingMode(_builtins.str, Enum):
    SOURCE_EVENT_ATTRIBUTE = ...
    CHANNEL_NAME_HEADER = ...

@pulumi.type_token("azure-native:eventgrid:PermissionType")
class PermissionType(_builtins.str, Enum):
    PUBLISHER = ...
    SUBSCRIBER = ...

@pulumi.type_token("azure-native:eventgrid:PersistedConnectionStatus")
class PersistedConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:eventgrid:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:eventgrid:PublisherType")
class PublisherType(_builtins.str, Enum):
    CUSTOM = ...

@pulumi.type_token("azure-native:eventgrid:ReadinessState")
class ReadinessState(_builtins.str, Enum):
    NEVER_ACTIVATED = ...
    ACTIVATED = ...

@pulumi.type_token("azure-native:eventgrid:ResourceProvisioningState")
class ResourceProvisioningState(_builtins.str, Enum):
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...

@pulumi.type_token("azure-native:eventgrid:RoutingIdentityType")
class RoutingIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:eventgrid:SkuName")
class SkuName(_builtins.str, Enum):
    STANDARD = ...

@pulumi.type_token("azure-native:eventgrid:StaticRoutingEnrichmentType")
class StaticRoutingEnrichmentType(_builtins.str, Enum):
    STRING = ...

@pulumi.type_token("azure-native:eventgrid:TlsVersion")
class TlsVersion(_builtins.str, Enum):
    TLS_VERSION_1_0 = ...
    TLS_VERSION_1_1 = ...
    TLS_VERSION_1_2 = ...

@pulumi.type_token(...)
class TopicSpacesConfigurationState(_builtins.str, Enum):
    DISABLED = ...
    ENABLED = ...
