import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetDomainResult",
    "AwaitableGetDomainResult",
    "get_domain",
    "get_domain_output",
]

@pulumi.output_type
class GetDomainResult:
    def __init__(
        __self__,
        auto_create_topic_with_first_subscription=...,
        auto_delete_topic_with_last_subscription=...,
        azure_api_version=...,
        data_residency_boundary=...,
        disable_local_auth=...,
        endpoint=...,
        event_type_info=...,
        id=...,
        identity=...,
        inbound_ip_rules=...,
        input_schema=...,
        input_schema_mapping=...,
        location=...,
        metric_resource_id=...,
        minimum_tls_version_allowed=...,
        name=...,
        private_endpoint_connections=...,
        provisioning_state=...,
        public_network_access=...,
        system_data=...,
        tags=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="autoCreateTopicWithFirstSubscription")
    def auto_create_topic_with_first_subscription(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="autoDeleteTopicWithLastSubscription")
    def auto_delete_topic_with_last_subscription(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="dataResidencyBoundary")
    def data_residency_boundary(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="disableLocalAuth")
    def disable_local_auth(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="eventTypeInfo")
    def event_type_info(self) -> Optional[outputs.EventTypeInfoResponse]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[outputs.IdentityInfoResponse]: ...
    @_builtins.property
    @pulumi.getter(name="inboundIpRules")
    def inbound_ip_rules(self) -> Optional[Sequence[outputs.InboundIpRuleResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="inputSchema")
    def input_schema(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="inputSchemaMapping")
    def input_schema_mapping(
        self,
    ) -> Optional[outputs.JsonInputSchemaMappingResponse]: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="metricResourceId")
    def metric_resource_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="minimumTlsVersionAllowed")
    def minimum_tls_version_allowed(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="privateEndpointConnections")
    def private_endpoint_connections(
        self,
    ) -> Sequence[outputs.PrivateEndpointConnectionResponse]: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="publicNetworkAccess")
    def public_network_access(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetDomainResult(GetDomainResult):
    def __await__(self): ...

def get_domain(
    domain_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetDomainResult: ...
def get_domain_output(
    domain_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetDomainResult]: ...
