

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ApiKind', 'DeploymentState', 'EnvironmentKind', 'EnvironmentServerType', 'ImportSpecificationOptions', 'LifecycleStage', 'ManagedServiceIdentityType', 'MetadataAssignmentEntity']
@pulumi.type_token("azure-native:apicenter:ApiKind")
class ApiKind(_builtins.str, Enum):
    
    REST = ...
    GRAPHQL = ...
    GRPC = ...
    SOAP = ...
    WEBHOOK = ...
    WEBSOCKET = ...


@pulumi.type_token("azure-native:apicenter:DeploymentState")
class DeploymentState(_builtins.str, Enum):
    
    ACTIVE = ...
    INACTIVE = ...


@pulumi.type_token("azure-native:apicenter:EnvironmentKind")
class EnvironmentKind(_builtins.str, Enum):
    
    DEVELOPMENT = ...
    TESTING = ...
    STAGING = ...
    PRODUCTION = ...


@pulumi.type_token("azure-native:apicenter:EnvironmentServerType")
class EnvironmentServerType(_builtins.str, Enum):
    
    AZURE_AP_I_MANAGEMENT = ...
    AZURE_COMPUTE_SERVICE = ...
    APIGEE_AP_I_MANAGEMENT = ...
    AW_S_AP_I_GATEWAY = ...
    KONG_AP_I_GATEWAY = ...
    KUBERNETES = ...
    MULE_SOFT_AP_I_MANAGEMENT = ...


@pulumi.type_token("azure-native:apicenter:ImportSpecificationOptions")
class ImportSpecificationOptions(_builtins.str, Enum):
    
    NEVER = ...
    ON_DEMAND = ...
    ALWAYS = ...


@pulumi.type_token("azure-native:apicenter:LifecycleStage")
class LifecycleStage(_builtins.str, Enum):
    
    DESIGN = ...
    DEVELOPMENT = ...
    TESTING = ...
    PREVIEW = ...
    PRODUCTION = ...
    DEPRECATED = ...
    RETIRED = ...


@pulumi.type_token("azure-native:apicenter:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:apicenter:MetadataAssignmentEntity")
class MetadataAssignmentEntity(_builtins.str, Enum):
    
    API = ...
    ENVIRONMENT = ...
    DEPLOYMENT = ...


