

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ActionType', 'DeadlineType', 'Language', 'Month', 'NotificationType', 'OptimizationPreference', 'ResourceType', 'WeekDay']
@pulumi.type_token("azure-native:computeschedule:ActionType")
class ActionType(_builtins.str, Enum):
    
    START = ...
    DEALLOCATE = ...
    HIBERNATE = ...


@pulumi.type_token("azure-native:computeschedule:DeadlineType")
class DeadlineType(_builtins.str, Enum):
    
    UNKNOWN = ...
    INITIATE_AT = ...
    COMPLETE_BY = ...


@pulumi.type_token("azure-native:computeschedule:Language")
class Language(_builtins.str, Enum):
    
    EN_US = ...


@pulumi.type_token("azure-native:computeschedule:Month")
class Month(_builtins.str, Enum):
    
    JANUARY = ...
    FEBRUARY = ...
    MARCH = ...
    APRIL = ...
    MAY = ...
    JUNE = ...
    JULY = ...
    AUGUST = ...
    SEPTEMBER = ...
    OCTOBER = ...
    NOVEMBER = ...
    DECEMBER = ...
    ALL = ...


@pulumi.type_token("azure-native:computeschedule:NotificationType")
class NotificationType(_builtins.str, Enum):
    
    EMAIL = ...


@pulumi.type_token(...)
class OptimizationPreference(_builtins.str, Enum):
    
    COST = ...
    AVAILABILITY = ...
    COST_AVAILABILITY_BALANCED = ...


@pulumi.type_token("azure-native:computeschedule:ResourceType")
class ResourceType(_builtins.str, Enum):
    
    VIRTUAL_MACHINE = ...
    VIRTUAL_MACHINE_SCALE_SET = ...


@pulumi.type_token("azure-native:computeschedule:WeekDay")
class WeekDay(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...
    ALL = ...


