

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['DirectPeeringType', 'Kind', 'Role', 'SessionAddressProvider']
@pulumi.type_token("azure-native:peering:DirectPeeringType")
class DirectPeeringType(_builtins.str, Enum):
    
    EDGE = ...
    TRANSIT = ...
    CDN = ...
    INTERNAL = ...
    IX = ...
    IX_RS = ...
    VOICE = ...
    EDGE_ZONE_FOR_OPERATORS = ...


@pulumi.type_token("azure-native:peering:Kind")
class Kind(_builtins.str, Enum):
    
    DIRECT = ...
    EXCHANGE = ...


@pulumi.type_token("azure-native:peering:Role")
class Role(_builtins.str, Enum):
    
    NOC = ...
    POLICY = ...
    TECHNICAL = ...
    SERVICE = ...
    ESCALATION = ...
    OTHER = ...


@pulumi.type_token("azure-native:peering:SessionAddressProvider")
class SessionAddressProvider(_builtins.str, Enum):
    
    MICROSOFT = ...
    PEER = ...


