

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessMode', 'AdvertiseMode', 'DataResilienceTier', 'FailoverTier', 'NfsDirectoryActionOnVolumeDeletion', 'PerformanceTier', 'SCType', 'VolumeBindingMode', 'VolumeExpansion']
@pulumi.type_token("azure-native:kubernetesruntime:AccessMode")
class AccessMode(_builtins.str, Enum):
    
    READ_WRITE_ONCE = ...
    READ_WRITE_MANY = ...


@pulumi.type_token("azure-native:kubernetesruntime:AdvertiseMode")
class AdvertiseMode(_builtins.str, Enum):
    
    ARP = ...
    BGP = ...
    BOTH = ...


@pulumi.type_token("azure-native:kubernetesruntime:DataResilienceTier")
class DataResilienceTier(_builtins.str, Enum):
    
    NOT_DATA_RESILIENT = ...
    DATA_RESILIENT = ...


@pulumi.type_token("azure-native:kubernetesruntime:FailoverTier")
class FailoverTier(_builtins.str, Enum):
    
    NOT_AVAILABLE = ...
    SLOW = ...
    FAST = ...
    SUPER = ...


@pulumi.type_token(...)
class NfsDirectoryActionOnVolumeDeletion(_builtins.str, Enum):
    
    DELETE = ...
    RETAIN = ...


@pulumi.type_token("azure-native:kubernetesruntime:PerformanceTier")
class PerformanceTier(_builtins.str, Enum):
    
    UNDEFINED = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...
    ULTRA = ...


@pulumi.type_token("azure-native:kubernetesruntime:SCType")
class SCType(_builtins.str, Enum):
    
    NATIVE = ...
    RWX = ...
    BLOB = ...
    NFS = ...
    SMB = ...


@pulumi.type_token("azure-native:kubernetesruntime:VolumeBindingMode")
class VolumeBindingMode(_builtins.str, Enum):
    
    IMMEDIATE = ...
    WAIT_FOR_FIRST_CONSUMER = ...


@pulumi.type_token("azure-native:kubernetesruntime:VolumeExpansion")
class VolumeExpansion(_builtins.str, Enum):
    
    ALLOW = ...
    DISALLOW = ...


