import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AccessRights",
    "DefaultAction",
    "EndPointProvisioningState",
    "EntityStatus",
    "FilterType",
    "IPAction",
    "KeySource",
    "ManagedServiceIdentityType",
    "NetworkRuleIPAction",
    "PrivateLinkConnectionStatus",
    "PublicNetworkAccess",
    "PublicNetworkAccessFlag",
    "SkuName",
    "SkuTier",
    "TlsVersion",
]

@pulumi.type_token("azure-native:servicebus:AccessRights")
class AccessRights(_builtins.str, Enum):
    MANAGE = ...
    SEND = ...
    LISTEN = ...

@pulumi.type_token("azure-native:servicebus:DefaultAction")
class DefaultAction(_builtins.str, Enum):
    ALLOW = ...
    DENY = ...

@pulumi.type_token("azure-native:servicebus:EndPointProvisioningState")
class EndPointProvisioningState(_builtins.str, Enum):
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...

@pulumi.type_token("azure-native:servicebus:EntityStatus")
class EntityStatus(_builtins.str, Enum):
    ACTIVE = ...
    DISABLED = ...
    RESTORING = ...
    SEND_DISABLED = ...
    RECEIVE_DISABLED = ...
    CREATING = ...
    DELETING = ...
    RENAMING = ...
    UNKNOWN = ...

@pulumi.type_token("azure-native:servicebus:FilterType")
class FilterType(_builtins.str, Enum):
    SQL_FILTER = ...
    CORRELATION_FILTER = ...

@pulumi.type_token("azure-native:servicebus:IPAction")
class IPAction(_builtins.str, Enum):
    ACCEPT = ...
    REJECT = ...

@pulumi.type_token("azure-native:servicebus:KeySource")
class KeySource(_builtins.str, Enum):
    MICROSOFT_KEY_VAULT = ...

@pulumi.type_token("azure-native:servicebus:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...

@pulumi.type_token("azure-native:servicebus:NetworkRuleIPAction")
class NetworkRuleIPAction(_builtins.str, Enum):
    ALLOW = ...

@pulumi.type_token(...)
class PrivateLinkConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:servicebus:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...

@pulumi.type_token("azure-native:servicebus:PublicNetworkAccessFlag")
class PublicNetworkAccessFlag(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:servicebus:SkuName")
class SkuName(_builtins.str, Enum):
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:servicebus:SkuTier")
class SkuTier(_builtins.str, Enum):
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:servicebus:TlsVersion")
class TlsVersion(_builtins.str, Enum):
    TLS_VERSION_1_0 = ...
    TLS_VERSION_1_1 = ...
    TLS_VERSION_1_2 = ...
