import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ApplicationEnablement",
    "ArtifactReplicationStrategy",
    "ArtifactStoreType",
    "ArtifactType",
    "AzureArcKubernetesArtifactType",
    "AzureCoreArtifactType",
    "AzureOperatorNexusArtifactType",
    "BackingResourcePublicNetworkAccess",
    "ConfigurationGroupValueConfigurationType",
    "ContainerizedNetworkFunctionNFVIType",
    "DeviceType",
    "DiskCreateOptionTypes",
    "IPAllocationMethod",
    "IPVersion",
    "IdType",
    "ManagedServiceIdentityType",
    "NFVIType",
    "NetworkFunctionConfigurationType",
    "NetworkFunctionRoleConfigurationType",
    "NetworkFunctionType",
    "OperatingSystemTypes",
    "PublisherScope",
    "SkuDeploymentMode",
    "SkuName",
    "SkuType",
    "TemplateType",
    "Type",
    "VMSwitchType",
    "VirtualMachineSizeTypes",
    "VirtualNetworkFunctionNFVIType",
]

@pulumi.type_token("azure-native:hybridnetwork:ApplicationEnablement")
class ApplicationEnablement(_builtins.str, Enum):
    UNKNOWN = ...
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class ArtifactReplicationStrategy(_builtins.str, Enum):
    UNKNOWN = ...
    SINGLE_REPLICATION = ...

@pulumi.type_token("azure-native:hybridnetwork:ArtifactStoreType")
class ArtifactStoreType(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE_CONTAINER_REGISTRY = ...
    AZURE_STORAGE_ACCOUNT = ...

@pulumi.type_token("azure-native:hybridnetwork:ArtifactType")
class ArtifactType(_builtins.str, Enum):
    UNKNOWN = ...
    OCI_ARTIFACT = ...
    VHD_IMAGE_FILE = ...
    ARM_TEMPLATE = ...
    IMAGE_FILE = ...

@pulumi.type_token(...)
class AzureArcKubernetesArtifactType(_builtins.str, Enum):
    UNKNOWN = ...
    HELM_PACKAGE = ...

@pulumi.type_token("azure-native:hybridnetwork:AzureCoreArtifactType")
class AzureCoreArtifactType(_builtins.str, Enum):
    UNKNOWN = ...
    VHD_IMAGE_FILE = ...
    ARM_TEMPLATE = ...

@pulumi.type_token(...)
class AzureOperatorNexusArtifactType(_builtins.str, Enum):
    UNKNOWN = ...
    IMAGE_FILE = ...
    ARM_TEMPLATE = ...

@pulumi.type_token(...)
class BackingResourcePublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class ConfigurationGroupValueConfigurationType(_builtins.str, Enum):
    UNKNOWN = ...
    SECRET = ...
    OPEN = ...

@pulumi.type_token(...)
class ContainerizedNetworkFunctionNFVIType(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE_ARC_KUBERNETES = ...

@pulumi.type_token("azure-native:hybridnetwork:DeviceType")
class DeviceType(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE_STACK_EDGE = ...

@pulumi.type_token("azure-native:hybridnetwork:DiskCreateOptionTypes")
class DiskCreateOptionTypes(_builtins.str, Enum):
    UNKNOWN = ...
    EMPTY = ...

@pulumi.type_token("azure-native:hybridnetwork:IPAllocationMethod")
class IPAllocationMethod(_builtins.str, Enum):
    UNKNOWN = ...
    STATIC = ...
    DYNAMIC = ...

@pulumi.type_token("azure-native:hybridnetwork:IPVersion")
class IPVersion(_builtins.str, Enum):
    UNKNOWN = ...
    I_PV4 = ...

@pulumi.type_token("azure-native:hybridnetwork:IdType")
class IdType(_builtins.str, Enum):
    UNKNOWN = ...
    OPEN = ...
    SECRET = ...

@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:hybridnetwork:NFVIType")
class NFVIType(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE_ARC_KUBERNETES = ...
    AZURE_CORE = ...
    AZURE_OPERATOR_NEXUS = ...

@pulumi.type_token(...)
class NetworkFunctionConfigurationType(_builtins.str, Enum):
    UNKNOWN = ...
    SECRET = ...
    OPEN = ...

@pulumi.type_token(...)
class NetworkFunctionRoleConfigurationType(_builtins.str, Enum):
    UNKNOWN = ...
    VIRTUAL_MACHINE = ...

@pulumi.type_token("azure-native:hybridnetwork:NetworkFunctionType")
class NetworkFunctionType(_builtins.str, Enum):
    UNKNOWN = ...
    VIRTUAL_NETWORK_FUNCTION = ...
    CONTAINERIZED_NETWORK_FUNCTION = ...

@pulumi.type_token("azure-native:hybridnetwork:OperatingSystemTypes")
class OperatingSystemTypes(_builtins.str, Enum):
    UNKNOWN = ...
    WINDOWS = ...
    LINUX = ...

@pulumi.type_token("azure-native:hybridnetwork:PublisherScope")
class PublisherScope(_builtins.str, Enum):
    UNKNOWN = ...
    PRIVATE = ...

@pulumi.type_token("azure-native:hybridnetwork:SkuDeploymentMode")
class SkuDeploymentMode(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE = ...
    PRIVATE_EDGE_ZONE = ...

@pulumi.type_token("azure-native:hybridnetwork:SkuName")
class SkuName(_builtins.str, Enum):
    BASIC = ...
    STANDARD = ...

@pulumi.type_token("azure-native:hybridnetwork:SkuType")
class SkuType(_builtins.str, Enum):
    UNKNOWN = ...
    EVOLVED_PACKET_CORE = ...
    SDWAN = ...
    FIREWALL = ...

@pulumi.type_token("azure-native:hybridnetwork:TemplateType")
class TemplateType(_builtins.str, Enum):
    UNKNOWN = ...
    ARM_TEMPLATE = ...

@pulumi.type_token("azure-native:hybridnetwork:Type")
class Type(_builtins.str, Enum):
    UNKNOWN = ...
    ARM_RESOURCE_DEFINITION = ...
    NETWORK_FUNCTION_DEFINITION = ...

@pulumi.type_token("azure-native:hybridnetwork:VMSwitchType")
class VMSwitchType(_builtins.str, Enum):
    UNKNOWN = ...
    MANAGEMENT = ...
    WAN = ...
    LAN = ...

@pulumi.type_token("azure-native:hybridnetwork:VirtualMachineSizeTypes")
class VirtualMachineSizeTypes(_builtins.str, Enum):
    UNKNOWN = ...
    STANDARD_D1_V2 = ...
    STANDARD_D2_V2 = ...
    STANDARD_D3_V2 = ...
    STANDARD_D4_V2 = ...
    STANDARD_D5_V2 = ...
    STANDARD_D11_V2 = ...
    STANDARD_D12_V2 = ...
    STANDARD_D13_V2 = ...
    STANDARD_DS1_V2 = ...
    STANDARD_DS2_V2 = ...
    STANDARD_DS3_V2 = ...
    STANDARD_DS4_V2 = ...
    STANDARD_DS5_V2 = ...
    STANDARD_DS11_V2 = ...
    STANDARD_DS12_V2 = ...
    STANDARD_DS13_V2 = ...
    STANDARD_F1 = ...
    STANDARD_F2 = ...
    STANDARD_F4 = ...
    STANDARD_F8 = ...
    STANDARD_F16 = ...
    STANDARD_F1S = ...
    STANDARD_F2S = ...
    STANDARD_F4S = ...
    STANDARD_F8S = ...
    STANDARD_F16S = ...

@pulumi.type_token(...)
class VirtualNetworkFunctionNFVIType(_builtins.str, Enum):
    UNKNOWN = ...
    AZURE_CORE = ...
    AZURE_OPERATOR_NEXUS = ...
