

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['BillingManagementTenantState', 'InvoiceSectionState', 'InvoiceSectionStateReasonCode', 'ProvisioningTenantState']
@pulumi.type_token("azure-native:billing:BillingManagementTenantState")
class BillingManagementTenantState(_builtins.str, Enum):
    
    OTHER = ...
    NOT_ALLOWED = ...
    ACTIVE = ...
    REVOKED = ...


@pulumi.type_token("azure-native:billing:InvoiceSectionState")
class InvoiceSectionState(_builtins.str, Enum):
    
    OTHER = ...
    ACTIVE = ...
    DELETED = ...
    DISABLED = ...
    UNDER_REVIEW = ...
    WARNED = ...
    RESTRICTED = ...


@pulumi.type_token("azure-native:billing:InvoiceSectionStateReasonCode")
class InvoiceSectionStateReasonCode(_builtins.str, Enum):
    
    OTHER = ...
    PAST_DUE = ...
    UNUSUAL_ACTIVITY = ...
    SPENDING_LIMIT_REACHED = ...
    SPENDING_LIMIT_EXPIRED = ...


@pulumi.type_token("azure-native:billing:ProvisioningTenantState")
class ProvisioningTenantState(_builtins.str, Enum):
    
    OTHER = ...
    NOT_REQUESTED = ...
    ACTIVE = ...
    PENDING = ...
    BILLING_REQUEST_EXPIRED = ...
    BILLING_REQUEST_DECLINED = ...
    REVOKED = ...


