

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AlwaysLog', 'ApiGatewaySkuType', 'ApiType', 'ApimIdentityType', 'AppType', 'AuthorizationMethod', 'AuthorizationType', 'BackendProtocol', 'BackendType', 'BearerTokenSendingMethod', 'BearerTokenSendingMethods', 'CertificateSource', 'CertificateStatus', 'ClientAuthenticationMethod', 'Confirmation', 'ContentFormat', 'DataMaskingMode', 'DeveloperPortalStatus', 'GatewayListDebugCredentialsContractPurpose', 'GrantType', 'GroupType', 'HostnameType', 'HttpCorrelationProtocol', 'IdentityProviderType', 'KeyType', 'LegacyApiState', 'LegacyPortalStatus', 'LoggerType', 'NatGatewayState', 'OAuth2GrantType', 'OperationNameFormat', 'PolicyContentFormat', 'PolicyFragmentContentFormat', 'PolicyRestrictionRequireBase', 'PrivateEndpointServiceConnectionStatus', 'ProductState', 'Protocol', 'ProvisioningState', 'PublicNetworkAccess', 'SamplingType', 'SchemaType', 'SkuType', 'SoapApiType', 'State', 'SubscriptionState', 'TranslateRequiredQueryParametersConduct', 'UserState', 'Verbosity', 'VersioningScheme', 'VirtualNetworkType']
@pulumi.type_token("azure-native:apimanagement:AlwaysLog")
class AlwaysLog(_builtins.str, Enum):
    
    ALL_ERRORS = ...


@pulumi.type_token("azure-native:apimanagement:ApiGatewaySkuType")
class ApiGatewaySkuType(_builtins.str, Enum):
    
    STANDARD = ...
    WORKSPACE_GATEWAY_STANDARD = ...
    WORKSPACE_GATEWAY_PREMIUM = ...


@pulumi.type_token("azure-native:apimanagement:ApiType")
class ApiType(_builtins.str, Enum):
    
    HTTP = ...
    SOAP = ...
    WEBSOCKET = ...
    GRAPHQL = ...
    ODATA = ...
    GRPC = ...


@pulumi.type_token("azure-native:apimanagement:ApimIdentityType")
class ApimIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:apimanagement:AppType")
class AppType(_builtins.str, Enum):
    
    PORTAL = ...
    DEVELOPER_PORTAL = ...


@pulumi.type_token("azure-native:apimanagement:AuthorizationMethod")
class AuthorizationMethod(_builtins.str, Enum):
    HEAD = ...
    OPTIONS = ...
    TRACE = ...
    GET = ...
    POST = ...
    PUT = ...
    PATCH = ...
    DELETE = ...


@pulumi.type_token("azure-native:apimanagement:AuthorizationType")
class AuthorizationType(_builtins.str, Enum):
    
    O_AUTH2 = ...


@pulumi.type_token("azure-native:apimanagement:BackendProtocol")
class BackendProtocol(_builtins.str, Enum):
    
    HTTP = ...
    SOAP = ...


@pulumi.type_token("azure-native:apimanagement:BackendType")
class BackendType(_builtins.str, Enum):
    
    SINGLE = ...
    POOL = ...


@pulumi.type_token(...)
class BearerTokenSendingMethod(_builtins.str, Enum):
    AUTHORIZATION_HEADER = ...
    QUERY = ...


@pulumi.type_token(...)
class BearerTokenSendingMethods(_builtins.str, Enum):
    
    AUTHORIZATION_HEADER = ...
    QUERY = ...


@pulumi.type_token("azure-native:apimanagement:CertificateSource")
class CertificateSource(_builtins.str, Enum):
    
    MANAGED = ...
    KEY_VAULT = ...
    CUSTOM = ...
    BUILT_IN = ...


@pulumi.type_token("azure-native:apimanagement:CertificateStatus")
class CertificateStatus(_builtins.str, Enum):
    
    COMPLETED = ...
    FAILED = ...
    IN_PROGRESS = ...


@pulumi.type_token(...)
class ClientAuthenticationMethod(_builtins.str, Enum):
    BASIC = ...
    BODY = ...


@pulumi.type_token("azure-native:apimanagement:Confirmation")
class Confirmation(_builtins.str, Enum):
    
    SIGNUP = ...
    INVITE = ...


@pulumi.type_token("azure-native:apimanagement:ContentFormat")
class ContentFormat(_builtins.str, Enum):
    
    WADL_XML = ...
    WADL_LINK_JSON = ...
    SWAGGER_JSON = ...
    SWAGGER_LINK_JSON = ...
    WSDL = ...
    WSDL_LINK = ...
    OPENAPI = ...
    OPENAPI_JSON = ...
    OPENAPI_LINK = ...
    OPENAPI_JSON_LINK = ...
    GRAPHQL_LINK = ...
    ODATA = ...
    ODATA_LINK = ...
    GRPC = ...
    GRPC_LINK = ...


@pulumi.type_token("azure-native:apimanagement:DataMaskingMode")
class DataMaskingMode(_builtins.str, Enum):
    
    MASK = ...
    HIDE = ...


@pulumi.type_token("azure-native:apimanagement:DeveloperPortalStatus")
class DeveloperPortalStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class GatewayListDebugCredentialsContractPurpose(_builtins.str, Enum):
    
    TRACING = ...


@pulumi.type_token("azure-native:apimanagement:GrantType")
class GrantType(_builtins.str, Enum):
    AUTHORIZATION_CODE = ...
    IMPLICIT = ...
    RESOURCE_OWNER_PASSWORD = ...
    CLIENT_CREDENTIALS = ...


@pulumi.type_token("azure-native:apimanagement:GroupType")
class GroupType(_builtins.str, Enum):
    
    CUSTOM = ...
    SYSTEM = ...
    EXTERNAL = ...


@pulumi.type_token("azure-native:apimanagement:HostnameType")
class HostnameType(_builtins.str, Enum):
    
    PROXY = ...
    PORTAL = ...
    MANAGEMENT = ...
    SCM = ...
    DEVELOPER_PORTAL = ...
    CONFIGURATION_API = ...


@pulumi.type_token("azure-native:apimanagement:HttpCorrelationProtocol")
class HttpCorrelationProtocol(_builtins.str, Enum):
    
    NONE = ...
    LEGACY = ...
    W3_C = ...


@pulumi.type_token("azure-native:apimanagement:IdentityProviderType")
class IdentityProviderType(_builtins.str, Enum):
    
    FACEBOOK = ...
    GOOGLE = ...
    MICROSOFT = ...
    TWITTER = ...
    AAD = ...
    AAD_B2_C = ...


@pulumi.type_token("azure-native:apimanagement:KeyType")
class KeyType(_builtins.str, Enum):
    
    PRIMARY = ...
    SECONDARY = ...


@pulumi.type_token("azure-native:apimanagement:LegacyApiState")
class LegacyApiState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:apimanagement:LegacyPortalStatus")
class LegacyPortalStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:apimanagement:LoggerType")
class LoggerType(_builtins.str, Enum):
    
    AZURE_EVENT_HUB = ...
    APPLICATION_INSIGHTS = ...
    AZURE_MONITOR = ...


@pulumi.type_token("azure-native:apimanagement:NatGatewayState")
class NatGatewayState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:apimanagement:OAuth2GrantType")
class OAuth2GrantType(_builtins.str, Enum):
    
    AUTHORIZATION_CODE = ...
    CLIENT_CREDENTIALS = ...


@pulumi.type_token("azure-native:apimanagement:OperationNameFormat")
class OperationNameFormat(_builtins.str, Enum):
    
    NAME = ...
    URL = ...


@pulumi.type_token("azure-native:apimanagement:PolicyContentFormat")
class PolicyContentFormat(_builtins.str, Enum):
    
    XML = ...
    XML_LINK = ...
    RAWXML = ...
    RAWXML_LINK = ...


@pulumi.type_token(...)
class PolicyFragmentContentFormat(_builtins.str, Enum):
    
    XML = ...
    RAWXML = ...


@pulumi.type_token(...)
class PolicyRestrictionRequireBase(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:apimanagement:ProductState")
class ProductState(_builtins.str, Enum):
    
    NOT_PUBLISHED = ...
    PUBLISHED = ...


@pulumi.type_token("azure-native:apimanagement:Protocol")
class Protocol(_builtins.str, Enum):
    HTTP = ...
    HTTPS = ...
    WS = ...
    WSS = ...


@pulumi.type_token("azure-native:apimanagement:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    
    CREATED = ...


@pulumi.type_token("azure-native:apimanagement:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:apimanagement:SamplingType")
class SamplingType(_builtins.str, Enum):
    
    FIXED = ...


@pulumi.type_token("azure-native:apimanagement:SchemaType")
class SchemaType(_builtins.str, Enum):
    
    XML = ...
    JSON = ...


@pulumi.type_token("azure-native:apimanagement:SkuType")
class SkuType(_builtins.str, Enum):
    
    DEVELOPER = ...
    STANDARD = ...
    PREMIUM = ...
    BASIC = ...
    CONSUMPTION = ...
    ISOLATED = ...
    BASIC_V2 = ...
    STANDARD_V2 = ...


@pulumi.type_token("azure-native:apimanagement:SoapApiType")
class SoapApiType(_builtins.str, Enum):
    
    SOAP_TO_REST = ...
    SOAP_PASS_THROUGH = ...
    WEB_SOCKET = ...
    GRAPH_QL = ...
    O_DATA = ...
    G_RPC = ...


@pulumi.type_token("azure-native:apimanagement:State")
class State(_builtins.str, Enum):
    
    PROPOSED = ...
    OPEN = ...
    REMOVED = ...
    RESOLVED = ...
    CLOSED = ...


@pulumi.type_token("azure-native:apimanagement:SubscriptionState")
class SubscriptionState(_builtins.str, Enum):
    
    SUSPENDED = ...
    ACTIVE = ...
    EXPIRED = ...
    SUBMITTED = ...
    REJECTED = ...
    CANCELLED = ...


@pulumi.type_token(...)
class TranslateRequiredQueryParametersConduct(_builtins.str, Enum):
    
    TEMPLATE = ...
    QUERY = ...


@pulumi.type_token("azure-native:apimanagement:UserState")
class UserState(_builtins.str, Enum):
    
    ACTIVE = ...
    BLOCKED = ...
    PENDING = ...
    DELETED = ...


@pulumi.type_token("azure-native:apimanagement:Verbosity")
class Verbosity(_builtins.str, Enum):
    
    VERBOSE = ...
    INFORMATION = ...
    ERROR = ...


@pulumi.type_token("azure-native:apimanagement:VersioningScheme")
class VersioningScheme(_builtins.str, Enum):
    
    SEGMENT = ...
    QUERY = ...
    HEADER = ...


@pulumi.type_token("azure-native:apimanagement:VirtualNetworkType")
class VirtualNetworkType(_builtins.str, Enum):
    
    NONE = ...
    EXTERNAL = ...
    INTERNAL = ...


