import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetSchemaResult",
    "AwaitableGetSchemaResult",
    "get_schema",
    "get_schema_output",
]

@pulumi.output_type
class GetSchemaResult:
    def __init__(
        __self__,
        azure_api_version=...,
        description=...,
        id=...,
        name=...,
        schema_type=...,
        type=...,
        value=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="schemaType")
    def schema_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]: ...

class AwaitableGetSchemaResult(GetSchemaResult):
    def __await__(self): ...

def get_schema(
    resource_group_name: Optional[_builtins.str] = ...,
    schema_id: Optional[_builtins.str] = ...,
    service_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetSchemaResult: ...
def get_schema_output(
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    schema_id: Optional[pulumi.Input[_builtins.str]] = ...,
    service_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetSchemaResult]: ...
