

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AzureDiskSkuName', 'ElasticSanSkuName', 'ManagedServiceIdentityType', 'ReclaimPolicy', 'Zone']
@pulumi.type_token("azure-native:containerstorage:AzureDiskSkuName")
class AzureDiskSkuName(_builtins.str, Enum):
    
    PREMIUM_LRS = ...
    STANDARD_LRS = ...
    STANDARD_SS_D_LRS = ...
    ULTRA_SS_D_LRS = ...
    PREMIUM_ZRS = ...
    PREMIUM_V2_LRS = ...
    STANDARD_SS_D_ZRS = ...


@pulumi.type_token("azure-native:containerstorage:ElasticSanSkuName")
class ElasticSanSkuName(_builtins.str, Enum):
    
    PREMIUM_LRS = ...
    PREMIUM_ZRS = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:containerstorage:ReclaimPolicy")
class ReclaimPolicy(_builtins.str, Enum):
    
    DELETE = ...
    RETAIN = ...


@pulumi.type_token("azure-native:containerstorage:Zone")
class Zone(_builtins.str, Enum):
    
    ZONE1 = ...
    ZONE2 = ...
    ZONE3 = ...


