import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "FeatureStatus",
    "IncomingTrafficPolicy",
    "InitialDownloadPolicy",
    "InitialUploadPolicy",
    "LocalCacheMode",
    "ManagedServiceIdentityType",
    "PrivateEndpointServiceConnectionStatus",
]

@pulumi.type_token("azure-native:storagesync:FeatureStatus")
class FeatureStatus(_builtins.str, Enum):
    ON = ...
    OFF = ...

@pulumi.type_token("azure-native:storagesync:IncomingTrafficPolicy")
class IncomingTrafficPolicy(_builtins.str, Enum):
    ALLOW_ALL_TRAFFIC = ...
    ALLOW_VIRTUAL_NETWORKS_ONLY = ...

@pulumi.type_token("azure-native:storagesync:InitialDownloadPolicy")
class InitialDownloadPolicy(_builtins.str, Enum):
    NAMESPACE_ONLY = ...
    NAMESPACE_THEN_MODIFIED_FILES = ...
    AVOID_TIERED_FILES = ...

@pulumi.type_token("azure-native:storagesync:InitialUploadPolicy")
class InitialUploadPolicy(_builtins.str, Enum):
    SERVER_AUTHORITATIVE = ...
    MERGE = ...

@pulumi.type_token("azure-native:storagesync:LocalCacheMode")
class LocalCacheMode(_builtins.str, Enum):
    DOWNLOAD_NEW_AND_MODIFIED_FILES = ...
    UPDATE_LOCALLY_CACHED_FILES = ...

@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
