

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AvailabilityType', 'CloudInitDataSource', 'ComplianceAssignmentType', 'ConfidentialVmIntent', 'DeploymentMode', 'DeviceKind', 'DiagnosticLevel', 'DiskCreateOption', 'DiskFileFormat', 'EceSecrets', 'EdgeDeviceKind', 'EdgeMachineJobType', 'EdgeMachineKind', 'ExtendedLocationTypes', 'GpuAssignmentTypeEnum', 'HciEdgeDeviceJobType', 'HciJobType', 'HyperVGeneration', 'IPPoolTypeEnum', 'InboundNATRuleProtocol', 'IpAllocationMethodEnum', 'IpAssignmentType', 'LoadBalancerBackendAddressAdminState', 'LoadBalancerProbeProtocol', 'LoadBalancerRuleSessionPersistenceType', 'LoadBalancerRuleTransportProtocol', 'ManagedServiceIdentityType', 'NetworkTypeEnum', 'OSOperationType', 'OnboardingResourceType', 'OperatingSystemTypes', 'OperationType', 'OsTypeEnum', 'OwnerKeyType', 'ProvisioningAction', 'ProvisioningOsType', 'PublicIPAddressType', 'RemoteSupportAccessLevel', 'RemoteSupportType', 'ResourceIdentityType', 'SdnIntegrationIntent', 'SecretType', 'SecurityEncryptionType', 'SecurityRuleAccess', 'SecurityRuleDirection', 'SecurityRuleProtocol', 'SecurityTypes', 'ServiceName', 'SoftwareAssuranceIntent', 'State', 'UpdateRunPropertiesState', 'UpdateSummariesPropertiesState', 'VmSizeEnum', 'WindowsServerSubscription']
@pulumi.type_token("azure-native:azurestackhci:AvailabilityType")
class AvailabilityType(_builtins.str, Enum):
    
    LOCAL = ...
    ONLINE = ...
    NOTIFY = ...


@pulumi.type_token("azure-native:azurestackhci:CloudInitDataSource")
class CloudInitDataSource(_builtins.str, Enum):
    
    NO_CLOUD = ...
    AZURE = ...


@pulumi.type_token(...)
class ComplianceAssignmentType(_builtins.str, Enum):
    
    AUDIT = ...
    APPLY_AND_AUTO_CORRECT = ...


@pulumi.type_token("azure-native:azurestackhci:ConfidentialVmIntent")
class ConfidentialVmIntent(_builtins.str, Enum):
    
    ENABLE = ...
    DISABLE = ...


@pulumi.type_token("azure-native:azurestackhci:DeploymentMode")
class DeploymentMode(_builtins.str, Enum):
    
    VALIDATE = ...
    DEPLOY = ...


@pulumi.type_token("azure-native:azurestackhci:DeviceKind")
class DeviceKind(_builtins.str, Enum):
    
    HCI = ...


@pulumi.type_token("azure-native:azurestackhci:DiagnosticLevel")
class DiagnosticLevel(_builtins.str, Enum):
    
    OFF = ...
    BASIC = ...
    ENHANCED = ...


@pulumi.type_token("azure-native:azurestackhci:DiskCreateOption")
class DiskCreateOption(_builtins.str, Enum):
    
    COPY = ...
    EMPTY = ...


@pulumi.type_token("azure-native:azurestackhci:DiskFileFormat")
class DiskFileFormat(_builtins.str, Enum):
    
    VHDX = ...
    VHD = ...


@pulumi.type_token("azure-native:azurestackhci:EceSecrets")
class EceSecrets(_builtins.str, Enum):
    
    AZURE_STACK_LCMUSER_CREDENTIAL = ...
    DEFAULT_ARB_APPLICATION = ...
    LOCAL_ADMIN_CREDENTIAL = ...
    WITNESS_STORAGE_KEY = ...


@pulumi.type_token("azure-native:azurestackhci:EdgeDeviceKind")
class EdgeDeviceKind(_builtins.str, Enum):
    
    HCI = ...


@pulumi.type_token("azure-native:azurestackhci:EdgeMachineJobType")
class EdgeMachineJobType(_builtins.str, Enum):
    
    COLLECT_LOG = ...
    REMOTE_SUPPORT = ...
    PROVISION_OS = ...
    DOWNLOAD_OS = ...


@pulumi.type_token("azure-native:azurestackhci:EdgeMachineKind")
class EdgeMachineKind(_builtins.str, Enum):
    
    STANDARD = ...
    DEDICATED = ...


@pulumi.type_token("azure-native:azurestackhci:ExtendedLocationTypes")
class ExtendedLocationTypes(_builtins.str, Enum):
    
    CUSTOM_LOCATION = ...


@pulumi.type_token("azure-native:azurestackhci:GpuAssignmentTypeEnum")
class GpuAssignmentTypeEnum(_builtins.str, Enum):
    
    GPU_DDA = ...
    GPU_P = ...


@pulumi.type_token("azure-native:azurestackhci:HciEdgeDeviceJobType")
class HciEdgeDeviceJobType(_builtins.str, Enum):
    
    COLLECT_LOG = ...
    REMOTE_SUPPORT = ...


@pulumi.type_token("azure-native:azurestackhci:HciJobType")
class HciJobType(_builtins.str, Enum):
    
    CONFIGURE_CVM = ...
    CONFIGURE_SDN_INTEGRATION = ...


@pulumi.type_token("azure-native:azurestackhci:HyperVGeneration")
class HyperVGeneration(_builtins.str, Enum):
    
    V1 = ...
    V2 = ...


@pulumi.type_token("azure-native:azurestackhci:IPPoolTypeEnum")
class IPPoolTypeEnum(_builtins.str, Enum):
    
    VM = ...
    VIPPOOL = ...


@pulumi.type_token("azure-native:azurestackhci:InboundNATRuleProtocol")
class InboundNATRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...


@pulumi.type_token("azure-native:azurestackhci:IpAllocationMethodEnum")
class IpAllocationMethodEnum(_builtins.str, Enum):
    
    DYNAMIC = ...
    STATIC = ...


@pulumi.type_token("azure-native:azurestackhci:IpAssignmentType")
class IpAssignmentType(_builtins.str, Enum):
    
    AUTOMATIC = ...
    MANUAL = ...


@pulumi.type_token(...)
class LoadBalancerBackendAddressAdminState(_builtins.str, Enum):
    
    UP = ...
    DOWN = ...


@pulumi.type_token(...)
class LoadBalancerProbeProtocol(_builtins.str, Enum):
    
    TCP = ...
    HTTP = ...


@pulumi.type_token(...)
class LoadBalancerRuleSessionPersistenceType(_builtins.str, Enum):
    
    DEFAULT = ...
    SOURCE_IP = ...
    SOURCE_IP_PROTOCOL = ...


@pulumi.type_token(...)
class LoadBalancerRuleTransportProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ALL = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:azurestackhci:NetworkTypeEnum")
class NetworkTypeEnum(_builtins.str, Enum):
    
    NAT = ...
    TRANSPARENT = ...
    L2_BRIDGE = ...
    L2_TUNNEL = ...
    ICS = ...
    PRIVATE = ...
    OVERLAY = ...
    INTERNAL = ...
    MIRRORED = ...


@pulumi.type_token("azure-native:azurestackhci:OSOperationType")
class OSOperationType(_builtins.str, Enum):
    
    PROVISION = ...
    UPDATE = ...
    RE_IMAGE = ...


@pulumi.type_token("azure-native:azurestackhci:OnboardingResourceType")
class OnboardingResourceType(_builtins.str, Enum):
    
    HYBRID_COMPUTE_MACHINE = ...


@pulumi.type_token("azure-native:azurestackhci:OperatingSystemTypes")
class OperatingSystemTypes(_builtins.str, Enum):
    
    WINDOWS = ...
    LINUX = ...


@pulumi.type_token("azure-native:azurestackhci:OperationType")
class OperationType(_builtins.str, Enum):
    
    CLUSTER_PROVISIONING = ...
    CLUSTER_UPGRADE = ...


@pulumi.type_token("azure-native:azurestackhci:OsTypeEnum")
class OsTypeEnum(_builtins.str, Enum):
    
    LINUX = ...
    WINDOWS = ...


@pulumi.type_token("azure-native:azurestackhci:OwnerKeyType")
class OwnerKeyType(_builtins.str, Enum):
    
    MICROSOFT_MANAGED = ...


@pulumi.type_token("azure-native:azurestackhci:ProvisioningAction")
class ProvisioningAction(_builtins.str, Enum):
    
    INSTALL = ...
    UNINSTALL = ...
    REPAIR = ...


@pulumi.type_token("azure-native:azurestackhci:ProvisioningOsType")
class ProvisioningOsType(_builtins.str, Enum):
    
    AZURE_LINUX = ...
    HCI = ...


@pulumi.type_token("azure-native:azurestackhci:PublicIPAddressType")
class PublicIPAddressType(_builtins.str, Enum):
    
    I_PV4 = ...
    I_PV6 = ...


@pulumi.type_token(...)
class RemoteSupportAccessLevel(_builtins.str, Enum):
    
    NONE = ...
    DIAGNOSTICS = ...
    DIAGNOSTICS_AND_REPAIR = ...


@pulumi.type_token("azure-native:azurestackhci:RemoteSupportType")
class RemoteSupportType(_builtins.str, Enum):
    
    ENABLE = ...
    REVOKE = ...


@pulumi.type_token("azure-native:azurestackhci:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...


@pulumi.type_token("azure-native:azurestackhci:SdnIntegrationIntent")
class SdnIntegrationIntent(_builtins.str, Enum):
    
    ENABLE = ...
    DISABLE = ...


@pulumi.type_token("azure-native:azurestackhci:SecretType")
class SecretType(_builtins.str, Enum):
    
    KEY_VAULT = ...
    SSH_PUB_KEY = ...


@pulumi.type_token("azure-native:azurestackhci:SecurityEncryptionType")
class SecurityEncryptionType(_builtins.str, Enum):
    
    NON_PERSISTED_TPM = ...


@pulumi.type_token("azure-native:azurestackhci:SecurityRuleAccess")
class SecurityRuleAccess(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:azurestackhci:SecurityRuleDirection")
class SecurityRuleDirection(_builtins.str, Enum):
    
    INBOUND = ...
    OUTBOUND = ...


@pulumi.type_token("azure-native:azurestackhci:SecurityRuleProtocol")
class SecurityRuleProtocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...
    ICMP = ...
    ASTERISK = ...


@pulumi.type_token("azure-native:azurestackhci:SecurityTypes")
class SecurityTypes(_builtins.str, Enum):
    
    TRUSTED_LAUNCH = ...
    CONFIDENTIAL_VM = ...


@pulumi.type_token("azure-native:azurestackhci:ServiceName")
class ServiceName(_builtins.str, Enum):
    
    WAC = ...


@pulumi.type_token("azure-native:azurestackhci:SoftwareAssuranceIntent")
class SoftwareAssuranceIntent(_builtins.str, Enum):
    
    ENABLE = ...
    DISABLE = ...


@pulumi.type_token("azure-native:azurestackhci:State")
class State(_builtins.str, Enum):
    
    HAS_PREREQUISITE = ...
    OBSOLETE = ...
    READY = ...
    NOT_APPLICABLE_BECAUSE_ANOTHER_UPDATE_IS_IN_PROGRESS = ...
    PREPARING = ...
    INSTALLING = ...
    INSTALLED = ...
    PREPARATION_FAILED = ...
    INSTALLATION_FAILED = ...
    INVALID = ...
    RECALLED = ...
    DOWNLOADING = ...
    DOWNLOAD_FAILED = ...
    HEALTH_CHECKING = ...
    HEALTH_CHECK_FAILED = ...
    READY_TO_INSTALL = ...
    SCAN_IN_PROGRESS = ...
    SCAN_FAILED = ...
    ADDITIONAL_CONTENT_REQUIRED = ...


@pulumi.type_token(...)
class UpdateRunPropertiesState(_builtins.str, Enum):
    
    UNKNOWN = ...
    SUCCEEDED = ...
    IN_PROGRESS = ...
    FAILED = ...


@pulumi.type_token(...)
class UpdateSummariesPropertiesState(_builtins.str, Enum):
    
    UNKNOWN = ...
    APPLIED_SUCCESSFULLY = ...
    UPDATE_AVAILABLE = ...
    UPDATE_IN_PROGRESS = ...
    UPDATE_FAILED = ...
    NEEDS_ATTENTION = ...
    PREPARATION_IN_PROGRESS = ...
    PREPARATION_FAILED = ...


@pulumi.type_token("azure-native:azurestackhci:VmSizeEnum")
class VmSizeEnum(_builtins.str, Enum):
    
    DEFAULT = ...
    STANDARD_A2_V2 = ...
    STANDARD_A4_V2 = ...
    STANDARD_D2S_V3 = ...
    STANDARD_D4S_V3 = ...
    STANDARD_D8S_V3 = ...
    STANDARD_D16S_V3 = ...
    STANDARD_D32S_V3 = ...
    STANDARD_DS2_V2 = ...
    STANDARD_DS3_V2 = ...
    STANDARD_DS4_V2 = ...
    STANDARD_DS5_V2 = ...
    STANDARD_DS13_V2 = ...
    STANDARD_K8_S_V1 = ...
    STANDARD_K8_S2_V1 = ...
    STANDARD_K8_S3_V1 = ...
    STANDARD_K8_S4_V1 = ...
    STANDARD_NK6 = ...
    STANDARD_NK12 = ...
    STANDARD_NV6 = ...
    STANDARD_NV12 = ...
    STANDARD_K8_S5_V1 = ...
    CUSTOM = ...


@pulumi.type_token(...)
class WindowsServerSubscription(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


