import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["AADObjectType", "FirewallAllowAzureIpsState", "FirewallState", "TierType"]

@pulumi.type_token("azure-native:datalakeanalytics:AADObjectType")
class AADObjectType(_builtins.str, Enum):
    USER = ...
    GROUP = ...
    SERVICE_PRINCIPAL = ...

@pulumi.type_token(...)
class FirewallAllowAzureIpsState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:datalakeanalytics:FirewallState")
class FirewallState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:datalakeanalytics:TierType")
class TierType(_builtins.str, Enum):
    CONSUMPTION = ...
    COMMITMENT_100_AU_HOURS = ...
    COMMITMENT_500_AU_HOURS = ...
    COMMITMENT_1000_AU_HOURS = ...
    COMMITMENT_5000_AU_HOURS = ...
    COMMITMENT_10000_AU_HOURS = ...
    COMMITMENT_50000_AU_HOURS = ...
    COMMITMENT_100000_AU_HOURS = ...
    COMMITMENT_500000_AU_HOURS = ...
