import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AdditionalOptionsAsyncOperation",
    "AdditionalOptionsResourceTypeRegistration",
    "AuthenticationScheme",
    "AvailabilityZonePolicy",
    "BlockActionVerb",
    "CapacityPolicy",
    "CommonApiVersionsMergeMode",
    "CrossTenantTokenValidation",
    "DataBoundary",
    "EndpointType",
    "EndpointTypeResourceType",
    "ExpeditedRolloutIntent",
    "ExtendedLocationType",
    "ExtensionCategory",
    "ExtensionOptionType",
    "FeaturesPolicy",
    "FilterOption",
    "FrontdoorRequestMode",
    "IdentityManagementTypes",
    "Intent",
    "LegacyOperation",
    "LinkedAction",
    "LinkedOperation",
    "LoggingDetails",
    "LoggingDirections",
    "MarketplaceType",
    "MessageScope",
    "NotificationEndpointType",
    "NotificationMode",
    "NotificationOptions",
    "NotificationType",
    "OptInHeaderType",
    "OptOutHeaderType",
    "Policy",
    "PolicyExecutionType",
    "PreflightOption",
    "ProviderRegistrationKind",
    "QuotaPolicy",
    "Readiness",
    "Regionality",
    "ResourceAccessPolicy",
    "ResourceDeletionPolicy",
    "ResourceProviderCapabilitiesEffect",
    "ResourceProviderType",
    "ResourceSubType",
    "ResourceTypeCategory",
    "ResourceTypeEndpointKind",
    "ResourceTypeExtendedLocationPolicy",
    "ResourceTypeRegistrationKind",
    "ResourceValidation",
    "Role",
    "RoutingType",
    "ServerFailureResponseMessageType",
    "ServiceClientOptionsType",
    "ServiceStatus",
    "SignedRequestScope",
    "SkipNotifications",
    "SkuScaleType",
    "SubscriptionNotificationOperation",
    "SubscriptionReregistrationResult",
    "SubscriptionState",
    "SubscriptionTransitioningState",
    "SupportedOperations",
    "TemplateDeploymentCapabilities",
    "TemplateDeploymentPreflightNotifications",
    "TemplateDeploymentPreflightOptions",
    "ThrottlingMetricType",
    "TrafficRegionCategory",
]

@pulumi.type_token(...)
class AdditionalOptionsAsyncOperation(_builtins.str, Enum):
    PROTECTED_ASYNC_OPERATION_POLLING = ...
    PROTECTED_ASYNC_OPERATION_POLLING_AUDIT_ONLY = ...

@pulumi.type_token(...)
class AdditionalOptionsResourceTypeRegistration(_builtins.str, Enum):
    PROTECTED_ASYNC_OPERATION_POLLING = ...
    PROTECTED_ASYNC_OPERATION_POLLING_AUDIT_ONLY = ...

@pulumi.type_token("azure-native:providerhub:AuthenticationScheme")
class AuthenticationScheme(_builtins.str, Enum):
    PO_P = ...
    BEARER = ...

@pulumi.type_token("azure-native:providerhub:AvailabilityZonePolicy")
class AvailabilityZonePolicy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SINGLE_ZONED = ...
    MULTI_ZONED = ...

@pulumi.type_token("azure-native:providerhub:BlockActionVerb")
class BlockActionVerb(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    READ = ...
    WRITE = ...
    ACTION = ...
    DELETE = ...
    UNRECOGNIZED = ...

@pulumi.type_token("azure-native:providerhub:CapacityPolicy")
class CapacityPolicy(_builtins.str, Enum):
    DEFAULT = ...
    RESTRICTED = ...

@pulumi.type_token(...)
class CommonApiVersionsMergeMode(_builtins.str, Enum):
    MERGE = ...
    OVERWRITE = ...

@pulumi.type_token(...)
class CrossTenantTokenValidation(_builtins.str, Enum):
    ENSURE_SECURE_VALIDATION = ...
    PASSTHROUGH_INSECURE_TOKEN = ...

@pulumi.type_token("azure-native:providerhub:DataBoundary")
class DataBoundary(_builtins.str, Enum):
    NOT_DEFINED = ...
    GLOBAL_ = ...
    EU = ...
    US = ...

@pulumi.type_token("azure-native:providerhub:EndpointType")
class EndpointType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CANARY = ...
    PRODUCTION = ...
    TEST_IN_PRODUCTION = ...

@pulumi.type_token("azure-native:providerhub:EndpointTypeResourceType")
class EndpointTypeResourceType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CANARY = ...
    PRODUCTION = ...
    TEST_IN_PRODUCTION = ...

@pulumi.type_token("azure-native:providerhub:ExpeditedRolloutIntent")
class ExpeditedRolloutIntent(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    HOTFIX = ...

@pulumi.type_token("azure-native:providerhub:ExtendedLocationType")
class ExtendedLocationType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CUSTOM_LOCATION = ...
    EDGE_ZONE = ...
    ARC_ZONE = ...

@pulumi.type_token("azure-native:providerhub:ExtensionCategory")
class ExtensionCategory(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    RESOURCE_CREATION_VALIDATE = ...
    RESOURCE_CREATION_BEGIN = ...
    RESOURCE_CREATION_COMPLETED = ...
    RESOURCE_READ_VALIDATE = ...
    RESOURCE_READ_BEGIN = ...
    RESOURCE_PATCH_VALIDATE = ...
    RESOURCE_PATCH_COMPLETED = ...
    RESOURCE_DELETION_VALIDATE = ...
    RESOURCE_DELETION_BEGIN = ...
    RESOURCE_DELETION_COMPLETED = ...
    RESOURCE_POST_ACTION = ...
    SUBSCRIPTION_LIFECYCLE_NOTIFICATION = ...
    RESOURCE_PATCH_BEGIN = ...
    RESOURCE_MOVE_BEGIN = ...
    RESOURCE_MOVE_COMPLETED = ...
    BEST_MATCH_OPERATION_BEGIN = ...
    SUBSCRIPTION_LIFECYCLE_NOTIFICATION_DELETION = ...

@pulumi.type_token("azure-native:providerhub:ExtensionOptionType")
class ExtensionOptionType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    DO_NOT_MERGE_EXISTING_READ_ONLY_AND_SECRET_PROPERTIES = ...
    INCLUDE_INTERNAL_METADATA = ...

@pulumi.type_token("azure-native:providerhub:FeaturesPolicy")
class FeaturesPolicy(_builtins.str, Enum):
    ANY = ...
    ALL = ...

@pulumi.type_token("azure-native:providerhub:FilterOption")
class FilterOption(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ENABLE_SUBSCRIPTION_FILTER_ON_TENANT = ...

@pulumi.type_token("azure-native:providerhub:FrontdoorRequestMode")
class FrontdoorRequestMode(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    USE_MANIFEST = ...

@pulumi.type_token("azure-native:providerhub:IdentityManagementTypes")
class IdentityManagementTypes(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    ACTOR = ...
    DELEGATED_RESOURCE_IDENTITY = ...

@pulumi.type_token("azure-native:providerhub:Intent")
class Intent(_builtins.str, Enum):
    NO_T_SPECIFIED = ...
    LO_W_PRIVILEGE = ...
    DEFERRE_D_ACCES_S_CHECK = ...
    R_P_CONTRACT = ...

@pulumi.type_token("azure-native:providerhub:LegacyOperation")
class LegacyOperation(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CREATE = ...
    DELETE = ...
    WAITING = ...
    AZURE_ASYNC_OPERATION_WAITING = ...
    RESOURCE_CACHE_WAITING = ...
    ACTION = ...
    READ = ...
    EVALUATE_DEPLOYMENT_OUTPUT = ...
    DEPLOYMENT_CLEANUP = ...

@pulumi.type_token("azure-native:providerhub:LinkedAction")
class LinkedAction(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    BLOCKED = ...
    VALIDATE = ...
    ENABLED = ...

@pulumi.type_token("azure-native:providerhub:LinkedOperation")
class LinkedOperation(_builtins.str, Enum):
    NONE = ...
    CROSS_RESOURCE_GROUP_RESOURCE_MOVE = ...
    CROSS_SUBSCRIPTION_RESOURCE_MOVE = ...

@pulumi.type_token("azure-native:providerhub:LoggingDetails")
class LoggingDetails(_builtins.str, Enum):
    NONE = ...
    BODY = ...

@pulumi.type_token("azure-native:providerhub:LoggingDirections")
class LoggingDirections(_builtins.str, Enum):
    NONE = ...
    REQUEST = ...
    RESPONSE = ...

@pulumi.type_token("azure-native:providerhub:MarketplaceType")
class MarketplaceType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ADD_ON = ...
    BYPASS = ...
    STORE = ...

@pulumi.type_token("azure-native:providerhub:MessageScope")
class MessageScope(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    REGISTERED_SUBSCRIPTIONS = ...

@pulumi.type_token("azure-native:providerhub:NotificationEndpointType")
class NotificationEndpointType(_builtins.str, Enum):
    WEBHOOK = ...
    EVENTHUB = ...

@pulumi.type_token("azure-native:providerhub:NotificationMode")
class NotificationMode(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    EVENT_HUB = ...
    WEB_HOOK = ...

@pulumi.type_token("azure-native:providerhub:NotificationOptions")
class NotificationOptions(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NONE = ...
    EMIT_SPENDING_LIMIT = ...

@pulumi.type_token("azure-native:providerhub:NotificationType")
class NotificationType(_builtins.str, Enum):
    UNSPECIFIED = ...
    SUBSCRIPTION_NOTIFICATION = ...

@pulumi.type_token("azure-native:providerhub:OptInHeaderType")
class OptInHeaderType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SIGNED_USER_TOKEN = ...
    CLIENT_GROUP_MEMBERSHIP = ...
    SIGNED_AUXILIARY_TOKENS = ...
    UNBOUNDED_CLIENT_GROUP_MEMBERSHIP = ...
    PRIVATE_LINK_ID = ...
    PRIVATE_LINK_RESOURCE_ID = ...
    MANAGEMENT_GROUP_ANCESTORS_ENCODED = ...
    PRIVATE_LINK_VNET_TRAFFIC_TAG = ...
    RESOURCE_GROUP_LOCATION = ...
    CLIENT_PRINCIPAL_NAME_ENCODED = ...
    MSI_RESOURCE_ID_ENCODED = ...

@pulumi.type_token("azure-native:providerhub:OptOutHeaderType")
class OptOutHeaderType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SYSTEM_DATA_CREATED_BY_LAST_MODIFIED_BY = ...

@pulumi.type_token("azure-native:providerhub:Policy")
class Policy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    SYNCHRONIZE_BEGIN_EXTENSION = ...

@pulumi.type_token("azure-native:providerhub:PolicyExecutionType")
class PolicyExecutionType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    EXECUTE_POLICIES = ...
    BYPASS_POLICIES = ...
    EXPECT_PARTIAL_PUT_REQUESTS = ...

@pulumi.type_token("azure-native:providerhub:PreflightOption")
class PreflightOption(_builtins.str, Enum):
    NONE = ...
    CONTINUE_DEPLOYMENT_ON_FAILURE = ...
    DEFAULT_VALIDATION_ONLY = ...

@pulumi.type_token("azure-native:providerhub:ProviderRegistrationKind")
class ProviderRegistrationKind(_builtins.str, Enum):
    MANAGED = ...
    HYBRID = ...
    DIRECT = ...

@pulumi.type_token("azure-native:providerhub:QuotaPolicy")
class QuotaPolicy(_builtins.str, Enum):
    DEFAULT = ...
    NONE = ...
    RESTRICTED = ...

@pulumi.type_token("azure-native:providerhub:Readiness")
class Readiness(_builtins.str, Enum):
    CLOSING_DOWN = ...
    DEPRECATED = ...
    GA = ...
    IN_DEVELOPMENT = ...
    INTERNAL_ONLY = ...
    PRIVATE_PREVIEW = ...
    PUBLIC_PREVIEW = ...
    REMOVED_FROM_ARM = ...
    RETIRED = ...

@pulumi.type_token("azure-native:providerhub:Regionality")
class Regionality(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    GLOBAL_ = ...
    REGIONAL = ...

@pulumi.type_token("azure-native:providerhub:ResourceAccessPolicy")
class ResourceAccessPolicy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ACIS_READ_ALLOWED = ...
    ACIS_ACTION_ALLOWED = ...

@pulumi.type_token("azure-native:providerhub:ResourceDeletionPolicy")
class ResourceDeletionPolicy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CASCADE_DELETE_ALL = ...
    CASCADE_DELETE_PROXY_ONLY_CHILDREN = ...

@pulumi.type_token(...)
class ResourceProviderCapabilitiesEffect(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ALLOW = ...
    DISALLOW = ...

@pulumi.type_token("azure-native:providerhub:ResourceProviderType")
class ResourceProviderType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    INTERNAL = ...
    EXTERNAL = ...
    HIDDEN = ...
    REGISTRATION_FREE = ...
    LEGACY_REGISTRATION_REQUIRED = ...
    TENANT_ONLY = ...
    AUTHORIZATION_FREE = ...

@pulumi.type_token("azure-native:providerhub:ResourceSubType")
class ResourceSubType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ASYNC_OPERATION = ...

@pulumi.type_token("azure-native:providerhub:ResourceTypeCategory")
class ResourceTypeCategory(_builtins.str, Enum):
    NONE = ...
    FREE_FORM = ...
    INTERNAL = ...
    PURE_PROXY = ...

@pulumi.type_token("azure-native:providerhub:ResourceTypeEndpointKind")
class ResourceTypeEndpointKind(_builtins.str, Enum):
    MANAGED = ...
    DIRECT = ...

@pulumi.type_token(...)
class ResourceTypeExtendedLocationPolicy(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ALL = ...

@pulumi.type_token(...)
class ResourceTypeRegistrationKind(_builtins.str, Enum):
    MANAGED = ...
    HYBRID = ...
    DIRECT = ...

@pulumi.type_token("azure-native:providerhub:ResourceValidation")
class ResourceValidation(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    RESERVED_WORDS = ...
    PROFANE_WORDS = ...

@pulumi.type_token("azure-native:providerhub:Role")
class Role(_builtins.str, Enum):
    SERVICE_OWNER = ...
    LIMITED_OWNER = ...

@pulumi.type_token("azure-native:providerhub:RoutingType")
class RoutingType(_builtins.str, Enum):
    DEFAULT = ...
    PROXY_ONLY = ...
    HOST_BASED = ...
    EXTENSION = ...
    TENANT = ...
    FANOUT = ...
    LOCATION_BASED = ...
    FAILOVER = ...
    CASCADE_EXTENSION = ...
    CHILD_FANOUT = ...
    CASCADE_AUTHORIZED_EXTENSION = ...
    BYPASS_ENDPOINT_SELECTION_OPTIMIZATION = ...
    LOCATION_MAPPING = ...
    SERVICE_FANOUT = ...

@pulumi.type_token(...)
class ServerFailureResponseMessageType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    OUTAGE_REPORTING = ...

@pulumi.type_token("azure-native:providerhub:ServiceClientOptionsType")
class ServiceClientOptionsType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    DISABLE_AUTOMATIC_DECOMPRESSION = ...

@pulumi.type_token("azure-native:providerhub:ServiceStatus")
class ServiceStatus(_builtins.str, Enum):
    ACTIVE = ...
    INACTIVE = ...

@pulumi.type_token("azure-native:providerhub:SignedRequestScope")
class SignedRequestScope(_builtins.str, Enum):
    RESOURCE_URI = ...
    ENDPOINT = ...

@pulumi.type_token("azure-native:providerhub:SkipNotifications")
class SkipNotifications(_builtins.str, Enum):
    UNSPECIFIED = ...
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:providerhub:SkuScaleType")
class SkuScaleType(_builtins.str, Enum):
    NONE = ...
    MANUAL = ...
    AUTOMATIC = ...

@pulumi.type_token(...)
class SubscriptionNotificationOperation(_builtins.str, Enum):
    NOT_DEFINED = ...
    DELETE_ALL_RESOURCES = ...
    SOFT_DELETE_ALL_RESOURCES = ...
    NO_OP = ...
    BILLING_CANCELLATION = ...
    UNDO_SOFT_DELETE = ...

@pulumi.type_token(...)
class SubscriptionReregistrationResult(_builtins.str, Enum):
    NOT_APPLICABLE = ...
    CONDITIONAL_UPDATE = ...
    FORCED_UPDATE = ...
    FAILED = ...

@pulumi.type_token("azure-native:providerhub:SubscriptionState")
class SubscriptionState(_builtins.str, Enum):
    NOT_DEFINED = ...
    ENABLED = ...
    WARNED = ...
    PAST_DUE = ...
    DISABLED = ...
    DELETED = ...

@pulumi.type_token(...)
class SubscriptionTransitioningState(_builtins.str, Enum):
    REGISTERED = ...
    UNREGISTERED = ...
    WARNED = ...
    SUSPENDED = ...
    DELETED = ...
    WARNED_TO_REGISTERED = ...
    WARNED_TO_SUSPENDED = ...
    WARNED_TO_DELETED = ...
    WARNED_TO_UNREGISTERED = ...
    SUSPENDED_TO_REGISTERED = ...
    SUSPENDED_TO_WARNED = ...
    SUSPENDED_TO_DELETED = ...
    SUSPENDED_TO_UNREGISTERED = ...

@pulumi.type_token("azure-native:providerhub:SupportedOperations")
class SupportedOperations(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    GET = ...
    DELETE = ...

@pulumi.type_token(...)
class TemplateDeploymentCapabilities(_builtins.str, Enum):
    DEFAULT = ...
    PREFLIGHT = ...

@pulumi.type_token(...)
class TemplateDeploymentPreflightNotifications(_builtins.str, Enum):
    NONE = ...
    UNREGISTERED_SUBSCRIPTIONS = ...

@pulumi.type_token(...)
class TemplateDeploymentPreflightOptions(_builtins.str, Enum):
    NONE = ...
    VALIDATION_REQUESTS = ...
    DEPLOYMENT_REQUESTS = ...
    TEST_ONLY = ...
    REGISTERED_ONLY = ...

@pulumi.type_token("azure-native:providerhub:ThrottlingMetricType")
class ThrottlingMetricType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    NUMBER_OF_REQUESTS = ...
    NUMBER_OF_RESOURCES = ...

@pulumi.type_token("azure-native:providerhub:TrafficRegionCategory")
class TrafficRegionCategory(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    CANARY = ...
    LOW_TRAFFIC = ...
    MEDIUM_TRAFFIC = ...
    HIGH_TRAFFIC = ...
    NONE = ...
    REST_OF_THE_WORLD_GROUP_ONE = ...
    REST_OF_THE_WORLD_GROUP_TWO = ...
