import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetCustomRolloutResult",
    "AwaitableGetCustomRolloutResult",
    "get_custom_rollout",
    "get_custom_rollout_output",
]

@pulumi.output_type
class GetCustomRolloutResult:
    def __init__(
        __self__,
        azure_api_version=...,
        id=...,
        name=...,
        properties=...,
        system_data=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> outputs.CustomRolloutPropertiesResponse: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetCustomRolloutResult(GetCustomRolloutResult):
    def __await__(self): ...

def get_custom_rollout(
    provider_namespace: Optional[_builtins.str] = ...,
    rollout_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetCustomRolloutResult: ...
def get_custom_rollout_output(
    provider_namespace: Optional[pulumi.Input[_builtins.str]] = ...,
    rollout_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetCustomRolloutResult]: ...
