

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ActionsRequired', 'CertificatePermissions', 'CreateMode', 'JsonWebKeyCurveName', 'JsonWebKeyOperation', 'JsonWebKeyType', 'KeyPermissions', 'KeyRotationPolicyActionType', 'ManagedHsmSkuFamily', 'ManagedHsmSkuName', 'ManagedServiceIdentityType', 'NetworkRuleAction', 'NetworkRuleBypassOptions', 'PrivateEndpointServiceConnectionStatus', 'PublicNetworkAccess', 'SecretPermissions', 'SkuFamily', 'SkuName', 'StoragePermissions']
@pulumi.type_token("azure-native:keyvault:ActionsRequired")
class ActionsRequired(_builtins.str, Enum):
    
    NONE = ...


@pulumi.type_token("azure-native:keyvault:CertificatePermissions")
class CertificatePermissions(_builtins.str, Enum):
    ALL = ...
    GET = ...
    LIST = ...
    DELETE = ...
    CREATE = ...
    IMPORT_ = ...
    UPDATE = ...
    MANAGECONTACTS = ...
    GETISSUERS = ...
    LISTISSUERS = ...
    SETISSUERS = ...
    DELETEISSUERS = ...
    MANAGEISSUERS = ...
    RECOVER = ...
    PURGE = ...
    BACKUP = ...
    RESTORE = ...


@pulumi.type_token("azure-native:keyvault:CreateMode")
class CreateMode(_builtins.str, Enum):
    
    RECOVER = ...
    DEFAULT = ...


@pulumi.type_token("azure-native:keyvault:JsonWebKeyCurveName")
class JsonWebKeyCurveName(_builtins.str, Enum):
    
    P_256 = ...
    P_384 = ...
    P_521 = ...
    P_256_K = ...


@pulumi.type_token("azure-native:keyvault:JsonWebKeyOperation")
class JsonWebKeyOperation(_builtins.str, Enum):
    
    ENCRYPT = ...
    DECRYPT = ...
    SIGN = ...
    VERIFY = ...
    WRAP_KEY = ...
    UNWRAP_KEY = ...
    IMPORT_ = ...
    RELEASE = ...


@pulumi.type_token("azure-native:keyvault:JsonWebKeyType")
class JsonWebKeyType(_builtins.str, Enum):
    
    EC = ...
    E_C_HSM = ...
    RSA = ...
    RS_A_HSM = ...


@pulumi.type_token("azure-native:keyvault:KeyPermissions")
class KeyPermissions(_builtins.str, Enum):
    ALL = ...
    ENCRYPT = ...
    DECRYPT = ...
    WRAP_KEY = ...
    UNWRAP_KEY = ...
    SIGN = ...
    VERIFY = ...
    GET = ...
    LIST = ...
    CREATE = ...
    UPDATE = ...
    IMPORT_ = ...
    DELETE = ...
    BACKUP = ...
    RESTORE = ...
    RECOVER = ...
    PURGE = ...
    RELEASE = ...
    ROTATE = ...
    GETROTATIONPOLICY = ...
    SETROTATIONPOLICY = ...


@pulumi.type_token("azure-native:keyvault:KeyRotationPolicyActionType")
class KeyRotationPolicyActionType(_builtins.str, Enum):
    
    ROTATE = ...
    NOTIFY = ...


@pulumi.type_token("azure-native:keyvault:ManagedHsmSkuFamily")
class ManagedHsmSkuFamily(_builtins.str, Enum):
    
    B = ...
    C = ...


@pulumi.type_token("azure-native:keyvault:ManagedHsmSkuName")
class ManagedHsmSkuName(_builtins.str, Enum):
    
    STANDARD_B1 = ...
    CUSTOM_B32 = ...
    CUSTOM_B6 = ...
    CUSTOM_C42 = ...
    CUSTOM_C10 = ...


@pulumi.type_token("azure-native:keyvault:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:keyvault:NetworkRuleAction")
class NetworkRuleAction(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:keyvault:NetworkRuleBypassOptions")
class NetworkRuleBypassOptions(_builtins.str, Enum):
    
    AZURE_SERVICES = ...
    NONE = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:keyvault:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:keyvault:SecretPermissions")
class SecretPermissions(_builtins.str, Enum):
    ALL = ...
    GET = ...
    LIST = ...
    SET = ...
    DELETE = ...
    BACKUP = ...
    RESTORE = ...
    RECOVER = ...
    PURGE = ...


@pulumi.type_token("azure-native:keyvault:SkuFamily")
class SkuFamily(_builtins.str, Enum):
    
    A = ...


@pulumi.type_token("azure-native:keyvault:SkuName")
class SkuName(_builtins.str, Enum):
    
    STANDARD = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:keyvault:StoragePermissions")
class StoragePermissions(_builtins.str, Enum):
    ALL = ...
    GET = ...
    LIST = ...
    DELETE = ...
    SET = ...
    UPDATE = ...
    REGENERATEKEY = ...
    RECOVER = ...
    PURGE = ...
    BACKUP = ...
    RESTORE = ...
    SETSAS = ...
    LISTSAS = ...
    GETSAS = ...
    DELETESAS = ...


