

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ManagedIdentityTypes', 'MonitoringStatus', 'Operation', 'Status', 'TagAction']
@pulumi.type_token("azure-native:datadog:ManagedIdentityTypes")
class ManagedIdentityTypes(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


@pulumi.type_token("azure-native:datadog:MonitoringStatus")
class MonitoringStatus(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:datadog:Operation")
class Operation(_builtins.str, Enum):
    
    ADD_BEGIN = ...
    ADD_COMPLETE = ...
    DELETE_BEGIN = ...
    DELETE_COMPLETE = ...
    ACTIVE = ...


@pulumi.type_token("azure-native:datadog:Status")
class Status(_builtins.str, Enum):
    
    IN_PROGRESS = ...
    ACTIVE = ...
    FAILED = ...
    DELETING = ...


@pulumi.type_token("azure-native:datadog:TagAction")
class TagAction(_builtins.str, Enum):
    
    INCLUDE = ...
    EXCLUDE = ...


