import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListMonitorApiKeysResult",
    "AwaitableListMonitorApiKeysResult",
    "list_monitor_api_keys",
    "list_monitor_api_keys_output",
]

@pulumi.output_type
class ListMonitorApiKeysResult:
    def __init__(__self__, next_link=..., value=...) -> None: ...
    @_builtins.property
    @pulumi.getter(name="nextLink")
    def next_link(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[Sequence[outputs.DatadogApiKeyResponse]]: ...

class AwaitableListMonitorApiKeysResult(ListMonitorApiKeysResult):
    def __await__(self): ...

def list_monitor_api_keys(
    monitor_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListMonitorApiKeysResult: ...
def list_monitor_api_keys_output(
    monitor_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListMonitorApiKeysResult]: ...
