import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union, overload
from . import outputs
from ._enums import *
from ._inputs import *

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = ["GuestAgentArgs", "GuestAgent"]

@pulumi.input_type
class GuestAgentArgs:
    def __init__(
        __self__,
        *,
        resource_group_name: pulumi.Input[_builtins.str],
        virtual_machine_name: pulumi.Input[_builtins.str],
        credentials: Optional[pulumi.Input[GuestCredentialArgs]] = ...,
        guest_agent_name: Optional[pulumi.Input[_builtins.str]] = ...,
        http_proxy_config: Optional[pulumi.Input[HttpProxyConfigurationArgs]] = ...,
        provisioning_action: Optional[
            pulumi.Input[Union[_builtins.str, ProvisioningAction]]
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="resourceGroupName")
    def resource_group_name(self) -> pulumi.Input[_builtins.str]: ...
    @resource_group_name.setter
    def resource_group_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter(name="virtualMachineName")
    def virtual_machine_name(self) -> pulumi.Input[_builtins.str]: ...
    @virtual_machine_name.setter
    def virtual_machine_name(self, value: pulumi.Input[_builtins.str]): ...
    @_builtins.property
    @pulumi.getter
    def credentials(self) -> Optional[pulumi.Input[GuestCredentialArgs]]: ...
    @credentials.setter
    def credentials(self, value: Optional[pulumi.Input[GuestCredentialArgs]]): ...
    @_builtins.property
    @pulumi.getter(name="guestAgentName")
    def guest_agent_name(self) -> Optional[pulumi.Input[_builtins.str]]: ...
    @guest_agent_name.setter
    def guest_agent_name(self, value: Optional[pulumi.Input[_builtins.str]]): ...
    @_builtins.property
    @pulumi.getter(name="httpProxyConfig")
    def http_proxy_config(
        self,
    ) -> Optional[pulumi.Input[HttpProxyConfigurationArgs]]: ...
    @http_proxy_config.setter
    def http_proxy_config(
        self, value: Optional[pulumi.Input[HttpProxyConfigurationArgs]]
    ): ...
    @_builtins.property
    @pulumi.getter(name="provisioningAction")
    def provisioning_action(
        self,
    ) -> Optional[pulumi.Input[Union[_builtins.str, ProvisioningAction]]]: ...
    @provisioning_action.setter
    def provisioning_action(
        self, value: Optional[pulumi.Input[Union[_builtins.str, ProvisioningAction]]]
    ): ...

@pulumi.type_token("azure-native:scvmm:GuestAgent")
class GuestAgent(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: Optional[pulumi.ResourceOptions] = ...,
        credentials: Optional[
            pulumi.Input[Union[GuestCredentialArgs, GuestCredentialArgsDict]]
        ] = ...,
        guest_agent_name: Optional[pulumi.Input[_builtins.str]] = ...,
        http_proxy_config: Optional[
            pulumi.Input[
                Union[HttpProxyConfigurationArgs, HttpProxyConfigurationArgsDict]
            ]
        ] = ...,
        provisioning_action: Optional[
            pulumi.Input[Union[_builtins.str, ProvisioningAction]]
        ] = ...,
        resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
        virtual_machine_name: Optional[pulumi.Input[_builtins.str]] = ...,
        __props__=...,
    ) -> None: ...
    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: GuestAgentArgs,
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> None: ...
    def __init__(__self__, resource_name: str, *args, **kwargs) -> None: ...
    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: Optional[pulumi.ResourceOptions] = ...,
    ) -> GuestAgent: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def credentials(
        self,
    ) -> pulumi.Output[Optional[outputs.GuestCredentialResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="customResourceName")
    def custom_resource_name(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="httpProxyConfig")
    def http_proxy_config(
        self,
    ) -> pulumi.Output[Optional[outputs.HttpProxyConfigurationResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="provisioningAction")
    def provisioning_action(self) -> pulumi.Output[Optional[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> pulumi.Output[outputs.SystemDataResponse]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def uuid(self) -> pulumi.Output[_builtins.str]: ...
