import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AllocationState",
    "AnalyticalStorageSchemaType",
    "AuthenticationMethod",
    "AzureConnectionType",
    "BackupPolicyMigrationStatus",
    "BackupPolicyType",
    "BackupStorageRedundancy",
    "ClusterType",
    "CompositePathSortOrder",
    "ConflictResolutionMode",
    "ConnectorOffer",
    "ContinuousTier",
    "CreateMode",
    "DataType",
    "DatabaseAccountKind",
    "DatabaseAccountOfferType",
    "DedicatedGatewayType",
    "DefaultConsistencyLevel",
    "DefaultPriorityLevel",
    "DistanceFunction",
    "FleetspaceApiKind",
    "IndexKind",
    "IndexingMode",
    "ManagedCassandraProvisioningState",
    "ManagedCassandraResourceIdentityType",
    "MinimalTlsVersion",
    "MongoClusterCreateMode",
    "MongoRoleDefinitionType",
    "NetworkAclBypass",
    "NodeKind",
    "PartitionKind",
    "PublicNetworkAccess",
    "ResourceIdentityType",
    "RestoreMode",
    "RoleDefinitionType",
    "ServerVersion",
    "ServiceSize",
    "ServiceTier",
    "ServiceType",
    "SpatialType",
    "StorageLocationType",
    "TriggerOperation",
    "TriggerType",
    "VectorDataType",
    "VectorIndexType",
]

@pulumi.type_token("azure-native:cosmosdb:AllocationState")
class AllocationState(_builtins.str, Enum):
    ACTIVE = ...
    DEALLOCATED = ...

@pulumi.type_token("azure-native:cosmosdb:AnalyticalStorageSchemaType")
class AnalyticalStorageSchemaType(_builtins.str, Enum):
    WELL_DEFINED = ...
    FULL_FIDELITY = ...

@pulumi.type_token("azure-native:cosmosdb:AuthenticationMethod")
class AuthenticationMethod(_builtins.str, Enum):
    NONE = ...
    CASSANDRA = ...
    LDAP = ...

@pulumi.type_token("azure-native:cosmosdb:AzureConnectionType")
class AzureConnectionType(_builtins.str, Enum):
    NONE = ...
    VPN = ...

@pulumi.type_token("azure-native:cosmosdb:BackupPolicyMigrationStatus")
class BackupPolicyMigrationStatus(_builtins.str, Enum):
    INVALID = ...
    IN_PROGRESS = ...
    COMPLETED = ...
    FAILED = ...

@pulumi.type_token("azure-native:cosmosdb:BackupPolicyType")
class BackupPolicyType(_builtins.str, Enum):
    PERIODIC = ...
    CONTINUOUS = ...

@pulumi.type_token("azure-native:cosmosdb:BackupStorageRedundancy")
class BackupStorageRedundancy(_builtins.str, Enum):
    GEO = ...
    LOCAL = ...
    ZONE = ...

@pulumi.type_token("azure-native:cosmosdb:ClusterType")
class ClusterType(_builtins.str, Enum):
    PRODUCTION = ...
    NON_PRODUCTION = ...

@pulumi.type_token("azure-native:cosmosdb:CompositePathSortOrder")
class CompositePathSortOrder(_builtins.str, Enum):
    ASCENDING = ...
    DESCENDING = ...

@pulumi.type_token("azure-native:cosmosdb:ConflictResolutionMode")
class ConflictResolutionMode(_builtins.str, Enum):
    LAST_WRITER_WINS = ...
    CUSTOM = ...

@pulumi.type_token("azure-native:cosmosdb:ConnectorOffer")
class ConnectorOffer(_builtins.str, Enum):
    SMALL = ...

@pulumi.type_token("azure-native:cosmosdb:ContinuousTier")
class ContinuousTier(_builtins.str, Enum):
    CONTINUOUS7_DAYS = ...
    CONTINUOUS30_DAYS = ...

@pulumi.type_token("azure-native:cosmosdb:CreateMode")
class CreateMode(_builtins.str, Enum):
    DEFAULT = ...
    RESTORE = ...

@pulumi.type_token("azure-native:cosmosdb:DataType")
class DataType(_builtins.str, Enum):
    STRING = ...
    NUMBER = ...
    POINT = ...
    POLYGON = ...
    LINE_STRING = ...
    MULTI_POLYGON = ...

@pulumi.type_token("azure-native:cosmosdb:DatabaseAccountKind")
class DatabaseAccountKind(_builtins.str, Enum):
    GLOBAL_DOCUMENT_DB = ...
    MONGO_DB = ...
    PARSE = ...

@pulumi.type_token("azure-native:cosmosdb:DatabaseAccountOfferType")
class DatabaseAccountOfferType(_builtins.str, Enum):
    STANDARD = ...

@pulumi.type_token("azure-native:cosmosdb:DedicatedGatewayType")
class DedicatedGatewayType(_builtins.str, Enum):
    INTEGRATED_CACHE = ...
    DISTRIBUTED_QUERY = ...

@pulumi.type_token("azure-native:cosmosdb:DefaultConsistencyLevel")
class DefaultConsistencyLevel(_builtins.str, Enum):
    EVENTUAL = ...
    SESSION = ...
    BOUNDED_STALENESS = ...
    STRONG = ...
    CONSISTENT_PREFIX = ...

@pulumi.type_token("azure-native:cosmosdb:DefaultPriorityLevel")
class DefaultPriorityLevel(_builtins.str, Enum):
    HIGH = ...
    LOW = ...

@pulumi.type_token("azure-native:cosmosdb:DistanceFunction")
class DistanceFunction(_builtins.str, Enum):
    EUCLIDEAN = ...
    COSINE = ...
    DOTPRODUCT = ...

@pulumi.type_token("azure-native:cosmosdb:FleetspaceApiKind")
class FleetspaceApiKind(_builtins.str, Enum):
    NO_SQL = ...

@pulumi.type_token("azure-native:cosmosdb:IndexKind")
class IndexKind(_builtins.str, Enum):
    HASH = ...
    RANGE = ...
    SPATIAL = ...

@pulumi.type_token("azure-native:cosmosdb:IndexingMode")
class IndexingMode(_builtins.str, Enum):
    CONSISTENT = ...
    LAZY = ...
    NONE = ...

@pulumi.type_token(...)
class ManagedCassandraProvisioningState(_builtins.str, Enum):
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...

@pulumi.type_token(...)
class ManagedCassandraResourceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    NONE = ...

@pulumi.type_token("azure-native:cosmosdb:MinimalTlsVersion")
class MinimalTlsVersion(_builtins.str, Enum):
    TLS = ...
    TLS11 = ...
    TLS12 = ...

@pulumi.type_token("azure-native:cosmosdb:MongoClusterCreateMode")
class MongoClusterCreateMode(_builtins.str, Enum):
    DEFAULT = ...
    POINT_IN_TIME_RESTORE = ...

@pulumi.type_token("azure-native:cosmosdb:MongoRoleDefinitionType")
class MongoRoleDefinitionType(_builtins.str, Enum):
    BUILT_IN_ROLE = ...
    CUSTOM_ROLE = ...

@pulumi.type_token("azure-native:cosmosdb:NetworkAclBypass")
class NetworkAclBypass(_builtins.str, Enum):
    NONE = ...
    AZURE_SERVICES = ...

@pulumi.type_token("azure-native:cosmosdb:NodeKind")
class NodeKind(_builtins.str, Enum):
    SHARD = ...

@pulumi.type_token("azure-native:cosmosdb:PartitionKind")
class PartitionKind(_builtins.str, Enum):
    HASH = ...
    RANGE = ...
    MULTI_HASH = ...

@pulumi.type_token("azure-native:cosmosdb:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...

@pulumi.type_token("azure-native:cosmosdb:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...

@pulumi.type_token("azure-native:cosmosdb:RestoreMode")
class RestoreMode(_builtins.str, Enum):
    POINT_IN_TIME = ...

@pulumi.type_token("azure-native:cosmosdb:RoleDefinitionType")
class RoleDefinitionType(_builtins.str, Enum):
    BUILT_IN_ROLE = ...
    CUSTOM_ROLE = ...

@pulumi.type_token("azure-native:cosmosdb:ServerVersion")
class ServerVersion(_builtins.str, Enum):
    SERVER_VERSION_3_2 = ...
    SERVER_VERSION_3_6 = ...
    SERVER_VERSION_4_0 = ...
    SERVER_VERSION_4_2 = ...
    SERVER_VERSION_5_0 = ...
    SERVER_VERSION_6_0 = ...
    SERVER_VERSION_7_0 = ...

@pulumi.type_token("azure-native:cosmosdb:ServiceSize")
class ServiceSize(_builtins.str, Enum):
    COSMOS_D4S = ...
    COSMOS_D8S = ...
    COSMOS_D16S = ...

@pulumi.type_token("azure-native:cosmosdb:ServiceTier")
class ServiceTier(_builtins.str, Enum):
    GENERAL_PURPOSE = ...
    BUSINESS_CRITICAL = ...

@pulumi.type_token("azure-native:cosmosdb:ServiceType")
class ServiceType(_builtins.str, Enum):
    SQL_DEDICATED_GATEWAY = ...
    DATA_TRANSFER = ...
    GRAPH_API_COMPUTE = ...
    MATERIALIZED_VIEWS_BUILDER = ...

@pulumi.type_token("azure-native:cosmosdb:SpatialType")
class SpatialType(_builtins.str, Enum):
    POINT = ...
    LINE_STRING = ...
    POLYGON = ...
    MULTI_POLYGON = ...

@pulumi.type_token("azure-native:cosmosdb:StorageLocationType")
class StorageLocationType(_builtins.str, Enum):
    STORAGE_ACCOUNT = ...
    FABRIC_LAKEHOUSE = ...

@pulumi.type_token("azure-native:cosmosdb:TriggerOperation")
class TriggerOperation(_builtins.str, Enum):
    ALL = ...
    CREATE = ...
    UPDATE = ...
    DELETE = ...
    REPLACE = ...

@pulumi.type_token("azure-native:cosmosdb:TriggerType")
class TriggerType(_builtins.str, Enum):
    PRE = ...
    POST = ...

@pulumi.type_token("azure-native:cosmosdb:VectorDataType")
class VectorDataType(_builtins.str, Enum):
    FLOAT32 = ...
    UINT8 = ...
    INT8 = ...
    FLOAT16 = ...

@pulumi.type_token("azure-native:cosmosdb:VectorIndexType")
class VectorIndexType(_builtins.str, Enum):
    FLAT = ...
    DISK_ANN = ...
    QUANTIZED_FLAT = ...
