import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "CreateMode",
    "EntraPrincipalType",
    "HighAvailabilityMode",
    "IdentityProviderType",
    "PreviewFeature",
    "PrivateEndpointServiceConnectionStatus",
    "PublicNetworkAccess",
    "UserRole",
]

@pulumi.type_token("azure-native:mongocluster:CreateMode")
class CreateMode(_builtins.str, Enum):
    DEFAULT = ...
    POINT_IN_TIME_RESTORE = ...
    GEO_REPLICA = ...
    REPLICA = ...

@pulumi.type_token("azure-native:mongocluster:EntraPrincipalType")
class EntraPrincipalType(_builtins.str, Enum):
    USER = ...
    SERVICE_PRINCIPAL = ...

@pulumi.type_token("azure-native:mongocluster:HighAvailabilityMode")
class HighAvailabilityMode(_builtins.str, Enum):
    DISABLED = ...
    SAME_ZONE = ...
    ZONE_REDUNDANT_PREFERRED = ...

@pulumi.type_token("azure-native:mongocluster:IdentityProviderType")
class IdentityProviderType(_builtins.str, Enum):
    MICROSOFT_ENTRA_ID = ...

@pulumi.type_token("azure-native:mongocluster:PreviewFeature")
class PreviewFeature(_builtins.str, Enum):
    GEO_REPLICAS = ...

@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...

@pulumi.type_token("azure-native:mongocluster:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:mongocluster:UserRole")
class UserRole(_builtins.str, Enum):
    DATABASE_OWNER = ...
