import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AnalyticsConnectorDataDestinationType",
    "AnalyticsConnectorDataSourceType",
    "AnalyticsConnectorMappingType",
    "FhirResourceVersionPolicy",
    "FhirServiceKind",
    "FhirServiceVersion",
    "IotIdentityResolutionType",
    "Kind",
    "ManagedServiceIdentityType",
    "PrivateEndpointServiceConnectionStatus",
    "PublicNetworkAccess",
    "ServiceManagedIdentityType",
    "SmartDataActions",
]

@pulumi.type_token(...)
class AnalyticsConnectorDataDestinationType(_builtins.str, Enum):
    DATALAKE = ...

@pulumi.type_token(...)
class AnalyticsConnectorDataSourceType(_builtins.str, Enum):
    FHIRSERVICE = ...

@pulumi.type_token(...)
class AnalyticsConnectorMappingType(_builtins.str, Enum):
    FHIR_TO_PARQUET = ...

@pulumi.type_token(...)
class FhirResourceVersionPolicy(_builtins.str, Enum):
    NO_VERSION = ...
    VERSIONED = ...
    VERSIONED_UPDATE = ...

@pulumi.type_token("azure-native:healthcareapis:FhirServiceKind")
class FhirServiceKind(_builtins.str, Enum):
    FHIR_STU3 = ...
    FHIR_R4 = ...

@pulumi.type_token("azure-native:healthcareapis:FhirServiceVersion")
class FhirServiceVersion(_builtins.str, Enum):
    STU3 = ...
    R4 = ...

@pulumi.type_token(...)
class IotIdentityResolutionType(_builtins.str, Enum):
    CREATE = ...
    LOOKUP = ...

@pulumi.type_token("azure-native:healthcareapis:Kind")
class Kind(_builtins.str, Enum):
    FHIR = ...
    FHIR_STU3 = ...
    FHIR_R4 = ...

@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    NONE = ...

@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...

@pulumi.type_token("azure-native:healthcareapis:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class ServiceManagedIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:healthcareapis:SmartDataActions")
class SmartDataActions(_builtins.str, Enum):
    READ = ...
