import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AcceleratorManufacturer",
    "AcceleratorType",
    "AllocationStrategy",
    "ArchitectureType",
    "CachingTypes",
    "CapacityType",
    "ComponentName",
    "CpuManufacturer",
    "DeleteOptions",
    "DiffDiskOptions",
    "DiffDiskPlacement",
    "DiskControllerTypes",
    "DiskCreateOptionTypes",
    "DiskDeleteOptionTypes",
    "DiskDetachOptionTypes",
    "DomainNameLabelScopeTypes",
    "EvictionPolicy",
    "HyperVGeneration",
    "IPVersions",
    "LinuxPatchAssessmentMode",
    "LinuxVMGuestPatchAutomaticByPlatformRebootSetting",
    "LinuxVMGuestPatchMode",
    "LocalStorageDiskType",
    "ManagedServiceIdentityType",
    "Mode",
    "Modes",
    "NetworkApiVersion",
    "NetworkInterfaceAuxiliaryMode",
    "NetworkInterfaceAuxiliarySku",
    "OperatingSystemTypes",
    "PassName",
    "ProtocolTypes",
    "PublicIPAddressSkuName",
    "PublicIPAddressSkuTier",
    "PublicIPAllocationMethod",
    "SecurityEncryptionTypes",
    "SecurityTypes",
    "SettingNames",
    "StorageAccountTypes",
    "VMAttributeSupport",
    "VMCategory",
    "VirtualMachineType",
    "WindowsPatchAssessmentMode",
    ...,
    "WindowsVMGuestPatchMode",
    "ZoneDistributionStrategy",
]

@pulumi.type_token(...)
class AcceleratorManufacturer(_builtins.str, Enum):
    AMD = ...
    NVIDIA = ...
    XILINX = ...

@pulumi.type_token("azure-native:computebulkactions:AcceleratorType")
class AcceleratorType(_builtins.str, Enum):
    GPU = ...
    FPGA = ...

@pulumi.type_token("azure-native:computebulkactions:AllocationStrategy")
class AllocationStrategy(_builtins.str, Enum):
    LOWEST_PRICE = ...
    CAPACITY_OPTIMIZED = ...
    PRIORITIZED = ...

@pulumi.type_token("azure-native:computebulkactions:ArchitectureType")
class ArchitectureType(_builtins.str, Enum):
    ARM64 = ...
    X64 = ...

@pulumi.type_token("azure-native:computebulkactions:CachingTypes")
class CachingTypes(_builtins.str, Enum):
    NONE = ...
    READ_ONLY = ...
    READ_WRITE = ...

@pulumi.type_token("azure-native:computebulkactions:CapacityType")
class CapacityType(_builtins.str, Enum):
    VM = ...
    V_CPU = ...

@pulumi.type_token("azure-native:computebulkactions:ComponentName")
class ComponentName(_builtins.str, Enum):
    MICROSOFT_WINDOWS_SHELL_SETUP = ...

@pulumi.type_token("azure-native:computebulkactions:CpuManufacturer")
class CpuManufacturer(_builtins.str, Enum):
    INTEL = ...
    AMD = ...
    MICROSOFT = ...
    AMPERE = ...

@pulumi.type_token("azure-native:computebulkactions:DeleteOptions")
class DeleteOptions(_builtins.str, Enum):
    DELETE = ...
    DETACH = ...

@pulumi.type_token("azure-native:computebulkactions:DiffDiskOptions")
class DiffDiskOptions(_builtins.str, Enum):
    LOCAL = ...

@pulumi.type_token("azure-native:computebulkactions:DiffDiskPlacement")
class DiffDiskPlacement(_builtins.str, Enum):
    CACHE_DISK = ...
    RESOURCE_DISK = ...
    NVME_DISK = ...

@pulumi.type_token(...)
class DiskControllerTypes(_builtins.str, Enum):
    SCSI = ...
    NV_ME = ...

@pulumi.type_token(...)
class DiskCreateOptionTypes(_builtins.str, Enum):
    FROM_IMAGE = ...
    EMPTY = ...
    ATTACH = ...
    COPY = ...
    RESTORE = ...

@pulumi.type_token(...)
class DiskDeleteOptionTypes(_builtins.str, Enum):
    DELETE = ...
    DETACH = ...

@pulumi.type_token(...)
class DiskDetachOptionTypes(_builtins.str, Enum):
    FORCE_DETACH = ...

@pulumi.type_token(...)
class DomainNameLabelScopeTypes(_builtins.str, Enum):
    TENANT_REUSE = ...
    SUBSCRIPTION_REUSE = ...
    RESOURCE_GROUP_REUSE = ...
    NO_REUSE = ...

@pulumi.type_token("azure-native:computebulkactions:EvictionPolicy")
class EvictionPolicy(_builtins.str, Enum):
    DELETE = ...
    DEALLOCATE = ...

@pulumi.type_token("azure-native:computebulkactions:HyperVGeneration")
class HyperVGeneration(_builtins.str, Enum):
    GEN1 = ...
    GEN2 = ...

@pulumi.type_token("azure-native:computebulkactions:IPVersions")
class IPVersions(_builtins.str, Enum):
    I_PV4 = ...
    I_PV6 = ...

@pulumi.type_token(...)
class LinuxPatchAssessmentMode(_builtins.str, Enum):
    IMAGE_DEFAULT = ...
    AUTOMATIC_BY_PLATFORM = ...

@pulumi.type_token(...)
class LinuxVMGuestPatchAutomaticByPlatformRebootSetting(_builtins.str, Enum):
    UNKNOWN = ...
    IF_REQUIRED = ...
    NEVER = ...
    ALWAYS = ...

@pulumi.type_token(...)
class LinuxVMGuestPatchMode(_builtins.str, Enum):
    IMAGE_DEFAULT = ...
    AUTOMATIC_BY_PLATFORM = ...

@pulumi.type_token(...)
class LocalStorageDiskType(_builtins.str, Enum):
    HDD = ...
    SSD = ...

@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:computebulkactions:Mode")
class Mode(_builtins.str, Enum):
    AUDIT = ...
    ENFORCE = ...

@pulumi.type_token("azure-native:computebulkactions:Modes")
class Modes(_builtins.str, Enum):
    AUDIT = ...
    ENFORCE = ...
    DISABLED = ...

@pulumi.type_token("azure-native:computebulkactions:NetworkApiVersion")
class NetworkApiVersion(_builtins.str, Enum):
    NETWORK_API_VERSION_2020_11_01 = ...
    NETWORK_API_VERSION_2022_11_01 = ...

@pulumi.type_token(...)
class NetworkInterfaceAuxiliaryMode(_builtins.str, Enum):
    NONE = ...
    ACCELERATED_CONNECTIONS = ...
    FLOATING = ...

@pulumi.type_token(...)
class NetworkInterfaceAuxiliarySku(_builtins.str, Enum):
    NONE = ...
    A1 = ...
    A2 = ...
    A4 = ...
    A8 = ...

@pulumi.type_token(...)
class OperatingSystemTypes(_builtins.str, Enum):
    WINDOWS = ...
    LINUX = ...

@pulumi.type_token("azure-native:computebulkactions:PassName")
class PassName(_builtins.str, Enum):
    OOBE_SYSTEM = ...

@pulumi.type_token("azure-native:computebulkactions:ProtocolTypes")
class ProtocolTypes(_builtins.str, Enum):
    HTTP = ...
    HTTPS = ...

@pulumi.type_token(...)
class PublicIPAddressSkuName(_builtins.str, Enum):
    BASIC = ...
    STANDARD = ...

@pulumi.type_token(...)
class PublicIPAddressSkuTier(_builtins.str, Enum):
    REGIONAL = ...
    GLOBAL_ = ...

@pulumi.type_token(...)
class PublicIPAllocationMethod(_builtins.str, Enum):
    DYNAMIC = ...
    STATIC = ...

@pulumi.type_token(...)
class SecurityEncryptionTypes(_builtins.str, Enum):
    VM_GUEST_STATE_ONLY = ...
    DISK_WITH_VM_GUEST_STATE = ...
    NON_PERSISTED_TPM = ...

@pulumi.type_token("azure-native:computebulkactions:SecurityTypes")
class SecurityTypes(_builtins.str, Enum):
    TRUSTED_LAUNCH = ...
    CONFIDENTIAL_VM = ...

@pulumi.type_token("azure-native:computebulkactions:SettingNames")
class SettingNames(_builtins.str, Enum):
    AUTO_LOGON = ...
    FIRST_LOGON_COMMANDS = ...

@pulumi.type_token(...)
class StorageAccountTypes(_builtins.str, Enum):
    STANDARD_LRS = ...
    PREMIUM_LRS = ...
    STANDARD_SS_D_LRS = ...
    ULTRA_SS_D_LRS = ...
    PREMIUM_ZRS = ...
    STANDARD_SS_D_ZRS = ...
    PREMIUM_V2_LRS = ...

@pulumi.type_token("azure-native:computebulkactions:VMAttributeSupport")
class VMAttributeSupport(_builtins.str, Enum):
    EXCLUDED = ...
    INCLUDED = ...
    REQUIRED = ...

@pulumi.type_token("azure-native:computebulkactions:VMCategory")
class VMCategory(_builtins.str, Enum):
    GENERAL_PURPOSE = ...
    COMPUTE_OPTIMIZED = ...
    MEMORY_OPTIMIZED = ...
    STORAGE_OPTIMIZED = ...
    GPU_ACCELERATED = ...
    FPGA_ACCELERATED = ...
    HIGH_PERFORMANCE_COMPUTE = ...

@pulumi.type_token("azure-native:computebulkactions:VirtualMachineType")
class VirtualMachineType(_builtins.str, Enum):
    REGULAR = ...
    SPOT = ...

@pulumi.type_token(...)
class WindowsPatchAssessmentMode(_builtins.str, Enum):
    IMAGE_DEFAULT = ...
    AUTOMATIC_BY_PLATFORM = ...

@pulumi.type_token(...)
class WindowsVMGuestPatchAutomaticByPlatformRebootSetting(_builtins.str, Enum):
    UNKNOWN = ...
    IF_REQUIRED = ...
    NEVER = ...
    ALWAYS = ...

@pulumi.type_token(...)
class WindowsVMGuestPatchMode(_builtins.str, Enum):
    MANUAL = ...
    AUTOMATIC_BY_OS = ...
    AUTOMATIC_BY_PLATFORM = ...

@pulumi.type_token(...)
class ZoneDistributionStrategy(_builtins.str, Enum):
    BEST_EFFORT_SINGLE_ZONE = ...
    PRIORITIZED = ...
    BEST_EFFORT_BALANCED = ...
    STRICT_BALANCED = ...
