import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "BrokerMemoryProfile",
    "DataLakeDatabaseFormat",
    "DeltaTableFormatEnum",
    "ExtendedLocationType",
    "FabricPathType",
    "KafkaAcks",
    "KafkaMessageCompressionType",
    "KafkaPartitionStrategy",
    "KafkaSaslType",
    "MqttBridgeRemoteBrokerProtocol",
    "MqttBridgeRouteDirection",
    "MqttProtocol",
    "ResourceInfoDefinitionMethods",
    "RunMode",
    "ServiceType",
]

@pulumi.type_token("azure-native:iotoperationsmq:BrokerMemoryProfile")
class BrokerMemoryProfile(_builtins.str, Enum):
    TINY = ...
    LOW = ...
    MEDIUM = ...
    HIGH = ...

@pulumi.type_token(...)
class DataLakeDatabaseFormat(_builtins.str, Enum):
    DELTA = ...
    PARQUET = ...

@pulumi.type_token("azure-native:iotoperationsmq:DeltaTableFormatEnum")
class DeltaTableFormatEnum(_builtins.str, Enum):
    BOOLEAN = ...
    INT8 = ...
    INT16 = ...
    INT32 = ...
    U_INT8 = ...
    U_INT16 = ...
    U_INT32 = ...
    U_INT64 = ...
    FLOAT16 = ...
    FLOAT32 = ...
    FLOAT64 = ...
    DATE32 = ...
    DATE64 = ...
    BINARY = ...
    UTF8 = ...

@pulumi.type_token("azure-native:iotoperationsmq:ExtendedLocationType")
class ExtendedLocationType(_builtins.str, Enum):
    CUSTOM_LOCATION = ...

@pulumi.type_token("azure-native:iotoperationsmq:FabricPathType")
class FabricPathType(_builtins.str, Enum):
    FILES = ...
    TABLES = ...

@pulumi.type_token("azure-native:iotoperationsmq:KafkaAcks")
class KafkaAcks(_builtins.str, Enum):
    ZERO = ...
    ONE = ...
    ALL = ...

@pulumi.type_token(...)
class KafkaMessageCompressionType(_builtins.str, Enum):
    NONE = ...
    GZIP = ...
    SNAPPY = ...
    LZ4 = ...

@pulumi.type_token(...)
class KafkaPartitionStrategy(_builtins.str, Enum):
    DEFAULT = ...
    STATIC = ...
    TOPIC = ...
    PROPERTY = ...

@pulumi.type_token("azure-native:iotoperationsmq:KafkaSaslType")
class KafkaSaslType(_builtins.str, Enum):
    PLAIN = ...
    SCRAM_SHA256 = ...
    SCRAM_SHA512 = ...

@pulumi.type_token(...)
class MqttBridgeRemoteBrokerProtocol(_builtins.str, Enum):
    MQTT = ...
    WEB_SOCKET = ...

@pulumi.type_token(...)
class MqttBridgeRouteDirection(_builtins.str, Enum):
    REMOTE_TO_LOCAL = ...
    LOCAL_TO_REMOTE = ...

@pulumi.type_token("azure-native:iotoperationsmq:MqttProtocol")
class MqttProtocol(_builtins.str, Enum):
    V3 = ...
    V5 = ...

@pulumi.type_token(...)
class ResourceInfoDefinitionMethods(_builtins.str, Enum):
    CONNECT = ...
    PUBLISH = ...
    SUBSCRIBE = ...

@pulumi.type_token("azure-native:iotoperationsmq:RunMode")
class RunMode(_builtins.str, Enum):
    AUTO = ...
    DISTRIBUTED = ...

@pulumi.type_token("azure-native:iotoperationsmq:ServiceType")
class ServiceType(_builtins.str, Enum):
    CLUSTER_IP = ...
    LOAD_BALANCER = ...
    NODE_PORT = ...
