import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["Edition", "ProvisioningState", "SupportStatus"]

@pulumi.type_token("azure-native:mysqldiscovery:Edition")
class Edition(_builtins.str, Enum):
    COMMUNITY = ...
    ENTERPRISE = ...

@pulumi.type_token("azure-native:mysqldiscovery:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    UNKNOWN = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    CREATING = ...
    DELETING = ...
    UPDATING = ...

@pulumi.type_token("azure-native:mysqldiscovery:SupportStatus")
class SupportStatus(_builtins.str, Enum):
    OUT_OF_SUPPORT = ...
    EXTENDED = ...
    MAINSTREAM = ...
