import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AdministratorType",
    "AlwaysEncryptedEnclaveType",
    "AuthMetadataLookupModes",
    "AutoExecuteStatus",
    "AvailabilityZoneType",
    "BackupStorageAccessTier",
    "BackupStorageRedundancy",
    "BlobAuditingPolicyState",
    "CatalogCollationType",
    "ClientClassificationSource",
    "CreateMode",
    "DataMaskingState",
    "DatabaseIdentityType",
    "DatabaseLicenseType",
    "DatabaseReadScale",
    "DayOfWeek",
    "ElasticPoolLicenseType",
    "FailoverGroupDatabasesSecondaryType",
    "FailoverModeType",
    "FreeLimitExhaustionBehavior",
    "GeoBackupPolicyState",
    "HybridSecondaryUsage",
    "IdentityType",
    "InstancePoolLicenseType",
    "JobAgentIdentityType",
    "JobScheduleType",
    "JobStepActionSource",
    "JobStepActionType",
    "JobStepOutputType",
    "JobTargetGroupMembershipType",
    "JobTargetType",
    "LinkRole",
    "ManagedDatabaseCreateMode",
    "ManagedInstanceAdministratorType",
    "ManagedInstanceDatabaseFormat",
    "ManagedInstanceLicenseType",
    "ManagedInstanceProxyOverride",
    "ManagedServerCreateMode",
    "MinimalTlsVersion",
    "PricingModel",
    "PrincipalType",
    "PrivateLinkServiceConnectionStateStatus",
    "ReadOnlyEndpointFailoverPolicy",
    "ReadWriteEndpointFailoverPolicy",
    "ReplicationLinkType",
    "ReplicationModeType",
    "SampleName",
    "SecondaryInstanceType",
    "SecondaryType",
    "SecurityAlertPolicyEmailAccountAdmins",
    "SecurityAlertPolicyState",
    "SecurityAlertPolicyUseServerDefault",
    "SecurityAlertsPolicyState",
    "SeedingModeType",
    "SensitivityLabelRank",
    "ServerKeyType",
    "ServerNetworkAccessFlag",
    "ServerPublicNetworkAccessFlag",
    "ServicePrincipalType",
    "SqlVulnerabilityAssessmentState",
    "SyncConflictResolutionPolicy",
    "SyncDirection",
    "SyncMemberDbType",
    "TransparentDataEncryptionState",
    "TrustScope",
]

@pulumi.type_token("azure-native:sql:AdministratorType")
class AdministratorType(_builtins.str, Enum):
    ACTIVE_DIRECTORY = ...

@pulumi.type_token("azure-native:sql:AlwaysEncryptedEnclaveType")
class AlwaysEncryptedEnclaveType(_builtins.str, Enum):
    DEFAULT = ...
    VBS = ...

@pulumi.type_token("azure-native:sql:AuthMetadataLookupModes")
class AuthMetadataLookupModes(_builtins.str, Enum):
    AZURE_AD = ...
    PAIRED = ...
    WINDOWS = ...

@pulumi.type_token("azure-native:sql:AutoExecuteStatus")
class AutoExecuteStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    DEFAULT = ...

@pulumi.type_token("azure-native:sql:AvailabilityZoneType")
class AvailabilityZoneType(_builtins.str, Enum):
    NO_PREFERENCE = ...
    ONE = ...
    TWO = ...
    THREE = ...

@pulumi.type_token("azure-native:sql:BackupStorageAccessTier")
class BackupStorageAccessTier(_builtins.str, Enum):
    HOT = ...
    ARCHIVE = ...

@pulumi.type_token("azure-native:sql:BackupStorageRedundancy")
class BackupStorageRedundancy(_builtins.str, Enum):
    GEO = ...
    LOCAL = ...
    ZONE = ...
    GEO_ZONE = ...

@pulumi.type_token("azure-native:sql:BlobAuditingPolicyState")
class BlobAuditingPolicyState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:CatalogCollationType")
class CatalogCollationType(_builtins.str, Enum):
    DATABAS_E_DEFAULT = ...
    SQ_L_LATIN1_GENERAL_CP1_C_I_AS = ...

@pulumi.type_token("azure-native:sql:ClientClassificationSource")
class ClientClassificationSource(_builtins.str, Enum):
    NONE = ...
    NATIVE = ...
    RECOMMENDED = ...
    MIP = ...

@pulumi.type_token("azure-native:sql:CreateMode")
class CreateMode(_builtins.str, Enum):
    DEFAULT = ...
    COPY = ...
    SECONDARY = ...
    POINT_IN_TIME_RESTORE = ...
    RESTORE = ...
    RECOVERY = ...
    RESTORE_EXTERNAL_BACKUP = ...
    RESTORE_EXTERNAL_BACKUP_SECONDARY = ...
    RESTORE_LONG_TERM_RETENTION_BACKUP = ...
    ONLINE_SECONDARY = ...

@pulumi.type_token("azure-native:sql:DataMaskingState")
class DataMaskingState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:DatabaseIdentityType")
class DatabaseIdentityType(_builtins.str, Enum):
    NONE = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:sql:DatabaseLicenseType")
class DatabaseLicenseType(_builtins.str, Enum):
    LICENSE_INCLUDED = ...
    BASE_PRICE = ...

@pulumi.type_token("azure-native:sql:DatabaseReadScale")
class DatabaseReadScale(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...

@pulumi.type_token("azure-native:sql:ElasticPoolLicenseType")
class ElasticPoolLicenseType(_builtins.str, Enum):
    LICENSE_INCLUDED = ...
    BASE_PRICE = ...

@pulumi.type_token(...)
class FailoverGroupDatabasesSecondaryType(_builtins.str, Enum):
    GEO = ...
    STANDBY = ...

@pulumi.type_token("azure-native:sql:FailoverModeType")
class FailoverModeType(_builtins.str, Enum):
    NONE = ...
    MANUAL = ...

@pulumi.type_token("azure-native:sql:FreeLimitExhaustionBehavior")
class FreeLimitExhaustionBehavior(_builtins.str, Enum):
    AUTO_PAUSE = ...
    BILL_OVER_USAGE = ...

@pulumi.type_token("azure-native:sql:GeoBackupPolicyState")
class GeoBackupPolicyState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:HybridSecondaryUsage")
class HybridSecondaryUsage(_builtins.str, Enum):
    ACTIVE = ...
    PASSIVE = ...

@pulumi.type_token("azure-native:sql:IdentityType")
class IdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:sql:InstancePoolLicenseType")
class InstancePoolLicenseType(_builtins.str, Enum):
    LICENSE_INCLUDED = ...
    BASE_PRICE = ...

@pulumi.type_token("azure-native:sql:JobAgentIdentityType")
class JobAgentIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:sql:JobScheduleType")
class JobScheduleType(_builtins.str, Enum):
    ONCE = ...
    RECURRING = ...

@pulumi.type_token("azure-native:sql:JobStepActionSource")
class JobStepActionSource(_builtins.str, Enum):
    INLINE = ...

@pulumi.type_token("azure-native:sql:JobStepActionType")
class JobStepActionType(_builtins.str, Enum):
    T_SQL = ...

@pulumi.type_token("azure-native:sql:JobStepOutputType")
class JobStepOutputType(_builtins.str, Enum):
    SQL_DATABASE = ...

@pulumi.type_token("azure-native:sql:JobTargetGroupMembershipType")
class JobTargetGroupMembershipType(_builtins.str, Enum):
    INCLUDE = ...
    EXCLUDE = ...

@pulumi.type_token("azure-native:sql:JobTargetType")
class JobTargetType(_builtins.str, Enum):
    TARGET_GROUP = ...
    SQL_DATABASE = ...
    SQL_ELASTIC_POOL = ...
    SQL_SHARD_MAP = ...
    SQL_SERVER = ...

@pulumi.type_token("azure-native:sql:LinkRole")
class LinkRole(_builtins.str, Enum):
    PRIMARY = ...
    SECONDARY = ...

@pulumi.type_token("azure-native:sql:ManagedDatabaseCreateMode")
class ManagedDatabaseCreateMode(_builtins.str, Enum):
    DEFAULT = ...
    RESTORE_EXTERNAL_BACKUP = ...
    POINT_IN_TIME_RESTORE = ...
    RECOVERY = ...
    RESTORE_LONG_TERM_RETENTION_BACKUP = ...

@pulumi.type_token("azure-native:sql:ManagedInstanceAdministratorType")
class ManagedInstanceAdministratorType(_builtins.str, Enum):
    ACTIVE_DIRECTORY = ...

@pulumi.type_token("azure-native:sql:ManagedInstanceDatabaseFormat")
class ManagedInstanceDatabaseFormat(_builtins.str, Enum):
    ALWAYS_UP_TO_DATE = ...
    SQL_SERVER2022 = ...

@pulumi.type_token("azure-native:sql:ManagedInstanceLicenseType")
class ManagedInstanceLicenseType(_builtins.str, Enum):
    LICENSE_INCLUDED = ...
    BASE_PRICE = ...

@pulumi.type_token("azure-native:sql:ManagedInstanceProxyOverride")
class ManagedInstanceProxyOverride(_builtins.str, Enum):
    PROXY = ...
    REDIRECT = ...
    DEFAULT = ...

@pulumi.type_token("azure-native:sql:ManagedServerCreateMode")
class ManagedServerCreateMode(_builtins.str, Enum):
    DEFAULT = ...
    POINT_IN_TIME_RESTORE = ...

@pulumi.type_token("azure-native:sql:MinimalTlsVersion")
class MinimalTlsVersion(_builtins.str, Enum):
    NONE = ...
    MINIMAL_TLS_VERSION_1_0 = ...
    MINIMAL_TLS_VERSION_1_1 = ...
    MINIMAL_TLS_VERSION_1_2 = ...
    MINIMAL_TLS_VERSION_1_3 = ...

@pulumi.type_token("azure-native:sql:PricingModel")
class PricingModel(_builtins.str, Enum):
    REGULAR = ...
    FREEMIUM = ...

@pulumi.type_token("azure-native:sql:PrincipalType")
class PrincipalType(_builtins.str, Enum):
    USER = ...
    GROUP = ...
    APPLICATION = ...

@pulumi.type_token(...)
class PrivateLinkServiceConnectionStateStatus(_builtins.str, Enum):
    APPROVED = ...
    PENDING = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:sql:ReadOnlyEndpointFailoverPolicy")
class ReadOnlyEndpointFailoverPolicy(_builtins.str, Enum):
    DISABLED = ...
    ENABLED = ...

@pulumi.type_token("azure-native:sql:ReadWriteEndpointFailoverPolicy")
class ReadWriteEndpointFailoverPolicy(_builtins.str, Enum):
    MANUAL = ...
    AUTOMATIC = ...

@pulumi.type_token("azure-native:sql:ReplicationLinkType")
class ReplicationLinkType(_builtins.str, Enum):
    GEO = ...
    NAMED = ...
    STANDBY = ...

@pulumi.type_token("azure-native:sql:ReplicationModeType")
class ReplicationModeType(_builtins.str, Enum):
    ASYNC_ = ...
    SYNC = ...

@pulumi.type_token("azure-native:sql:SampleName")
class SampleName(_builtins.str, Enum):
    ADVENTURE_WORKS_LT = ...
    WIDE_WORLD_IMPORTERS_STD = ...
    WIDE_WORLD_IMPORTERS_FULL = ...

@pulumi.type_token("azure-native:sql:SecondaryInstanceType")
class SecondaryInstanceType(_builtins.str, Enum):
    GEO = ...
    STANDBY = ...

@pulumi.type_token("azure-native:sql:SecondaryType")
class SecondaryType(_builtins.str, Enum):
    GEO = ...
    NAMED = ...
    STANDBY = ...

@pulumi.type_token(...)
class SecurityAlertPolicyEmailAccountAdmins(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:SecurityAlertPolicyState")
class SecurityAlertPolicyState(_builtins.str, Enum):
    NEW = ...
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class SecurityAlertPolicyUseServerDefault(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:SecurityAlertsPolicyState")
class SecurityAlertsPolicyState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:SeedingModeType")
class SeedingModeType(_builtins.str, Enum):
    AUTOMATIC = ...
    MANUAL = ...

@pulumi.type_token("azure-native:sql:SensitivityLabelRank")
class SensitivityLabelRank(_builtins.str, Enum):
    NONE = ...
    LOW = ...
    MEDIUM = ...
    HIGH = ...
    CRITICAL = ...

@pulumi.type_token("azure-native:sql:ServerKeyType")
class ServerKeyType(_builtins.str, Enum):
    SERVICE_MANAGED = ...
    AZURE_KEY_VAULT = ...

@pulumi.type_token("azure-native:sql:ServerNetworkAccessFlag")
class ServerNetworkAccessFlag(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:ServerPublicNetworkAccessFlag")
class ServerPublicNetworkAccessFlag(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...

@pulumi.type_token("azure-native:sql:ServicePrincipalType")
class ServicePrincipalType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:sql:SqlVulnerabilityAssessmentState")
class SqlVulnerabilityAssessmentState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:SyncConflictResolutionPolicy")
class SyncConflictResolutionPolicy(_builtins.str, Enum):
    HUB_WIN = ...
    MEMBER_WIN = ...

@pulumi.type_token("azure-native:sql:SyncDirection")
class SyncDirection(_builtins.str, Enum):
    BIDIRECTIONAL = ...
    ONE_WAY_MEMBER_TO_HUB = ...
    ONE_WAY_HUB_TO_MEMBER = ...

@pulumi.type_token("azure-native:sql:SyncMemberDbType")
class SyncMemberDbType(_builtins.str, Enum):
    AZURE_SQL_DATABASE = ...
    SQL_SERVER_DATABASE = ...

@pulumi.type_token("azure-native:sql:TransparentDataEncryptionState")
class TransparentDataEncryptionState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:sql:TrustScope")
class TrustScope(_builtins.str, Enum):
    GLOBAL_TRANSACTIONS = ...
    SERVICE_BROKER = ...
