import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetDatabaseResult",
    "AwaitableGetDatabaseResult",
    "get_database",
    "get_database_output",
]

@pulumi.output_type
class GetDatabaseResult:
    def __init__(
        __self__,
        auto_pause_delay=...,
        availability_zone=...,
        azure_api_version=...,
        catalog_collation=...,
        collation=...,
        creation_date=...,
        current_backup_storage_redundancy=...,
        current_service_objective_name=...,
        current_sku=...,
        database_id=...,
        default_secondary_location=...,
        earliest_restore_date=...,
        elastic_pool_id=...,
        encryption_protector=...,
        encryption_protector_auto_rotation=...,
        failover_group_id=...,
        federated_client_id=...,
        free_limit_exhaustion_behavior=...,
        high_availability_replica_count=...,
        id=...,
        identity=...,
        is_infra_encryption_enabled=...,
        is_ledger_on=...,
        keys=...,
        kind=...,
        license_type=...,
        location=...,
        maintenance_configuration_id=...,
        managed_by=...,
        manual_cutover=...,
        max_log_size_bytes=...,
        max_size_bytes=...,
        min_capacity=...,
        name=...,
        paused_date=...,
        perform_cutover=...,
        preferred_enclave_type=...,
        read_scale=...,
        requested_backup_storage_redundancy=...,
        requested_service_objective_name=...,
        resumed_date=...,
        secondary_type=...,
        sku=...,
        status=...,
        tags=...,
        type=...,
        use_free_limit=...,
        zone_redundant=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="autoPauseDelay")
    def auto_pause_delay(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter(name="availabilityZone")
    def availability_zone(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="catalogCollation")
    def catalog_collation(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def collation(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="creationDate")
    def creation_date(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="currentBackupStorageRedundancy")
    def current_backup_storage_redundancy(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="currentServiceObjectiveName")
    def current_service_objective_name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="currentSku")
    def current_sku(self) -> outputs.SkuResponse: ...
    @_builtins.property
    @pulumi.getter(name="databaseId")
    def database_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="defaultSecondaryLocation")
    def default_secondary_location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="earliestRestoreDate")
    def earliest_restore_date(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="elasticPoolId")
    def elastic_pool_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="encryptionProtector")
    def encryption_protector(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="encryptionProtectorAutoRotation")
    def encryption_protector_auto_rotation(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="failoverGroupId")
    def failover_group_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="federatedClientId")
    def federated_client_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="freeLimitExhaustionBehavior")
    def free_limit_exhaustion_behavior(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="highAvailabilityReplicaCount")
    def high_availability_replica_count(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[outputs.DatabaseIdentityResponse]: ...
    @_builtins.property
    @pulumi.getter(name="isInfraEncryptionEnabled")
    def is_infra_encryption_enabled(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="isLedgerOn")
    def is_ledger_on(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter
    def keys(self) -> Optional[Mapping[str, outputs.DatabaseKeyResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def kind(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="licenseType")
    def license_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="maintenanceConfigurationId")
    def maintenance_configuration_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="managedBy")
    def managed_by(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="manualCutover")
    def manual_cutover(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="maxLogSizeBytes")
    def max_log_size_bytes(self) -> _builtins.float: ...
    @_builtins.property
    @pulumi.getter(name="maxSizeBytes")
    def max_size_bytes(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter(name="minCapacity")
    def min_capacity(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="pausedDate")
    def paused_date(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="performCutover")
    def perform_cutover(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="preferredEnclaveType")
    def preferred_enclave_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="readScale")
    def read_scale(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="requestedBackupStorageRedundancy")
    def requested_backup_storage_redundancy(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="requestedServiceObjectiveName")
    def requested_service_objective_name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="resumedDate")
    def resumed_date(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="secondaryType")
    def secondary_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def sku(self) -> Optional[outputs.SkuResponse]: ...
    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="useFreeLimit")
    def use_free_limit(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="zoneRedundant")
    def zone_redundant(self) -> Optional[_builtins.bool]: ...

class AwaitableGetDatabaseResult(GetDatabaseResult):
    def __await__(self): ...

def get_database(
    database_name: Optional[_builtins.str] = ...,
    expand: Optional[_builtins.str] = ...,
    filter: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    server_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetDatabaseResult: ...
def get_database_output(
    database_name: Optional[pulumi.Input[_builtins.str]] = ...,
    expand: Optional[pulumi.Input[Optional[_builtins.str]]] = ...,
    filter: Optional[pulumi.Input[Optional[_builtins.str]]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    server_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetDatabaseResult]: ...
