import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetJobStepResult",
    "AwaitableGetJobStepResult",
    "get_job_step",
    "get_job_step_output",
]

@pulumi.output_type
class GetJobStepResult:
    def __init__(
        __self__,
        action=...,
        azure_api_version=...,
        credential=...,
        execution_options=...,
        id=...,
        name=...,
        output=...,
        step_id=...,
        target_group=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def action(self) -> outputs.JobStepActionResponse: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def credential(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="executionOptions")
    def execution_options(
        self,
    ) -> Optional[outputs.JobStepExecutionOptionsResponse]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def output(self) -> Optional[outputs.JobStepOutputResponse]: ...
    @_builtins.property
    @pulumi.getter(name="stepId")
    def step_id(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter(name="targetGroup")
    def target_group(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetJobStepResult(GetJobStepResult):
    def __await__(self): ...

def get_job_step(
    job_agent_name: Optional[_builtins.str] = ...,
    job_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    server_name: Optional[_builtins.str] = ...,
    step_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetJobStepResult: ...
def get_job_step_output(
    job_agent_name: Optional[pulumi.Input[_builtins.str]] = ...,
    job_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    server_name: Optional[pulumi.Input[_builtins.str]] = ...,
    step_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetJobStepResult]: ...
