import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetInstanceFailoverGroupResult",
    "AwaitableGetInstanceFailoverGroupResult",
    "get_instance_failover_group",
    "get_instance_failover_group_output",
]

@pulumi.output_type
class GetInstanceFailoverGroupResult:
    def __init__(
        __self__,
        azure_api_version=...,
        id=...,
        managed_instance_pairs=...,
        name=...,
        partner_regions=...,
        read_only_endpoint=...,
        read_write_endpoint=...,
        replication_role=...,
        replication_state=...,
        secondary_type=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="managedInstancePairs")
    def managed_instance_pairs(
        self,
    ) -> Sequence[outputs.ManagedInstancePairInfoResponse]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="partnerRegions")
    def partner_regions(self) -> Sequence[outputs.PartnerRegionInfoResponse]: ...
    @_builtins.property
    @pulumi.getter(name="readOnlyEndpoint")
    def read_only_endpoint(
        self,
    ) -> Optional[outputs.InstanceFailoverGroupReadOnlyEndpointResponse]: ...
    @_builtins.property
    @pulumi.getter(name="readWriteEndpoint")
    def read_write_endpoint(
        self,
    ) -> outputs.InstanceFailoverGroupReadWriteEndpointResponse: ...
    @_builtins.property
    @pulumi.getter(name="replicationRole")
    def replication_role(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="replicationState")
    def replication_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="secondaryType")
    def secondary_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetInstanceFailoverGroupResult(GetInstanceFailoverGroupResult):
    def __await__(self): ...

def get_instance_failover_group(
    failover_group_name: Optional[_builtins.str] = ...,
    location_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetInstanceFailoverGroupResult: ...
def get_instance_failover_group_output(
    failover_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    location_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetInstanceFailoverGroupResult]: ...
