

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AzureDevOpsPermissionType', 'CachingType', 'CertificateStoreNameOption', 'EphemeralType', 'LogonType', 'ManagedServiceIdentityType', 'OsDiskStorageAccountType', 'PredictionPreference', 'ProvisioningState', 'ResourcePredictionsProfileType', 'StorageAccountType']
@pulumi.type_token(...)
class AzureDevOpsPermissionType(_builtins.str, Enum):
    
    INHERIT = ...
    CREATOR_ONLY = ...
    SPECIFIC_ACCOUNTS = ...


@pulumi.type_token("azure-native:devopsinfrastructure:CachingType")
class CachingType(_builtins.str, Enum):
    
    NONE = ...
    READ_ONLY = ...
    READ_WRITE = ...


@pulumi.type_token(...)
class CertificateStoreNameOption(_builtins.str, Enum):
    
    MY = ...
    ROOT = ...


@pulumi.type_token("azure-native:devopsinfrastructure:EphemeralType")
class EphemeralType(_builtins.str, Enum):
    
    AUTOMATIC = ...
    CACHE_DISK = ...
    RESOURCE_DISK = ...


@pulumi.type_token("azure-native:devopsinfrastructure:LogonType")
class LogonType(_builtins.str, Enum):
    
    SERVICE = ...
    INTERACTIVE = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token(...)
class OsDiskStorageAccountType(_builtins.str, Enum):
    
    STANDARD = ...
    PREMIUM = ...
    STANDARD_SSD = ...


@pulumi.type_token(...)
class PredictionPreference(_builtins.str, Enum):
    
    BALANCED = ...
    MOST_COST_EFFECTIVE = ...
    MORE_COST_EFFECTIVE = ...
    MORE_PERFORMANCE = ...
    BEST_PERFORMANCE = ...


@pulumi.type_token(...)
class ProvisioningState(_builtins.str, Enum):
    
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    PROVISIONING = ...
    UPDATING = ...
    DELETING = ...
    ACCEPTED = ...


@pulumi.type_token(...)
class ResourcePredictionsProfileType(_builtins.str, Enum):
    
    MANUAL = ...
    AUTOMATIC = ...


@pulumi.type_token(...)
class StorageAccountType(_builtins.str, Enum):
    
    STANDARD_LRS = ...
    PREMIUM_LRS = ...
    STANDARD_SSDLRS = ...
    PREMIUM_ZRS = ...
    STANDARD_SSDZRS = ...


