import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["ProvisioningState"]

@pulumi.type_token("azure-native:offazurespringboot:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    UNKNOWN = ...
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    ACCEPTED = ...
    PROVISIONING = ...
    DELETING = ...
