import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["CopyMode", "CredentialType", "DayOfWeek", "EndpointType", "NfsVersion"]

@pulumi.type_token("azure-native:storagemover:CopyMode")
class CopyMode(_builtins.str, Enum):
    ADDITIVE = ...
    MIRROR = ...

@pulumi.type_token("azure-native:storagemover:CredentialType")
class CredentialType(_builtins.str, Enum):
    AZURE_KEY_VAULT_SMB = ...

@pulumi.type_token("azure-native:storagemover:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...

@pulumi.type_token("azure-native:storagemover:EndpointType")
class EndpointType(_builtins.str, Enum):
    AZURE_STORAGE_BLOB_CONTAINER = ...
    NFS_MOUNT = ...
    AZURE_STORAGE_SMB_FILE_SHARE = ...
    SMB_MOUNT = ...

@pulumi.type_token("azure-native:storagemover:NfsVersion")
class NfsVersion(_builtins.str, Enum):
    NF_SAUTO = ...
    NF_SV3 = ...
    NF_SV4 = ...
