import builtins as _builtins
import sys
import pulumi
from typing import Any, Mapping, Optional, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetAssignmentResult",
    "AwaitableGetAssignmentResult",
    "get_assignment",
    "get_assignment_output",
]

@pulumi.output_type
class GetAssignmentResult:
    def __init__(
        __self__,
        additional_data=...,
        assigned_component=...,
        assigned_standard=...,
        azure_api_version=...,
        description=...,
        display_name=...,
        effect=...,
        etag=...,
        expires_on=...,
        id=...,
        kind=...,
        location=...,
        metadata=...,
        name=...,
        scope=...,
        system_data=...,
        tags=...,
        type=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="additionalData")
    def additional_data(
        self,
    ) -> Optional[outputs.AssignmentPropertiesResponseAdditionalData]: ...
    @_builtins.property
    @pulumi.getter(name="assignedComponent")
    def assigned_component(self) -> Optional[outputs.AssignedComponentItemResponse]: ...
    @_builtins.property
    @pulumi.getter(name="assignedStandard")
    def assigned_standard(self) -> Optional[outputs.AssignedStandardItemResponse]: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def effect(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def etag(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="expiresOn")
    def expires_on(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[Any]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def scope(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="systemData")
    def system_data(self) -> outputs.SystemDataResponse: ...
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetAssignmentResult(GetAssignmentResult):
    def __await__(self): ...

def get_assignment(
    assignment_id: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetAssignmentResult: ...
def get_assignment_output(
    assignment_id: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetAssignmentResult]: ...
