import builtins as _builtins
import sys
import pulumi
from typing import Optional, Union

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetAdvancedThreatProtectionResult",
    "AwaitableGetAdvancedThreatProtectionResult",
    "get_advanced_threat_protection",
    "get_advanced_threat_protection_output",
]

@pulumi.output_type
class GetAdvancedThreatProtectionResult:
    def __init__(
        __self__, azure_api_version=..., id=..., is_enabled=..., name=..., type=...
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableGetAdvancedThreatProtectionResult(GetAdvancedThreatProtectionResult):
    def __await__(self): ...

def get_advanced_threat_protection(
    resource_id: Optional[_builtins.str] = ...,
    setting_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetAdvancedThreatProtectionResult: ...
def get_advanced_threat_protection_output(
    resource_id: Optional[pulumi.Input[_builtins.str]] = ...,
    setting_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetAdvancedThreatProtectionResult]: ...
