import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["EngineMode", "EngineType", "InstanceType", "StorageType"]

@pulumi.type_token("aws:rds/EngineMode:EngineMode")
class EngineMode(_builtins.str, Enum):
    PROVISIONED = ...
    SERVERLESS = ...
    PARALLEL_QUERY = ...
    GLOBAL_ = ...

@pulumi.type_token("aws:rds/EngineType:EngineType")
class EngineType(_builtins.str, Enum):
    AURORA = ...
    AURORA_MYSQL = ...
    AURORA_POSTGRESQL = ...
    MYSQL = ...
    POSTGRES = ...

@pulumi.type_token("aws:rds/InstanceType:InstanceType")
class InstanceType(_builtins.str, Enum):
    T4_G_MICRO = ...
    T4_G_SMALL = ...
    T4_G_MEDIUM = ...
    T4_G_LARGE = ...
    T4_G_X_LARGE = ...
    T4_G_2_X_LARGE = ...
    T3_MICRO = ...
    T3_SMALL = ...
    T3_MEDIUM = ...
    T3_LARGE = ...
    T3_X_LARGE = ...
    T3_2_X_LARGE = ...
    T2_MICRO = ...
    T2_SMALL = ...
    T2_MEDIUM = ...
    T2_LARGE = ...
    T2_X_LARGE = ...
    T2_2_X_LARGE = ...
    M1_SMALL = ...
    M1_MEDIUM = ...
    M1_LARGE = ...
    M1_X_LARGE = ...
    M2_X_LARGE = ...
    M2_2_X_LARGE = ...
    M2_4_X_LARGE = ...
    M3_MEDIUM = ...
    M3_LARGE = ...
    M3_X_LARGE = ...
    M3_2_X_LARGE = ...
    M4_LARGE = ...
    M4_X_LARGE = ...
    M4_2_X_LARGE = ...
    M4_4_X_LARGE = ...
    M4_10_X_LARGE = ...
    M4_16_X_LARGE = ...
    M5_LARGE = ...
    M5_X_LARGE = ...
    M5_2_X_LARGE = ...
    M5_4_X_LARGE = ...
    M5_12_X_LARGE = ...
    M5_24_X_LARGE = ...
    M6_G_LARGE = ...
    M6_G_X_LARGE = ...
    M6_G_2_X_LARGE = ...
    M6_G_4_X_LARGE = ...
    M6_G_8_X_LARGE = ...
    M6_G_12_X_LARGE = ...
    M6_G_16_X_LARGE = ...
    R3_LARGE = ...
    R3_X_LARGE = ...
    R3_2_X_LARGE = ...
    R3_4_X_LARGE = ...
    R3_8_X_LARGE = ...
    R4_LARGE = ...
    R4_X_LARGE = ...
    R4_2_X_LARGE = ...
    R4_4_X_LARGE = ...
    R4_8_X_LARGE = ...
    R4_16_X_LARGE = ...
    R5_LARGE = ...
    R5_X_LARGE = ...
    R5_2_X_LARGE = ...
    R5_4_X_LARGE = ...
    R5_12_X_LARGE = ...
    R5_24_X_LARGE = ...
    R6_G_LARGE = ...
    R6_G_X_LARGE = ...
    R6_G_2_X_LARGE = ...
    R6_G_4_X_LARGE = ...
    R6_G_8_X_LARGE = ...
    R6_G_12_X_LARGE = ...
    R6_G_16_X_LARGE = ...
    X1_16_X_LARGE = ...
    X1_32_X_LARGE = ...
    X1_E_X_LARGE = ...
    X1_E_2_X_LARGE = ...
    X1_E_4_X_LARGE = ...
    X1_E_8_X_LARGE = ...
    X1_E_32_X_LARGE = ...

@pulumi.type_token("aws:rds/StorageType:StorageType")
class StorageType(_builtins.str, Enum):
    STANDARD = ...
    GP2 = ...
    GP3 = ...
    IO1 = ...
