import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AddonType",
    "AffinityStrength",
    "AffinityType",
    "AvailabilityStrategy",
    "AzureHybridBenefitType",
    "DhcpTypeEnum",
    "DnsServiceLogLevelEnum",
    "DnsZoneType",
    "EncryptionState",
    "InternetEnum",
    "LicenseKind",
    "MountOptionEnum",
    "PlacementPolicyState",
    "PlacementPolicyType",
    "PortMirroringDirectionEnum",
    "ScriptExecutionParameterType",
    "SkuTier",
    "SslEnum",
    "SystemAssignedServiceIdentityType",
]

@pulumi.type_token("azure-native:avs:AddonType")
class AddonType(_builtins.str, Enum):
    SRM = ...
    VR = ...
    HCX = ...
    ARC = ...

@pulumi.type_token("azure-native:avs:AffinityStrength")
class AffinityStrength(_builtins.str, Enum):
    SHOULD = ...
    MUST = ...

@pulumi.type_token("azure-native:avs:AffinityType")
class AffinityType(_builtins.str, Enum):
    AFFINITY = ...
    ANTI_AFFINITY = ...

@pulumi.type_token("azure-native:avs:AvailabilityStrategy")
class AvailabilityStrategy(_builtins.str, Enum):
    SINGLE_ZONE = ...
    DUAL_ZONE = ...

@pulumi.type_token("azure-native:avs:AzureHybridBenefitType")
class AzureHybridBenefitType(_builtins.str, Enum):
    SQL_HOST = ...
    NONE = ...

@pulumi.type_token("azure-native:avs:DhcpTypeEnum")
class DhcpTypeEnum(_builtins.str, Enum):
    SERVER = ...
    RELAY = ...

@pulumi.type_token("azure-native:avs:DnsServiceLogLevelEnum")
class DnsServiceLogLevelEnum(_builtins.str, Enum):
    DEBUG = ...
    INFO = ...
    WARNING = ...
    ERROR = ...
    FATAL = ...

@pulumi.type_token("azure-native:avs:DnsZoneType")
class DnsZoneType(_builtins.str, Enum):
    PUBLIC = ...
    PRIVATE = ...

@pulumi.type_token("azure-native:avs:EncryptionState")
class EncryptionState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:avs:InternetEnum")
class InternetEnum(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:avs:LicenseKind")
class LicenseKind(_builtins.str, Enum):
    VMWARE_FIREWALL = ...

@pulumi.type_token("azure-native:avs:MountOptionEnum")
class MountOptionEnum(_builtins.str, Enum):
    MOUNT = ...
    ATTACH = ...

@pulumi.type_token("azure-native:avs:PlacementPolicyState")
class PlacementPolicyState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:avs:PlacementPolicyType")
class PlacementPolicyType(_builtins.str, Enum):
    VM_VM = ...
    VM_HOST = ...

@pulumi.type_token("azure-native:avs:PortMirroringDirectionEnum")
class PortMirroringDirectionEnum(_builtins.str, Enum):
    INGRESS = ...
    EGRESS = ...
    BIDIRECTIONAL = ...

@pulumi.type_token("azure-native:avs:ScriptExecutionParameterType")
class ScriptExecutionParameterType(_builtins.str, Enum):
    VALUE = ...
    SECURE_VALUE = ...
    CREDENTIAL = ...

@pulumi.type_token("azure-native:avs:SkuTier")
class SkuTier(_builtins.str, Enum):
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:avs:SslEnum")
class SslEnum(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:avs:SystemAssignedServiceIdentityType")
class SystemAssignedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
