

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ActionType', 'BackendEnabledState', 'CustomRuleEnabledState', 'DynamicCompressionEnabled', 'EnforceCertificateNameCheckEnabledState', 'FrontDoorEnabledState', 'FrontDoorForwardingProtocol', 'FrontDoorHealthProbeMethod', 'FrontDoorProtocol', 'FrontDoorQuery', 'FrontDoorRedirectProtocol', 'FrontDoorRedirectType', 'HeaderActionType', 'HealthProbeEnabled', 'ManagedRuleEnabledState', 'ManagedRuleExclusionMatchVariable', 'ManagedRuleExclusionSelectorMatchOperator', 'ManagedRuleSetActionType', 'MatchProcessingBehavior', 'MatchVariable', 'Operator', 'PolicyEnabledState', 'PolicyMode', 'PolicyRequestBodyCheck', 'RoutingRuleEnabledState', 'RuleType', 'RulesEngineMatchVariable', 'RulesEngineOperator', 'ScrubbingRuleEntryMatchOperator', 'ScrubbingRuleEntryMatchVariable', 'ScrubbingRuleEntryState', 'SessionAffinityEnabledState', 'SkuName', 'State', 'Transform', 'TransformType', 'VariableName', 'WebApplicationFirewallScrubbingState']
@pulumi.type_token("azure-native:frontdoor:ActionType")
class ActionType(_builtins.str, Enum):
    
    ALLOW = ...
    BLOCK = ...
    LOG = ...
    REDIRECT = ...
    ANOMALY_SCORING = ...
    JS_CHALLENGE = ...


@pulumi.type_token("azure-native:frontdoor:BackendEnabledState")
class BackendEnabledState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:CustomRuleEnabledState")
class CustomRuleEnabledState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:frontdoor:DynamicCompressionEnabled")
class DynamicCompressionEnabled(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token(...)
class EnforceCertificateNameCheckEnabledState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorEnabledState")
class FrontDoorEnabledState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorForwardingProtocol")
class FrontDoorForwardingProtocol(_builtins.str, Enum):
    
    HTTP_ONLY = ...
    HTTPS_ONLY = ...
    MATCH_REQUEST = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorHealthProbeMethod")
class FrontDoorHealthProbeMethod(_builtins.str, Enum):
    
    GET = ...
    HEAD = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorProtocol")
class FrontDoorProtocol(_builtins.str, Enum):
    
    HTTP = ...
    HTTPS = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorQuery")
class FrontDoorQuery(_builtins.str, Enum):
    
    STRIP_NONE = ...
    STRIP_ALL = ...
    STRIP_ONLY = ...
    STRIP_ALL_EXCEPT = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorRedirectProtocol")
class FrontDoorRedirectProtocol(_builtins.str, Enum):
    
    HTTP_ONLY = ...
    HTTPS_ONLY = ...
    MATCH_REQUEST = ...


@pulumi.type_token("azure-native:frontdoor:FrontDoorRedirectType")
class FrontDoorRedirectType(_builtins.str, Enum):
    
    MOVED = ...
    FOUND = ...
    TEMPORARY_REDIRECT = ...
    PERMANENT_REDIRECT = ...


@pulumi.type_token("azure-native:frontdoor:HeaderActionType")
class HeaderActionType(_builtins.str, Enum):
    
    APPEND = ...
    DELETE = ...
    OVERWRITE = ...


@pulumi.type_token("azure-native:frontdoor:HealthProbeEnabled")
class HealthProbeEnabled(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:ManagedRuleEnabledState")
class ManagedRuleEnabledState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token(...)
class ManagedRuleExclusionMatchVariable(_builtins.str, Enum):
    
    REQUEST_HEADER_NAMES = ...
    REQUEST_COOKIE_NAMES = ...
    QUERY_STRING_ARG_NAMES = ...
    REQUEST_BODY_POST_ARG_NAMES = ...
    REQUEST_BODY_JSON_ARG_NAMES = ...


@pulumi.type_token(...)
class ManagedRuleExclusionSelectorMatchOperator(_builtins.str, Enum):
    
    EQUALS = ...
    CONTAINS = ...
    STARTS_WITH = ...
    ENDS_WITH = ...
    EQUALS_ANY = ...


@pulumi.type_token("azure-native:frontdoor:ManagedRuleSetActionType")
class ManagedRuleSetActionType(_builtins.str, Enum):
    
    BLOCK = ...
    LOG = ...
    REDIRECT = ...


@pulumi.type_token("azure-native:frontdoor:MatchProcessingBehavior")
class MatchProcessingBehavior(_builtins.str, Enum):
    
    CONTINUE_ = ...
    STOP = ...


@pulumi.type_token("azure-native:frontdoor:MatchVariable")
class MatchVariable(_builtins.str, Enum):
    
    REMOTE_ADDR = ...
    REQUEST_METHOD = ...
    QUERY_STRING = ...
    POST_ARGS = ...
    REQUEST_URI = ...
    REQUEST_HEADER = ...
    REQUEST_BODY = ...
    COOKIES = ...
    SOCKET_ADDR = ...


@pulumi.type_token("azure-native:frontdoor:Operator")
class Operator(_builtins.str, Enum):
    
    ANY = ...
    IP_MATCH = ...
    GEO_MATCH = ...
    EQUAL = ...
    CONTAINS = ...
    LESS_THAN = ...
    GREATER_THAN = ...
    LESS_THAN_OR_EQUAL = ...
    GREATER_THAN_OR_EQUAL = ...
    BEGINS_WITH = ...
    ENDS_WITH = ...
    REG_EX = ...


@pulumi.type_token("azure-native:frontdoor:PolicyEnabledState")
class PolicyEnabledState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:frontdoor:PolicyMode")
class PolicyMode(_builtins.str, Enum):
    
    PREVENTION = ...
    DETECTION = ...


@pulumi.type_token("azure-native:frontdoor:PolicyRequestBodyCheck")
class PolicyRequestBodyCheck(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:frontdoor:RoutingRuleEnabledState")
class RoutingRuleEnabledState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:RuleType")
class RuleType(_builtins.str, Enum):
    
    MATCH_RULE = ...
    RATE_LIMIT_RULE = ...


@pulumi.type_token("azure-native:frontdoor:RulesEngineMatchVariable")
class RulesEngineMatchVariable(_builtins.str, Enum):
    
    IS_MOBILE = ...
    REMOTE_ADDR = ...
    REQUEST_METHOD = ...
    QUERY_STRING = ...
    POST_ARGS = ...
    REQUEST_URI = ...
    REQUEST_PATH = ...
    REQUEST_FILENAME = ...
    REQUEST_FILENAME_EXTENSION = ...
    REQUEST_HEADER = ...
    REQUEST_BODY = ...
    REQUEST_SCHEME = ...


@pulumi.type_token("azure-native:frontdoor:RulesEngineOperator")
class RulesEngineOperator(_builtins.str, Enum):
    
    ANY = ...
    IP_MATCH = ...
    GEO_MATCH = ...
    EQUAL = ...
    CONTAINS = ...
    LESS_THAN = ...
    GREATER_THAN = ...
    LESS_THAN_OR_EQUAL = ...
    GREATER_THAN_OR_EQUAL = ...
    BEGINS_WITH = ...
    ENDS_WITH = ...


@pulumi.type_token(...)
class ScrubbingRuleEntryMatchOperator(_builtins.str, Enum):
    
    EQUALS_ANY = ...
    EQUALS = ...


@pulumi.type_token(...)
class ScrubbingRuleEntryMatchVariable(_builtins.str, Enum):
    
    REQUEST_IP_ADDRESS = ...
    REQUEST_URI = ...
    QUERY_STRING_ARG_NAMES = ...
    REQUEST_HEADER_NAMES = ...
    REQUEST_COOKIE_NAMES = ...
    REQUEST_BODY_POST_ARG_NAMES = ...
    REQUEST_BODY_JSON_ARG_NAMES = ...


@pulumi.type_token("azure-native:frontdoor:ScrubbingRuleEntryState")
class ScrubbingRuleEntryState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:SessionAffinityEnabledState")
class SessionAffinityEnabledState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:SkuName")
class SkuName(_builtins.str, Enum):
    
    CLASSIC_AZURE_FRONT_DOOR = ...
    STANDARD_AZURE_FRONT_DOOR = ...
    PREMIUM_AZURE_FRONT_DOOR = ...


@pulumi.type_token("azure-native:frontdoor:State")
class State(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:frontdoor:Transform")
class Transform(_builtins.str, Enum):
    
    LOWERCASE = ...
    UPPERCASE = ...
    TRIM = ...
    URL_DECODE = ...
    URL_ENCODE = ...
    REMOVE_NULLS = ...


@pulumi.type_token("azure-native:frontdoor:TransformType")
class TransformType(_builtins.str, Enum):
    
    LOWERCASE = ...
    UPPERCASE = ...
    TRIM = ...
    URL_DECODE = ...
    URL_ENCODE = ...
    REMOVE_NULLS = ...


@pulumi.type_token("azure-native:frontdoor:VariableName")
class VariableName(_builtins.str, Enum):
    
    SOCKET_ADDR = ...
    GEO_LOCATION = ...
    NONE = ...


@pulumi.type_token(...)
class WebApplicationFirewallScrubbingState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


