

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['DriveState', 'EncryptionKekType']
@pulumi.type_token("azure-native:importexport:DriveState")
class DriveState(_builtins.str, Enum):
    
    SPECIFIED = ...
    RECEIVED = ...
    NEVER_RECEIVED = ...
    TRANSFERRING = ...
    COMPLETED = ...
    COMPLETED_MORE_INFO = ...
    SHIPPED_BACK = ...


@pulumi.type_token("azure-native:importexport:EncryptionKekType")
class EncryptionKekType(_builtins.str, Enum):
    
    MICROSOFT_MANAGED = ...
    CUSTOMER_MANAGED = ...


