

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AdvertiseToFabric', 'AgentPoolMode', 'BareMetalMachineKeySetPrivilegeLevel', 'BfdEnabled', 'BgpMultiHop', 'BmcKeySetPrivilegeLevel', 'CloudServicesNetworkEnableDefaultEgressEndpoints', 'ClusterSecretArchiveEnabled', 'ClusterType', 'ClusterUpdateStrategyType', 'ConsoleEnabled', 'DefaultGateway', 'FabricPeeringEnabled', 'HugepagesSize', 'HybridAksIpamEnabled', 'HybridAksPluginType', 'IpAllocationType', 'KubernetesPluginType', 'L3NetworkConfigurationIpamEnabled', 'ManagedServiceIdentitySelectorType', 'ManagedServiceIdentityType', 'OsDiskCreateOption', 'OsDiskDeleteOption', 'RuntimeProtectionEnforcementLevel', 'SecurityRuleDirection', 'ValidationThresholdGrouping', 'ValidationThresholdType', 'VirtualMachineBootMethod', 'VirtualMachineDeviceModelType', 'VirtualMachineIPAllocationMethod', 'VirtualMachineIsolateEmulatorThread', 'VirtualMachinePlacementHintPodAffinityScope', 'VirtualMachinePlacementHintType', 'VirtualMachineSchedulingExecution', 'VirtualMachineVirtioInterfaceType', 'VulnerabilityScanningSettingsContainerScan']
@pulumi.type_token("azure-native:networkcloud:AdvertiseToFabric")
class AdvertiseToFabric(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:AgentPoolMode")
class AgentPoolMode(_builtins.str, Enum):
    
    SYSTEM = ...
    USER = ...
    NOT_APPLICABLE = ...


@pulumi.type_token(...)
class BareMetalMachineKeySetPrivilegeLevel(_builtins.str, Enum):
    
    STANDARD = ...
    SUPERUSER = ...


@pulumi.type_token("azure-native:networkcloud:BfdEnabled")
class BfdEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:BgpMultiHop")
class BgpMultiHop(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:BmcKeySetPrivilegeLevel")
class BmcKeySetPrivilegeLevel(_builtins.str, Enum):
    
    READ_ONLY = ...
    ADMINISTRATOR = ...


@pulumi.type_token(...)
class CloudServicesNetworkEnableDefaultEgressEndpoints(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token(...)
class ClusterSecretArchiveEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:ClusterType")
class ClusterType(_builtins.str, Enum):
    
    SINGLE_RACK = ...
    MULTI_RACK = ...


@pulumi.type_token(...)
class ClusterUpdateStrategyType(_builtins.str, Enum):
    
    RACK = ...
    PAUSE_AFTER_RACK = ...


@pulumi.type_token("azure-native:networkcloud:ConsoleEnabled")
class ConsoleEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:DefaultGateway")
class DefaultGateway(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:FabricPeeringEnabled")
class FabricPeeringEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:HugepagesSize")
class HugepagesSize(_builtins.str, Enum):
    
    HUGEPAGES_SIZE_2_M = ...
    HUGEPAGES_SIZE_1_G = ...


@pulumi.type_token("azure-native:networkcloud:HybridAksIpamEnabled")
class HybridAksIpamEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token("azure-native:networkcloud:HybridAksPluginType")
class HybridAksPluginType(_builtins.str, Enum):
    
    DPDK = ...
    SRIOV = ...
    OS_DEVICE = ...


@pulumi.type_token("azure-native:networkcloud:IpAllocationType")
class IpAllocationType(_builtins.str, Enum):
    
    IPV4 = ...
    IPV6 = ...
    DUAL_STACK = ...


@pulumi.type_token("azure-native:networkcloud:KubernetesPluginType")
class KubernetesPluginType(_builtins.str, Enum):
    
    DPDK = ...
    SRIOV = ...
    OS_DEVICE = ...
    MACVLAN = ...
    IPVLAN = ...


@pulumi.type_token(...)
class L3NetworkConfigurationIpamEnabled(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token(...)
class ManagedServiceIdentitySelectorType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED_IDENTITY = ...
    USER_ASSIGNED_IDENTITY = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:networkcloud:OsDiskCreateOption")
class OsDiskCreateOption(_builtins.str, Enum):
    
    EPHEMERAL = ...
    PERSISTENT = ...


@pulumi.type_token("azure-native:networkcloud:OsDiskDeleteOption")
class OsDiskDeleteOption(_builtins.str, Enum):
    
    DELETE = ...


@pulumi.type_token(...)
class RuntimeProtectionEnforcementLevel(_builtins.str, Enum):
    
    AUDIT = ...
    DISABLED = ...
    ON_DEMAND = ...
    PASSIVE = ...
    REAL_TIME = ...


@pulumi.type_token("azure-native:networkcloud:SecurityRuleDirection")
class SecurityRuleDirection(_builtins.str, Enum):
    
    INBOUND = ...
    OUTBOUND = ...


@pulumi.type_token(...)
class ValidationThresholdGrouping(_builtins.str, Enum):
    
    PER_CLUSTER = ...
    PER_RACK = ...


@pulumi.type_token("azure-native:networkcloud:ValidationThresholdType")
class ValidationThresholdType(_builtins.str, Enum):
    
    COUNT_SUCCESS = ...
    PERCENT_SUCCESS = ...


@pulumi.type_token("azure-native:networkcloud:VirtualMachineBootMethod")
class VirtualMachineBootMethod(_builtins.str, Enum):
    
    UEFI = ...
    BIOS = ...


@pulumi.type_token(...)
class VirtualMachineDeviceModelType(_builtins.str, Enum):
    
    T1 = ...
    T2 = ...
    T3 = ...


@pulumi.type_token(...)
class VirtualMachineIPAllocationMethod(_builtins.str, Enum):
    
    DYNAMIC = ...
    STATIC = ...
    DISABLED = ...


@pulumi.type_token(...)
class VirtualMachineIsolateEmulatorThread(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...


@pulumi.type_token(...)
class VirtualMachinePlacementHintPodAffinityScope(_builtins.str, Enum):
    
    RACK = ...
    MACHINE = ...


@pulumi.type_token(...)
class VirtualMachinePlacementHintType(_builtins.str, Enum):
    
    AFFINITY = ...
    ANTI_AFFINITY = ...


@pulumi.type_token(...)
class VirtualMachineSchedulingExecution(_builtins.str, Enum):
    
    HARD = ...
    SOFT = ...


@pulumi.type_token(...)
class VirtualMachineVirtioInterfaceType(_builtins.str, Enum):
    
    MODERN = ...
    TRANSITIONAL = ...


@pulumi.type_token(...)
class VulnerabilityScanningSettingsContainerScan(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


