import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ConnectionType",
    "CreateOption",
    "EnableState",
    "RecurrenceFrequency",
    "ResourceIdentityType",
    "ShutdownOnIdleMode",
    "SkuTier",
    "WeekDay",
]

@pulumi.type_token("azure-native:labservices:ConnectionType")
class ConnectionType(_builtins.str, Enum):
    PUBLIC = ...
    PRIVATE = ...
    NONE = ...

@pulumi.type_token("azure-native:labservices:CreateOption")
class CreateOption(_builtins.str, Enum):
    IMAGE = ...
    TEMPLATE_VM = ...

@pulumi.type_token("azure-native:labservices:EnableState")
class EnableState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:labservices:RecurrenceFrequency")
class RecurrenceFrequency(_builtins.str, Enum):
    DAILY = ...
    WEEKLY = ...

@pulumi.type_token("azure-native:labservices:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:labservices:ShutdownOnIdleMode")
class ShutdownOnIdleMode(_builtins.str, Enum):
    NONE = ...
    USER_ABSENCE = ...
    LOW_USAGE = ...

@pulumi.type_token("azure-native:labservices:SkuTier")
class SkuTier(_builtins.str, Enum):
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...

@pulumi.type_token("azure-native:labservices:WeekDay")
class WeekDay(_builtins.str, Enum):
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
