import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "GetManagedNetworkGroupResult",
    "AwaitableGetManagedNetworkGroupResult",
    "get_managed_network_group",
    "get_managed_network_group_output",
]

@pulumi.output_type
class GetManagedNetworkGroupResult:
    def __init__(
        __self__,
        azure_api_version=...,
        etag=...,
        id=...,
        kind=...,
        location=...,
        management_groups=...,
        name=...,
        provisioning_state=...,
        subnets=...,
        subscriptions=...,
        type=...,
        virtual_networks=...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def etag(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="managementGroups")
    def management_groups(self) -> Optional[Sequence[outputs.ResourceIdResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def subnets(self) -> Optional[Sequence[outputs.ResourceIdResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def subscriptions(self) -> Optional[Sequence[outputs.ResourceIdResponse]]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="virtualNetworks")
    def virtual_networks(self) -> Optional[Sequence[outputs.ResourceIdResponse]]: ...

class AwaitableGetManagedNetworkGroupResult(GetManagedNetworkGroupResult):
    def __await__(self): ...

def get_managed_network_group(
    managed_network_group_name: Optional[_builtins.str] = ...,
    managed_network_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableGetManagedNetworkGroupResult: ...
def get_managed_network_group_output(
    managed_network_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    managed_network_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[GetManagedNetworkGroupResult]: ...
