import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["DiskIndependenceMode", "NICType"]

@pulumi.type_token(...)
class DiskIndependenceMode(_builtins.str, Enum):
    PERSISTENT = ...
    INDEPENDENT_PERSISTENT = ...
    INDEPENDENT_NONPERSISTENT = ...

@pulumi.type_token("azure-native:vmwarecloudsimple:NICType")
class NICType(_builtins.str, Enum):
    E1000 = ...
    E1000_E = ...
    PCNET32 = ...
    VMXNET = ...
    VMXNET2 = ...
    VMXNET3 = ...
