

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessTier', 'AccountImmutabilityPolicyState', 'AccountType', 'Action', 'AllowedCopyScope', 'AllowedMethods', 'BlobAccessTier', 'BlobType', 'Bypass', 'DefaultAction', 'DefaultSharePermission', 'DirectoryServiceOptions', 'DnsEndpointType', 'EnabledProtocols', 'EncryptionScopeSource', 'EncryptionScopeState', 'ExpirationAction', 'ExtendedLocationTypes', 'Format', 'HttpProtocol', 'IdentityType', 'IntervalUnit', 'InventoryRuleType', 'KeySource', 'KeyType', 'Kind', 'LargeFileSharesState', 'MinimumTlsVersion', 'Name', 'ObjectType', 'Permissions', 'PrivateEndpointServiceConnectionStatus', 'PublicAccess', 'PublicNetworkAccess', 'RootSquashType', 'RoutingChoice', 'RuleType', 'Schedule', 'Services', 'ShareAccessTier', 'SignedResource', 'SignedResourceTypes', 'SkuName', 'State', 'TriggerType']
@pulumi.type_token("azure-native:storage:AccessTier")
class AccessTier(_builtins.str, Enum):
    
    HOT = ...
    COOL = ...
    PREMIUM = ...
    COLD = ...


@pulumi.type_token(...)
class AccountImmutabilityPolicyState(_builtins.str, Enum):
    
    UNLOCKED = ...
    LOCKED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:storage:AccountType")
class AccountType(_builtins.str, Enum):
    
    USER = ...
    COMPUTER = ...


@pulumi.type_token("azure-native:storage:Action")
class Action(_builtins.str, Enum):
    
    ALLOW = ...


@pulumi.type_token("azure-native:storage:AllowedCopyScope")
class AllowedCopyScope(_builtins.str, Enum):
    
    PRIVATE_LINK = ...
    AAD = ...


@pulumi.type_token("azure-native:storage:AllowedMethods")
class AllowedMethods(_builtins.str, Enum):
    DELETE = ...
    GET = ...
    HEAD = ...
    MERGE = ...
    POST = ...
    OPTIONS = ...
    PUT = ...
    PATCH = ...
    CONNECT = ...
    TRACE = ...


@pulumi.type_token("azure-native:storage:BlobAccessTier")
class BlobAccessTier(_builtins.str, Enum):
    
    HOT = ...
    COOL = ...
    ARCHIVE = ...


@pulumi.type_token("azure-native:storage:BlobType")
class BlobType(_builtins.str, Enum):
    
    BLOCK = ...
    APPEND = ...


@pulumi.type_token("azure-native:storage:Bypass")
class Bypass(_builtins.str, Enum):
    
    NONE = ...
    LOGGING = ...
    METRICS = ...
    AZURE_SERVICES = ...


@pulumi.type_token("azure-native:storage:DefaultAction")
class DefaultAction(_builtins.str, Enum):
    
    ALLOW = ...
    DENY = ...


@pulumi.type_token("azure-native:storage:DefaultSharePermission")
class DefaultSharePermission(_builtins.str, Enum):
    
    NONE = ...
    STORAGE_FILE_DATA_SMB_SHARE_READER = ...
    STORAGE_FILE_DATA_SMB_SHARE_CONTRIBUTOR = ...
    STORAGE_FILE_DATA_SMB_SHARE_ELEVATED_CONTRIBUTOR = ...


@pulumi.type_token("azure-native:storage:DirectoryServiceOptions")
class DirectoryServiceOptions(_builtins.str, Enum):
    
    NONE = ...
    AADDS = ...
    AD = ...
    AADKERB = ...


@pulumi.type_token("azure-native:storage:DnsEndpointType")
class DnsEndpointType(_builtins.str, Enum):
    
    STANDARD = ...
    AZURE_DNS_ZONE = ...


@pulumi.type_token("azure-native:storage:EnabledProtocols")
class EnabledProtocols(_builtins.str, Enum):
    
    SMB = ...
    NFS = ...


@pulumi.type_token("azure-native:storage:EncryptionScopeSource")
class EncryptionScopeSource(_builtins.str, Enum):
    
    MICROSOFT_STORAGE = ...
    MICROSOFT_KEY_VAULT = ...


@pulumi.type_token("azure-native:storage:EncryptionScopeState")
class EncryptionScopeState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:storage:ExpirationAction")
class ExpirationAction(_builtins.str, Enum):
    
    LOG = ...
    BLOCK = ...


@pulumi.type_token("azure-native:storage:ExtendedLocationTypes")
class ExtendedLocationTypes(_builtins.str, Enum):
    
    EDGE_ZONE = ...


@pulumi.type_token("azure-native:storage:Format")
class Format(_builtins.str, Enum):
    
    CSV = ...
    PARQUET = ...


@pulumi.type_token("azure-native:storage:HttpProtocol")
class HttpProtocol(_builtins.str, Enum):
    
    HTTPS_HTTP = ...
    HTTPS = ...


@pulumi.type_token("azure-native:storage:IdentityType")
class IdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:storage:IntervalUnit")
class IntervalUnit(_builtins.str, Enum):
    
    DAYS = ...


@pulumi.type_token("azure-native:storage:InventoryRuleType")
class InventoryRuleType(_builtins.str, Enum):
    
    INVENTORY = ...


@pulumi.type_token("azure-native:storage:KeySource")
class KeySource(_builtins.str, Enum):
    
    MICROSOFT_STORAGE = ...
    MICROSOFT_KEYVAULT = ...


@pulumi.type_token("azure-native:storage:KeyType")
class KeyType(_builtins.str, Enum):
    
    SERVICE = ...
    ACCOUNT = ...


@pulumi.type_token("azure-native:storage:Kind")
class Kind(_builtins.str, Enum):
    
    STORAGE = ...
    STORAGE_V2 = ...
    BLOB_STORAGE = ...
    FILE_STORAGE = ...
    BLOCK_BLOB_STORAGE = ...


@pulumi.type_token("azure-native:storage:LargeFileSharesState")
class LargeFileSharesState(_builtins.str, Enum):
    
    DISABLED = ...
    ENABLED = ...


@pulumi.type_token("azure-native:storage:MinimumTlsVersion")
class MinimumTlsVersion(_builtins.str, Enum):
    
    TLS1_0 = ...
    TLS1_1 = ...
    TLS1_2 = ...
    TLS1_3 = ...


@pulumi.type_token("azure-native:storage:Name")
class Name(_builtins.str, Enum):
    
    ACCESS_TIME_TRACKING = ...


@pulumi.type_token("azure-native:storage:ObjectType")
class ObjectType(_builtins.str, Enum):
    
    BLOB = ...
    CONTAINER = ...


@pulumi.type_token("azure-native:storage:Permissions")
class Permissions(_builtins.str, Enum):
    
    R = ...
    D = ...
    W = ...
    L = ...
    A = ...
    C = ...
    U = ...
    P = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:storage:PublicAccess")
class PublicAccess(_builtins.str, Enum):
    
    CONTAINER = ...
    BLOB = ...
    NONE = ...


@pulumi.type_token("azure-native:storage:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...


@pulumi.type_token("azure-native:storage:RootSquashType")
class RootSquashType(_builtins.str, Enum):
    
    NO_ROOT_SQUASH = ...
    ROOT_SQUASH = ...
    ALL_SQUASH = ...


@pulumi.type_token("azure-native:storage:RoutingChoice")
class RoutingChoice(_builtins.str, Enum):
    
    MICROSOFT_ROUTING = ...
    INTERNET_ROUTING = ...


@pulumi.type_token("azure-native:storage:RuleType")
class RuleType(_builtins.str, Enum):
    
    LIFECYCLE = ...


@pulumi.type_token("azure-native:storage:Schedule")
class Schedule(_builtins.str, Enum):
    
    DAILY = ...
    WEEKLY = ...


@pulumi.type_token("azure-native:storage:Services")
class Services(_builtins.str, Enum):
    
    B = ...
    Q = ...
    T = ...
    F = ...


@pulumi.type_token("azure-native:storage:ShareAccessTier")
class ShareAccessTier(_builtins.str, Enum):
    
    TRANSACTION_OPTIMIZED = ...
    HOT = ...
    COOL = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:storage:SignedResource")
class SignedResource(_builtins.str, Enum):
    
    B = ...
    C = ...
    F = ...
    S = ...


@pulumi.type_token("azure-native:storage:SignedResourceTypes")
class SignedResourceTypes(_builtins.str, Enum):
    
    S = ...
    C = ...
    O = ...


@pulumi.type_token("azure-native:storage:SkuName")
class SkuName(_builtins.str, Enum):
    
    STANDARD_LRS = ...
    STANDARD_GRS = ...
    STANDARD_RAGRS = ...
    STANDARD_ZRS = ...
    PREMIUM_LRS = ...
    PREMIUM_ZRS = ...
    STANDARD_GZRS = ...
    STANDARD_RAGZRS = ...
    STANDARD_V2_LRS = ...
    STANDARD_V2_GRS = ...
    STANDARD_V2_ZRS = ...
    STANDARD_V2_GZRS = ...
    PREMIUM_V2_LRS = ...
    PREMIUM_V2_ZRS = ...


@pulumi.type_token("azure-native:storage:State")
class State(_builtins.str, Enum):
    
    PROVISIONING = ...
    DEPROVISIONING = ...
    SUCCEEDED = ...
    FAILED = ...
    NETWORK_SOURCE_DELETED = ...


@pulumi.type_token("azure-native:storage:TriggerType")
class TriggerType(_builtins.str, Enum):
    
    RUN_ONCE = ...
    ON_SCHEDULE = ...


