import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "DataSetKind",
    "DataSetMappingKind",
    "OutputType",
    "RecurrenceInterval",
    "ShareKind",
    "SynchronizationMode",
    "SynchronizationSettingKind",
    "TriggerKind",
    "Type",
]

@pulumi.type_token("azure-native:datashare:DataSetKind")
class DataSetKind(_builtins.str, Enum):
    BLOB = ...
    CONTAINER = ...
    BLOB_FOLDER = ...
    ADLS_GEN2_FILE_SYSTEM = ...
    ADLS_GEN2_FOLDER = ...
    ADLS_GEN2_FILE = ...
    ADLS_GEN1_FOLDER = ...
    ADLS_GEN1_FILE = ...
    KUSTO_CLUSTER = ...
    KUSTO_DATABASE = ...
    KUSTO_TABLE = ...
    SQL_DB_TABLE = ...
    SQL_DW_TABLE = ...
    SYNAPSE_WORKSPACE_SQL_POOL_TABLE = ...

@pulumi.type_token("azure-native:datashare:DataSetMappingKind")
class DataSetMappingKind(_builtins.str, Enum):
    BLOB = ...
    CONTAINER = ...
    BLOB_FOLDER = ...
    ADLS_GEN2_FILE_SYSTEM = ...
    ADLS_GEN2_FOLDER = ...
    ADLS_GEN2_FILE = ...
    KUSTO_CLUSTER = ...
    KUSTO_DATABASE = ...
    KUSTO_TABLE = ...
    SQL_DB_TABLE = ...
    SQL_DW_TABLE = ...
    SYNAPSE_WORKSPACE_SQL_POOL_TABLE = ...

@pulumi.type_token("azure-native:datashare:OutputType")
class OutputType(_builtins.str, Enum):
    CSV = ...
    PARQUET = ...

@pulumi.type_token("azure-native:datashare:RecurrenceInterval")
class RecurrenceInterval(_builtins.str, Enum):
    HOUR = ...
    DAY = ...

@pulumi.type_token("azure-native:datashare:ShareKind")
class ShareKind(_builtins.str, Enum):
    COPY_BASED = ...
    IN_PLACE = ...

@pulumi.type_token("azure-native:datashare:SynchronizationMode")
class SynchronizationMode(_builtins.str, Enum):
    INCREMENTAL = ...
    FULL_SYNC = ...

@pulumi.type_token("azure-native:datashare:SynchronizationSettingKind")
class SynchronizationSettingKind(_builtins.str, Enum):
    SCHEDULE_BASED = ...

@pulumi.type_token("azure-native:datashare:TriggerKind")
class TriggerKind(_builtins.str, Enum):
    SCHEDULE_BASED = ...

@pulumi.type_token("azure-native:datashare:Type")
class Type(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
