import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListShareSubscriptionSynchronizationDetailsResult",
    ...,
    "list_share_subscription_synchronization_details",
    ...,
]

@pulumi.output_type
class ListShareSubscriptionSynchronizationDetailsResult:
    def __init__(__self__, next_link=..., value=...) -> None: ...
    @_builtins.property
    @pulumi.getter(name="nextLink")
    def next_link(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Sequence[outputs.SynchronizationDetailsResponse]: ...

class AwaitableListShareSubscriptionSynchronizationDetailsResult(
    ListShareSubscriptionSynchronizationDetailsResult
):
    def __await__(self): ...

def list_share_subscription_synchronization_details(
    account_name: Optional[_builtins.str] = ...,
    filter: Optional[_builtins.str] = ...,
    orderby: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    share_subscription_name: Optional[_builtins.str] = ...,
    skip_token: Optional[_builtins.str] = ...,
    synchronization_id: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListShareSubscriptionSynchronizationDetailsResult: ...
def list_share_subscription_synchronization_details_output(
    account_name: Optional[pulumi.Input[_builtins.str]] = ...,
    filter: Optional[pulumi.Input[Optional[_builtins.str]]] = ...,
    orderby: Optional[pulumi.Input[Optional[_builtins.str]]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    share_subscription_name: Optional[pulumi.Input[_builtins.str]] = ...,
    skip_token: Optional[pulumi.Input[Optional[_builtins.str]]] = ...,
    synchronization_id: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListShareSubscriptionSynchronizationDetailsResult]: ...
