import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ACLAction",
    "EventListenerEndpointDiscriminator",
    "EventListenerFilterDiscriminator",
    "ManagedIdentityType",
    "PrivateLinkServiceConnectionStatus",
    "ServiceKind",
    "UpstreamAuthType",
    "WebPubSubRequestType",
    "WebPubSubSkuTier",
]

@pulumi.type_token("azure-native:webpubsub:ACLAction")
class ACLAction(_builtins.str, Enum):
    ALLOW = ...
    DENY = ...

@pulumi.type_token(...)
class EventListenerEndpointDiscriminator(_builtins.str, Enum):
    EVENT_HUB = ...

@pulumi.type_token(...)
class EventListenerFilterDiscriminator(_builtins.str, Enum):
    EVENT_NAME = ...

@pulumi.type_token("azure-native:webpubsub:ManagedIdentityType")
class ManagedIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token(...)
class PrivateLinkServiceConnectionStatus(_builtins.str, Enum):
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...

@pulumi.type_token("azure-native:webpubsub:ServiceKind")
class ServiceKind(_builtins.str, Enum):
    WEB_PUB_SUB = ...
    SOCKET_IO = ...

@pulumi.type_token("azure-native:webpubsub:UpstreamAuthType")
class UpstreamAuthType(_builtins.str, Enum):
    NONE = ...
    MANAGED_IDENTITY = ...

@pulumi.type_token("azure-native:webpubsub:WebPubSubRequestType")
class WebPubSubRequestType(_builtins.str, Enum):
    CLIENT_CONNECTION = ...
    SERVER_CONNECTION = ...
    RESTAPI = ...
    TRACE = ...

@pulumi.type_token("azure-native:webpubsub:WebPubSubSkuTier")
class WebPubSubSkuTier(_builtins.str, Enum):
    FREE = ...
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...
