import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AllowedEndpointRecordType",
    "AlwaysServe",
    "EndpointMonitorStatus",
    "EndpointStatus",
    "MonitorProtocol",
    "ProfileMonitorStatus",
    "ProfileStatus",
    "TrafficRoutingMethod",
    "TrafficViewEnrollmentStatus",
]

@pulumi.type_token(...)
class AllowedEndpointRecordType(_builtins.str, Enum):
    DOMAIN_NAME = ...
    I_PV4_ADDRESS = ...
    I_PV6_ADDRESS = ...
    ANY = ...

@pulumi.type_token("azure-native:trafficmanager:AlwaysServe")
class AlwaysServe(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:trafficmanager:EndpointMonitorStatus")
class EndpointMonitorStatus(_builtins.str, Enum):
    CHECKING_ENDPOINT = ...
    ONLINE = ...
    DEGRADED = ...
    DISABLED = ...
    INACTIVE = ...
    STOPPED = ...
    UNMONITORED = ...

@pulumi.type_token("azure-native:trafficmanager:EndpointStatus")
class EndpointStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:trafficmanager:MonitorProtocol")
class MonitorProtocol(_builtins.str, Enum):
    HTTP = ...
    HTTPS = ...
    TCP = ...

@pulumi.type_token("azure-native:trafficmanager:ProfileMonitorStatus")
class ProfileMonitorStatus(_builtins.str, Enum):
    CHECKING_ENDPOINTS = ...
    ONLINE = ...
    DEGRADED = ...
    DISABLED = ...
    INACTIVE = ...

@pulumi.type_token("azure-native:trafficmanager:ProfileStatus")
class ProfileStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:trafficmanager:TrafficRoutingMethod")
class TrafficRoutingMethod(_builtins.str, Enum):
    PERFORMANCE = ...
    PRIORITY = ...
    WEIGHTED = ...
    GEOGRAPHIC = ...
    MULTI_VALUE = ...
    SUBNET = ...

@pulumi.type_token(...)
class TrafficViewEnrollmentStatus(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
