

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['Metric', 'MetricsGranularity', 'NotificationType']
@pulumi.type_token("aws:autoscaling/Metric:Metric")
class Metric(_builtins.str, Enum):
    
    GROUP_MIN_SIZE = ...
    GROUP_MAX_SIZE = ...
    GROUP_DESIRED_CAPACITY = ...
    GROUP_IN_SERVICE_INSTANCES = ...
    GROUP_IN_SERVICE_CAPACITY = ...
    GROUP_PENDING_INSTANCES = ...
    GROUP_PENDING_CAPACITY = ...
    GROUP_STANDBY_INSTANCES = ...
    GROUP_STANDBY_CAPACITY = ...
    GROUP_TERMINATING_INSTANCES = ...
    GROUP_TERMINATING_CAPACITY = ...
    GROUP_TOTAL_INSTANCES = ...
    GROUP_TOTAL_CAPACITY = ...
    WARM_POOL_DESIRED_CAPACITY = ...
    WARM_POOL_WARMED_CAPACITY = ...
    WARM_POOL_PENDING_CAPACITY = ...
    WARM_POOL_TERMINATING_CAPACITY = ...
    WARM_POOL_TOTAL_CAPACITY = ...
    GROUP_AND_WARM_POOL_DESIRED_CAPACITY = ...
    GROUP_AND_WARM_POOL_TOTAL_CAPACITY = ...


@pulumi.type_token(...)
class MetricsGranularity(_builtins.str, Enum):
    
    ONE_MINUTE = ...


@pulumi.type_token("aws:autoscaling/NotificationType:NotificationType")
class NotificationType(_builtins.str, Enum):
    
    INSTANCE_LAUNCH = ...
    INSTANCE_TERMINATE = ...
    INSTANCE_LAUNCH_ERROR = ...
    INSTANCE_TERMINATE_ERROR = ...
    TEST_NOTIFICATION = ...


