

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AzureBareMetalHardwareTypeNamesEnum', 'AzureBareMetalInstancePowerStateEnum', 'AzureBareMetalInstanceSizeNamesEnum', 'ProvisioningState', 'ResourceIdentityType']
@pulumi.type_token(...)
class AzureBareMetalHardwareTypeNamesEnum(_builtins.str, Enum):
    
    CISCO_UCS = ...
    HPE = ...
    SDFLEX = ...


@pulumi.type_token(...)
class AzureBareMetalInstancePowerStateEnum(_builtins.str, Enum):
    
    STARTING = ...
    STARTED = ...
    STOPPING = ...
    STOPPED = ...
    RESTARTING = ...
    UNKNOWN = ...


@pulumi.type_token(...)
class AzureBareMetalInstanceSizeNamesEnum(_builtins.str, Enum):
    
    S72M = ...
    S144M = ...
    S72 = ...
    S144 = ...
    S192 = ...
    S192M = ...
    S192XM = ...
    S96 = ...
    S112 = ...
    S224 = ...
    S224M = ...
    S224OM = ...
    S224OO = ...
    S224OOM = ...
    S224OOO = ...
    S384 = ...
    S384M = ...
    S384XM = ...
    S384XXM = ...
    S448 = ...
    S448M = ...
    S448OM = ...
    S448OO = ...
    S448OOM = ...
    S448OOO = ...
    S448SE = ...
    S576M = ...
    S576XM = ...
    S672 = ...
    S672M = ...
    S672OM = ...
    S672OO = ...
    S672OOM = ...
    S672OOO = ...
    S768 = ...
    S768M = ...
    S768XM = ...
    S896 = ...
    S896M = ...
    S896OM = ...
    S896OO = ...
    S896OOM = ...
    S896OOO = ...
    S960M = ...


@pulumi.type_token(...)
class ProvisioningState(_builtins.str, Enum):
    
    ACCEPTED = ...
    CREATING = ...
    UPDATING = ...
    FAILED = ...
    SUCCEEDED = ...
    DELETING = ...
    CANCELED = ...
    MIGRATING = ...


@pulumi.type_token(...)
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    NONE = ...


