import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "ApplicationArtifactType",
    "ApplicationDefinitionArtifactName",
    "ApplicationLockLevel",
    "ApplicationManagementMode",
    "DeploymentMode",
    "JitApprovalMode",
    "JitApproverType",
    "JitSchedulingType",
    "ResourceIdentityType",
]

@pulumi.type_token("azure-native:solutions:ApplicationArtifactType")
class ApplicationArtifactType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    TEMPLATE = ...
    CUSTOM = ...

@pulumi.type_token(...)
class ApplicationDefinitionArtifactName(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    APPLICATION_RESOURCE_TEMPLATE = ...
    CREATE_UI_DEFINITION = ...
    MAIN_TEMPLATE_PARAMETERS = ...

@pulumi.type_token("azure-native:solutions:ApplicationLockLevel")
class ApplicationLockLevel(_builtins.str, Enum):
    CAN_NOT_DELETE = ...
    READ_ONLY = ...
    NONE = ...

@pulumi.type_token("azure-native:solutions:ApplicationManagementMode")
class ApplicationManagementMode(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    UNMANAGED = ...
    MANAGED = ...

@pulumi.type_token("azure-native:solutions:DeploymentMode")
class DeploymentMode(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    INCREMENTAL = ...
    COMPLETE = ...

@pulumi.type_token("azure-native:solutions:JitApprovalMode")
class JitApprovalMode(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    AUTO_APPROVE = ...
    MANUAL_APPROVE = ...

@pulumi.type_token("azure-native:solutions:JitApproverType")
class JitApproverType(_builtins.str, Enum):
    USER = ...
    GROUP = ...

@pulumi.type_token("azure-native:solutions:JitSchedulingType")
class JitSchedulingType(_builtins.str, Enum):
    NOT_SPECIFIED = ...
    ONCE = ...
    RECURRING = ...

@pulumi.type_token("azure-native:solutions:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...
