

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['DayOfWeek', 'ManagedServiceIdentityType', 'PrivateEndpointServiceConnectionStatus', 'PublicNetworkAccess', 'ReplicationRole', 'SkuFamily', 'SkuName', 'TlsVersion', 'UpdateChannel', 'ZonalAllocationPolicy']
@pulumi.type_token("azure-native:redis:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...
    EVERYDAY = ...
    WEEKEND = ...


@pulumi.type_token("azure-native:redis:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token(...)
class PrivateEndpointServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...


@pulumi.type_token("azure-native:redis:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:redis:ReplicationRole")
class ReplicationRole(_builtins.str, Enum):
    
    PRIMARY = ...
    SECONDARY = ...


@pulumi.type_token("azure-native:redis:SkuFamily")
class SkuFamily(_builtins.str, Enum):
    
    C = ...
    P = ...


@pulumi.type_token("azure-native:redis:SkuName")
class SkuName(_builtins.str, Enum):
    
    BASIC = ...
    STANDARD = ...
    PREMIUM = ...


@pulumi.type_token("azure-native:redis:TlsVersion")
class TlsVersion(_builtins.str, Enum):
    
    TLS_VERSION_1_0 = ...
    TLS_VERSION_1_1 = ...
    TLS_VERSION_1_2 = ...


@pulumi.type_token("azure-native:redis:UpdateChannel")
class UpdateChannel(_builtins.str, Enum):
    
    STABLE = ...
    PREVIEW = ...


@pulumi.type_token("azure-native:redis:ZonalAllocationPolicy")
class ZonalAllocationPolicy(_builtins.str, Enum):
    
    AUTOMATIC = ...
    USER_DEFINED = ...
    NO_ZONES = ...


