import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["Runtime"]

@pulumi.type_token("aws:lambda/Runtime:Runtime")
class Runtime(_builtins.str, Enum):
    DOTNET6 = ...
    DOTNET8 = ...
    DOTNET10 = ...
    JAVA11 = ...
    JAVA17 = ...
    JAVA21 = ...
    JAVA25 = ...
    JAVA8_AL2 = ...
    NODE_JS18D_X = ...
    NODE_JS20D_X = ...
    NODE_JS22D_X = ...
    NODE_JS24D_X = ...
    CUSTOM_AL2 = ...
    CUSTOM_AL2023 = ...
    PYTHON3D10 = ...
    PYTHON3D11 = ...
    PYTHON3D12 = ...
    PYTHON3D13 = ...
    PYTHON3D14 = ...
    PYTHON3D9 = ...
    RUBY3D2 = ...
    RUBY3D3 = ...
    RUBY3D4 = ...
    DOTNET5D0 = ...
    DOTNET7 = ...
    DOTNET_CORE2D1 = ...
    DOTNET_CORE3D1 = ...
    GO1DX = ...
    JAVA8 = ...
    NODE_JS10D_X = ...
    NODE_JS12D_X = ...
    NODE_JS14D_X = ...
    NODE_JS16D_X = ...
    CUSTOM = ...
    PYTHON2D7 = ...
    PYTHON3D6 = ...
    PYTHON3D7 = ...
    PYTHON3D8 = ...
    RUBY2D5 = ...
    RUBY2D7 = ...
