import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AccumulatedType",
    "BudgetNotificationOperatorType",
    "BudgetOperatorType",
    "CategoryType",
    "ChartType",
    "ConnectorBillingModel",
    "ConnectorStatus",
    "CostAllocationPolicyType",
    "CostAllocationResourceType",
    "CultureCode",
    "DaysOfWeek",
    "ExportType",
    "FileFormat",
    "FormatType",
    "Frequency",
    "FunctionType",
    "GranularityType",
    "KpiTypeType",
    "MetricType",
    "OperatorType",
    "PivotTypeType",
    "QueryColumnType",
    "RecurrenceType",
    "ReportColumnType",
    "ReportConfigSortingType",
    "ReportGranularityType",
    "ReportTimeframeType",
    "ReportType",
    "RuleStatus",
    "ScheduleFrequency",
    "ScheduledActionKind",
    "ScheduledActionStatus",
    "SettingsKind",
    "StatusType",
    "SystemAssignedServiceIdentityType",
    "ThresholdType",
    "TimeGrainType",
    "TimeframeType",
    "WeeksOfMonth",
]

@pulumi.type_token("azure-native:costmanagement:AccumulatedType")
class AccumulatedType(_builtins.str, Enum):
    TRUE = ...
    FALSE = ...

@pulumi.type_token(...)
class BudgetNotificationOperatorType(_builtins.str, Enum):
    EQUAL_TO = ...
    GREATER_THAN = ...
    GREATER_THAN_OR_EQUAL_TO = ...
    LESS_THAN = ...

@pulumi.type_token("azure-native:costmanagement:BudgetOperatorType")
class BudgetOperatorType(_builtins.str, Enum):
    IN_ = ...

@pulumi.type_token("azure-native:costmanagement:CategoryType")
class CategoryType(_builtins.str, Enum):
    COST = ...
    RESERVATION_UTILIZATION = ...

@pulumi.type_token("azure-native:costmanagement:ChartType")
class ChartType(_builtins.str, Enum):
    AREA = ...
    LINE = ...
    STACKED_COLUMN = ...
    GROUPED_COLUMN = ...
    TABLE = ...

@pulumi.type_token("azure-native:costmanagement:ConnectorBillingModel")
class ConnectorBillingModel(_builtins.str, Enum):
    TRIAL = ...
    AUTO_UPGRADE = ...
    PREMIUM = ...
    EXPIRED = ...

@pulumi.type_token("azure-native:costmanagement:ConnectorStatus")
class ConnectorStatus(_builtins.str, Enum):
    ACTIVE = ...
    ERROR = ...
    SUSPENDED = ...

@pulumi.type_token(...)
class CostAllocationPolicyType(_builtins.str, Enum):
    FIXED_PROPORTION = ...

@pulumi.type_token(...)
class CostAllocationResourceType(_builtins.str, Enum):
    DIMENSION = ...
    TAG = ...

@pulumi.type_token("azure-native:costmanagement:CultureCode")
class CultureCode(_builtins.str, Enum):
    EN_US = ...
    JA_JP = ...
    ZH_CN = ...
    DE_DE = ...
    ES_ES = ...
    FR_FR = ...
    IT_IT = ...
    KO_KR = ...
    PT_BR = ...
    RU_RU = ...
    ZH_TW = ...
    CS_CZ = ...
    PL_PL = ...
    TR_TR = ...
    DA_DK = ...
    EN_GB = ...
    HU_HU = ...
    NB_NO = ...
    NL_NL = ...
    PT_PT = ...
    SV_SE = ...

@pulumi.type_token("azure-native:costmanagement:DaysOfWeek")
class DaysOfWeek(_builtins.str, Enum):
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...
    SUNDAY = ...

@pulumi.type_token("azure-native:costmanagement:ExportType")
class ExportType(_builtins.str, Enum):
    USAGE = ...
    ACTUAL_COST = ...
    AMORTIZED_COST = ...

@pulumi.type_token("azure-native:costmanagement:FileFormat")
class FileFormat(_builtins.str, Enum):
    CSV = ...

@pulumi.type_token("azure-native:costmanagement:FormatType")
class FormatType(_builtins.str, Enum):
    CSV = ...

@pulumi.type_token("azure-native:costmanagement:Frequency")
class Frequency(_builtins.str, Enum):
    DAILY = ...
    WEEKLY = ...
    MONTHLY = ...

@pulumi.type_token("azure-native:costmanagement:FunctionType")
class FunctionType(_builtins.str, Enum):
    SUM = ...

@pulumi.type_token("azure-native:costmanagement:GranularityType")
class GranularityType(_builtins.str, Enum):
    DAILY = ...
    HOURLY = ...

@pulumi.type_token("azure-native:costmanagement:KpiTypeType")
class KpiTypeType(_builtins.str, Enum):
    FORECAST = ...
    BUDGET = ...

@pulumi.type_token("azure-native:costmanagement:MetricType")
class MetricType(_builtins.str, Enum):
    ACTUAL_COST = ...
    AMORTIZED_COST = ...
    AHUB = ...

@pulumi.type_token("azure-native:costmanagement:OperatorType")
class OperatorType(_builtins.str, Enum):
    IN_ = ...
    CONTAINS = ...

@pulumi.type_token("azure-native:costmanagement:PivotTypeType")
class PivotTypeType(_builtins.str, Enum):
    DIMENSION = ...
    TAG_KEY = ...

@pulumi.type_token("azure-native:costmanagement:QueryColumnType")
class QueryColumnType(_builtins.str, Enum):
    TAG_KEY = ...
    DIMENSION = ...

@pulumi.type_token("azure-native:costmanagement:RecurrenceType")
class RecurrenceType(_builtins.str, Enum):
    DAILY = ...
    WEEKLY = ...
    MONTHLY = ...
    ANNUALLY = ...

@pulumi.type_token("azure-native:costmanagement:ReportColumnType")
class ReportColumnType(_builtins.str, Enum):
    TAG = ...
    DIMENSION = ...

@pulumi.type_token(...)
class ReportConfigSortingType(_builtins.str, Enum):
    ASCENDING = ...
    DESCENDING = ...

@pulumi.type_token("azure-native:costmanagement:ReportGranularityType")
class ReportGranularityType(_builtins.str, Enum):
    DAILY = ...
    MONTHLY = ...

@pulumi.type_token("azure-native:costmanagement:ReportTimeframeType")
class ReportTimeframeType(_builtins.str, Enum):
    WEEK_TO_DATE = ...
    MONTH_TO_DATE = ...
    YEAR_TO_DATE = ...
    CUSTOM = ...

@pulumi.type_token("azure-native:costmanagement:ReportType")
class ReportType(_builtins.str, Enum):
    USAGE = ...

@pulumi.type_token("azure-native:costmanagement:RuleStatus")
class RuleStatus(_builtins.str, Enum):
    NOT_ACTIVE = ...
    ACTIVE = ...
    PROCESSING = ...

@pulumi.type_token("azure-native:costmanagement:ScheduleFrequency")
class ScheduleFrequency(_builtins.str, Enum):
    DAILY = ...
    WEEKLY = ...
    MONTHLY = ...

@pulumi.type_token("azure-native:costmanagement:ScheduledActionKind")
class ScheduledActionKind(_builtins.str, Enum):
    EMAIL = ...
    INSIGHT_ALERT = ...

@pulumi.type_token("azure-native:costmanagement:ScheduledActionStatus")
class ScheduledActionStatus(_builtins.str, Enum):
    DISABLED = ...
    ENABLED = ...
    EXPIRED = ...

@pulumi.type_token("azure-native:costmanagement:SettingsKind")
class SettingsKind(_builtins.str, Enum):
    TAGINHERITANCE = ...

@pulumi.type_token("azure-native:costmanagement:StatusType")
class StatusType(_builtins.str, Enum):
    ACTIVE = ...
    INACTIVE = ...

@pulumi.type_token(...)
class SystemAssignedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...

@pulumi.type_token("azure-native:costmanagement:ThresholdType")
class ThresholdType(_builtins.str, Enum):
    ACTUAL = ...
    FORECASTED = ...

@pulumi.type_token("azure-native:costmanagement:TimeGrainType")
class TimeGrainType(_builtins.str, Enum):
    MONTHLY = ...
    QUARTERLY = ...
    ANNUALLY = ...
    BILLING_MONTH = ...
    BILLING_QUARTER = ...
    BILLING_ANNUAL = ...
    LAST7_DAYS = ...
    LAST30_DAYS = ...

@pulumi.type_token("azure-native:costmanagement:TimeframeType")
class TimeframeType(_builtins.str, Enum):
    WEEK_TO_DATE = ...
    MONTH_TO_DATE = ...
    CUSTOM = ...

@pulumi.type_token("azure-native:costmanagement:WeeksOfMonth")
class WeeksOfMonth(_builtins.str, Enum):
    FIRST = ...
    SECOND = ...
    THIRD = ...
    FOURTH = ...
    LAST = ...
