import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    "AKSVolumeTypes",
    "AbsoluteMarker",
    "AlertsState",
    "CrossRegionRestoreState",
    "CrossSubscriptionRestoreState",
    "DataStoreTypes",
    "DayOfWeek",
    "EncryptionState",
    "IdentityType",
    "ImmutabilityState",
    "InfrastructureEncryptionState",
    "Month",
    "ResourcePropertiesObjectType",
    "SecretStoreType",
    "SoftDeleteState",
    "StorageSettingStoreTypes",
    "StorageSettingTypes",
    "ValidationType",
    "WeekNumber",
]

@pulumi.type_token("azure-native:dataprotection:AKSVolumeTypes")
class AKSVolumeTypes(_builtins.str, Enum):
    AZURE_DISK = ...
    AZURE_FILE_SHARE_SMB = ...

@pulumi.type_token("azure-native:dataprotection:AbsoluteMarker")
class AbsoluteMarker(_builtins.str, Enum):
    ALL_BACKUP = ...
    FIRST_OF_DAY = ...
    FIRST_OF_MONTH = ...
    FIRST_OF_WEEK = ...
    FIRST_OF_YEAR = ...

@pulumi.type_token("azure-native:dataprotection:AlertsState")
class AlertsState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token(...)
class CrossRegionRestoreState(_builtins.str, Enum):
    DISABLED = ...
    ENABLED = ...

@pulumi.type_token(...)
class CrossSubscriptionRestoreState(_builtins.str, Enum):
    DISABLED = ...
    PERMANENTLY_DISABLED = ...
    ENABLED = ...

@pulumi.type_token("azure-native:dataprotection:DataStoreTypes")
class DataStoreTypes(_builtins.str, Enum):
    OPERATIONAL_STORE = ...
    VAULT_STORE = ...
    ARCHIVE_STORE = ...

@pulumi.type_token("azure-native:dataprotection:DayOfWeek")
class DayOfWeek(_builtins.str, Enum):
    FRIDAY = ...
    MONDAY = ...
    SATURDAY = ...
    SUNDAY = ...
    THURSDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...

@pulumi.type_token("azure-native:dataprotection:EncryptionState")
class EncryptionState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...
    INCONSISTENT = ...

@pulumi.type_token("azure-native:dataprotection:IdentityType")
class IdentityType(_builtins.str, Enum):
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...

@pulumi.type_token("azure-native:dataprotection:ImmutabilityState")
class ImmutabilityState(_builtins.str, Enum):
    DISABLED = ...
    UNLOCKED = ...
    LOCKED = ...

@pulumi.type_token(...)
class InfrastructureEncryptionState(_builtins.str, Enum):
    ENABLED = ...
    DISABLED = ...

@pulumi.type_token("azure-native:dataprotection:Month")
class Month(_builtins.str, Enum):
    APRIL = ...
    AUGUST = ...
    DECEMBER = ...
    FEBRUARY = ...
    JANUARY = ...
    JULY = ...
    JUNE = ...
    MARCH = ...
    MAY = ...
    NOVEMBER = ...
    OCTOBER = ...
    SEPTEMBER = ...

@pulumi.type_token(...)
class ResourcePropertiesObjectType(_builtins.str, Enum):
    DEFAULT_RESOURCE_PROPERTIES = ...

@pulumi.type_token("azure-native:dataprotection:SecretStoreType")
class SecretStoreType(_builtins.str, Enum):
    INVALID = ...
    AZURE_KEY_VAULT = ...

@pulumi.type_token("azure-native:dataprotection:SoftDeleteState")
class SoftDeleteState(_builtins.str, Enum):
    OFF = ...
    ON = ...
    ALWAYS_ON = ...

@pulumi.type_token(...)
class StorageSettingStoreTypes(_builtins.str, Enum):
    ARCHIVE_STORE = ...
    OPERATIONAL_STORE = ...
    VAULT_STORE = ...

@pulumi.type_token("azure-native:dataprotection:StorageSettingTypes")
class StorageSettingTypes(_builtins.str, Enum):
    GEO_REDUNDANT = ...
    LOCALLY_REDUNDANT = ...
    ZONE_REDUNDANT = ...

@pulumi.type_token("azure-native:dataprotection:ValidationType")
class ValidationType(_builtins.str, Enum):
    SHALLOW_VALIDATION = ...
    DEEP_VALIDATION = ...

@pulumi.type_token("azure-native:dataprotection:WeekNumber")
class WeekNumber(_builtins.str, Enum):
    FIRST = ...
    FOURTH = ...
    LAST = ...
    SECOND = ...
    THIRD = ...
