import builtins as _builtins
import sys
import pulumi
from typing import Any, Mapping, Optional, Sequence
from . import outputs
from ._enums import *

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "AbsoluteDeleteOptionResponse",
    "AdhocBasedTaggingCriteriaResponse",
    "AdhocBasedTriggerContextResponse",
    "AzureBackupParamsResponse",
    "AzureBackupRuleResponse",
    "AzureMonitorAlertSettingsResponse",
    "AzureOperationalStoreParametersResponse",
    "AzureRetentionRuleResponse",
    "BackupInstanceResponse",
    "BackupPolicyResponse",
    "BackupScheduleResponse",
    "BackupVaultResponse",
    "BlobBackupDatasourceParametersResponse",
    "CmkKekIdentityResponse",
    "CmkKeyVaultPropertiesResponse",
    "CopyOnExpiryOptionResponse",
    "CrossRegionRestoreSettingsResponse",
    "CrossSubscriptionRestoreSettingsResponse",
    "CustomCopyOptionResponse",
    "DataStoreInfoBaseResponse",
    "DatasourceResponse",
    "DatasourceSetResponse",
    "DayResponse",
    "DefaultResourcePropertiesResponse",
    "DppIdentityDetailsResponse",
    "EncryptionSettingsResponse",
    "FeatureSettingsResponse",
    "IdentityDetailsResponse",
    "ImmediateCopyOptionResponse",
    "ImmutabilitySettingsResponse",
    "InnerErrorResponse",
    ...,
    "MonitoringSettingsResponse",
    "NamespacedNameResourceResponse",
    "PolicyInfoResponse",
    "PolicyParametersResponse",
    "ProtectionStatusDetailsResponse",
    "ResourceGuardOperationDetailResponse",
    "ResourceGuardOperationResponse",
    "ResourceGuardProxyBaseResponse",
    "ResourceGuardResponse",
    "ResourceMoveDetailsResponse",
    "RetentionTagResponse",
    "ScheduleBasedBackupCriteriaResponse",
    "ScheduleBasedTriggerContextResponse",
    "SecretStoreBasedAuthCredentialsResponse",
    "SecretStoreResourceResponse",
    "SecuritySettingsResponse",
    "SoftDeleteSettingsResponse",
    "SourceLifeCycleResponse",
    "StorageSettingResponse",
    "SystemDataResponse",
    "TaggingCriteriaResponse",
    "TargetCopySettingResponse",
    "UserAssignedIdentityResponse",
    "UserFacingErrorResponse",
]

@pulumi.output_type
class AbsoluteDeleteOptionResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, duration: _builtins.str, object_type: _builtins.str
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def duration(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class AdhocBasedTaggingCriteriaResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, tag_info: Optional[outputs.RetentionTagResponse] = ...
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="tagInfo")
    def tag_info(self) -> Optional[outputs.RetentionTagResponse]: ...

@pulumi.output_type
class AdhocBasedTriggerContextResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        object_type: _builtins.str,
        tagging_criteria: outputs.AdhocBasedTaggingCriteriaResponse,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="taggingCriteria")
    def tagging_criteria(self) -> outputs.AdhocBasedTaggingCriteriaResponse: ...

@pulumi.output_type
class AzureBackupParamsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, backup_type: _builtins.str, object_type: _builtins.str
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="backupType")
    def backup_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class AzureBackupRuleResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        data_store: outputs.DataStoreInfoBaseResponse,
        name: _builtins.str,
        object_type: _builtins.str,
        trigger: Any,
        backup_parameters: Optional[outputs.AzureBackupParamsResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="dataStore")
    def data_store(self) -> outputs.DataStoreInfoBaseResponse: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def trigger(self) -> Any: ...
    @_builtins.property
    @pulumi.getter(name="backupParameters")
    def backup_parameters(self) -> Optional[outputs.AzureBackupParamsResponse]: ...

@pulumi.output_type
class AzureMonitorAlertSettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, alerts_for_all_job_failures: Optional[_builtins.str] = ...
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="alertsForAllJobFailures")
    def alerts_for_all_job_failures(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class AzureOperationalStoreParametersResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        data_store_type: _builtins.str,
        object_type: _builtins.str,
        resource_group_id: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="dataStoreType")
    def data_store_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="resourceGroupId")
    def resource_group_id(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class AzureRetentionRuleResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        lifecycles: Sequence[outputs.SourceLifeCycleResponse],
        name: _builtins.str,
        object_type: _builtins.str,
        is_default: Optional[_builtins.bool] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def lifecycles(self) -> Sequence[outputs.SourceLifeCycleResponse]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="isDefault")
    def is_default(self) -> Optional[_builtins.bool]: ...

@pulumi.output_type
class BackupInstanceResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        current_protection_state: _builtins.str,
        data_source_info: outputs.DatasourceResponse,
        object_type: _builtins.str,
        policy_info: outputs.PolicyInfoResponse,
        protection_error_details: outputs.UserFacingErrorResponse,
        protection_status: outputs.ProtectionStatusDetailsResponse,
        provisioning_state: _builtins.str,
        data_source_set_info: Optional[outputs.DatasourceSetResponse] = ...,
        datasource_auth_credentials: Optional[
            outputs.SecretStoreBasedAuthCredentialsResponse
        ] = ...,
        friendly_name: Optional[_builtins.str] = ...,
        identity_details: Optional[outputs.IdentityDetailsResponse] = ...,
        resource_guard_operation_requests: Optional[Sequence[_builtins.str]] = ...,
        validation_type: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="currentProtectionState")
    def current_protection_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="dataSourceInfo")
    def data_source_info(self) -> outputs.DatasourceResponse: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="policyInfo")
    def policy_info(self) -> outputs.PolicyInfoResponse: ...
    @_builtins.property
    @pulumi.getter(name="protectionErrorDetails")
    def protection_error_details(self) -> outputs.UserFacingErrorResponse: ...
    @_builtins.property
    @pulumi.getter(name="protectionStatus")
    def protection_status(self) -> outputs.ProtectionStatusDetailsResponse: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="dataSourceSetInfo")
    def data_source_set_info(self) -> Optional[outputs.DatasourceSetResponse]: ...
    @_builtins.property
    @pulumi.getter(name="datasourceAuthCredentials")
    def datasource_auth_credentials(
        self,
    ) -> Optional[outputs.SecretStoreBasedAuthCredentialsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="friendlyName")
    def friendly_name(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="identityDetails")
    def identity_details(self) -> Optional[outputs.IdentityDetailsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="resourceGuardOperationRequests")
    def resource_guard_operation_requests(
        self,
    ) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="validationType")
    def validation_type(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class BackupPolicyResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        datasource_types: Sequence[_builtins.str],
        object_type: _builtins.str,
        policy_rules: Sequence[Any],
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="datasourceTypes")
    def datasource_types(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="policyRules")
    def policy_rules(self) -> Sequence[Any]: ...

@pulumi.output_type
class BackupScheduleResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        repeating_time_intervals: Sequence[_builtins.str],
        time_zone: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="repeatingTimeIntervals")
    def repeating_time_intervals(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="timeZone")
    def time_zone(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class BackupVaultResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        bcdr_security_level: _builtins.str,
        is_vault_protected_by_resource_guard: _builtins.bool,
        provisioning_state: _builtins.str,
        resource_move_details: outputs.ResourceMoveDetailsResponse,
        resource_move_state: _builtins.str,
        secure_score: _builtins.str,
        storage_settings: Sequence[outputs.StorageSettingResponse],
        feature_settings: Optional[outputs.FeatureSettingsResponse] = ...,
        monitoring_settings: Optional[outputs.MonitoringSettingsResponse] = ...,
        replicated_regions: Optional[Sequence[_builtins.str]] = ...,
        resource_guard_operation_requests: Optional[Sequence[_builtins.str]] = ...,
        security_settings: Optional[outputs.SecuritySettingsResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="bcdrSecurityLevel")
    def bcdr_security_level(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="isVaultProtectedByResourceGuard")
    def is_vault_protected_by_resource_guard(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="resourceMoveDetails")
    def resource_move_details(self) -> outputs.ResourceMoveDetailsResponse: ...
    @_builtins.property
    @pulumi.getter(name="resourceMoveState")
    def resource_move_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="secureScore")
    def secure_score(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="storageSettings")
    def storage_settings(self) -> Sequence[outputs.StorageSettingResponse]: ...
    @_builtins.property
    @pulumi.getter(name="featureSettings")
    def feature_settings(self) -> Optional[outputs.FeatureSettingsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="monitoringSettings")
    def monitoring_settings(self) -> Optional[outputs.MonitoringSettingsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="replicatedRegions")
    def replicated_regions(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="resourceGuardOperationRequests")
    def resource_guard_operation_requests(
        self,
    ) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="securitySettings")
    def security_settings(self) -> Optional[outputs.SecuritySettingsResponse]: ...

@pulumi.output_type
class BlobBackupDatasourceParametersResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        containers_list: Sequence[_builtins.str],
        object_type: _builtins.str,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="containersList")
    def containers_list(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class CmkKekIdentityResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        identity_id: Optional[_builtins.str] = ...,
        identity_type: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="identityId")
    def identity_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="identityType")
    def identity_type(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class CmkKeyVaultPropertiesResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(__self__, *, key_uri: Optional[_builtins.str] = ...) -> None: ...
    @_builtins.property
    @pulumi.getter(name="keyUri")
    def key_uri(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class CopyOnExpiryOptionResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(__self__, *, object_type: _builtins.str) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class CrossRegionRestoreSettingsResponse(dict):
    def __init__(__self__, *, state: Optional[_builtins.str] = ...) -> None: ...
    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class CrossSubscriptionRestoreSettingsResponse(dict):
    def __init__(__self__, *, state: Optional[_builtins.str] = ...) -> None: ...
    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class CustomCopyOptionResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, object_type: _builtins.str, duration: Optional[_builtins.str] = ...
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def duration(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class DataStoreInfoBaseResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, data_store_type: _builtins.str, object_type: _builtins.str
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="dataStoreType")
    def data_store_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class DatasourceResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        resource_id: _builtins.str,
        datasource_type: Optional[_builtins.str] = ...,
        object_type: Optional[_builtins.str] = ...,
        resource_location: Optional[_builtins.str] = ...,
        resource_name: Optional[_builtins.str] = ...,
        resource_properties: Optional[outputs.DefaultResourcePropertiesResponse] = ...,
        resource_type: Optional[_builtins.str] = ...,
        resource_uri: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="resourceID")
    def resource_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="datasourceType")
    def datasource_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceLocation")
    def resource_location(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceName")
    def resource_name(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceProperties")
    def resource_properties(
        self,
    ) -> Optional[outputs.DefaultResourcePropertiesResponse]: ...
    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceUri")
    def resource_uri(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class DatasourceSetResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        resource_id: _builtins.str,
        datasource_type: Optional[_builtins.str] = ...,
        object_type: Optional[_builtins.str] = ...,
        resource_location: Optional[_builtins.str] = ...,
        resource_name: Optional[_builtins.str] = ...,
        resource_properties: Optional[outputs.DefaultResourcePropertiesResponse] = ...,
        resource_type: Optional[_builtins.str] = ...,
        resource_uri: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="resourceID")
    def resource_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="datasourceType")
    def datasource_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceLocation")
    def resource_location(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceName")
    def resource_name(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceProperties")
    def resource_properties(
        self,
    ) -> Optional[outputs.DefaultResourcePropertiesResponse]: ...
    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceUri")
    def resource_uri(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class DayResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        date: Optional[_builtins.int] = ...,
        is_last: Optional[_builtins.bool] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def date(self) -> Optional[_builtins.int]: ...
    @_builtins.property
    @pulumi.getter(name="isLast")
    def is_last(self) -> Optional[_builtins.bool]: ...

@pulumi.output_type
class DefaultResourcePropertiesResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(__self__, *, object_type: _builtins.str) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class DppIdentityDetailsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        principal_id: _builtins.str,
        tenant_id: _builtins.str,
        type: Optional[_builtins.str] = ...,
        user_assigned_identities: Optional[
            Mapping[str, outputs.UserAssignedIdentityResponse]
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="principalId")
    def principal_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="userAssignedIdentities")
    def user_assigned_identities(
        self,
    ) -> Optional[Mapping[str, outputs.UserAssignedIdentityResponse]]: ...

@pulumi.output_type
class EncryptionSettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        infrastructure_encryption: Optional[_builtins.str] = ...,
        kek_identity: Optional[outputs.CmkKekIdentityResponse] = ...,
        key_vault_properties: Optional[outputs.CmkKeyVaultPropertiesResponse] = ...,
        state: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="infrastructureEncryption")
    def infrastructure_encryption(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="kekIdentity")
    def kek_identity(self) -> Optional[outputs.CmkKekIdentityResponse]: ...
    @_builtins.property
    @pulumi.getter(name="keyVaultProperties")
    def key_vault_properties(
        self,
    ) -> Optional[outputs.CmkKeyVaultPropertiesResponse]: ...
    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class FeatureSettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        cross_region_restore_settings: Optional[
            outputs.CrossRegionRestoreSettingsResponse
        ] = ...,
        cross_subscription_restore_settings: Optional[
            outputs.CrossSubscriptionRestoreSettingsResponse
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="crossRegionRestoreSettings")
    def cross_region_restore_settings(
        self,
    ) -> Optional[outputs.CrossRegionRestoreSettingsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="crossSubscriptionRestoreSettings")
    def cross_subscription_restore_settings(
        self,
    ) -> Optional[outputs.CrossSubscriptionRestoreSettingsResponse]: ...

@pulumi.output_type
class IdentityDetailsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        use_system_assigned_identity: Optional[_builtins.bool] = ...,
        user_assigned_identity_arm_url: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="useSystemAssignedIdentity")
    def use_system_assigned_identity(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="userAssignedIdentityArmUrl")
    def user_assigned_identity_arm_url(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class ImmediateCopyOptionResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(__self__, *, object_type: _builtins.str) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...

@pulumi.output_type
class ImmutabilitySettingsResponse(dict):
    def __init__(__self__, *, state: Optional[_builtins.str] = ...) -> None: ...
    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class InnerErrorResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        additional_info: Optional[Mapping[str, _builtins.str]] = ...,
        code: Optional[_builtins.str] = ...,
        embedded_inner_error: Optional[outputs.InnerErrorResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="additionalInfo")
    def additional_info(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def code(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="embeddedInnerError")
    def embedded_inner_error(self) -> Optional[outputs.InnerErrorResponse]: ...

@pulumi.output_type
class KubernetesClusterBackupDatasourceParametersResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        include_cluster_scope_resources: _builtins.bool,
        object_type: _builtins.str,
        snapshot_volumes: _builtins.bool,
        backup_hook_references: Optional[
            Sequence[outputs.NamespacedNameResourceResponse]
        ] = ...,
        excluded_namespaces: Optional[Sequence[_builtins.str]] = ...,
        excluded_resource_types: Optional[Sequence[_builtins.str]] = ...,
        included_namespaces: Optional[Sequence[_builtins.str]] = ...,
        included_resource_types: Optional[Sequence[_builtins.str]] = ...,
        included_volume_types: Optional[Sequence[_builtins.str]] = ...,
        label_selectors: Optional[Sequence[_builtins.str]] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="includeClusterScopeResources")
    def include_cluster_scope_resources(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="snapshotVolumes")
    def snapshot_volumes(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="backupHookReferences")
    def backup_hook_references(
        self,
    ) -> Optional[Sequence[outputs.NamespacedNameResourceResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="excludedNamespaces")
    def excluded_namespaces(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="excludedResourceTypes")
    def excluded_resource_types(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="includedNamespaces")
    def included_namespaces(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="includedResourceTypes")
    def included_resource_types(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="includedVolumeTypes")
    def included_volume_types(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="labelSelectors")
    def label_selectors(self) -> Optional[Sequence[_builtins.str]]: ...

@pulumi.output_type
class MonitoringSettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        azure_monitor_alert_settings: Optional[
            outputs.AzureMonitorAlertSettingsResponse
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="azureMonitorAlertSettings")
    def azure_monitor_alert_settings(
        self,
    ) -> Optional[outputs.AzureMonitorAlertSettingsResponse]: ...

@pulumi.output_type
class NamespacedNameResourceResponse(dict):
    def __init__(
        __self__,
        *,
        name: Optional[_builtins.str] = ...,
        namespace: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def namespace(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class PolicyInfoResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        policy_id: _builtins.str,
        policy_version: _builtins.str,
        policy_parameters: Optional[outputs.PolicyParametersResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="policyId")
    def policy_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="policyVersion")
    def policy_version(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="policyParameters")
    def policy_parameters(self) -> Optional[outputs.PolicyParametersResponse]: ...

@pulumi.output_type
class PolicyParametersResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        backup_datasource_parameters_list: Optional[Sequence[Any]] = ...,
        data_store_parameters_list: Optional[
            Sequence[outputs.AzureOperationalStoreParametersResponse]
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="backupDatasourceParametersList")
    def backup_datasource_parameters_list(self) -> Optional[Sequence[Any]]: ...
    @_builtins.property
    @pulumi.getter(name="dataStoreParametersList")
    def data_store_parameters_list(
        self,
    ) -> Optional[Sequence[outputs.AzureOperationalStoreParametersResponse]]: ...

@pulumi.output_type
class ProtectionStatusDetailsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        error_details: Optional[outputs.UserFacingErrorResponse] = ...,
        status: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="errorDetails")
    def error_details(self) -> Optional[outputs.UserFacingErrorResponse]: ...
    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class ResourceGuardOperationDetailResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        default_resource_request: Optional[_builtins.str] = ...,
        vault_critical_operation: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="defaultResourceRequest")
    def default_resource_request(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="vaultCriticalOperation")
    def vault_critical_operation(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class ResourceGuardOperationResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        request_resource_type: _builtins.str,
        vault_critical_operation: _builtins.str,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="requestResourceType")
    def request_resource_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="vaultCriticalOperation")
    def vault_critical_operation(self) -> _builtins.str: ...

@pulumi.output_type
class ResourceGuardProxyBaseResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        description: Optional[_builtins.str] = ...,
        last_updated_time: Optional[_builtins.str] = ...,
        resource_guard_operation_details: Optional[
            Sequence[outputs.ResourceGuardOperationDetailResponse]
        ] = ...,
        resource_guard_resource_id: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="lastUpdatedTime")
    def last_updated_time(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="resourceGuardOperationDetails")
    def resource_guard_operation_details(
        self,
    ) -> Optional[Sequence[outputs.ResourceGuardOperationDetailResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="resourceGuardResourceId")
    def resource_guard_resource_id(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class ResourceGuardResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        allow_auto_approvals: _builtins.bool,
        description: _builtins.str,
        provisioning_state: _builtins.str,
        resource_guard_operations: Sequence[outputs.ResourceGuardOperationResponse],
        vault_critical_operation_exclusion_list: Optional[
            Sequence[_builtins.str]
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="allowAutoApprovals")
    def allow_auto_approvals(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="provisioningState")
    def provisioning_state(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="resourceGuardOperations")
    def resource_guard_operations(
        self,
    ) -> Sequence[outputs.ResourceGuardOperationResponse]: ...
    @_builtins.property
    @pulumi.getter(name="vaultCriticalOperationExclusionList")
    def vault_critical_operation_exclusion_list(
        self,
    ) -> Optional[Sequence[_builtins.str]]: ...

@pulumi.output_type
class ResourceMoveDetailsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        completion_time_utc: Optional[_builtins.str] = ...,
        operation_id: Optional[_builtins.str] = ...,
        source_resource_path: Optional[_builtins.str] = ...,
        start_time_utc: Optional[_builtins.str] = ...,
        target_resource_path: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="completionTimeUtc")
    def completion_time_utc(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="operationId")
    def operation_id(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="sourceResourcePath")
    def source_resource_path(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="startTimeUtc")
    def start_time_utc(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="targetResourcePath")
    def target_resource_path(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class RetentionTagResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, e_tag: _builtins.str, id: _builtins.str, tag_name: _builtins.str
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="eTag")
    def e_tag(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="tagName")
    def tag_name(self) -> _builtins.str: ...

@pulumi.output_type
class ScheduleBasedBackupCriteriaResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        object_type: _builtins.str,
        absolute_criteria: Optional[Sequence[_builtins.str]] = ...,
        days_of_month: Optional[Sequence[outputs.DayResponse]] = ...,
        days_of_the_week: Optional[Sequence[_builtins.str]] = ...,
        months_of_year: Optional[Sequence[_builtins.str]] = ...,
        schedule_times: Optional[Sequence[_builtins.str]] = ...,
        weeks_of_the_month: Optional[Sequence[_builtins.str]] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="absoluteCriteria")
    def absolute_criteria(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="daysOfMonth")
    def days_of_month(self) -> Optional[Sequence[outputs.DayResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="daysOfTheWeek")
    def days_of_the_week(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="monthsOfYear")
    def months_of_year(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="scheduleTimes")
    def schedule_times(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="weeksOfTheMonth")
    def weeks_of_the_month(self) -> Optional[Sequence[_builtins.str]]: ...

@pulumi.output_type
class ScheduleBasedTriggerContextResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        object_type: _builtins.str,
        schedule: outputs.BackupScheduleResponse,
        tagging_criteria: Sequence[outputs.TaggingCriteriaResponse],
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def schedule(self) -> outputs.BackupScheduleResponse: ...
    @_builtins.property
    @pulumi.getter(name="taggingCriteria")
    def tagging_criteria(self) -> Sequence[outputs.TaggingCriteriaResponse]: ...

@pulumi.output_type
class SecretStoreBasedAuthCredentialsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        object_type: _builtins.str,
        secret_store_resource: Optional[outputs.SecretStoreResourceResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="objectType")
    def object_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="secretStoreResource")
    def secret_store_resource(
        self,
    ) -> Optional[outputs.SecretStoreResourceResponse]: ...

@pulumi.output_type
class SecretStoreResourceResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        secret_store_type: _builtins.str,
        uri: Optional[_builtins.str] = ...,
        value: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="secretStoreType")
    def secret_store_type(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def uri(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class SecuritySettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        encryption_settings: Optional[outputs.EncryptionSettingsResponse] = ...,
        immutability_settings: Optional[outputs.ImmutabilitySettingsResponse] = ...,
        soft_delete_settings: Optional[outputs.SoftDeleteSettingsResponse] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="encryptionSettings")
    def encryption_settings(self) -> Optional[outputs.EncryptionSettingsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="immutabilitySettings")
    def immutability_settings(
        self,
    ) -> Optional[outputs.ImmutabilitySettingsResponse]: ...
    @_builtins.property
    @pulumi.getter(name="softDeleteSettings")
    def soft_delete_settings(self) -> Optional[outputs.SoftDeleteSettingsResponse]: ...

@pulumi.output_type
class SoftDeleteSettingsResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        retention_duration_in_days: Optional[_builtins.float] = ...,
        state: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="retentionDurationInDays")
    def retention_duration_in_days(self) -> Optional[_builtins.float]: ...
    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class SourceLifeCycleResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        delete_after: outputs.AbsoluteDeleteOptionResponse,
        source_data_store: outputs.DataStoreInfoBaseResponse,
        target_data_store_copy_settings: Optional[
            Sequence[outputs.TargetCopySettingResponse]
        ] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="deleteAfter")
    def delete_after(self) -> outputs.AbsoluteDeleteOptionResponse: ...
    @_builtins.property
    @pulumi.getter(name="sourceDataStore")
    def source_data_store(self) -> outputs.DataStoreInfoBaseResponse: ...
    @_builtins.property
    @pulumi.getter(name="targetDataStoreCopySettings")
    def target_data_store_copy_settings(
        self,
    ) -> Optional[Sequence[outputs.TargetCopySettingResponse]]: ...

@pulumi.output_type
class StorageSettingResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        datastore_type: Optional[_builtins.str] = ...,
        type: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="datastoreType")
    def datastore_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class SystemDataResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        created_at: Optional[_builtins.str] = ...,
        created_by: Optional[_builtins.str] = ...,
        created_by_type: Optional[_builtins.str] = ...,
        last_modified_at: Optional[_builtins.str] = ...,
        last_modified_by: Optional[_builtins.str] = ...,
        last_modified_by_type: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="createdBy")
    def created_by(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="createdByType")
    def created_by_type(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="lastModifiedAt")
    def last_modified_at(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="lastModifiedBy")
    def last_modified_by(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter(name="lastModifiedByType")
    def last_modified_by_type(self) -> Optional[_builtins.str]: ...

@pulumi.output_type
class TaggingCriteriaResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        is_default: _builtins.bool,
        tag_info: outputs.RetentionTagResponse,
        tagging_priority: _builtins.float,
        criteria: Optional[Sequence[outputs.ScheduleBasedBackupCriteriaResponse]] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="isDefault")
    def is_default(self) -> _builtins.bool: ...
    @_builtins.property
    @pulumi.getter(name="tagInfo")
    def tag_info(self) -> outputs.RetentionTagResponse: ...
    @_builtins.property
    @pulumi.getter(name="taggingPriority")
    def tagging_priority(self) -> _builtins.float: ...
    @_builtins.property
    @pulumi.getter
    def criteria(
        self,
    ) -> Optional[Sequence[outputs.ScheduleBasedBackupCriteriaResponse]]: ...

@pulumi.output_type
class TargetCopySettingResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, copy_after: Any, data_store: outputs.DataStoreInfoBaseResponse
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="copyAfter")
    def copy_after(self) -> Any: ...
    @_builtins.property
    @pulumi.getter(name="dataStore")
    def data_store(self) -> outputs.DataStoreInfoBaseResponse: ...

@pulumi.output_type
class UserAssignedIdentityResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__, *, client_id: _builtins.str, principal_id: _builtins.str
    ) -> None: ...
    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter(name="principalId")
    def principal_id(self) -> _builtins.str: ...

@pulumi.output_type
class UserFacingErrorResponse(dict):
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default=...) -> Any: ...
    def __init__(
        __self__,
        *,
        code: Optional[_builtins.str] = ...,
        details: Optional[Sequence[outputs.UserFacingErrorResponse]] = ...,
        inner_error: Optional[outputs.InnerErrorResponse] = ...,
        is_retryable: Optional[_builtins.bool] = ...,
        is_user_error: Optional[_builtins.bool] = ...,
        message: Optional[_builtins.str] = ...,
        properties: Optional[Mapping[str, _builtins.str]] = ...,
        recommended_action: Optional[Sequence[_builtins.str]] = ...,
        target: Optional[_builtins.str] = ...,
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def code(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def details(self) -> Optional[Sequence[outputs.UserFacingErrorResponse]]: ...
    @_builtins.property
    @pulumi.getter(name="innerError")
    def inner_error(self) -> Optional[outputs.InnerErrorResponse]: ...
    @_builtins.property
    @pulumi.getter(name="isRetryable")
    def is_retryable(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter(name="isUserError")
    def is_user_error(self) -> Optional[_builtins.bool]: ...
    @_builtins.property
    @pulumi.getter
    def message(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> Optional[Mapping[str, _builtins.str]]: ...
    @_builtins.property
    @pulumi.getter(name="recommendedAction")
    def recommended_action(self) -> Optional[Sequence[_builtins.str]]: ...
    @_builtins.property
    @pulumi.getter
    def target(self) -> Optional[_builtins.str]: ...
