import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union
from . import outputs

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListHostPoolRegistrationTokensResult",
    "AwaitableListHostPoolRegistrationTokensResult",
    "list_host_pool_registration_tokens",
    "list_host_pool_registration_tokens_output",
]

@pulumi.output_type
class ListHostPoolRegistrationTokensResult:
    def __init__(__self__, next_link=..., value=...) -> None: ...
    @_builtins.property
    @pulumi.getter(name="nextLink")
    def next_link(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[Sequence[outputs.RegistrationTokenMinimalResponse]]: ...

class AwaitableListHostPoolRegistrationTokensResult(
    ListHostPoolRegistrationTokensResult
):
    def __await__(self): ...

def list_host_pool_registration_tokens(
    host_pool_name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListHostPoolRegistrationTokensResult: ...
def list_host_pool_registration_tokens_output(
    host_pool_name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListHostPoolRegistrationTokensResult]: ...
