

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessRights', 'EndPointProvisioningState', 'PrivateLinkConnectionStatus', 'PublicNetworkAccess', 'Relaytype', 'SkuName', 'SkuTier']
@pulumi.type_token("azure-native:relay:AccessRights")
class AccessRights(_builtins.str, Enum):
    MANAGE = ...
    SEND = ...
    LISTEN = ...


@pulumi.type_token("azure-native:relay:EndPointProvisioningState")
class EndPointProvisioningState(_builtins.str, Enum):
    
    CREATING = ...
    UPDATING = ...
    DELETING = ...
    SUCCEEDED = ...
    CANCELED = ...
    FAILED = ...


@pulumi.type_token("azure-native:relay:PrivateLinkConnectionStatus")
class PrivateLinkConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:relay:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...
    SECURED_BY_PERIMETER = ...


@pulumi.type_token("azure-native:relay:Relaytype")
class Relaytype(_builtins.str, Enum):
    
    NET_TCP = ...
    HTTP = ...


@pulumi.type_token("azure-native:relay:SkuName")
class SkuName(_builtins.str, Enum):
    
    STANDARD = ...


@pulumi.type_token("azure-native:relay:SkuTier")
class SkuTier(_builtins.str, Enum):
    
    STANDARD = ...


