

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['ArtifactKind', 'AssignmentLockMode', 'BlueprintTargetScope', 'ManagedServiceIdentityType', 'TemplateParameterType']
@pulumi.type_token("azure-native:blueprint:ArtifactKind")
class ArtifactKind(_builtins.str, Enum):
    
    TEMPLATE = ...
    ROLE_ASSIGNMENT = ...
    POLICY_ASSIGNMENT = ...


@pulumi.type_token("azure-native:blueprint:AssignmentLockMode")
class AssignmentLockMode(_builtins.str, Enum):
    
    NONE = ...
    ALL_RESOURCES_READ_ONLY = ...
    ALL_RESOURCES_DO_NOT_DELETE = ...


@pulumi.type_token("azure-native:blueprint:BlueprintTargetScope")
class BlueprintTargetScope(_builtins.str, Enum):
    
    SUBSCRIPTION = ...
    MANAGEMENT_GROUP = ...


@pulumi.type_token("azure-native:blueprint:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...


@pulumi.type_token("azure-native:blueprint:TemplateParameterType")
class TemplateParameterType(_builtins.str, Enum):
    
    STRING = ...
    ARRAY = ...
    BOOL = ...
    INT = ...
    OBJECT = ...
    SECURE_OBJECT = ...
    SECURE_STRING = ...


