

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AuthenticationMethod', 'AutoUpgradeOptions', 'AzureHybridBenefit', 'ConnectedClusterKind', 'PrivateLinkState', 'ProvisioningState', 'ResourceIdentityType']
@pulumi.type_token("azure-native:kubernetes:AuthenticationMethod")
class AuthenticationMethod(_builtins.str, Enum):
    
    TOKEN = ...
    AAD = ...


@pulumi.type_token("azure-native:kubernetes:AutoUpgradeOptions")
class AutoUpgradeOptions(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:kubernetes:AzureHybridBenefit")
class AzureHybridBenefit(_builtins.str, Enum):
    
    TRUE = ...
    FALSE = ...
    NOT_APPLICABLE = ...


@pulumi.type_token("azure-native:kubernetes:ConnectedClusterKind")
class ConnectedClusterKind(_builtins.str, Enum):
    
    PROVISIONED_CLUSTER = ...


@pulumi.type_token("azure-native:kubernetes:PrivateLinkState")
class PrivateLinkState(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:kubernetes:ProvisioningState")
class ProvisioningState(_builtins.str, Enum):
    
    SUCCEEDED = ...
    FAILED = ...
    CANCELED = ...
    PROVISIONING = ...
    UPDATING = ...
    DELETING = ...
    ACCEPTED = ...


@pulumi.type_token("azure-native:kubernetes:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...


