

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AccessRights', 'AuthenticationType', 'Capabilities', 'DefaultAction', 'IotHubSku', 'IpFilterActionType', 'NetworkRuleIPAction', 'PrivateLinkServiceConnectionStatus', 'PublicNetworkAccess', 'ResourceIdentityType', 'RoutingSource']
@pulumi.type_token("azure-native:iothub:AccessRights")
class AccessRights(_builtins.str, Enum):
    
    REGISTRY_READ = ...
    REGISTRY_WRITE = ...
    SERVICE_CONNECT = ...
    DEVICE_CONNECT = ...
    REGISTRY_READ_REGISTRY_WRITE = ...
    REGISTRY_READ_SERVICE_CONNECT = ...
    REGISTRY_READ_DEVICE_CONNECT = ...
    REGISTRY_WRITE_SERVICE_CONNECT = ...
    REGISTRY_WRITE_DEVICE_CONNECT = ...
    SERVICE_CONNECT_DEVICE_CONNECT = ...
    REGISTRY_READ_REGISTRY_WRITE_SERVICE_CONNECT = ...
    REGISTRY_READ_REGISTRY_WRITE_DEVICE_CONNECT = ...
    REGISTRY_READ_SERVICE_CONNECT_DEVICE_CONNECT = ...
    REGISTRY_WRITE_SERVICE_CONNECT_DEVICE_CONNECT = ...
    REGISTRY_READ_REGISTRY_WRITE_SERVICE_CONNECT_DEVICE_CONNECT = ...


@pulumi.type_token("azure-native:iothub:AuthenticationType")
class AuthenticationType(_builtins.str, Enum):
    
    KEY_BASED = ...
    IDENTITY_BASED = ...


@pulumi.type_token("azure-native:iothub:Capabilities")
class Capabilities(_builtins.str, Enum):
    
    NONE = ...
    DEVICE_MANAGEMENT = ...


@pulumi.type_token("azure-native:iothub:DefaultAction")
class DefaultAction(_builtins.str, Enum):
    
    DENY = ...
    ALLOW = ...


@pulumi.type_token("azure-native:iothub:IotHubSku")
class IotHubSku(_builtins.str, Enum):
    
    F1 = ...
    S1 = ...
    S2 = ...
    S3 = ...
    B1 = ...
    B2 = ...
    B3 = ...


@pulumi.type_token("azure-native:iothub:IpFilterActionType")
class IpFilterActionType(_builtins.str, Enum):
    
    ACCEPT = ...
    REJECT = ...


@pulumi.type_token("azure-native:iothub:NetworkRuleIPAction")
class NetworkRuleIPAction(_builtins.str, Enum):
    
    ALLOW = ...


@pulumi.type_token(...)
class PrivateLinkServiceConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:iothub:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:iothub:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:iothub:RoutingSource")
class RoutingSource(_builtins.str, Enum):
    
    INVALID = ...
    DEVICE_MESSAGES = ...
    TWIN_CHANGE_EVENTS = ...
    DEVICE_LIFECYCLE_EVENTS = ...
    DEVICE_JOB_LIFECYCLE_EVENTS = ...
    DEVICE_CONNECTION_STATE_EVENTS = ...


