

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ['AdoptionPolicy', 'AdvancedNetworkPolicies', 'AgentPoolMode', 'AgentPoolSSHAccess', 'AgentPoolType', 'ArtifactSource', 'AutoUpgradeNodeImageSelectionType', 'BackendPoolType', 'Code', 'ConnectionStatus', 'DeletePolicy', 'DeploymentSafeguardsLevel', 'ExecutionPoint', 'Expander', 'ExtendedLocationTypes', 'GPUDriver', 'GPUInstanceProfile', 'IpFamily', 'IstioIngressGatewayMode', 'KeyVaultNetworkAccessTypes', 'KubeletDiskType', 'KubernetesSupportPlan', 'LabelSelectorOperator', 'LicenseType', 'LoadBalancerSku', 'LocalDNSForwardDestination', 'LocalDNSForwardPolicy', 'LocalDNSMode', 'LocalDNSProtocol', 'LocalDNSQueryLogging', 'LocalDNSServeStale', 'ManagedClusterSKUName', 'ManagedClusterSKUTier', 'ManagedClusterUpgradeType', 'ManagedServiceIdentityType', 'NetworkDataplane', 'NetworkMode', 'NetworkPlugin', 'NetworkPluginMode', 'NetworkPolicy', 'NginxIngressControllerType', 'NodeImageSelectionType', 'NodeOSUpgradeChannel', 'NodeProvisioningDefaultNodePools', 'NodeProvisioningMode', 'OSDiskType', 'OSSKU', 'OSType', 'Operator', 'OutboundType', 'PlacementType', 'PodIPAllocationMode', 'PolicyRule', 'PropagationType', 'PropertySelectorOperator', 'Protocol', 'PublicNetworkAccess', 'ResourceIdentityType', 'RestrictionLevel', 'ScaleDownMode', 'ScaleSetEvictionPolicy', 'ScaleSetPriority', 'ScriptType', 'ServiceMeshMode', 'SnapshotType', 'TaintEffect', 'TolerationOperator', 'Type', 'UndrainableNodeBehavior', 'UpgradeChannel', 'WeekDay', 'WorkloadRuntime']
@pulumi.type_token("azure-native:containerservice:AdoptionPolicy")
class AdoptionPolicy(_builtins.str, Enum):
    
    NEVER = ...
    IF_IDENTICAL = ...
    ALWAYS = ...


@pulumi.type_token(...)
class AdvancedNetworkPolicies(_builtins.str, Enum):
    
    L7 = ...
    FQDN = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:AgentPoolMode")
class AgentPoolMode(_builtins.str, Enum):
    
    SYSTEM = ...
    USER = ...
    GATEWAY = ...


@pulumi.type_token("azure-native:containerservice:AgentPoolSSHAccess")
class AgentPoolSSHAccess(_builtins.str, Enum):
    
    LOCAL_USER = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerservice:AgentPoolType")
class AgentPoolType(_builtins.str, Enum):
    
    VIRTUAL_MACHINE_SCALE_SETS = ...
    AVAILABILITY_SET = ...
    VIRTUAL_MACHINES = ...


@pulumi.type_token("azure-native:containerservice:ArtifactSource")
class ArtifactSource(_builtins.str, Enum):
    
    CACHE = ...
    DIRECT = ...


@pulumi.type_token(...)
class AutoUpgradeNodeImageSelectionType(_builtins.str, Enum):
    
    LATEST = ...
    CONSISTENT = ...


@pulumi.type_token("azure-native:containerservice:BackendPoolType")
class BackendPoolType(_builtins.str, Enum):
    
    NODE_IP_CONFIGURATION = ...
    NODE_IP = ...


@pulumi.type_token("azure-native:containerservice:Code")
class Code(_builtins.str, Enum):
    
    RUNNING = ...
    STOPPED = ...


@pulumi.type_token("azure-native:containerservice:ConnectionStatus")
class ConnectionStatus(_builtins.str, Enum):
    
    PENDING = ...
    APPROVED = ...
    REJECTED = ...
    DISCONNECTED = ...


@pulumi.type_token("azure-native:containerservice:DeletePolicy")
class DeletePolicy(_builtins.str, Enum):
    
    KEEP = ...
    DELETE = ...


@pulumi.type_token(...)
class DeploymentSafeguardsLevel(_builtins.str, Enum):
    
    WARN = ...
    ENFORCE = ...


@pulumi.type_token("azure-native:containerservice:ExecutionPoint")
class ExecutionPoint(_builtins.str, Enum):
    
    NODE_IMAGE_BUILD_TIME = ...
    NODE_PROVISION_TIME = ...


@pulumi.type_token("azure-native:containerservice:Expander")
class Expander(_builtins.str, Enum):
    
    LEAST_WASTE = ...
    MOST_PODS = ...
    PRIORITY = ...
    RANDOM = ...


@pulumi.type_token(...)
class ExtendedLocationTypes(_builtins.str, Enum):
    
    EDGE_ZONE = ...


@pulumi.type_token("azure-native:containerservice:GPUDriver")
class GPUDriver(_builtins.str, Enum):
    
    INSTALL = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:GPUInstanceProfile")
class GPUInstanceProfile(_builtins.str, Enum):
    
    MIG1G = ...
    MIG2G = ...
    MIG3G = ...
    MIG4G = ...
    MIG7G = ...


@pulumi.type_token("azure-native:containerservice:IpFamily")
class IpFamily(_builtins.str, Enum):
    
    I_PV4 = ...
    I_PV6 = ...


@pulumi.type_token(...)
class IstioIngressGatewayMode(_builtins.str, Enum):
    
    EXTERNAL = ...
    INTERNAL = ...


@pulumi.type_token(...)
class KeyVaultNetworkAccessTypes(_builtins.str, Enum):
    
    PUBLIC = ...
    PRIVATE = ...


@pulumi.type_token("azure-native:containerservice:KubeletDiskType")
class KubeletDiskType(_builtins.str, Enum):
    
    OS = ...
    TEMPORARY = ...


@pulumi.type_token(...)
class KubernetesSupportPlan(_builtins.str, Enum):
    
    KUBERNETES_OFFICIAL = ...
    AKS_LONG_TERM_SUPPORT = ...


@pulumi.type_token(...)
class LabelSelectorOperator(_builtins.str, Enum):
    
    IN_ = ...
    NOT_IN = ...
    EXISTS = ...
    DOES_NOT_EXIST = ...


@pulumi.type_token("azure-native:containerservice:LicenseType")
class LicenseType(_builtins.str, Enum):
    
    NONE = ...
    WINDOWS_SERVER = ...


@pulumi.type_token("azure-native:containerservice:LoadBalancerSku")
class LoadBalancerSku(_builtins.str, Enum):
    
    STANDARD = ...
    BASIC = ...


@pulumi.type_token(...)
class LocalDNSForwardDestination(_builtins.str, Enum):
    
    CLUSTER_CORE_DNS = ...
    VNET_DNS = ...


@pulumi.type_token(...)
class LocalDNSForwardPolicy(_builtins.str, Enum):
    
    SEQUENTIAL = ...
    ROUND_ROBIN = ...
    RANDOM = ...


@pulumi.type_token("azure-native:containerservice:LocalDNSMode")
class LocalDNSMode(_builtins.str, Enum):
    
    PREFERRED = ...
    REQUIRED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerservice:LocalDNSProtocol")
class LocalDNSProtocol(_builtins.str, Enum):
    
    PREFER_UDP = ...
    FORCE_TCP = ...


@pulumi.type_token("azure-native:containerservice:LocalDNSQueryLogging")
class LocalDNSQueryLogging(_builtins.str, Enum):
    
    ERROR = ...
    LOG = ...


@pulumi.type_token("azure-native:containerservice:LocalDNSServeStale")
class LocalDNSServeStale(_builtins.str, Enum):
    
    VERIFY = ...
    IMMEDIATE = ...
    DISABLE = ...


@pulumi.type_token(...)
class ManagedClusterSKUName(_builtins.str, Enum):
    
    BASE = ...
    AUTOMATIC = ...


@pulumi.type_token(...)
class ManagedClusterSKUTier(_builtins.str, Enum):
    
    PREMIUM = ...
    STANDARD = ...
    FREE = ...


@pulumi.type_token(...)
class ManagedClusterUpgradeType(_builtins.str, Enum):
    
    FULL = ...
    NODE_IMAGE_ONLY = ...
    CONTROL_PLANE_ONLY = ...


@pulumi.type_token(...)
class ManagedServiceIdentityType(_builtins.str, Enum):
    
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...


@pulumi.type_token("azure-native:containerservice:NetworkDataplane")
class NetworkDataplane(_builtins.str, Enum):
    
    AZURE = ...
    CILIUM = ...


@pulumi.type_token("azure-native:containerservice:NetworkMode")
class NetworkMode(_builtins.str, Enum):
    
    TRANSPARENT = ...
    BRIDGE = ...


@pulumi.type_token("azure-native:containerservice:NetworkPlugin")
class NetworkPlugin(_builtins.str, Enum):
    
    AZURE = ...
    KUBENET = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:NetworkPluginMode")
class NetworkPluginMode(_builtins.str, Enum):
    
    OVERLAY = ...


@pulumi.type_token("azure-native:containerservice:NetworkPolicy")
class NetworkPolicy(_builtins.str, Enum):
    
    NONE = ...
    CALICO = ...
    AZURE = ...
    CILIUM = ...


@pulumi.type_token(...)
class NginxIngressControllerType(_builtins.str, Enum):
    
    ANNOTATION_CONTROLLED = ...
    EXTERNAL = ...
    INTERNAL = ...
    NONE = ...


@pulumi.type_token(...)
class NodeImageSelectionType(_builtins.str, Enum):
    
    LATEST = ...
    CONSISTENT = ...
    CUSTOM = ...


@pulumi.type_token("azure-native:containerservice:NodeOSUpgradeChannel")
class NodeOSUpgradeChannel(_builtins.str, Enum):
    
    NONE = ...
    UNMANAGED = ...
    NODE_IMAGE = ...
    SECURITY_PATCH = ...


@pulumi.type_token(...)
class NodeProvisioningDefaultNodePools(_builtins.str, Enum):
    
    NONE = ...
    AUTO = ...


@pulumi.type_token("azure-native:containerservice:NodeProvisioningMode")
class NodeProvisioningMode(_builtins.str, Enum):
    
    MANUAL = ...
    AUTO = ...


@pulumi.type_token("azure-native:containerservice:OSDiskType")
class OSDiskType(_builtins.str, Enum):
    
    MANAGED = ...
    EPHEMERAL = ...


@pulumi.type_token("azure-native:containerservice:OSSKU")
class OSSKU(_builtins.str, Enum):
    
    UBUNTU = ...
    AZURE_LINUX = ...
    AZURE_LINUX3 = ...
    CBL_MARINER = ...
    WINDOWS2019 = ...
    WINDOWS2022 = ...
    UBUNTU2204 = ...


@pulumi.type_token("azure-native:containerservice:OSType")
class OSType(_builtins.str, Enum):
    
    LINUX = ...
    WINDOWS = ...


@pulumi.type_token("azure-native:containerservice:Operator")
class Operator(_builtins.str, Enum):
    
    IN_ = ...
    NOT_IN = ...
    EXISTS = ...
    DOES_NOT_EXIST = ...


@pulumi.type_token("azure-native:containerservice:OutboundType")
class OutboundType(_builtins.str, Enum):
    
    LOAD_BALANCER = ...
    USER_DEFINED_ROUTING = ...
    MANAGED_NAT_GATEWAY = ...
    USER_ASSIGNED_NAT_GATEWAY = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:PlacementType")
class PlacementType(_builtins.str, Enum):
    
    PICK_ALL = ...
    PICK_FIXED = ...


@pulumi.type_token("azure-native:containerservice:PodIPAllocationMode")
class PodIPAllocationMode(_builtins.str, Enum):
    
    DYNAMIC_INDIVIDUAL = ...
    STATIC_BLOCK = ...


@pulumi.type_token("azure-native:containerservice:PolicyRule")
class PolicyRule(_builtins.str, Enum):
    
    DENY_ALL = ...
    ALLOW_ALL = ...
    ALLOW_SAME_NAMESPACE = ...


@pulumi.type_token("azure-native:containerservice:PropagationType")
class PropagationType(_builtins.str, Enum):
    
    PLACEMENT = ...


@pulumi.type_token(...)
class PropertySelectorOperator(_builtins.str, Enum):
    
    GT = ...
    GE = ...
    EQ = ...
    NE = ...
    LT = ...
    LE = ...


@pulumi.type_token("azure-native:containerservice:Protocol")
class Protocol(_builtins.str, Enum):
    
    TCP = ...
    UDP = ...


@pulumi.type_token("azure-native:containerservice:PublicNetworkAccess")
class PublicNetworkAccess(_builtins.str, Enum):
    
    ENABLED = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerservice:ResourceIdentityType")
class ResourceIdentityType(_builtins.str, Enum):
    
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:RestrictionLevel")
class RestrictionLevel(_builtins.str, Enum):
    
    UNRESTRICTED = ...
    READ_ONLY = ...


@pulumi.type_token("azure-native:containerservice:ScaleDownMode")
class ScaleDownMode(_builtins.str, Enum):
    
    DELETE = ...
    DEALLOCATE = ...


@pulumi.type_token(...)
class ScaleSetEvictionPolicy(_builtins.str, Enum):
    
    DELETE = ...
    DEALLOCATE = ...


@pulumi.type_token("azure-native:containerservice:ScaleSetPriority")
class ScaleSetPriority(_builtins.str, Enum):
    
    SPOT = ...
    REGULAR = ...


@pulumi.type_token("azure-native:containerservice:ScriptType")
class ScriptType(_builtins.str, Enum):
    
    BASH = ...
    POWER_SHELL = ...


@pulumi.type_token("azure-native:containerservice:ServiceMeshMode")
class ServiceMeshMode(_builtins.str, Enum):
    
    ISTIO = ...
    DISABLED = ...


@pulumi.type_token("azure-native:containerservice:SnapshotType")
class SnapshotType(_builtins.str, Enum):
    
    NODE_POOL = ...


@pulumi.type_token("azure-native:containerservice:TaintEffect")
class TaintEffect(_builtins.str, Enum):
    
    NO_SCHEDULE = ...


@pulumi.type_token("azure-native:containerservice:TolerationOperator")
class TolerationOperator(_builtins.str, Enum):
    
    EXISTS = ...
    EQUAL = ...


@pulumi.type_token("azure-native:containerservice:Type")
class Type(_builtins.str, Enum):
    
    FIRST = ...
    SECOND = ...
    THIRD = ...
    FOURTH = ...
    LAST = ...


@pulumi.type_token(...)
class UndrainableNodeBehavior(_builtins.str, Enum):
    
    CORDON = ...
    SCHEDULE = ...


@pulumi.type_token("azure-native:containerservice:UpgradeChannel")
class UpgradeChannel(_builtins.str, Enum):
    
    RAPID = ...
    STABLE = ...
    PATCH = ...
    NODE_IMAGE = ...
    NONE = ...


@pulumi.type_token("azure-native:containerservice:WeekDay")
class WeekDay(_builtins.str, Enum):
    
    SUNDAY = ...
    MONDAY = ...
    TUESDAY = ...
    WEDNESDAY = ...
    THURSDAY = ...
    FRIDAY = ...
    SATURDAY = ...


@pulumi.type_token("azure-native:containerservice:WorkloadRuntime")
class WorkloadRuntime(_builtins.str, Enum):
    
    OCI_CONTAINER = ...
    WASM_WASI = ...
    KATA_VM_ISOLATION = ...


