

import builtins as _builtins
import sys
import pulumi
from typing import Mapping, Optional, Sequence, Union
from . import outputs

if sys.version_info >= (3, 11):
    ...
else:
    ...
__all__ = ['GetWebAppResult', 'AwaitableGetWebAppResult', 'get_web_app', 'get_web_app_output']
@pulumi.output_type
class GetWebAppResult:
    
    def __init__(__self__, auto_generated_domain_name_label_scope=..., availability_state=..., azure_api_version=..., client_affinity_enabled=..., client_affinity_partitioning_enabled=..., client_affinity_proxy_enabled=..., client_cert_enabled=..., client_cert_exclusion_paths=..., client_cert_mode=..., container_size=..., custom_domain_verification_id=..., daily_memory_time_quota=..., dapr_config=..., default_host_name=..., dns_configuration=..., enabled=..., enabled_host_names=..., end_to_end_encryption_enabled=..., extended_location=..., function_app_config=..., host_name_ssl_states=..., host_names=..., host_names_disabled=..., hosting_environment_profile=..., https_only=..., hyper_v=..., id=..., identity=..., in_progress_operation_id=..., ip_mode=..., is_default_container=..., is_xenon=..., key_vault_reference_identity=..., kind=..., last_modified_time_utc=..., location=..., managed_environment_id=..., max_number_of_workers=..., name=..., outbound_ip_addresses=..., outbound_vnet_routing=..., possible_outbound_ip_addresses=..., public_network_access=..., redundancy_mode=..., repository_site_name=..., reserved=..., resource_config=..., resource_group=..., scm_site_also_stopped=..., server_farm_id=..., sku=..., slot_swap_status=..., ssh_enabled=..., state=..., storage_account_required=..., suspended_till=..., tags=..., target_swap_slot=..., traffic_manager_host_names=..., type=..., usage_state=..., virtual_network_subnet_id=..., workload_profile_name=...) -> None:
        ...
    
    @_builtins.property
    @pulumi.getter(name="autoGeneratedDomainNameLabelScope")
    def auto_generated_domain_name_label_scope(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="availabilityState")
    def availability_state(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="azureApiVersion")
    def azure_api_version(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientAffinityEnabled")
    def client_affinity_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientAffinityPartitioningEnabled")
    def client_affinity_partitioning_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientAffinityProxyEnabled")
    def client_affinity_proxy_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientCertEnabled")
    def client_cert_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientCertExclusionPaths")
    def client_cert_exclusion_paths(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="clientCertMode")
    def client_cert_mode(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="containerSize")
    def container_size(self) -> Optional[_builtins.int]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="customDomainVerificationId")
    def custom_domain_verification_id(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="dailyMemoryTimeQuota")
    def daily_memory_time_quota(self) -> Optional[_builtins.int]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="daprConfig")
    def dapr_config(self) -> Optional[outputs.DaprConfigResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="defaultHostName")
    def default_host_name(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="dnsConfiguration")
    def dns_configuration(self) -> Optional[outputs.SiteDnsConfigResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="enabledHostNames")
    def enabled_host_names(self) -> Sequence[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="endToEndEncryptionEnabled")
    def end_to_end_encryption_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="extendedLocation")
    def extended_location(self) -> Optional[outputs.ExtendedLocationResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="functionAppConfig")
    def function_app_config(self) -> Optional[outputs.FunctionAppConfigResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="hostNameSslStates")
    def host_name_ssl_states(self) -> Optional[Sequence[outputs.HostNameSslStateResponse]]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="hostNames")
    def host_names(self) -> Sequence[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="hostNamesDisabled")
    def host_names_disabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="hostingEnvironmentProfile")
    def hosting_environment_profile(self) -> Optional[outputs.HostingEnvironmentProfileResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="httpsOnly")
    def https_only(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="hyperV")
    def hyper_v(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def identity(self) -> Optional[outputs.ManagedServiceIdentityResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="inProgressOperationId")
    def in_progress_operation_id(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="ipMode")
    def ip_mode(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="isDefaultContainer")
    def is_default_container(self) -> _builtins.bool:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="isXenon")
    def is_xenon(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="keyVaultReferenceIdentity")
    def key_vault_reference_identity(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="lastModifiedTimeUtc")
    def last_modified_time_utc(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="managedEnvironmentId")
    def managed_environment_id(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="maxNumberOfWorkers")
    def max_number_of_workers(self) -> _builtins.int:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="outboundIpAddresses")
    def outbound_ip_addresses(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="outboundVnetRouting")
    def outbound_vnet_routing(self) -> Optional[outputs.OutboundVnetRoutingResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="possibleOutboundIpAddresses")
    def possible_outbound_ip_addresses(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="publicNetworkAccess")
    def public_network_access(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="redundancyMode")
    def redundancy_mode(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="repositorySiteName")
    def repository_site_name(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def reserved(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="resourceConfig")
    def resource_config(self) -> Optional[outputs.ResourceConfigResponse]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="resourceGroup")
    def resource_group(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="scmSiteAlsoStopped")
    def scm_site_also_stopped(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="serverFarmId")
    def server_farm_id(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def sku(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="slotSwapStatus")
    def slot_swap_status(self) -> outputs.SlotSwapStatusResponse:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="sshEnabled")
    def ssh_enabled(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="storageAccountRequired")
    def storage_account_required(self) -> Optional[_builtins.bool]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="suspendedTill")
    def suspended_till(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="targetSwapSlot")
    def target_swap_slot(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="trafficManagerHostNames")
    def traffic_manager_host_names(self) -> Sequence[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="usageState")
    def usage_state(self) -> _builtins.str:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="virtualNetworkSubnetId")
    def virtual_network_subnet_id(self) -> Optional[_builtins.str]:
        
        ...
    
    @_builtins.property
    @pulumi.getter(name="workloadProfileName")
    def workload_profile_name(self) -> Optional[_builtins.str]:
        
        ...
    


class AwaitableGetWebAppResult(GetWebAppResult):
    def __await__(self): # -> Generator[Never, Any, GetWebAppResult]:
        ...
    


def get_web_app(name: Optional[_builtins.str] = ..., resource_group_name: Optional[_builtins.str] = ..., opts: Optional[pulumi.InvokeOptions] = ...) -> AwaitableGetWebAppResult:
    
    ...

def get_web_app_output(name: Optional[pulumi.Input[_builtins.str]] = ..., resource_group_name: Optional[pulumi.Input[_builtins.str]] = ..., opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...) -> pulumi.Output[GetWebAppResult]:
    
    ...

