import builtins as _builtins
import sys
import pulumi
from typing import Optional, Sequence, Union

"""
This type stub file was generated by pyright.
"""
if sys.version_info >= (3, 11): ...
else: ...
__all__ = [
    "ListStaticSiteConfiguredRolesResult",
    "AwaitableListStaticSiteConfiguredRolesResult",
    "list_static_site_configured_roles",
    "list_static_site_configured_roles_output",
]

@pulumi.output_type
class ListStaticSiteConfiguredRolesResult:
    def __init__(
        __self__, id=..., kind=..., name=..., properties=..., type=...
    ) -> None: ...
    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def kind(self) -> Optional[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str: ...
    @_builtins.property
    @pulumi.getter
    def properties(self) -> Sequence[_builtins.str]: ...
    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str: ...

class AwaitableListStaticSiteConfiguredRolesResult(ListStaticSiteConfiguredRolesResult):
    def __await__(self): ...

def list_static_site_configured_roles(
    name: Optional[_builtins.str] = ...,
    resource_group_name: Optional[_builtins.str] = ...,
    opts: Optional[pulumi.InvokeOptions] = ...,
) -> AwaitableListStaticSiteConfiguredRolesResult: ...
def list_static_site_configured_roles_output(
    name: Optional[pulumi.Input[_builtins.str]] = ...,
    resource_group_name: Optional[pulumi.Input[_builtins.str]] = ...,
    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = ...,
) -> pulumi.Output[ListStaticSiteConfiguredRolesResult]: ...
