import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["ManagedServiceIdentityType", "ProviderStatus"]

@pulumi.type_token("azure-native:quantum:ManagedServiceIdentityType")
class ManagedServiceIdentityType(_builtins.str, Enum):
    NONE = ...
    SYSTEM_ASSIGNED = ...
    USER_ASSIGNED = ...
    SYSTEM_ASSIGNED_USER_ASSIGNED = ...

@pulumi.type_token("azure-native:quantum:ProviderStatus")
class ProviderStatus(_builtins.str, Enum):
    SUCCEEDED = ...
    LAUNCHING = ...
    UPDATING = ...
    DELETING = ...
    DELETED = ...
    FAILED = ...
