import builtins as _builtins
import pulumi
from enum import Enum

__all__ = ["Region"]

@pulumi.type_token("aws:index/Region:Region")
class Region(_builtins.str, Enum):
    AF_SOUTH1 = ...
    AP_EAST1 = ...
    AP_EAST2 = ...
    AP_NORTHEAST1 = ...
    AP_NORTHEAST2 = ...
    AP_NORTHEAST3 = ...
    AP_SOUTH1 = ...
    AP_SOUTH2 = ...
    AP_SOUTHEAST1 = ...
    AP_SOUTHEAST2 = ...
    AP_SOUTHEAST3 = ...
    AP_SOUTHEAST4 = ...
    AP_SOUTHEAST5 = ...
    AP_SOUTHEAST7 = ...
    CA_CENTRAL = ...
    CA_WEST1 = ...
    EU_CENTRAL1 = ...
    EU_CENTRAL2 = ...
    EU_NORTH1 = ...
    EU_SOUTH1 = ...
    EU_SOUTH2 = ...
    EU_WEST1 = ...
    EU_WEST2 = ...
    EU_WEST3 = ...
    IL_CENTRAL1 = ...
    ME_CENTRAL1 = ...
    ME_SOUTH1 = ...
    MX_CENTRAL1 = ...
    SA_EAST1 = ...
    US_EAST1 = ...
    US_EAST2 = ...
    US_WEST1 = ...
    US_WEST2 = ...
    CN_NORTH1 = ...
    CN_NORTHWEST1 = ...
    US_GOV_EAST1 = ...
    US_GOV_WEST1 = ...
    USISO_EAST1 = ...
    USISO_WEST1 = ...
    USISOB_EAST1 = ...
    EUISOE_WEST1 = ...
